openfoodfacts/openfoodfacts-server

lib/ProductOpener/Display.pm, scss/_off.scss, templates/display_rev_info.tt.html
Updates `display_rev_info` to use `Template::Toolkit`. Also updates the styling to be compatible with RTL text direction.
=> Templatize revision info and navigator

html/js/display-map.js, html/js/display-tag.js, lib/ProductOpener/Display.pm, templates/display_map.tt.html, templates/display_tag_map.tt.html
Updates some leaflet based map views to use `Template::Toolkit`. At the same time, it removes manual JSON building and moves some previously inline JavaScript to TT templates or separate JavaScript files.
=> Templatize leaflet maps

taxonomies/categories.txt
Those are PGI categories that were left on my drive. This is still a work in progress
=> Adding more European PGI categories

taxonomies/categories.txt
=> Agribalyse proxies

taxonomies/categories.txt
+ taxonomy build in progress (commit coming soon)
=> removing duplicate entry

lib/ProductOpener/Ingredients.pm, taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/ingredients.txt, taxonomies/minerals.txt
Found a load of unrecognised ingredients in Romanian entries. Note the change to Ingredients.pm.
=> Taxonomy edits 8 - mostly adding romanian ingredients

cgi/user.pl, lib/ProductOpener/Orgs.pm, lib/ProductOpener/Users.pm, templates/user_form.tt.html
allows users to edit their profile
=> fix user edit form, fixes #4106

lib/ProductOpener/Ingredients.pm
=> Mistranslations: changed of to van

taxonomies/categories.txt
=> Apply translations from web categories.txt

cgi/export_products.pl, po/common/common.pot, po/common/en.po, templates/display_product.tt.html, templates/export_products.tt.html
On the platform for producer, this adds a button on the product page to export it to the public database.
The script to export products has also been templatized with Template::Toolkit.
=> export a specific product + templatization

lib/ProductOpener/Display.pm
- Add nutrients to the &fields= parameter to request only specific fields. e.g. &fields=sugar_100g - #4128
- Deduplicate the code to customize / filter product responses according to the request
- More documentation
=> support requesting only some nutrients in the API + deduplicating code

po/common/it.po
=> fix broken html in italian translation

lib/ProductOpener/Display.pm
fix for queries with .json + query params like ?fields=...
=> fix issue with .json + query params, fixes #4141

lib/ProductOpener/Display.pm, lib/ProductOpener/Orgs.pm, po/common/common.pot, po/common/en.po
=> return 404 for unknown users/orgs, fixes #4151

taxonomies/ingredients.txt
=> Peanuts update

cgi/display.pl, lib/ProductOpener/Attributes.pm, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Display.pm
- Moved functions in a more logical order (in the source code)
- Factorized some code that was used in multiple places
- Start of API to list the available product attributes (to be used by clients to display interfaces to choose user preferences)
=> reorganized the code for attributes

po/openbeautyfacts/openbeautyfacts.pot, po/openpetfoodfacts/openpetfoodfacts.pot, po/openproductsfacts/openproductsfacts.pot
=> App links for flavors

lib/ProductOpener/Food.pm
=> fix kcal conversion for prepared product, fixes #4180

lib/ProductOpener/Ingredients.pm, t/ingredients_clean.t
Continuing the Nordic series. Additional patterns for cleaning the ingredient list.
=> Nordic ingredient list cleaning patterns

lib/startup_apache2.pl
Should close #4178 and #4147 
**Related issues and discussion:** #4178 #4147
=> fix: set useragent IP to X-Forwarded-For

taxonomies/labels.txt
Some organic stuff in the labels taxonomy.
=> organic additions

lib/ProductOpener/Ingredients.pm, taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/categories.txt, taxonomies/ingredients.txt
Some more languages' category dupes have been eliminated entirely:
=> Taxonomy edits 15 - category PGI/PDO dedupes, and some added ingredients

taxonomies/ingredients.txt
=> add tamarillo and white peach

lib/ProductOpener/DataQualityFood.pm
for the corner case 1 kcal / 5 kJ
=> small fix for energy-value-in-kcal-does-not-match-value-in-kj

lib/ProductOpener/Images.pm
- dates that look like barcode numbers #4218 
- failing to scan barcode for some images #4220
=> Fix 2 small bugs for bulk image upload

cgi/import_photos_upload.pl, cgi/product_image_upload.pl, po/common/common.pot, po/common/en.po
#4223 : auto start uploads, remove buttons to start / cancel upload for each file
=> Issue 4223/simplify bulk image upload

lib/ProductOpener/Display.pm, po/common/common.pot, templates/display_new.tt.html, templates/donate_banner.tt.html
I think the checkbox with "Hey, a box to uncheck?!" is not really useful and disturbs the flow. Therefore, I'd like to completely hide the banner and checkbox once it's unchecked. Since we don't need the HTML then, we can also just not add it to the DOM in the first place, when the site is loaded the next time.
=> Remove unchecked donation banner

po/common/it.po, t/i18n.t
Also `$lang{$key}{$lang}` actually working is not helping to convince me perl is a sane language. :D
=> text_direction translation - fix and prevention for #4233

t/ingredients_nesting.t
it was fixed at some point, here's a test to make sure.
=> add test to make sure #3838 stays fixed

taxonomies/categories.txt
=> agb proxies

html/js/product-multilingual.js
This PR fixes an issue related to rotation cropping on a new product.
**Related issues and discussion:** #3186
=> Fix issue cropping on a new product

scripts/build_tags_taxonomy.pl
it won't let me submit the pull request without typing something in this box, so i shall reluctantly do exactly that.
=> fix error message typo in build_tags_taxonomy.pl

lib/ProductOpener/Ingredients.pm, t/ingredients_parsing.t
=> add w/ & w/o abbreviations, fixes #3270

lib/ProductOpener/Display.pm, lib/ProductOpener/Tags.pm, po/common/common.pot, po/common/en.po, scss/_off.scss, t/tags.t
=> replace old additives risk levels by efsa overexpose risk, #4272

docker/backend/Dockerfile
tired of reinstalling it, and it's fairly fundamental and has no extra dependencies.
=> add "less" to docker image

taxonomies/allergens.txt
Not sure how it was missing for so long.
https://world.openfoodfacts.org/allergen/sv:ost
I hope I'm doing this correctly.
=> Added the Swedish word for "cheese" to allergens.

cgi/generate_sample_import_file.pl, cgi/remove_products.pl, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Producers.pm, po/common/common.pot, po/common/en.po, po/common/fr.po
There were a few issues with some fields.
The sample Excel files are generated on the producers platform https://world.pro.openfoodfacts.org 
Here is the ouput for English and French:
[openfoodfacts-import-en.xlsx](https://github.com/openfoodfacts/openfoodfacts-server/files/5305109/openfoodfacts-import-en.xlsx)
[openfoodfacts-import-fr.xlsx](https://github.com/openfoodfacts/openfoodfacts-server/files/5305110/openfoodfacts-import-fr.xlsx)
=> Small fixes for sample Excel file for producers to import their product data through the producers platform

scripts/api_stats.pl
Some usage examples are included in the comments at the top of the file.
=> Script to compute stats from calls to the scan API

taxonomies/labels.txt
=> Label updates

scripts/export_database.pl
as suggested by @hangy https://github.com/openfoodfacts/openfoodfacts-server/issues/3857#issuecomment-703100516
=> export_database.pl - make cursor immortal

gulpfile.js, package.json
I added a new command `build:watch` to watch changes on scss and js files, this helps during development. Do I need to add other task on gulp to watch changes and build?
=> Add build:watch command to watch changes on scss and js files

lib/startup_apache2.pl
I forgot to commit startup.pl, so the agribalyse data is not loaded.
=> load agribalyse data at startup

cgi/display.pl, lib/ProductOpener/Display.pm
Fixes #4314 
And adds support for downloading results through new /search API.
=> Remove download link on home page / facet page + support for download on new /search API

lib/ProductOpener/Ingredients.pm, t/ingredients_tags.t
=> Fix ignore phrase regexp in Dutch - 'o.a.' -> 'o\.a\.'

cgi/search.pl
quick fix for #4357 to avoid mongodb being overloaded
=> display an error message for google spreadsheet queries, fixes #4357

taxonomies/categories.txt
=> Agribalyse fixes

lib/ProductOpener/Ingredients.pm
=> remove existing ingedients_text_with_allergens fields, bug #3836

lib/ProductOpener/Display.pm
I broke the user profiles with a stupid mistake a couple of weeks ago, this fixes it.
Fixes #4186
=> fix displaying user profiles, fixes #4186

taxonomies/categories.result.txt
to update the agribalyse matches
=> built categories taxonomy

taxonomies/categories.txt
=> Agribalyse - 19 octobre

lib/ProductOpener/Ecoscore.pm
The Eco-Score is computed from life cycle analysis (LCA) data from the Agribalyse database (based on its category), to which bonuses and maluses are added depending on labels, ingredients, origins of ingredients and packaging.
We have already implemented the LCA / Agribalyse part, this adds the labels bonuses for the production system (e.g. organic)
Related issue: #4287
=> add ecoscore bonuses for labels 

package-lock.json, package.json
=> update tagify to fix #4280 - searching for tags with accented characters

taxonomies/categories.txt
This will increase the % of Agribalyse coverage by 1%
https://fr.openfoodfacts.org/popularite/top-10000-fr-scans-2019/categorie/margarines  (almost no margarines have a match today)
=> add agribalyse proxy for margarines

lib/ProductOpener/Ecoscore.pm, t/ecoscore.t
continuing the implementation of ecoscore bonuses and maluses #4287 
-10 malus for palm oil
=> add palm oil malus for ecoscore, #4287

t/tags.t, taxonomies/categories.result.txt, taxonomies/categories.txt
jams: this should get us another 1%
sodas: at least 0.5%
=> add agribalyse proxy for jams and sodas

taxonomies/categories.txt, taxonomies/ingredients.txt
=> Some minor repairs

lib/ProductOpener/Import.pm
=> make sure lang is set to lc, fixes #4427

lib/ProductOpener/Display.pm
=> add image_packaging_url, fixes #4442

taxonomies/ingredients.txt
**Checklist:**
Add "Kokossahne" as a synonym for "coconut cream" (German), also add Swedish version "Kokosgrädde". Both are taken from an ice-cream packaging and matched through the Finnish "kookoskerma" in the ingredient list.
Sadly I found neither hard proof those are, nor those are not the exactly same ingredient. The match is only made through the Finnish translation.
**Related issues and discussion:** n/a
=> Taxonomies: Add German / Swedish for "coconut cream"

lib/ProductOpener/Ingredients.pm, t/ingredients_parsing.t, taxonomies/additives.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt
quick pass of italian unknowns, to give it some love as the [stats](https://wiki.openfoodfacts.org/Ingredients_Analysis_Quality_Evaluation_-_March_2020_-_May_2020#IT_-_Italian_-_Italy) had hardly moved since may. :)
=> Taxonomy edits 23 - mostly italian additions

taxonomies/origins.txt
Most popular oceans and seas, up until `ocean-indien-ouest | 16 | *`
=> Oceans and seas

scripts/equadis-import/dereference.sh
=> Automated import through Equadis: ignore T0137:EN (envelope)

.github/workflows/translation-check.yml
=> restrict-l10n-test

lib/ProductOpener/Display.pm, templates/display_product.tt.html
So the browser can decide what to spellcheck it as. Also some tidying.
=> Add lang= attribute to moderator ingredients edit on product view

taxonomies/categories.txt
=> Small taxonomy expansions

html/js/product-preferences.js, html/js/product-search.js, lib/ProductOpener/Display.pm, po/common/common.pot, po/common/en.po, templates/search_results.tt.html
- Changed the "Edit your food preferences" panel to make it smaller and to explain more clearly what it does (based on whether we are on a product page or a list of products page)
- Changed the wording of the tabs
- Added a delete all preferences button
=> Improvements for displaying and editing preferences

scripts/generate_dump_for_offline_apps_off.py
Add support for the Eco-Score for Offline-Scan
=> Add support for the Eco-Score for Offline-Scan

lang/en/texts/data.html
=> Add JSONL data export - closes #3385

lib/ProductOpener/Display.pm
Add stickoncontact option to highcharts scatter plots https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/tooltip/stickoncontact/
Fixes #4519 
Currently live on .dev: https://fr.openfoodfacts.dev/cgi/search.pl?action=process&tagtype_0=categories&tag_contains_0=contains&tag_0=miels&sort_by=unique_scans_n&page_size=20&axis_x=sugars&axis_y=fat&graph=1
=> fixes #4519, graphs links

scripts/gen_pro_users_emails_list.pl
the scripts list users that have an associated organization
=> script to generate a list of producers accounts

scripts/export_database.pl
This fix the timeout issue we have for the CSV export.
(see #3857)
=> increase timeout for export 

html/images/icons/product-silhouette-transparent.svg, html/js/product-search.js, lib/ProductOpener/Display.pm
1. Display product name + brand + quantity and not just product name
2. Display the barcode number if we don't have a product name
3. Display a jar silhouette icon if we don't have a product picture
4. Add a title tooltip when hovering on top of the attributes icons to show what they are and the associated details / recommendation.
=> Improvements for product cards

cgi/product_jqm_multilingual.pl, lib/ProductOpener/Products.pm
=> fix invalid barcode product move issue, fixes #4441

html/files/tagline-off.json
I just see one issue: the blog is still not responsive.
=> tagline-packaging

lang/fr/texts/index-pro.html
Add an experimental "We're here to help" for producers + the Producer Guide (French only at the moment). If that works, we'll scale it.
=> Add an experimental message for producers

lib/ProductOpener/ForestFootprint.pm, lib/ProductOpener/Ingredients.pm, t/expected_test_results/forest_footprint/fr-ingredients-filet-de-poulet-bio-oeuf-label-rouge-os-de-poulet-igp.json, t/expected_test_results/forest_footprint/fr-ingredients-filet-de-poulet-bio.json, t/expected_test_results/forest_footprint/fr-ingredients-nested-matching-ingredient.json, t/expected_test_results/forest_footprint/fr-ingredients-nested-matching-sub-ingredient.json, t/expected_test_results/forest_footprint/fr-ingredients-poulet-du-gers.json, t/expected_test_results/forest_footprint/fr-ingredients-poulet.json
=> Forest footprint small fix

taxonomies/ingredients.txt
I added one Danish and some German translations for ingredients.
=> Mostly German ingredients

html/js/product-search.js
- fixes "1 1 product" -> "1 product"
- fixes a broken HTML tag
=> small fixes for product cards

taxonomies/ingredients.txt
Added German "ingredient list end words" and one stopword.
I am not sure about the syntax. I try to keep the edits small so if there is a fatal mistake it is not to much work which goes to waste.
=> mostly added German words that end the ingredient list

lib/ProductOpener/Ingredients.pm, t/expected_test_results/ingredients/es-percent-loop.json, t/expected_test_results/ingredients/xx-single-letters.json, t/ingredients.t
=> fix ingredients percent loop, fixes #4575

lib/ProductOpener/Import.pm
=> import products on another server (obf etc.) only if they do not exist on target server

po/common/fr.po
Translations for the Empreinte Forêt. At this point, I'm not quite sure anymore what should stay in or out, so please review thoroughly. I'll do another PR for other languages.
=> Translations for the Empreinte Forêt

lang/fr/texts/empreinte-foret-des-produits-alimentaires.html, lib/ProductOpener/Display.pm, templates/display_product.tt.html
- enable the display of the forest footprint for France (and for moderators in all countries)
- small Forest Footprint information page (just a start, we'll flesh it out later)
- change link to info page in template
=> enable display of forest footprint in France

lib/ProductOpener/Display.pm, templates/ecoscore_details.tt.html
Added a little bit of structure to the details of the computation.
There will probably be more to come, e.g. some icons, probably some details about the LCA impacts of ingredients, processing, transportation etc.
=> better ecoscore details display

taxonomies/ingredients.txt
Adding one widely used Spanish synonym for High-fructose corn syrup
=> Add 1 Spanish synonym

taxonomies/packaging_materials.txt, taxonomies/packaging_recycling.txt, taxonomies/packaging_shapes.txt
Added German translations for packaging taxonomies.
=> Add german translations for packaging taxonomies

lib/ProductOpener/Food.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/Producers.pm, t/producers.t
one producer is sending packaging text :)
=> add support for importing packaging image and text through producers platform

lib/ProductOpener/Import.pm
needed for a Spanish producer who sends % of fruits
=> fix % unit specified in imports

po/common/fr.po
Cherrypick fr.po as I fix the rest of languages in a separate PR.
=> Cherrypick fr.po

taxonomies/labels.txt
=> Add xx:AT-BIO-301 thingies (translations)

taxonomies/categories.txt
**Checklist:**
Added agribalyse proxy for dates
=> Added agribalyse proxy for dates

lib/ProductOpener/Display.pm, templates/donate_banner.tt.html
Currently in English and French, we should add more languages.
=> update donate banner with text banner

taxonomies/additives_classes.txt
=> cs antioxidanty

lang/en/texts/logo.html
Add icon to press page (need icon deployment from preview PR)
=> Add icon to press page

.gitignore, docker/backend-dev/conf/Config.pm, docker/docker-compose.dev.yml
- mount the logs for easier debugging as suggested by @leventgunay 
- update Config.pm so that it loads the new taxonomies (and also add support for many other things like product attributes)
fixes #4591
=> mount logs, update Config.pm, fixes #4591

.eslintrc.js, html/js/search.js
=> fix #4307 and improve focus by rolling.

lib/ProductOpener/Export.pm, lib/ProductOpener/Images.pm, lib/ProductOpener/Import.pm
- Added packaging images
- Fixes a bug related to the coordinates of selected images (whether they were related to a 400x400 image or to the full image)
=> Small bug fixes related to exporting and importing cropped photos from the producers platform

taxonomies/labels.txt
Some label translations, mostly sourced from the unknown ingredient lists of dk, fi, is, and no domains.
=> Nordic label translations W52

taxonomies/categories.txt
See https://wiki.openfoodfacts.org/Olive_oil_-_en for an explanation
=> Added olive oil related categories

cgi/search.pl
small fix to support more than 2 nutrient filters in search api v0/v1
fixes #4655
=> fixes #4655, more than 2 nutrient filters

lib/ProductOpener/Ingredients.pm
Mostly `ignore_regexps` so as not to remove anything useful following them.
=> Ingredient analyzer patterns sourced from Nordic ingredient lists

taxonomies/labels.txt
[Per issue #4600](https://github.com/openfoodfacts/openfoodfacts-server/issues/4600)
Thanks!
=> Adding "Sin TACC", gluten-free label in Argentina

taxonomies/ingredients.txt
=> Milk-related Spanish synonyms

cgi/product_image_crop.pl, lib/ProductOpener/Images.pm
=> fix cropping issue for small images, fixes #4678

taxonomies/categories.txt
More spanish olive oil repairs
=> More spanish olive oil repairs

taxonomies/ingredients.txt
=> Synonyms for citrus pectin

lib/ProductOpener/Display.pm
This is to speed up MongoDB count queries (see #4705). It re-uses the smaller  products_tags collection introduced by @syl10100
=> when possible, run count on products_tags collection, #4705

cgi/product_multilingual.pl
Needed for Ecoscore testing.
fixes #4707
=> let admins edit infocards, fixes #4707

lib/ProductOpener/Images.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/ImportConvert.pm, lib/ProductOpener/Packaging.pm, t/images.t
compute the ecoscore when we import products
=> small fixes for producers platform

po/common/fr.po
=> French translations for Eco-Score

lib/ProductOpener/Config_off.pm, lib/ProductOpener/Display.pm
=> Attributes : enable forest footprint + add factor and minimum_match for preferences

lib/ProductOpener/Display.pm
=> display products even if count is 0, workaround for #4729

lang/en/texts/ecoscore-the-environmental-impact-of-food-products.html
=> Eco-Score page in English

lib/ProductOpener/Import.pm
This should solve the root cause of #4733 : bad nutrition_data_per values from equadis imports.
=> equadis import - fix for nutrition_data_per / nutrition_data_prepared_per

taxonomies/stores.txt
This is the list of the most predominant stores in Israel with their Wikidata items notation.
=> Added the Israeli stores

lang/en/texts/open-food-facts-vision-mission-values-and-programs.html, po/common/common.pot, po/common/en.po, templates/display_new.tt.html
This is to deploy the text that was discussed on Slack and on Google Doc: https://docs.google.com/document/d/1edx2Rr2vW1l9wCrDMnydaAb-cwSKKByz6a1ZPkbhJ0g/edit#
=> Add OFF vision, mission, values and programs text and link

lib/ProductOpener/Packaging.pm, t/expected_test_results/packaging/packaging_fr_redundant_entries.json, t/packaging.t
=> better combination of packaging tags, fix #4752

README.md
Add a design section to the README
=> Add a design section to the README

taxonomies/packaging_materials.txt
Hoping we can pull some useful data and translations from there
=> Added some wikidata links

taxonomies/ingredients.txt
=> Adding Durum synonyms used in Argentina

lib/ProductOpener/Import.pm, scripts/export_producers_platform_data_to_public_database.sh
- Map some sub orgs to nestle-france
- Synchronize unilever-france-rhd
=> New orgs from Equadis

scripts/export_producers_platform_data_to_public_database.sh
=> add org-panzani-sa, org-cristalco to nightly equadis imports

lib/ProductOpener/Import.pm
=> add mapping table from GLN to org-ids for GS1/Equadis imports

cgi/reset_password.pl, cgi/session.pl, lib/ProductOpener/Display.pm, lib/ProductOpener/Users.pm, po/common/common.pot, po/common/en.po, po/common/fr.po, templates/reset_password.tt.html
- fix reset password issue
- add more logs
- add better feedback for users
- add link to reset password
=> fix reset password bug #4734

scripts/update_all_products.pl
small improvement to allow OR queries
=> update_all_products.pl script - allow OR queries for tags

lib/ProductOpener/ImportConvert.pm, lib/ProductOpener/Producers.pm, taxonomies/ingredients.txt
+ a couple of missing ingredients
=> small fixes for ldc import

taxonomies/packaging_shapes.txt
Add mold to possible packaging shapes
=> Add mold to possible packaging shapes

cgi/product_multilingual.pl, po/common/common.pot, po/common/en.po
fixes #4776 / fixes #1090 (for moderators)
fixes #1141 (for everyone)
=> buttons to remove nutrients, fixes #4776 #1141

lib/ProductOpener/Attributes.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/Ecoscore.pm, t/ecoscore.t, t/expected_test_results/ecoscore/category-without-ecoscore-sodas.json, t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json, t/expected_test_results/ecoscore/ingredient-palm-oil.json, t/expected_test_results/ecoscore/known-category-butters.json, t/expected_test_results/ecoscore/known-category-margarines.json, t/expected_test_results/ecoscore/label-organic.json, t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json, t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json, t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json, t/expected_test_results/ecoscore/origins-of-ingredients-nested.json, t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json, t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json, t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json, t/expected_test_results/ecoscore/origins-of-ingredients-specified.json, t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json, t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json, t/expected_test_results/ecoscore/packaging-en-multiple.json, t/expected_test_results/ecoscore/packaging-en-pet-bottle.json, t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json, t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json, t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
changes for sodas and beverages
=> Implement new Eco-Score formula, fixes #4783

taxonomies/additives.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt
All taken from ingredient list of Danish products I added
=> Added Danish taxonomy

lang/en/texts/data.html
I just wrote a data contribution section for the Dart package, and I felt it would be useful here.
=> Data contribution section

t/ingredients_processing.t, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/packaging_materials.txt
Added random German translation and ingredients I found to be missing
=> Added German translations and some new ingredients

lang/en/texts/how-to-add-a-product.html
Some accessibility fixes on how to add a product page
=> Accessibility fixes on the "How to add a product" page

scripts/packager-codes/non-eu/README.md
Small addition to the Python doc for Outside EU codes
Related: https://github.com/openfoodfacts/openfoodfacts-server/issues/4030
=> Small addition to the Python doc for Outside EU codes

taxonomies/countries.txt
Add wikidata to countries in /taxonomies/countries.txt
=> Add wikidata to countries

scripts/export_database.pl
in production it took 72 minutes yesterday
=> increase timeout to 3 hours for export mongodb query

lang/en/texts/index-pro.html, lang/fr/texts/index-pro.html
Experimental promo for the producer platform
=> Experimental promo for the producer platform

taxonomies.obf/allergens.txt
=> EU allergens for OBF

taxonomies/labels.txt
EG Oko-Verordnung is EU Organic
=> EG Oko-Verordnung is EU Organic

lang/en/texts/google-summer-of-code.html
Initial updates for GSOC 2021. Feel free to amend this PR, or to make subsequent ones.
=> Initial updates for GSOC 2021

taxonomies/origins.txt
Small additions for the origins taxonomy
=> Additions for the origins taxonomy

lib/ProductOpener/ImportConvert.pm, t/import.t
e.g. "Nutriscore_A"
also a fix to convert "NESTLE, RICORE" to "Nestle, Ricore" and not "Nestle, ricore"
=> small improvements to handle more variations of producer data

taxonomies/ingredients.txt
new ingredients from https://github.com/openfoodfacts/openfoodfacts-server/pull/3842
=> fodmap ingredients from @etatdesprit

taxonomies/labels.txt
=> Added the Israeli Mandatory labels

taxonomies.obf/safety.txt
Global safety taxonomy for OBF
=> Global safety taxonomy for OBF

lib/ProductOpener/Ingredients.pm, t/ingredients_parsing.t
e.g. "Sel, sucre², graisse de palme¹, amidons¹ (maïs¹, pomme de terre¹), oignon¹ : 8,9%, ail¹, oignon grillé¹ : 1,4%, épices¹ et aromate¹ (livèche¹ : 0,4%, curcuma¹, noix de muscade¹), carotte¹ : 0,5%. Peut contenir : céleri, céréales contenant du gluten, lait, moutarde, œuf, soja. ¹Ingrédients issus de l'Agriculture Biologique. ² Ingrédients issus du commerce équitable"
=> handle ¹ and ² symbols in ingredients lists

scripts/export_producers_platform_data_to_public_database.sh
=> equadis - sync materne + garofalo-france

cgi/org.pl, lib/ProductOpener/Display.pm
=> allow org admins to edit org profile, fixes #4854

lang/fr/texts/logo.html
=> French Press page update

cgi/product_image_move.pl, lib/ProductOpener/Images.pm, lib/ProductOpener/Products.pm
fixes #4880 
tricky but seems to be working
=> Move images between servers

lib/ProductOpener/Display.pm
as we now have the Eco-Score. Otherwise it is quite confusing.
fixes #4875
=> remove old ecological table

lang/de/texts/index-pro.html, lang/en/texts/index-pro.html
Multilingual help for the producer platform
=> Multilingual help for the producer platform

lib/ProductOpener/Display.pm, templates/ecoscore_details_simple_html.tt.html
Fixes #4662
The apps need to be changed to send the language of the app in API queries (e.g. &lc=fr )
=> Return Ecoscore details simple html in the environment_infocard field displayed in mobile apps

lib/ProductOpener/Ecoscore.pm, t/expected_test_results/ecoscore/packaging-en-multiple.json
fr_packaging_shapes.csv has some values like "0,2".
=> fix some packaging ratios: convert comma to dot

taxonomies/ingredients.txt
Hi!
I want to translate as many ingredients from Russian as possible and this is my first attempt at learning how to properly change the ingredients.txt file :)
For this PR I picked all the salt I could find here: https://ru.openfoodfacts.org/ingredients?status=unknown&limit=10000
I'm still not sure about the `-` symbol though - the ingredients page has all whitespaces replaced by `-`, but if you look at the products their ingredients have whitespaces in names, not `-`.
=> Add Russian salt to taxonomies/ingredients.txt

.github/workflows/crowdin.yml
Restrict Crowdin sync to pushes on Master
=> Restrict Crowdin sync to pushes on Master

taxonomies/additives_classes.txt
Adding some Russian additive classes (in singular and plural forms).
=> Add some Russian additive classes

taxonomies/ingredients.txt
Adding some Russian ingredients.
=> Add some Russian ingredients to taxonomies/ingredients.txt

lib/ProductOpener/ImportConvert.pm, t/import.t
This is an improvement to the regexp that removes the quantity from the product name.
=> Small fix for imports: escape parenthesis in quantity regexp

taxonomies/additives_classes.txt, taxonomies/ingredients.txt
Adding some Russian ingredients and additives classes
=> Adding some Russian ingredients and additives classes

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/ingredients.txt
Adding some Russian ingredients, additives and additives classes
=> Add some Russian ingredients, additives and additives classes

cgi/user.pl, lib/ProductOpener/Users.pm, po/common/common.pot, po/common/en.po, templates/user_form.tt.html
This makes the existing "delete user" checkbox in the user edit form work.
fixes #3596
=> allow admins to delete users

lib/ProductOpener/Producers.pm
Just a few more French synonyms found in a producer file.
=> producers platform : recognize more French column names (easy review)

taxonomies/categories.txt
Maybe we should go through the EU database to add al PGI's?
=> Cioccolato di Modico

t/additives.t, taxonomies/additives.txt
=> add French synonym for E410 (easy review)

templates/ecoscore_details_simple_html.tt.html
The Agribayse domain name has changed. This PR puts the new agribalyse URL structure in the Eco-Score template.
=> new agribalyse URL structure (easy to review)

po/openproductsfacts/openproductsfacts.pot
=> crowdin-hint

lib/ProductOpener/GS1.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/Products.pm
- map "BEL FRANCE" GLN to the existing "Groupe Bel" org
- add "CodeOnline", "Equadis" and "GSDN" to the data sources field
=> small changes for codeonline import

taxonomies/additives.txt, taxonomies/ingredients.txt, taxonomies/minerals.txt
Adding some Russian additives, ingredients and minerals.
=> Add some Russian additives, ingredients and minerals

lib/ProductOpener/Food.pm, lib/ProductOpener/Import.pm, scripts/codeonline-import/stats_gs1_codeonline_json.pl, taxonomies/labels.txt
Small improvements for the producers platform.
=> Producers : map Garofalo to Panzani org + added oligosaccharides

templates/ecoscore_details_simple_html.tt.html
=> remove-unopened-divs

templates/user_form.tt.html
=> display register or save in user form submit button, fixes #4889

lib/ProductOpener/Ingredients.pm, t/ingredients_tags.t
=> Add Russian and/or support in ingredients analysis

taxonomies/states.txt
translations for the states taxonomy
=> translations for the states taxonomy

taxonomies/origins.txt
=> Translations for origins

lib/ProductOpener/Images.pm, t/images.t
fixes #4951 and #4971
added corresponding tests
=> Improve filename to imagefield match for producers platform bulk image upload

taxonomies/ingredients.txt
Adding a few Russian ingredients
=> Add a few Russian ingredients

lib/ProductOpener/Users.pm
Small fix for producer platform emails
=> Usability fix for producer platform emails

po/common/common.pot, po/common/en.po
needed for new features from previous commit
=> New strings for producers platform

lib/ProductOpener/Food.pm
=> Small fixes for Italy

taxonomies/labels.txt
Translations for the labels taxonomy
Note: some translations on xx:Labels
=> Translations for the labels taxonomy

taxonomies/additives.txt
Translations for the additives taxonomy
A first review pass would be welcome
=> Translations for the additives taxonomy

taxonomies/ingredients.txt
Adding some Russian ingredients
=> Add some Russian ingredients

cgi/import_file_select_format.pl, lib/ProductOpener/Export.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/ImportConvert.pm, lib/ProductOpener/Producers.pm, t/import.t
This solves issues with data we got from producers that was unexpected, and a bug regarding the obsolete products.
=> Import: fix for "not specified" values, fix for obsolete and unobsolete

lib/ProductOpener/Attributes.pm, t/expected_test_results/attributes/en-attributes.json, t/expected_test_results/attributes/fr-palm-oil-free.json, t/expected_test_results/attributes/fr-palm-oil.json, t/expected_test_results/attributes/fr-sesame-seeds.json, t/expected_test_results/attributes/fr-vegetable-oils.json
Fix issues introduced while fixing #5007 
+ new tests
=> Fix attributes issues

cpanfile
Updates all renewed CPAN packages to the recent versions.
=> Bump CPAN dependencies

lib/ProductOpener/Users.pm
Fix the HTML emails for the producers admins.
=> update producers message

taxonomies/containers.txt
New Portuguese translations and a few fixes in Portuguese existing translations. 
Added also English translation "en:Plate"
=> Portuguese translation in containers.txt

cgi/export_products.pl
Follow-up email for export requests
=> Follow-up email for export requests

po/common/common.pot, po/common/en.po, po/common/fr.po
=> Indicate source of data for CodeOnline and Equadis + dedicated pages

taxonomies/packaging_recycling.result.txt
Adding Portuguese translations for packaging_recycling.result.txt
=> Translations for packaging_recycling.result.txt

lang/en/texts/faq.html, lang/en/texts/who-we-are.html
Removed uservoice links 
I hope this is the correct file to edit, the same files need to be updated in openfoodfacts-web too.
Ref: https://openfoodfacts.slack.com/archives/C02KVRT2C/p1616595558021000
CC: @stephanegigandet
=> Removed uservoice links

lib/ProductOpener/Food.pm, lib/ProductOpener/Import.pm
A recent fix for imports that have only the field "energy" field (and not energy-kj and/or energy-kcal) caused another bug: the "energy" field is not set anymore. This fixes the fix.
=> fix energy bug

taxonomies/recycling_instructions.txt
Adding Portuguese translations for recycling_instructions.txt
=> Translations for recycling_instructions.txt

taxonomies/ingredients.txt
Translations for the ingredients taxonomy
=> Translations for the ingredients taxonomy

docker/README.md, docker/backend/Dockerfile, docker/build_dev.sh, installation/dev-environment-quick-start-guide.md
Updated the readme to add the "docker-compose -f ./docker-compose.yml -f ./docker-compose.dev.yml build backend" step suggested by @svensven 
Fixes #5043
=> update docker readme to add backend build step

po/common/common.pot, po/common/en.po, templates/display_product.tt.html, templates/ecoscore_details.tt.html, templates/ecoscore_details_simple_html.tt.html
Internationalization of the (forest footprint + ecoscore) warnings and computation details
- product page insert
- mobile insert
=> Internationalization of the (forest footprint + ecoscore) warnings and computation details

cgi/test_ingredients_analysis.pl, templates/test_ingredients_analysis.tt.html
Description: Templatization of the file `cgi/test_ingredients_analysis.pl`
Fixes: https://github.com/openfoodfacts/openfoodfacts-server/issues/5095
=> Test Ingredients Analysis Templatization

po/common/common.pot, po/common/en.po, templates/ecoscore_details.tt.html, templates/ecoscore_details_simple_html.tt.html
Finished the integration of the strings move to .po files by @teolemon
=> Internationalization of the Eco-Score details template

taxonomies/categories.txt
per Segundo on slack #taxonomies
=> rearrange Calvados categories

cgi/change_password.pl, cgi/login.pl, cgi/product_image.pl, cgi/search.pl, cgi/spellcheck_test.pl, cgi/top_translators.pl
**Description:** Changed the old script files in which the old function `$tt->process()` was used. Updated the files to add the new 
`process_template()` ' function. 
**Updated Files:** 
1. `cgi/change_password.pl`
2. `cgi/login.pl`
3. `cgi/spellcheck_test.pl`
4. `cgi/search.pl`
5. `cgi/product_image.pl`
6. `cgi/top_translators.pl`
**Fixes:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5132
=> Updated files

po/common/common.pot, po/common/en.po, po/common/fr.po, templates/display_product.tt.html
The message is slightly different for France and for other countries.
=> Indicate that the Eco-Score is experimental and being internationalized

lib/ProductOpener/Display.pm, po/common/common.pot, po/common/en.po, po/common/fr.po, templates/display_new.tt.html
fixes #5092
I added a way to have different messages based on page type at first (e.g. product page or not), but I don't have a very good idea of a page specific message, so I guess let's keep it simple.
=> Add app stores logo in app banner on mobile web

taxonomies/allergens.txt
Adding and fixing Portuguese translations for allergens.txt
=> Translations for allergens.txt

taxonomies/states.txt
Adding and fixing Portuguese translations for states.txt
=> Translations for states.txt

taxonomies/nova_groups.txt
Adding and fixing Portuguese translations for nova-groups.txt
=> Translations for nova-groups.txt

taxonomies/ingredients_analysis.txt
Adding and fixing Portuguese translations for ingredients_analysis.txt
=> Translations for ingredients_analysis.txt

taxonomies/other_nutritional_substances.txt
Adding Portuguese translation for other_nutritional_substances.txt
=> Translation for other_nutritional_substances.txt

taxonomies/periods_after_opening.txt
Adding Portuguese translations for periods_after_opening.txt
=>  Translations for periods_after_opening.txt

po/common/en.po
=> remove dupes

cgi/user2.pl, templates/user_form2.tt.html, templates/user_form2.tt.js
1. Created three new files to provide the same functionality `user.pl` and `user-form.tt.html` were providing.
2. `user.pl` uses three functions defined in `Users.pm` for user creation and user profile form. These three functions consist highly of HTML.
3. The newly created three files which can be viewed in this PR are using Template::Toolkit to provide the same functionality and remove the usage of HTML including functions. 
4. Moreover, removed the usage of `<table>` to make the form responsive.
**Related issues and discussion:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5106
=> Refactor the user creation / user profile form

templates/display_product.tt.html
To allow use of # in the URL and content manipulation with JS.
=> Add ids to <h2> levels

lib/ProductOpener/Config_off.pm, scripts/export_database.pl
currently only the French Eco-Score
=> Add ecoscore in CSV export

README.md
for the Personal Search project
=> add NlNet / NGI logo in sponsors

taxonomies/stores.txt
Adding  stores in Portugal, Brazil, Angola, Netherlands and United States of America
=> Translations for stores.txt

po/tags/hu.po
Completing Tag translation and fixing previous mistakes.
=> Update Hungarian tag translation

README.md
The number of products on OFF is increasing rapidly. Updated to show the current number of products.
=> Updated data of products in README.md file

lib/ProductOpener/DataQualityFood.pm
small fix for products with prepared nutrition data
=> fix for data quality en:all-nutrition-values-set-to-0

package-lock.json, package.json
=> result of npm update

t/nutriscore.t, taxonomies/ingredients.result.txt, taxonomies/ingredients.txt
=> count mushrooms and algae as vegetables for nutriscore, fixes #5223

lib/ProductOpener/DataQualityFood.pm
fruits vegetables estimate is a computed value, it should not count for empty / non-empty values
=> small fix for data quality food facet

taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt
Small changes to have less unknown ingredients for "cassoulets".
Added the "soaked" processing (for soaked beans)
=> ingredients and ingredients processing taxonomy changes for cassoulets

taxonomies/ingredients.txt
needed to get the right nutriscore for some products
=> add ingredient fr:féverole, féverolle

templates/display_new.tt.html
=> Show 'Chat with us' on producers platform

docker/backend-dev/conf/Config2_pro.pm, docker/backend-dev/conf/minion_log.conf, docker/backend-pro-dev/conf/.gitattributes, docker/backend-pro-dev/conf/Config.pm, docker/backend-pro-dev/conf/Config2.pm, docker/backend-pro-dev/conf/apache.conf, docker/backend-pro-dev/conf/log.conf, docker/backend-pro-dev/conf/minion_log.conf, docker/backend-pro-dev/conf/po-foreground.sh, docker/backend-pro-dev/scripts/import_sample_data.sh, docker/backend-pro/Dockerfile, docker/backend/Dockerfile, docker/build_pro_dev.sh, docker/docker-compose.pro.dev.yml, docker/docker-compose.pro.yml, docker/docker-compose.yml, docker/frontend-git/conf/nginx.conf, docker/start_pro_dev.sh
Everything is not working yet, but this makes a few things work.
Tracking bug: #5258
=> Changes to make the producers platform work in Docker

cgi/import_file_process.pl, templates/import_file_process.tt.html, templates/import_file_process.tt.js
**Description**
Added the template files for `cgi/import_file_process.pl`. 
**Fixes:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5254
=> Added template files for import_file_process.pl

po/common/zh_CN.po
Manual update for Chinese from Crowdin since automatic does not seem to work for Chinese
=> Updates for Chinese from Crowdin

docker/backend-dev/conf/po-foreground.sh, docker/backend-pro-dev/conf/po-foreground.sh
**Description:** Changed the script in `docker/backend-pro-dev/conf/po-foreground.sh` to add `orgs` directory. 
**Fixes:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5284
=> Added orgs directory

templates/change_password.tt.html, templates/login.tt.html, templates/reset_password.tt.html
Fixes: https://github.com/openfoodfacts/openfoodfacts-server/issues/5294
=> Updated error_list.tt.html path

templates/org_form.tt.html
Fixes: https://github.com/openfoodfacts/openfoodfacts-server/issues/5294
=> Updated path of error_list.tt.html in org_from.tt.html

installation/dev-environment-quick-start-guide.md
Added a subheading for setting up the producer environment on a local machine.
=> Update dev-environment-quick-start-guide.md to add producer's platform section

installation/Developer-guide.md
Added a developer's guide which consists of different useful commands. These commands can help newcomers and contributors.
=> Added Developer's Guide

taxonomies/categories.txt
=> Italian products

lib/ProductOpener/Display.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/Orgs.pm, templates/emails/import_csv_file_admin_notification.tt.html
This is for USDA and CodeOnline imports, to get stats about the number of products for each organization, see which organizations were created, are unauthorized etc.
=> Add support for multi orgs imports + new email notification report for imports (USDA, CodeOnline)

cgi/import_photos_upload.pl, templates/web/pages/import_photos_upload/import_photos_upload.tt.html, templates/web/pages/import_photos_upload/import_photos_upload.tt.js
Added the template for the HTML code of the form in `import_photo_upload.pl`.
=> Templatization of import_photo_upload.pl

cgi/import_products_categories_from_public_database.pl, templates/web/pages/import_product_categories_process/import_product_categories_from_public_database_process.tt.html, templates/web/pages/import_product_categories_process/import_product_categories_from_public_database_process.tt.js
Description:
* Added a new template file for process part of `import_product_categories_from_public_database`. 
* Changed the `<div>` tags to `<span>` for better UI.
=> Templatization of import_product_categories_from_public_database

scripts/usda-import/README.md, scripts/usda-import/deduplicate_usda.sh, scripts/usda-import/import_usda.sh, scripts/usda-import/keep_most_recent_row_for_each_product.py
Adding some docs next to the code. The readme is not yet in markdown and is missing things, we can add to it later.
Also added a step to remove all the duplicate entries in the USDA data.
=> USDA import - start of readme file + deduplicating script

cgi/session.pl, templates/web/pages/session/session.tt.html
* Removed the `html` code from `session.pl`.
* Added the template file for `html` code.
**Fixes:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5335
=> Templatization of session.pl

cgi/remove_products.pl, templates/web/pages/remove_products/remove_products.tt.html
* Added the template file for `html` code. 
**Fixes**: https://github.com/openfoodfacts/openfoodfacts-server/issues/5333
=> Templatization of remove_products.pl

taxonomies/ingredients.txt
**Description**: Added new products and their missing ingredients in `ingredients.txt`.
=> Added ingredients in ingredients.txt

.github/workflows/crowdin.yml
Reenable partial translations since partial translations (like Japanese) are not coming in until completion.
=> Reenable partial translations

installation/dev-environment-quick-start-guide.md
Added a comment about the docker group to the 'install docker' step.
=> Added a comment about the docker group to the 'install docker' step.

taxonomies/labels.txt
=> Fiber label additions

cgi/org.pl, lib/ProductOpener/Config_off.pm
This is to have checkboxes for codeonline and the USDA in the admin section of the org profile edit form:
=> added import_sources: codeonline, database-usda

taxonomies/categories.result.txt, taxonomies/categories.txt
in particular, frozen mixes should not trigger fresh vegetables
=> Fixed mixed vegetables categories

taxonomies/origins.txt
Translations for the origins taxonomy
=> Translations for the origins taxonomy

taxonomies/ingredients_analysis.txt
Translations for the ingredients analysis taxonomy
=> Translations for the ingredients analysis taxonomy

taxonomies/ingredients.txt
For product https://fr.openfoodfacts.org/produit/3273220085301/dessert-vegetal-noisette-amande-sojasun
I do now know how to add `sels de calcium`, as there are many of those.
=> New ingredients

lib/ProductOpener/Display.pm, templates/web/common/includes/display_login_register.tt.html
**Description:** Added template file for the function `display_login_register()` and moved the HTML part. 
**Fixes:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5409
=> Template file for display_login_register of Display.pm

taxonomies/nutrient_levels.result.txt
Please inform me if I need to change the sources for these strings.
=> Some Hebrew fixes

templates/web/pages/import_file_process/import_file_process.tt.js
=> fix JS issue in import_file_process

lib/ProductOpener/Import.pm
We use the producers platform to load product data from some 3rd parties. For instance some labels such as Bleu Blanc Coeur send us the list of all products with their label. Usually we have a few fields like product name or brand.
The product names etc. might not be the best ones though. So we should not import them over fields that have already been imported by the actual owner of the product.
=> Prevent imports from overwriting fields already set by the owner

lib/ProductOpener/Attributes.pm, t/expected_test_results/attributes/en-attributes.json, t/expected_test_results/attributes/fr-palm-kernel-fat.json, t/expected_test_results/attributes/fr-palm-oil-free.json, t/expected_test_results/attributes/fr-palm-oil.json, t/expected_test_results/attributes/fr-vegetable-oils.json
Put additives attribute in the processing attributes group.
Fixes #4702
=> fix attribute group for additives attribute

lib/ProductOpener/Display.pm, templates/web/common/includes/display_my_block.tt.html
Add missing links on the side column.
=> Fix my products links

templates/web/pages/product_edit/product_edit_form_display.tt.html
**Fixed:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5425
**Description:** Removed extra spaces, Fixed the indentation and fixed the bug.
=> Fixed the UI bug of product page

installation/Developer-guide.md
Updated the `Developer Guide`. Added the script to restart docker backend-pro without quitting the rest of the environment.
=> Added script for running docker_backend-pro

taxonomies/categories.txt
=> Hummus and other categories changes 

taxonomies/ingredients.txt
New ingredients for: https://world.openfoodfacts.org/product/8712423024588/danie-makaron-bolognese-knorr
Mainly in Polish
=> add missing ingredients

taxonomies/ingredients.txt
=> Added herb sumac to ingredients tax

taxonomies/ingredients.txt
* Move some mis-translations.
* Add some plural and declensed forms.
* Remove "harilik" ("common") prefix from some plants which is rarely used in actual writing/speaking.
* Add some colloquial forms of words.
(I am a native Estonian speaker)
=> Fix and improve Estonian ingredients

lib/ProductOpener/Display.pm
**Description:**  Changed the domain to the `http://world.productopener.localhost` to keep it permanent. 
**Related to:** https://github.com/openfoodfacts/openfoodfacts-server/issues/5416
=> Fixing the SEO of product page

.github/ISSUE_TEMPLATE/epic.md
Encourage more hierarchy in issues and epics
=> Add the Part of section

lib/ProductOpener/Display.pm, templates/web/common/includes/display_list_of_tags_translate.tt.html
=> Templatization for display_list_of_tags_translate() in Display.pm

installation/dev-environment-quick-start-guide.md
=> Update documentation for setting up PO server locally.

po/openbeautyfacts/openbeautyfacts.pot
=> Fix typo in Footer link

docker/backend-dev/conf/Config.pm, docker/backend-dev/conf/Config2.pm, docker/backend-dev/conf/apache.conf, lib/ProductOpener/Images.pm
Fixes Google Cloud Vision OCR in dev env
=> Fix Google Cloud Vision OCR

.github/workflows/crowdin.yml
=> trigger-crowdin-less-often

lib/ProductOpener/Display.pm, templates/web/common/site_layout.tt.html
**Related issues and discussion:** #5261
=> 2 more ids + small fixes

html/files/knowledge_panel_test.json
This is a test file to demonstrate the response format of the new Knowledge Panels API (see https://docs.google.com/document/d/1vJ9gatmv8pCXxyOERmYD16jOKRWJpz1RaQQ5MEcTxms/edit#heading=h.f5zx2tcu9c5t )
Test file on https://fr.openfoodfacts.dev/files/knowledge_panel_test.json (login and pass: off)
=> test file for knowledge panels

scripts/run_cloud_vision_ocr.pl
This is so that the .dev / .net product opener instances can call the corresponding dev robotoff instances.
Note that I'm getting a "rejected" message from robotoff:
off@ns3135968:/srv/off/scripts$ tail ../logs/run_cloud_vision_ocr.log 
..
file: /srv/off/new_images/1616750415.3560071009380.search.11.jpg destination: /srv/off/html/images/products/356/007/100/9380/11.jpg code: 3560071009380 image_url: https://static.openfoodfacts.dev/images/products/356/007/100/9380/11.jpg json_file: /srv/off/html/images/products/356/007/100/9380/11.json
--> cloud vision success
--> robotoff success: {"status":"rejected"}
=> use robotoff_url variable to notify the right robotoff instance after ocr

lib/ProductOpener/Display.pm, lib/ProductOpener/KnowledgePanels.pm
- Start of #5541:
- added a way to request knowledge panels, similar to the product attributes API
- started to implement the Eco-Score panels
to test: https://world.openfoodfacts.dev/api/v2/product/3017620422003/nutella-ferrero?fields=knowledge_panels
- #5493
=> Initial plumbing for knowledge panels API + start of Eco-Score panel

taxonomies/packaging_materials.txt
increase packaging taxonomization by adding XX: entries
- #5520
=> increase packaging taxonomization

taxonomies/brands.txt
- Add more organic brands to feed https://github.com/openfoodfacts/openfoodfacts-server/issues/3426
- #5520
=> Add more organic brands

taxonomies/labels.txt
**Related issues and discussion:** #5624
=> Add Eco-Score label

installation/dev-environment-quick-start-guide.md
Added how to solve my persistent docker problem.
=> Added a solution to a docker problem.

html/files/app/tagline/tagline-off-ios.json, html/files/tagline-off.json
Tweak the app tagline to get more answers to the survey
Solves #5630
=> Survey tagline

lib/ProductOpener/Attributes.pm, t/expected_test_results/attributes/en-attributes.json, t/expected_test_results/attributes/en-nutriscore.json
Fixes #5636
This fixes the computation of the Nutri-Score attribute score (we go from a scale of -15 to 40 to a scale of 0 to 100, but we need to make sure that A / B / C / D / E grades are between 100-81, 80-61 etc. even though the Nutri-Score scale is not linear...
=> Fix match score computation for Nutri-Score attribute 

templates/web/common/site_layout.tt.html
- I accidentally merged the loading of the crowdin javascript while experimenting with #5610 
- This is to disable loading the button, except for one language (Russian), for experimental purposes.
- #5528
=> disable crowdin button, except for ru

scripts/run_cloud_vision_ocr.pl
more details in logs to debug issue with cloud vision OCR incrond setup
=> more info in logs for run_cloud_vision_ocr.pl script

t/templates.t
Fixes #5666 
Should make the tests for #5650 fail.
=> Add tests for Template::Toolkit templates 

.github/workflows/mongo-deploy.yml
Also re-deploy mongodb when an edit to the GitHub action is made. Fix `make prune` command.
=> Fix mongo deployment

templates/web/common/site_layout.tt.html
- Reenable the call to translations on more languages
- Related to https://github.com/openfoodfacts/openfoodfacts-server/pull/5646
Speed up translations
https://ru.openfoodfacts.org/ (you have to be logged in, bottom right)
=> Reenable the call to translations on more languages

scripts/po-foreground.sh
If it doesn't exist, incron will not monitor it :(
=> Create new_images folder on startup

conf/nginx.conf, conf/nginx/sites-available/off
This is to save what we have in prod, we'll need to make the spaces/tabs etc. more consistent.
=> update nginx config file from production

Makefile, docker-compose.yml, scripts/import_sample_data.sh, scripts/po-foreground.sh
Fixes dev setup permissions + cleanup permission sets + creation of /mnt/podata folders
=> fix: set local permissions correctly

.github/workflows/daily.yml, Makefile
Jobs currently timeout after 10m, increasing to 20m.
=> ci: increase command timeout for daily tasks

lib/ProductOpener/Display.pm, templates/api/knowledge-panels/ecoscore/agribalyse.tt.json, templates/api/knowledge-panels/ecoscore/ecoscore.tt.json, templates/api/knowledge-panels/ecoscore/ecoscore_unknown.tt.json, templates/api/knowledge-panels/ecoscore/origins_of_ingredients.tt.json, templates/api/knowledge-panels/ecoscore/packaging.tt.json, templates/api/knowledge-panels/ecoscore/production_system.tt.json, templates/api/knowledge-panels/ecoscore/threatened_species.tt.json, templates/web/common/site_layout.tt.html, templates/web/panels/panel.tt.html
=> Panels: renamed element field to text_element, table_element etc.

lib/ProductOpener/Import.pm
Future products from Equadis will be split to the 3 organizations: panzani-sa, garofalo-france, lustucru-frais
I'm in the process of reimporting the existing products so that the 3 orgs have only their own products.
=> Producers: split garofalo france and lustucru frais from panzani sa org

lib/ProductOpener/Recipes.pm, t/expected_test_results/recipes/nectars.guava-nectar.json, t/expected_test_results/recipes/nectars.json, t/expected_test_results/recipes/nectars.strawberry-nectar.json, t/recipes.t
See #5696 for a description of the recipe analysis project.
This PR is the started of a new Recipes.pm module to analyze the distribution of selected parent ingredients for a specific set of products. (e.g. to compare the % of tomato, other vegetables, meat, and cheese in pizzas.
=> Start of implementation of recipes analysis

taxonomies/data_quality.txt
Spanish translations for data quality taxonomy
@hangy @aleene @VaiTon Could you provide translations to German, Dutch, Italian ?
- #5521
=> Spanish translations for data quality taxonomy

README.md
Update API url to new documentation
=> Update API url to new documentation

.github/workflows/crowdin.yml
=> Semantic PR for Crowdin

lib/ProductOpener/Images.pm
=> Do not load jquery.fileupload.js twice, fixes producers platform image upload bug

taxonomies/categories.txt
=> bug fix for bug 5715

lib/ProductOpener/Display.pm
fixes #5782
Makes the query for the ecoscore impact estimator fast. :)
=> feat: Add no_count parameter, rename nocache to no_cache

po/common/en.po
=> fix: Add missing English translations for donate banner

t/additives.t, t/additives_tags.t, taxonomies/additives.txt, taxonomies/ingredients.txt
Repaired the test.
There is an issue with en:turmeric/kurkuma and en:E100/curcumine. The ingredients and additives interfere.
Need to move turmeric from ingredients to additives.
**Related issues and discussion:** #5791
=> test repair

lib/ProductOpener/Recipes.pm
**Checklist:**
*trivial*
Style fix on return statement.
**Related issues and discussion:** #5732
=> fix return statement to please perlcritic. fixes #5732

CONTRIBUTING.md, installation/dev-environment-quick-start-guide.md
Very tiny changes to documentation to connect pages for developer onboarding
=> docs: add some pointers to dev quick start documentation

html/files/app/tagline/tagline-off-ios.json, html/files/tagline-off.json
=> Fix tagline CTAs

cgi/display.pl, lib/ProductOpener/Display.pm
**Checklist:**
*skipped as this is only documentation*
Some docs added while reading code.
=> docs: document analyze_request

html/js/product-preferences.js, scss/_off.scss
- make it possible to select and activate the buttons to select preferences
- add a fieldset around the radio buttons for each attribute
- add empty alt="" for icons (all of them have a text label besides them)
fixes #5818
=> fix: accessibility issues with personal search preferences

html/js/folksonomy.js
Fix bring/brought/brought in Folksonomy Engine
=> Fix bring/brought/brought in Folksonomy Engine

html/images/attributes/src/maybe-vegetarian.svg, html/images/attributes/src/non-vegetarian.svg, html/images/attributes/src/vegetarian-status-unknown.svg, html/images/attributes/src/vegetarian.svg
We currently use a leaf for the vegan icon, and an egg for the vegetarian icon. But we also use the egg icon to indicate the presence of eggs as an allergen, so it can be confusing.
This PR is to change the vegetarian icon:
=> New vegetarian icons

scripts/export_products_data_and_images.pl
=> Fix perlcritic issue: 3 arguments open

po/common/common.pot, po/common/en.po
as suggested in #translations on Slack
=> better wording for ingredients that threaten species

templates/web/common/includes/donate_banner.tt.html
=> Donate 2022 updates

lib/ProductOpener/Ingredients.pm, t/expected_test_results/packaging/packaging_text_nl_doosje_oud_papier.json, t/expected_test_results/packaging/packaging_text_nl_fles_glasbak.json, t/expected_test_results/packaging/packaging_text_nl_over_plastic_afval.json, t/packaging.t, taxonomies/additives.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/materials.txt, taxonomies/packaging_shapes.txt, taxonomies/recycling_bins.txt
I tried to add (some) dutch recycling instructions. But I am not sure I add them to the right files. The instructions often have the structure `<packaging> in/bij <recycling bin>`. Where can I add the structure? And what to do about adding logo's for Robotoff?
=> Dutch specific additions

taxonomies/labels.txt
=> made in (for robotoff)

cgi/css.pl, html/donate/en.html, html/donate/fr.html, html/donate/he.html
fixes #6082
An alternative would be to try to hardcode all subdomains + languages that need RTL, and have some JS code to select the CSS.
But this should be good enough.
=> New /cgi/css.pl to serve LTR or RTL CSS based on subdomain language

lib/ProductOpener/Ingredients.pm, t/expected_test_results/ingredients/en-vegetal-ingredients.json, t/expected_test_results/ingredients/nl-e471-niet-dierlijk.json, t/ingredients.t, t/ingredients_tags.t, taxonomies/labels.result.txt, taxonomies/labels.txt
=> Recognize vegetal ingredients e.g. 'gelatin (from plants)'

html/js/folksonomy.js
Very few changes, but diff is lost because I have reformatted the code.
=> Folksonomy 2

installation/deploy.md
=> minimal documentation for prod deployment

html/donate/en_AU.html, html/donate/fr.helloasso.html, html/donate/he.html, html/donate/it.html, html/donate/kmr.html, html/donate/me.html, html/donate/nl.html, html/donate/ry.html, html/donate/sh.html, html/donate/sr_CS.html
Replaces 2020 or 2021 by 2022.
=> Update donate page year to 2022

.github/workflows/container-deploy.yml
I had put the wrong path to lang folder !
I have also augmented the docker timeout because of actions issues we have (would be better to diagnose why it's so slow though).
=> ops: fix web content path

docker/dev.yml, docker/mongodb.yml
=> fix: remove MONGO_INIT_ROOT_USERNAME/PASSWORD as it breaks the dev workflow"

t/expected_test_results/packaging/packaging_text_nl_blik_bij_restafval.json, t/expected_test_results/packaging/packaging_text_nl_koffiepad_bij_gft.json, t/expected_test_results/packaging/packaging_text_nl_over_plastic_afval.json, t/expected_test_results/packaging/packaging_text_nl_plastic_fles.json, t/expected_test_results/packaging/packaging_text_nl_statiegeldfles.json, t/expected_test_results/packaging/packaging_text_nl_three_instructions.json, t/expected_test_results/packaging/packaging_text_nl_verpakking_bij_drankencartons.json, t/expected_test_results/packaging/packaging_text_nl_wel_pmd.json, t/packaging.t, taxonomies/packaging_materials.txt, taxonomies/packaging_recycling.txt, taxonomies/packaging_shapes.txt
Dutch recycling bins and instructions and tests
=> Dutch recycling

html/donate/en.html, html/donate/fr.helloasso.html
Help us to fund -> help us fund
Removed "A message from the OFF team"
=> Minor changes to shorten text

html/donate/en.html, html/donate/fr.helloasso.html, lib/ProductOpener/Display.pm, templates/web/common/includes/donate_banner.tt.html
currently live on https://fr.openfoodfacts.dev/
=> Replace French Eco-Score banner by donation banner

taxonomies/ingredients.result.txt
tests seem to be failing because the ingredients taxonomy is not built
=> built ingredients taxonomy

cgi/reset_password.pl, cgi/user.pl, lib/ProductOpener/Import.pm, lib/ProductOpener/Orgs.pm, lib/ProductOpener/Users.pm
=> move users_emails.sto and orgs_glns.sto to /users and /orgs

.github/workflows/container-deploy.yml, .github/workflows/pull_request.yml, docker-compose.yml
This will help validate the developer workflow on new changes
=> ci: run dev workflow on pull requests

lib/ProductOpener/Display.pm
fixes #6157
removing some fields with : in key names, that are internal fields anyway.
=> fix XML API issue

docs/introduction/dev-environment-quick-start-guide.md
Fix of two broken links in docs
=> docs: fix two links - fixes #6163

lib/ProductOpener/Food.pm
=> remove nutriscore fiber warning if not specified on product 

lib/ProductOpener/Food.pm, scripts/update_all_products.pl
recently deployed changes resulted in the checkboxes for "nutrition specified" to be turned off.
=> fix issue with nutrition facts edits through API

.env, .github/workflows/container-deploy.yml, conf/nginx.conf, docker-compose.yml, docker/admin-uis.yml, docker/dev.yml, docker/prod.yml, docs/explanations/pro-dev-setup.md, docs/how-to-guides/pro-development.md, lib/ProductOpener/Config2_docker.pm, setenv-pro.sh
This should enable using pro platform for dev (no deployment yet).
There is an explanation.
Docker file are a bit complexified, but I hope not too much.
=> Ag docker pro

taxonomies/categories.txt
The distinction is needed by the EREN research team in France.
=> Fat and lean fishes

taxonomies/categories.txt, taxonomies/categories.wip.txt
Improving a few PGI categories
=> Improving a few PGI categories

.github/workflows/container-deploy.yml
Sorry, I was too much in a hurry in PR #6178
=> fix: use PRODUCT_OPENER_DOMAIN for MINION_QUEUES

taxonomies/categories.txt, taxonomies/categories.wip.txt
=> Category fixes

lib/ProductOpener/Import.pm
=> Add useragent to bypass CloudFlare blocking. 

docs/how-to-guides/using-pages-from-openfoodfacts-web.md
=> docs: fixes in using-pages-from-openfoodfacts-web

docker/monitor.yml, docker/prod.yml
=> fix: docker networks in prod after exporters crashing

lib/ProductOpener/Config_off.pm, lib/ProductOpener/Food.pm, t/nova.t, taxonomies/categories.txt
According to the NOVA paper, starches are NOVA 2: https://www.fao.org/3/ca5644en/ca5644en.pdf
We previously made them NOVA 3.
Also added some tests.
=> NOVA updates for starches + tests

README.md
=> Remove obsolete badge

Makefile
=> ops: remove tab before comment in Makefile

.gitattributes
to avoid problems on windows, as file are meant to be executed in docker in linux env
=> fix: keep eol to lf as default

taxonomies.obf/categories.txt
Fixes for the Open Beauty Facts categories 
- #5505
=> Wikidata Fixes for the Open Beauty Facts categories 

taxonomies/categories.txt
**Checklist:**
Milchfrei means without milk
=> Fix typo in vegan cheese category (german)

lib/ProductOpener/Import.pm
Refactor of csv import for clarity and avoid a small code repeat.
=> Import refactor

taxonomies/additives.txt, taxonomies/brands.txt, taxonomies/containers.txt, taxonomies/ingredients.txt
- Commented out proposed categories for the draft brand taxonomy
- Ingredients: fix: `en:superioir quality Camargue long grain rice`
- containers: Added wikidata entries
- additives: small fix + Added wikidata entries
=> Small taxonomy fixes

lib/ProductOpener/KnowledgePanels.pm, templates/api/knowledge-panels/health/ingredients/ingredients.tt.json, templates/web/panels/panel.tt.html
Just a basic panel to display the ingredients list.
Also include new fields that can be used to add an Edit button in the app and/or the website:
```
{
elements: [
{
element_type: "text",
text_element: {
html: "(French)"
}
},
{
element_type: "text",
text_element: {
edit_field_id: "ingredients_text_fr",
edit_field_type: "ingredients_text",
edit_field_value: "Eau, boulgour 15% (blé dur concassé) grand épeautre 9% ( contient gluten), carottes 5,3%, courgettes 5,3%, pois chiches 5,3%, poivrons rouges 4%, oignons 3,3%, huile d'olive vierge extra, raisins secs 1,6% (raisins secs, huile de coton), double concentré de tomate, farine de blé, épices 0,8% (coriandre, anis, cannelle, girofle, poivre, curcuma, cumin, fenugrec, fenouil, piment, cardamome, livèche, ail, paprika), coriandre 0,4 %, purée …
```
=> Start of ingredients knowledge panel

.github/workflows/mongo-deploy.yml, scripts/gen_top_tags_per_country.pl
This is urgent because the fix I made in prod for mongodb was not deployed because of too loose deploy trigger.
=> Ag fix mongo deploy

taxonomies/categories.txt
- Add Wikidata items to categories
- Misc fixes
- One commented out knowledge experiment on a category
=> feat: Add Wikidata items to categories

taxonomies/categories.result.txt, taxonomies/categories.txt, taxonomies/ingredients.result.txt
+ fix 3 small issues in categories.txt
=> built taxonomies: categories, ingredients, additives

.github/workflows/top-issues.yml
=> Feat: Add Top Issues

lib/ProductOpener/Images.pm
added some documentation to describe how we store product images.
=> doc: document the different types of product image files

templates/api/knowledge-panels/recommendations/health/world/who_alcohol.tt.json, templates/web/panels/panel.tt.html
=> Use blockquote for panel quotes + add (WHO) to alcohol panel

.github/labeler.yml
Added - t/**/* to auto-labelling
=> Added - t/**/* to auto-labelling

Dockerfile, conf/apache-mpm_prefork.conf, docker-compose.yml
see  #6144
I tested it locally also with some load.
=> ops: make apache use prefork as in prod

cgi/import_file_process.pl, t/producers.t, templates/web/pages/import_file_select_format/import_file_select_format.tt.js
Fixes JS to initialize column matches.
- fixes #6310
=> fix: set language of fields during init

taxonomies/ingredients.txt
=> prinsessenbonen

scripts/add_nutriscore_to_scanbot_csv.pl, scripts/scanbot.pl
Add Eco-Score stats to scanbot.
=> Scanbot improvements

lib/ProductOpener/Config_off.pm
Passing "example" as the code parameter to the API will return this fake product:
https://world.openfoodfacts.org/product/093270067481501/a-good-product-for-you-open-food-facts
=> A good product for you - example product for apps

.github/dependabot.yml
=> Make Dependabot semantic

conf/mongodb/create_indexes.js, po/common/common.pot, po/common/en.po, po/common/fr.po, po/tags/fr.po, scripts/refresh_products_tags.js
New strings for the food groups facet + new index for MongoDB.
=> New food groups facet

po/common/en_AU.po, po/common/nl_NL.po, po/common/pt_PT.po, po/common/sr_RS.po, po/common/zh_CN.po, po/common/zh_TW.po
=> fix lang warnings

lib/ProductOpener/Display.pm, templates/web/pages/product/includes/ingredients_analysis.tt.html
Simplify code and remove labels overrides as they are already done during ingredients analysis.
=> small improvements to display ingredients analysis

taxonomies/categories.txt
=> Translation doubles

taxonomies/categories.txt
=> Translation doubles continued

.github/labeler.yml
=> Labeler improvements

taxonomies/categories.txt
=> Translation doubles continues 3

.github/ISSUE_TEMPLATE/epic.md
=> Epic update

.github/workflows/semantic-pr.yml
=> Semantic PR bot

.github/PULL_REQUEST_TEMPLATE.md
- Improve and harmonize the Pull request template
=> chore: Pull Request template fix

.github/labeler.yml
=> chore: Adding labeler rules for packaging

taxonomies/packaging_materials.txt
I added translations in Bulgarian.
**Checklist:**
=> chore: Update taxonomies/packaging_materials.txt

.github/workflows/merge-conflict-autolabel.yml
- Autolabel Merge conflicts
- #5512
=> ci: merge conflicts autolabel

po/tags/bg.po
=> chore: Update bg.po

.github/labeler.yml
=> chore: labeler improvements

.github/labeler.yml
- chore: Auto-label tagline changes
=> chore: Auto-label tagline changes

Makefile, taxonomies/Makefile
This is a fix of the makefile + a rebuild to rebuild them all.
=> build: better make taxonomies

taxonomies/origins.txt
This is a rebase of #6432 by @Roto15
=> chore: Update origins.txt

po/common/common.pot
- Switch to the new FAQ system
- https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/101
=> feat: Switch to the new FAQ system

README.md
=> docs: Add links to robotoff and smooth-app repos

Makefile
Link is outdated so it is modified with the new one.
=> docs: Changed message in the MakeFile

CONTRIBUTING.md
=> docs: Typo correction

taxonomies/additives.txt, taxonomies/categories.txt, taxonomies/nutrients.txt
Changes to the taxonomies based on new dutch products.
=> feat: Dutch additions

lib/ProductOpener/Display.pm
Sorry moved my git branch and ended up closing the old PR (https://github.com/openfoodfacts/openfoodfacts-server/pull/6513)
I'm making a commit for an outreachy project
=> fix: outreachy uninitialized value update

scripts/export_producers_platform_data_to_public_database.sh
This is a temporary fix, a better solution will be to do #6558
=> chore: add org-d-aucy to nightly imports

.github/workflows/github-projects.yml
=> ci: add to github projects

po/README.md
doc: Add a translation README to avoid translations being overwritten
=> docs: Add README to avoid overwritten contribs

.github/workflows/github-projects.yml
Auto-add pull requests to GitHub projects
=> ci: PR autoadd to GitHub projects

.github/workflows/translation-check.yml
=> ci: enforce translation checks on PRs

t/ingredients_processing.t, taxonomies/ingredients_processing.txt
- Added a test that would verify when the fix has been implemented.
- Added dry as a secondary word for dried
- Test for #6634
=> fix: "Dry" not being recognized as a processing type

.github/workflows/github-projects.yml
ci: do not run add to gh on forked pr
=> ci: do not run add to gh on forked pr

.github/workflows/crowdin.yml
=> ci: run crowdin every night

taxonomies/languages.txt
Some additions and fixes to Turkish translations
=> chore: Update languages.txt (Turkish translations)

scripts/gen_users_emails_list.pl
=> feat: add userid to emails' export

lib/ProductOpener/GS1.pm, t/expected_test_results/import_gs1/agena3000_andros.off.json, t/expected_test_results/import_gs1/agena3000_aoste.off.json
part of #6537
needed as Equadis and Agena3000 have different ways of passing the values for energy in both kj and kcal
=> feat: add support for 2 GS1 quantityContained field in nutrientDetail

lib/ProductOpener/Display.pm
This fixes "Use of uninitialized value" warning.
=> fix: undefined variable warning

scripts/gen_users_emails_list.pl
Add newsletter and moderator fields
=> feat: Add newsletter and moderator fields to users' export

po/common/common.pot, po/common/en.po, templates/api/knowledge-panels/environment/carbon_footprint.tt.json
The carbon emission figure comes from ADEME's Agribalyse database, for the category:
- Fixes #6350
=> fix: unlocalized knowledge panel string for Smoothie

.github/workflows/translation-check.yml, Dockerfile, Makefile, scripts/check-translations.sh
=> build: fix translation checks

taxonomies/ingredients_analysis.txt
=> fix: non ambiguous translation for palm oil content unknown 

gulpfile.js, icons/svgo.config.js
fix #6706 with workaround from https://github.com/ben-eb/gulp-svgmin/issues/125#issuecomment-1026938305
=> fix: options for gulp-svgmin/svgo icons #6706

.github/workflows/github-projects-for-openfoodfacts-design.yml
=> ci: Send design-related issues to openfoodfacts-design

.github/workflows/auto-assign-pr.yml
=> ci: autoassign PRs

t/expected_test_results/export/27096765.json, t/expected_test_results/export_more_fields/27096765.json, taxonomies/labels.txt
=> fix: add UTZ Certified xx: and fr: translations

.github/workflows/github-projects.yml
ci: don't run on dependabot made prs as it will fail
=> ci: don't run on dependabot made prs as it will fail

taxonomies/ingredients.txt
Add `natural rice sourdough` with some translations
=> chore: add natural rice sourdough with some translations

scripts/export_producers_platform_data_to_public_database.sh
Lea Nature sends data through Equadis.
=> chore: add lea-nature to daily exports

taxonomies/ingredients.txt
=> fix: Slovak additions

taxonomies/ingredients_processing.txt
feat: adding Wikidata entities for processing methods
=> feat: adding Wikidata entities for processing methods

taxonomies/labels.txt
chore: Label fixes
- label_categories to enable clustering of labels
- wikidata entries
=> chore: Label fixes

.gitignore
Exclude files generated by JetBrains IDEA, WebStorm and others from adding to GIT.
=> chore: Git ignore settings for JetBrains editors

lib/ProductOpener/Config_off.pm
Add @galnaf and @manon-corneille to admins
=> chore: add Gala and Manon to admins

html/js/product-search.js
=> fix: typo in product scoring

scripts/generate_madenearme_page.pl
fixes #6789
https://madenear.me
https://cestemballepresdechezvous.fr
=> fix: bigger timeout for Made Near Me generation 

templates/api/knowledge-panels/health/ingredients/ingredients.tt.json, templates/api/knowledge-panels/health/nutrition/nutrition_facts_table.tt.json, templates/web/panels/panel.tt.html
for now web is always considered large, but we have a specific class we could play upon.
Applied to nutrition and ingredients panels
fixes #6786
=> feat: expand some panels only on large devices

.github/workflows/pull_request.yml, Makefile, docker/dev.yml
This is an attempt at speeding up build time, by uploading docker images as artifacts
=> build: speed up build actions

cgi/search.pl
Potential fix for https://github.com/openfoodfacts/openfoodfacts-server/issues/6845
=> fix: Undefined variable in search.pl

Makefile
Adds a Makefile target to run a single test. I believe this can be an enhancement to the developer experience.
- Fixes #6876
=> chore: Add make target to run a single test

scripts/agena3000/run_agena3000_import.sh, scripts/gen_feeds_daily_off.sh
This to activate the agena3000 import in production.
=> feat: activate agena3000 import in production

.github/workflows/crowdin-per-language.yml, .github/workflows/crowdin.yml, .github/workflows/release-please.yml, .github/workflows/semantic-pr.yml, CONTRIBUTING.md
This enable to report them on release description
fixes #6863
=> ci: commit prefixes for translation and taxonomy changes

.github/workflows/release-please.yml
See https://github.com/openfoodfacts/openfoodfacts-server/pull/6906
=> fix: release please workflow pt.2

t/display.t
Unit tests for analyze_request function in lib/ProductOpener/Display.pm
=> test: analyze_request unit tests

templates/web/common/site_layout.tt.html
Potential fix for https://github.com/openfoodfacts/openfoodfacts-server/issues/6925
=> fix: invalid json

lib/ProductOpener/Display.pm
display_form doesn't seem to be used, no other functions call for it.
=> refactor: display_form not used

cgi/product_multilingual.pl
=> fix: typo in %DV and IU units property names 

lib/ProductOpener/Tags.pm
This function doesn't seem to be used, it doesn't get called nor does it call other functions.
=> refactor: remove canonicalize_saint

lib/ProductOpener/Products.pm
Noticed the `product_url($)` sub was somehow duplicated. Just a quick clean-up PR.
=> fix: duplicate `sub product_url($)` in Products.pm

.github/workflows/release-please.yml
=> fix: typo in release-please github action

t/ingredients_analysis.t, taxonomies/categories.txt, taxonomies/ingredients.txt
This PR extends ingredient analysis support for,
- cultured cream, 
- sweet cream buttermilk, 
- heavy cream,
- cream cheese
[us-filter:cream-status:unknown](https://us.openfoodfacts.org/ingredients?status=unknown&filter=cream)
=> fix: support for some common and popular US dairy ingredients

po/common/nl_NL.po, po/common/pt_PT.po, po/common/zh_CN.po
=> fix: zh_CN, pt_PT and nl_NL

taxonomies/ingredients.txt
Added polish translation of UHT pasteurised milk
=> taxonomy: add polish name of UHT pasteurised milk to ingridients.txt

lib/ProductOpener/Users.pm
Documentation for create_password_hash
=> docs: create_password_hash documentation

lib/ProductOpener/Config_off.pm
adding @manon-corneille to the list of users who can upload images (from producers)
=> chore: permissions to add small images

lib/ProductOpener/Images.pm
This export doesn't appear to have a function to go with it.
=> refactor: display_image_form unused export

lib/ProductOpener/Images.pm
This function appears to only be defined, it isn't used anywhere and it doesn't call other functions.
=> refactor: remove dims

lib/ProductOpener/Images.pm
This function doesn't appear to have a matching function
=> refactor: process_image_form unused export

lib/ProductOpener/Store.pm
This export doesn't appear to have a function to go with it.
=> refactor: get_fileid_punycode unused export

lib/ProductOpener/Food.pm, lib/ProductOpener/Ingredients.pm
- Refactored `default_unit_for_nid()`  (had a lot of `return` statements with conditionals)
- Refactored `compute_serving_size_data()`  (had a lot of `delete` calls)
- documented `default_unit_for_nid()` and `canonicalize_nutriment()` in the POD format
=> refactor: refactor repeated code and add documentation

lib/ProductOpener/Users.pm
Switching "shift" prototypes to perl signature
=> refactor: replace perl shift prototype in `Users.pm`

lib/ProductOpener/ProducersFood.pm
Changing perl prototype to signature
=> refactor: replace perl "shift" prototype in `ProducersFood.pm`

lib/ProductOpener/Index.pm
Changing perl prototype to signature
=> refactor: replace perl "shift" prototype in `Index.pm`

po/common/common.pot, po/common/en.po
Better wording to indicate that we need a precise category for the Eco-Score.
Fixes https://github.com/openfoodfacts/smooth-app/issues/2542
=> fix: better wording for adding a precise category

lib/ProductOpener/Display.pm, lib/ProductOpener/Images.pm, templates/web/common/includes/display_search_image_form.tt.html
Templatizing the `display_search_image_form` method from `Images.pm`
**Related issues and Discussion**
Issue https://github.com/openfoodfacts/openfoodfacts-server/issues/6927
=> refactor: templatize display_search_image_form from 'Images.pm`

.perltidy_excludes, cgi/session.pl, cgi/version.pl
Implementing perltidy to `cgi/session.pl` and `cgi/version.pl`
=> refactor: adding perltidy to files

taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/vitamins.txt
Merged double entries
Corrected some typos
Added/removed "s" to match parent name
=> taxonomy: Changed some entries, mostly double entries

cgi/auth.pl
Fix for https://github.com/openfoodfacts/openfoodfacts-server/issues/6462
=> fix: set access-control-allow-credentials=true for auth.pl

.perltidy_excludes, cgi/css.pl
Implementing perltidy to `cgi/css.pl`, which will cause a merge conflict with PR #6663 
Please approve this PR, then I will merge it and fix the conflicts
=> refactor: adding perltidy to cgi/css.pl

taxonomies/labels.txt
Modification on @segundo suggestion
=> taxonomy: "Nature & Progrès" is not biodynamic

templates/emails/user_new_pro_account.tt.txt
=> chore: Update user_new_pro_account.tt.txt

templates/emails/user_new_pro_account_org_request_validated.tt.txt
=> chore: Update user_new_pro_account_org_request_validated.tt.txt

templates/emails/user_new_pro_account_admin_notification.tt.html
=> chore: Update user_new_pro_account_admin_notification.tt.html

.github/ISSUE_TEMPLATE/feature_request.yml
=> ci:improve tmpl output

Makefile
to avoid conflicting with dev instance
fixes: #7127
=> build: fix mongodb port for tests

lib/ProductOpener/Data.pm, lib/ProductOpener/DataQualityFood.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/I18N.pm, lib/ProductOpener/Images.pm, lib/ProductOpener/Nutriscore.pm, lib/ProductOpener/Products.pm
I'm planning on correcting all of the misspelled comments in perl files and then implementing `[Documentation::PodSpelling]`
=> fix: Spelling correction

docs/explanations/pro-dev-setup.md, docs/how-to-guides/docker-developer-guide.md, docs/how-to-guides/use-repl.md, docs/introduction/dev-environment-quick-start-guide.md
- Document how to use re.pl
- Update docker dev  docs
=> docs: repl and docker dev

cgi/countries.pl, html/js/display.js
I completely forgot there was one cgi script in the /cgi/i18n/ directory, so it was still calling init() instead of init_request().
As there was only one cgi, I moved it to /cgi instead.
=> fix: countries.pl for countries dropdown

cgi/css.pl, lib/ProductOpener/Display.pm
This should allow the redirect function to set a cookie.
Renamed to redirect_to_url as it was clashing with another function imported in Images.pm
=> fix: set cookie when redirecting

lib/ProductOpener/Export.pm
Replacing "shift" prototype with perl signature
=> refactor: enable perl signature Export.pm

lib/ProductOpener/Images.pm
Replacing "shift" perl protoypes with signatures.
=> refactor: enable perl signature Images.pm

lib/ProductOpener/Products.pm
Replacing "shift" perl prototypes with perl signatures
=> refactor: enable perl signature Product.pm

lib/ProductOpener/Food.pm
Replacing "shift" with signatures
=> refactor: enable perl signature Food.pm

lib/ProductOpener/Packaging.pm
=> refactor: enable perl signature Packaging.pm

lib/ProductOpener/Tags.pm
Replacing "shift" prototypes with signatures
=> refactor: enable perl signature `Tags.pm`

taxonomies/additives.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/minerals.txt, taxonomies/nutrients.txt, taxonomies/origins.txt
Removed repeated entries
Added some missing elements : language code, colon...
=> taxonomy: Remove repeated entries

lib/ProductOpener/KnowledgePanels.pm
=> refactor: enable perl signature `KnowledgePanels.pm`

lib/ProductOpener/Producers.pm
Replacing "shift" prototypes with perl signatures.
=> refactor: enable perl signature Producers.pm

lib/ProductOpener/Attributes.pm
=> refactor: enable perl signatures Attributes.pm

taxonomies/data_quality.txt
- Add taxonomy entries for quality
=> feat: Add taxonomy entries for quality

lib/ProductOpener/Tags.pm
=> fix: bug introduced by previous refactor

lib/ProductOpener/Orgs.pm
replacing "shift" with signatures
=> refactor: enable perl signature Orgs.pm

lib/ProductOpener/ImportConvertCarrefourFrance.pm
replacing "shift" prototypes with perl signatures
=> refactor: enable perl signature ImportConvertCarrefourFrance.pm

lib/ProductOpener/MainCountries.pm
Replacing "shift" prototypes with signatures
=> refactor: enable perl signature `MainCountries.pm`

lib/ProductOpener/GS1.pm
Replacing "shift" prototypes with signatures
=> refactor: enable perl signature GS1.pm

lib/ProductOpener/Ingredients.pm
Replacing "shift" prototypes with signatures in Ingredients.pm
=> refactor: enable perl signatures `Ingredients.pm`

lib/ProductOpener/ForestFootprint.pm
Replacing perl "shift" prototypes with signatures.
=> refactor: enable perl signatures in ForestFootprint.pm

.perlcriticrc, lib/ProductOpener/Import.pm
Reducing the amount of nesting in Import.pm and lowering the limit for nesting
=> refactor: reducing nesting

taxonomies/ingredients.txt
added croatian translation for raw cashews
None
=> taxonomy: ingredients - added croatian translation for raw cashews

lib/ProductOpener/URL.pm
replacing "shift" with signatures
=> refactor: enable perl signature URL.pm

lib/ProductOpener/Data.pm
=> refactor: enable perl signature `Data.pm`

.github/workflows/pull_request.yml
=> refactor: fixing typo

lib/ProductOpener/Lang.pm
Replacing "shift" with perl signatures
=> refactor: enable perl signature Lang.pm

taxonomies/packaging_materials.txt, taxonomies/preservation.txt, taxonomies/states.txt, tests/unit/expected_test_results/packaging/en-aa-84-c-x.json, tests/unit/packaging.t
Many new packaging materials and improvements to the recycling codes. I am very open to improvements of my changes and I hope I did not make a stupid mistake.
=> taxonomy: Add new packaging materials and translations

lib/ProductOpener/Display.pm
Reverting the `if` statements to lessen the amount of nesting
=> refactor: reduce nesting Display.pm

cgi/product_multilingual.pl
I'm going to change the files in the `cgi` directory.  This is the only file that has subroutines so I did this one separately but I'm planning on updating the files 5 at a time.
=> refactor: enable perl signatures product_mulitlingual.pl

taxonomies/ingredients.txt
Somme additiobns
- Fixes #7242
=> taxonomy: Ingredient additions

lib/ProductOpener/GS1.pm
Turning the most deeply nested part of GS1.pm (`function gs1_to_off`) to a separate function (`nutrient_per_quantity`)
Suggestions for the new function name is welcomed :-) I wasn't exactly sure what it should be called.
=> refactor: reduce nesting `GS1.pm`

cgi/user.pl, lib/ProductOpener/Food.pm, lib/ProductOpener/Text.pm, lib/ProductOpener/Users.pm
=> refactor: enable perl signature `Text.pm`

taxonomies/ingredients.txt
added croatian translation of ingredients of choco product from delicia brand
=> taxonomy: adding croatian translation for ingredient of choco delicia

po/common/common.pot
doc: warn about strings with an impact on tests
=> docs: warn about strings with an impact on tests

taxonomies/ingredients.txt
taxonomy: 
added some ingredients for cremolli hazelnut - belprom in HR
=> taxonomy: added some ingredients for cremolli hazelnut - belprom in HR

taxonomies/ingredients.txt
taxonomy: 
added some ingredients for toast tojeto in HR
=> taxonomy: added some ingredients for toast tojeto in HR

taxonomies/ingredients.txt
taxonomy: 
added some ingredients of monster energy drink in HR
=> taxonomy: added some ingredients of monster energy drink in HR

taxonomies/ingredients.txt
taxonomie: added pasteurised milk in HR
=> taxonomy: added pasteurised milk in HR

taxonomies/ingredients.txt
taxonomy: added some ingredients of krem kakao tojeto in HR
=> taxonomy: added some ingredients of krem kakao tojeto in HR

taxonomies/ingredients.txt
Tried to fix conflict on PR by @benbenben2 : https://github.com/openfoodfacts/openfoodfacts-server/pull/7327
=> taxonomy: added some ingredients for crunchy almonds - spar in HR

taxonomies/ingredients.txt
taxonomy: added some ingredients for sir s paprom from gligora in HR
=> taxonomy: added some ingredients for sir s paprom from gligora in HR

taxonomies/categories.txt
• Create **Pâtisson** (squash) with Agribalyse proxy on Courge melonnette
• Create **Echine de porc** (Agribalyse 28302)
• Link **Aiguillettes de canard** to Duck breasts (vs Duck today) to give a better Agribalyse reference (Aiguillettes are a part of the Magret)
• Create **Batavia** type of salad and use Iceberg as an Abribalyse proxy (Iceberg is from the _laitues pommées batavias_ family)
=> taxonomy: create Pâtisson (squash)

taxonomies/additives_classes.txt, taxonomies/ingredients.txt
taxonomy: added some ingredients for margarin kolace i kuhanje in HR
=> taxonomy: added some ingredients for margarin kolace i kuhanje in HR

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/ingredients.txt, taxonomies/vitamins.txt
Added translation in Croatian for some ingredients. 
added ingredients for ISO sport naranča-limun
added ingredients for Granicarska - Gavrilovic
added ingredients for Malvazija istarska 2016 - Vina Istria
added ingredients for Njoki od krumpira - Karla
added ingredients for Ribanac - Sirela
added ingredients for cokoladno mlijeko jaffa - Dukat
added ingredients for Nectar peach apple - Vindi
added ingredients for Nectar sour cherry - Vindi
added ingredients for Hajdučka tjestenina - Cetina
added ingredients for Lizika - KPlus
added ingredients for Dimljena gauda - KPlus
added ingredients for Fanta Mucho
added ingredients for Štrudle smokva - Konzum
added ingredients for Džem višnja - KPlus
added ingredients for Wok - Kotanyi
added ingredients for Rukola - Spar
added ingredients for …
=> taxonomy: isosport and some old added product hr

taxonomies/additives.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt
* Added some missing polish translations for ingredients (based on _unknown_ ingredients from the ingredients list and from personal experience)
=> taxonomy: add missing polish translations

taxonomies/categories.txt
• fix Pork ham escalope redundant categs (x3 😱) and differentiate cooked vs raw
• add proxy to Boudins blancs : copy from Boudins blancs with truffle
=> taxonomy: fix Pork ham escalope

taxonomies/categories.txt
• Proposal to use Cooked Peppers as proxy for Frozen Peppers since Agribalyse Cooked vs Raw difference is same as Frozen vs Raw for vegetables
• add frozen mashed potatoes (purée surgelée) - Agribalyse proxy on 4043: Potato, pre-fried into cubes, frozen, raw
[sorry for the merge commit ;-(
=> taxonomy: use Cooked Peppers as proxy for Frozen Peppers

Makefile
on staging mongodb refresh.
To avoid taking too much space..
=> fix: better removal of mongodb files

taxonomies/additives.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt
Added some ingredients for Pipi and for some beers.
=> taxonomy: added ingredients for Pipi and some beers in HR

cgi/sso.pl
fixes authentification on the wiki
=> fix: sso for wiki

taxonomies/additives.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt, taxonomies/vitamins.txt
added some ingredients for an ice-cream (https://hr.openfoodfacts.org/product/3850116036113/quattro-joy-ledo), in HR
=> taxonomy: added ingredients for ice-cream in HR

.github/workflows/generate-doc.yml, README.md, mkdocs.yml, scripts/build_mkdocs.sh
* render nested list, when we use two indentations in markdown
* fix some links in README
=> docs: fix nested lists and some links

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/categories.txt, taxonomies/countries.txt, taxonomies/ingredients.txt, taxonomies/labels.txt, taxonomies/minerals.txt, taxonomies/packaging_shapes.txt
Taxonomy added ingredients for some old products in hr
1 commit = 1 product reviewed
=> taxonomy: added ingredients for some old products in hr

taxonomies/categories.txt
Differentiating swedish knäckebröd from extruded products.
=> chore: Extruded crispbread

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt
added ingredients for some croatian products
1 commit = 1 product
=> taxonomy: added some ingredients in hr

html/js/stikelem.js, scss/_off.scss, templates/web/common/site_layout.tt.html
Fixes #7410 : the footer should be at the bottom, even if the page has little content. There were some strange issues with the top menu dropdown menu going under the Open Food Facts bar below, but it should now work.
Also fixed #7464
=> fix: put footer at the bottom of the page + sign-in button on product page

html/js/product-multilingual.js, templates/web/pages/product_edit/product_edit_form_display.tt.html
=> fix: add language in product edit form 

scss/_product-page.scss, templates/web/pages/product_edit/product_edit_form_display.tt.html
=> fix: icon font 

README.md
docs: point people to new design issues
- #7295
=> docs: point people to new design issues

taxonomies/packaging_materials.txt, taxonomies/packaging_shapes.txt
added some hr entries for packaging
=> taxonomy: added some hr entries for packaging

taxonomies/additives.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/packaging_recycling.txt
Taxonomy add ingredients in hr
1 commit = 1 product
=> taxonomy: add ingredients in hr

.github/labeler.yml
ci: More auto-labelling for Pull Requests, and also a good way to understand files correlated with a label
=> ci: More auto-labelling

cpanfile, docker/dev.yml
I stumbled upon the fact that mongodb in dev did not have a volume for data !
This is far better to have one (I know understand how I have sometime lost my dev data…)
=> build: add a mongo volume in dev !

templates/api/knowledge-panels/environment/carbon_footprint.tt.json, templates/api/knowledge-panels/environment/ecoscore/agribalyse.tt.json, templates/api/knowledge-panels/environment/ecoscore/ecoscore_extended.tt.json
=> fix: text_type renamed to type

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/minerals.txt, taxonomies/nutrients.txt
=> taxonomy: add croatian entries

.github/ISSUE_TEMPLATE/feature_request.yml
doc: add code pointers to the issue template
=> doc: add code pointers to the issue template

.github/workflows/label.yml
- ci: make pr labeler work on forks
=> ci: make pr labeler work on forks

tests/unit/display.t
Urgent PR to fix test due to a new version of DateTime::Locale
=> test: fix display.t after DateTime::Locale new version

templates/web/pages/product_edit/product_edit_form_display_user-moderator.tt.html
Removed duplicate question mark
- Fixes #7512
=> fix: Removed duplicate question mark

.github/labeler.yml
=> ci: fixes for labeler

Makefile, package-lock.json
fixes #7616
just deleting package-lock.json failed (an empty directory was created instead of a file and docker was complaining about it), so I added a make front_npm_update
=> fix: generated new package-lock.json to make builds work 

po/common/common.pot, po/common/en.po, po/common/fr.po, templates/web/common/site_layout.tt.html
Add links to the newsletter subscription and the forum.
- Fixes #7588
=> feat: Add newsletter link (#7588)

templates/web/pages/user_profile/user_profile.tt.html
Fixes capitalisation issue
- Fixes #7491
=> chore: fix capitalisation issue

.github/labeler.yml
ci: tagline-for-smoothie-labeler
=> ci: add the tagline for the smoothie app in the labeler

.github/labeler.yml
ci: labeler for Open Beauty Facts, Open Pet Food Facts and Open Products Facts
=> ci: labeler for Open Beauty Facts, Open Pet Food Facts and Open Products Facts

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/vitamins.txt
added some croatian entries
1 commit = 1 product reviewed
=> taxonomy: hr ingredients 2

.github/workflows/generate-doc.yml, README.md, docs/reference/api.md, mkdocs.yml
* Make Open API documentation appear on the right
* remove the TODO file from the generated doc
=> docs: add open api documentation to index

.github/labeler.yml
ci: any PR touching Ingredients.pm pertains to analysis
=> ci: any PR touching Ingredients.pm pertains to analysis

docs/introduction/api.md, docs/reference/api.yml
=> docs: small fixes

docs/reference/api.yml, docs/tutorials/using-the-OFF-API-tutorial.md
This is a draft PR for now because the Write API isn't finished yet, however, reviews can keep coming as I improve.
=> docs: Write Nutri-Score data for a product

html/files/app/tagline/tagline-off-ios.json, html/files/tagline-off-android-v2.json, html/files/tagline-off-ios-v2.json, html/files/tagline-off.json
- feat: Add taglines for the 2022 donation campaign
=> feat: Add taglines for the 2022 donation campaign

cgi/user.pl, package-lock.json, package.json
Solves #7662 
Also solves #7642
=> fix: downgrade tagify to solve npm dependencies conflict

taxonomies/ingredients.txt
=> chore: week 46 taxonomy work

taxonomies/ingredients.txt
Removed (some) errors in the ingredients as noted in the tests.
=> chore: ingredients errors

taxonomies/packaging_recycling.txt
Recycling instruction additions
- Translations
- Conversion of comments to comments:en:
=> taxonomy: Recycling instruction additions

lib/ProductOpener/Routing.pm
fix error loading https://world.openfoodfacts.net/photographer/teolemon
=> fix: Routing.pm error

.github/workflows/top-issues.yml
fix: increase the number of top issues to make it more useful
=> fix: increase the number of top issues to make it more useful

templates/web/common/includes/donate_banner.tt.html, templates/web/common/includes/donate_banner_bottom.tt.html
=> fix: 2022-2023

.github/labeler.yml
=> ci: labeler update

package-lock.json, package.json
=> fix: downgrade jquery-ui 

.github/workflows/generate-doc.yml
Follow up of #7736 for I inverted both docs !
=> ci: Build api v3 docs

html/files/app/tagline/tagline-off-ios.json, html/files/tagline-off-android-v2.json, html/files/tagline-off-ios-v2.json, html/files/tagline-off.json
feat: Improve donation conversion by adding 💕
- #5720
=> feat: Improve donation conversion by adding 💕

docs/tutorials/using-the-OFF-API-tutorial.md
- Using the OFF Tutorial : Search for a products. 
- #7446
=> docs: search for a product tutorial

lib/ProductOpener/Display.pm, po/common/common.pot, po/common/en.po, templates/web/common/site_layout.tt.html
- Hunger Games on Facets for Categories, Labels and Brands.
- Will create a deep link to Hunger Games for that specific value of the facet
- Fixes #2804
=> feat: Hunger Games on Facets

docs/.pages, docs/introduction/.pages, docs/introduction/knowledge-panels.md, docs/reference/.pages, mkdocs.yml, scripts/build_mkdocs.sh
=> docs: improve docs navigation

taxonomies/categories.txt
I didn't keep some of the previous name as a synonym because the categorization was completely wrong, and we have to change everything anyway.
=> taxonomy: Junkets

taxonomies/categories.txt
- Added new category Kūčiukai ([Q518601](https://www.wikidata.org/wiki/Q518601)) [example product](https://world.openfoodfacts.org/product/4779030892164/k%C5%AB%C4%8Diukai-mini-jungtinis-duonos-centras) with a description
- Added new category Šaltibarščiai ([Q70241](https://www.wikidata.org/wiki/Q70241)) with a desription
- Translated soups categories into Lithuanian
PS how to do the "Merge branch 'main' into DanieliusAsm/main/lithuanian_categories" ? I messed up on a [similar closed PR](https://github.com/openfoodfacts/openfoodfacts-server/pull/7764). I wanted to merge branches and then the previous commits appeared... I did:
`git checkout lithuanian_categories
git merge main
git push`
=> taxonomy: Lithuanian categories: soups edition

docs/.pages
Made Home first item in the navbar
=> fix:  make home first in the nav bar

taxonomies/allergens.txt, taxonomies/categories.txt, taxonomies/ingredients.txt
- Translated Buillons, lasagne, Pizzas
- Added, translated allergens
- Translated a little bit of ingredients
=> taxonomy: Lithuanian categories, allergens, ingredients

docs/introduction/api.md
=> docs: link to tutorial in API intro

taxonomies/ingredients.txt
small additions in polish ingredients taxonomy
=> taxonomy: add Polish translations for caramel and safflower

taxonomies/categories.txt, taxonomies/ingredients.txt
added few varietals for wines
ingredients for beers
categories
=> taxonomy: reviewed some beers and wines in Croatia

taxonomies/ingredients_processing.txt
add/update Italian translations for many ingredients processing methods: pure, leaf, sliced, grated, granulated, pieces, flakes, flour, boned, shelled, peeled, pitted, peel, pulp, sieved, sap, juice, concentrated, double concentrated, dried, sundried, syrup, extract, pressed, cold pressed, frozen, unfrozen, blanched, caramelised, puffed, roasted, toasted, unsalted, sweetened, unsweetened, sugared, treated, untreated, malted, deodorized, fermented, marinated, pickled, brined, flavoured, smoked, non-hydrogenated, hydrogenated.
=> l10n: add/update Italian translations for many ingredients processing methods

.github/workflows/github-projects-for-openfoodfacts-design.yml
ci: Add infrastructure label to relevant GitHub Project
=> ci: Add infrastructure label to relevant GitHub Project

templates/web/pages/product_edit/product_edit_form_packagings.tt.html
=> fix: save all packaging components #7783

templates/web/common/site_layout.tt.html
fix: add alt attribute to make SonarCloud go green https://sonarcloud.io/project/issues?issues=AYSgpFHzYk1o3ETtfHmJ&open=AYSgpFHzYk1o3ETtfHmJ&id=openfoodfacts_openfoodfacts-server
=> fix: add alt attribute to make SonarCloud go green

README.md
=> docs: README refactor

taxonomies/categories.txt
=> taxonomy: Ground meats

.env, templates/web/pages/product_edit/product_edit_form_display.tt.html
=> fix: Barcode is not visible in the edit mode

lib/ProductOpener/Import.pm, lib/ProductOpener/Tags.pm
that I added as I try to understand the code
=> docs: some comments in Import.pm

lib/ProductOpener/DataQualityFood.pm
=> fix: avoid false positive errors for low energy values #7811

README.md
docs: add-server-doc-to-readme
=> docs: add-server-doc-to-readme

docs/introduction/dev-environment-quick-start-guide.md
- Added one more error faced while setting up the dev environment locally on Ubuntu (Linux) under troubleshooting section.
- Highlight some inline commands
=> docs: Added instructions under Troubleshooting section to solve error caused by local mongodb database server.

docs/reference/api.yml, docs/reference/schemas/product.yaml, docs/reference/schemas/tags_parameters.yaml
Add more query parameters to the search open api
=> docs: add more optional search parameters to open api

taxonomies/additives.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt
added ingredients translation in Croatian and Bosnian
=> taxonomy: added Croatian ingredients translation

scss/_product-list.scss
- Added css to make the product name responsive on product lists
- Fixes #7499 ]
=> fix: scattered product name in responsive mode on product lists Fixes #7499

taxonomies/nutrients.txt
added "Vitamin D3" and "D3" in the taxonomy nutrients.txt file.
This may resolves #2580
=> fix: added vitamin d3 in nutrients.txt

taxonomies/categories.txt
=> taxonomy: Natillas and crèmes aux oeufs

po/common/en.po, po/common/fr.po, templates/web/pages/product_edit/product_edit_form_packagings.tt.html, tests/integration/expected_test_results/api_v2_product_read/get-existing-product.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_write/get-product-auth-good-password.json, tests/integration/expected_test_results/api_v2_product_write/get-product.json, tests/integration/expected_test_results/api_v3_product_read/get-existing-product.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels.json
change wording of columns for packagings (suggestions from ADEME)
=> chore: column names for packagings

scss/_product-form.scss
Selected multiple images in the manage images section will highlight them.
- Fixes #7522
=> feat: highlight all selected images to delete for admins

taxonomies/labels.txt
=> taxonomy: Octogons + Various labels

lib/ProductOpener/Food.pm, tests/unit/expected_test_results/nutriscore/fr-orange-nectar-0-fat.json, tests/unit/expected_test_results/nutriscore/sunflower-oil-no-sugar-no-sat-fat.json, tests/unit/expected_test_results/nutriscore/sunflower-oil-no-sugar.json, tests/unit/nutriscore.t
where fat is 0 we can deduce saturated fat is 0, same for sugar from carbohydrates we use it to compute Nutri-Score
Fixes:
- #4561
=> feat: deduce 0 sugar/sat fat to compute nutriscore

po/common/ar.po, po/common/el.po, po/common/eu.po, po/common/he.po, po/common/kmr_TR.po, po/common/nl_NL.po, po/common/pl.po, po/common/tr.po, po/common/tt.po, po/common/uk.po, scripts/check-translations.sh
* chore: fix translations files
=> ci: fix check translations

docs/reference/schemas/product.yaml, html/data/data-fields.md, html/data/data-fields.txt, lib/ProductOpener/Config_off.pm, scripts/export_database.pl
Part of https://github.com/openfoodfacts/openfoodfacts-server/issues/2325
* [Fix bug to export sub-sub-nutrients](https://github.com/openfoodfacts/openfoodfacts-server/commit/102bdb26ba57d7a875b367ffd45c5f122ea66b26)
* [Erythritol documentation](https://github.com/openfoodfacts/openfoodfacts-server/commit/60d556617469d418ecffabb1c9747900935d75d1)
* [Add last_modify_by to the export](https://github.com/openfoodfacts/openfoodfacts-server/commit/6c437a2fa9e3b178a4e92df92aac455f24ebd841)
* [Fix no_nutriments](https://github.com/openfoodfacts/openfoodfacts-server/commit/569fc4ab4d53905a98061f0293a9b3e3b9d066ee)
=> feat: CSV export enhancements + fix

docs/how-to-guides/download-images.md
adapted from https://wiki.openfoodfacts.org/Developer-How_To
=> docs: Add documentation on product image download

taxonomies/ingredients.txt
Remove useless entry in ingredient taxonomy
=> taxonomy: remove useless item

docs/reference/api-tutorials/index.md
=> docs: dev journeys index

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/categories.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/minerals.txt
added some Croatian entries (categories, ingredients, etc.)
=> taxonomy: added Croatian entries

taxonomies/labels.txt
- Small fix from my local disk
=> taxonomy: A few more labels for Hunger Games

.github/labeler.yml, docs/tutorials/uploading-photo-to-a-product.md
This is a mini draft of this tutorial. I am hopingg more suggestions will shape it.
=> docs: tutorial: Upload photos using the Open Food Facts API

taxonomies/packaging_shapes.txt
=> fix: wine corks

taxonomies/labels.txt
taxonomy: add support for multi Nutri-Score
https://hunger.openfoodfacts.org/logos?logo_id=3481825&count=50
=> taxonomy: add support for multi Nutri-Score

taxonomies/packaging_materials.txt
adding adhesive tapes such as on this product:
There should probably more types of tape.
=> feat: adding adhesive tapes as a packaging material

.github/workflows/generate-doc.yml, docs/assets/.pages, docs/assets/api-rapidoc.html, docs/introduction/api.md, docs/reference/.pages, docs/reference/api-rapidoc.md, docs/reference/api.yml
Trying [rapidoc](https://rapidocweb.com/api.html#slots)
to solve:
- #7883
=> docs: try rapidoc

docs/introduction/dev-environment-quick-start-guide.md
=> docs: menu name for developper mode on win11

taxonomies/ingredients.txt
Added a taxonomy for orange juice
=> taxonomy: Added "Succo di arance bionde" under orange juice

docs/introduction/dev-environment-quick-start-guide.md
- Added Troubleshooting for setup
=> docs: add troubleshooting

taxonomies/labels.txt
https://gfco.org/gluten-intolerance-group-announces-the-rebranding-of-the-gluten-free-certification-organization-gfco-mark-to-support-global-expansion/
=> taxonomy: Certified Gluten Free

tests/unit/dataqualityfood.t
Related to issue #7984 that was solved through the PRs #7988, #8035
=> test: added unit tests fot negative nutriments

lib/ProductOpener/Products.pm, tests/integration/api_v3_product_write.t, tests/integration/expected_test_results/api_v2_product_read/get-existing-product.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-raw.json, tests/integration/expected_test_results/api_v3_product_read/get-existing-product.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-all.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-raw.json, tests/integration/expected_test_results/api_v3_product_write/patch-packagings-fr-fields.json, tests/integration/expected_test_results/api_v3_product_write/patch-packagings-quantity-and-weight.json, tests/integration/expected_test_results/api_v3_product_write/patch-request-fields-all.json, tests/integration/expected_test_results/import_csv_file/3270190128403.json, tests/integration/expected_test_results/search_v1/search-no-filter.json, tests/integration/expected_test_results/search_v1/search-without-ingredients-from-palm-oil.json
There was a typo that prevented the new weighters_tags facet to be computed correctly.
Also added some tests.
=> fix: correct computation of weighters_tags

taxonomies/ingredients.txt
added new taxonomy translations for Polish
=> taxonomy: add polish taxonomy translations, mainly around lemons

po/tags/fr.po
Thanks for spotting the error @john-gom
=> fix: typo for weighers id in fr.po

lib/ProductOpener/Config_off.pm, lib/ProductOpener/Products.pm, lib/ProductOpener/TestDefaults.pm, tests/unit/process_product_edit_rules.t
Block an app that causes too much data quality errors.
fixes:
- #6043
=> feat: block halal chackib

conf/nginx/snippets/off.domain-redirects.include
https://hungergames.openfoodfacts.org
=> fix: redirects for hungergames.openfoodfacts.org

lib/ProductOpener/DataQuality.pm, taxonomies/data_quality.txt
Add some structure to data quality.
Linked to #7718 and to PR #8032
=> taxonomy: add some structure to data quality
