openfoodfacts/openfoodfacts-server

lib/ProductOpener/Display.pm

Re-add the asterisk for non-taxonomized tags in lists

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Ingredients.pm
lib/ProductOpener/Lang.pm
lib/ProductOpener/Products.pm
lib/ProductOpener/Tags.pm
lib/ProductOpener/Users.pm

Fix some of the Perl warnings that (additionally) spam the build log.
Resolves some of the issues mentioned in #315.

Resolve some Perl warnings

---

cgi/product_multilingual.pl
lib/ProductOpener/Food.pm

Like pH or carbon footprint, it's not strictly a nutrient, but it fits the pattern.
Fixes #585

Allow glycemic index to be entered as a nutrient

---

cgi/search.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Lang.pm

Add Web Share API for products, tags, and searches.

Web Share API

---

lib/ProductOpener/Display.pm

Add tag images to the API

---

cgi/product_multilingual.pl

Only display the edit-mode alert-boxes if they have not been confirmed, yet.

Hide confirmed alert box

---

cgi/opensearch.pl
cgi/product_image_crop.pl
cgi/product_image_move.pl
cgi/product_image_upload.pl
cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
cgi/session.pl
cgi/sso.pl
cgi/sucres_check.pl
cgi/sugar_check.pl
cgi/suggest.pl
cgi/version.pl

I believe this should fix #670 as it's an encoding issue.

Fix JSON content type

---

html/js/product-multilingual.js

fix JS bugs causing problems with nutrients

---

cgi/product_multilingual.pl
html/images/misc/pacman.svg
lib/ProductOpener/Display.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Images.pm
po/common/en.po
scripts/delete_products_from_user.pl
scripts/import_us_ndb.pl

See #dataimports channel on Slack for discussion of those changes

Usda ndb import

---

po/openbeautyfacts/en.po

Add proper Android & iOS links for Open Beauty Facts to drive app installs

Add proper Android & iOS links for Open Beauty Facts

---

lib/ProductOpener/Config_off.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Products.pm
po/tags/en.po
scripts/update_all_products.pl

bug #862, improve code to handle fruits for nutriscore, add misc 

---

po/common/common.pot

Added donate link to POT files.

Donate link in POT file

---

lib/ProductOpener/Display.pm

What do you think about encoding the graph data with JSON:PP? This should take care of most/all encoding problems mentioned in #820.

Use JSON:PP to encode graph data.

---

bower.json
cgi/manifest.pl
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Display.pm

Generate Web App manifest dynamically with icons etc. loaded from ProductOpener::Config. Somewhat related to #549

Dynamic web manifest file

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Products.pm
po/common/common.pot
po/common/en.po

Replaced " - " as a translatable separator in order to making it possible to cater for local differences.

" - " translatable

---

lib/ProductOpener/Display.pm

This should fix #921. I don't have a running test instance of OFF right now, but the Perl syntax seems to be OK. Could you test this, please, @stephanegigandet? 😃

Ensure `languages_codes` is defined

---

lib/ProductOpener/Display.pm

This should fix #935. I don't have a running test instance of OFF right now, but the Perl syntax seems to be OK. Could you test this, please, @stephanegigandet? 😃

Fix for datatables bug

---

lib/ProductOpener/Config2_sample.pm
lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opff.pm
lib/ProductOpener/Display.pm

Use a connection string to connect to MongoDB. This allows us to use a MongoDB server that's located elsewhere than on localhost.

MongoDB connection string

---

cgi/product_multilingual.pl

Disable barcode change for normal users

---

lib/ProductOpener/Food.pm

Fixes #64 
Not sure if this is all that is required, or if there are other places in the code that need new values.

Add nutrients

---

README.md
lang/de/texts/discover.de.html
lang/el/texts/discover.el.html
lang/en/texts/discover.html
lang/es/texts/contribuir.html
lang/es/texts/descubrir.html
lang/es/texts/discover.es.html
lang/nl/texts/discover.nl.html
lang/pl/texts/discover.pl.html
lang/ro/texts/discover.ro.html

Remove dead links to /reuses content, which is 404

---

lang/en/texts/index.en.html
lang/it/texts/index.it.html
lang/pt/texts/index.pt.html

Fixes #878 
I left the imagery, static pages etc for the previous event alone though

Remove open food hunt links on landing pages

---

lib/ProductOpener/SiteQuality_off.pm

This could help in detecting bugged products for #185.

Check for missing/empty code or created_t

---

lib/ProductOpener/Display.pm

For admin users, adds links to OCR/Cloud Vision results, if they exist.

Add OCR links

---

lib/ProductOpener/Display.pm

Remember entered search term

---

cgi/top_translators.pl
lib/ProductOpener/Config2_sample.pm
lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opff.pm
lib/ProductOpener/Display.pm
package.json
po/common/common.pot
po/common/en.po
scripts/update_top_translators.pl
yarn.lock

Just download the data from the Crowdin API daily with a crontab? We could display the data similarly to https://crowdin.com/project/openfoodfacts/reports#ps-reports-top-members
Would close #120

Praise translators

---

lib/ProductOpener/Display.pm

``` 
{
"count":4,
"tags":[
{
"id":"en:pizza-with-ham-and-cheese",
"name":"Pizza with ham and cheese",
"products":1,
"url":"http://world.productopener.localhost/category/pizza-with-ham-and-cheese"
},
{
"id":"en:pizzas",
"name":"Pizzas",
"linkeddata":{
"wikidata:en":"Q177"
},
"products":1,
"url":"http://world.productopener.localhost/category/pizzas"
},
{
"id":"en:pizzas-pies-and-quiches",
"name":"Pizzas
pies and quiches",
"linkeddata":{
"pnns_group_2:en":"Pizza pies and
quiche"
},
"products":1,
"url":"http://world.productopener.localhost/category/pizzas-pies-and-quiches"
},
{
"id":"en:meals",
"name":"Meals",
"linkeddata":{
"pnns_group_2:en":"One-dish
meals"
},
"products":1,
"url":"http://world.productopener.localhost/category/meals"
}
]
}
```
Fixes #391

Wikidata and other linked data in JSON api

---

scripts/delete_old_cropped_images.pl

Details about the script and log of sample run : https://github.com/openfoodfacts/openfoodfacts-server/issues/1102
I'm always uneasy with scripts that contain "unlink", so please have a look. :-)

script to deleted old images - bug #1102

---

cgi/search.pl
lib/ProductOpener/Display.pm

add optional fields parameter to JSON API to retrieve and search products. closes #623, closes #554

add optional fields parameter to JSON API

---

cgi/product_multilingual.pl

Code by @CloCkWeRX https://github.com/openfoodfacts/openfoodfacts-server/issues/1028#issuecomment-355023253
Closes #609

Sticky edit comment

---

lib/ProductOpener/SiteQuality_off.pm

> @hangy can you add a quality facet based on this?
I think this should do that?

Add quality facet for cigarettes.

---

t/lang.t

Unit Test for translated logos

---

taxonomies/ingredients.txt

more than 700 added ingredients
i haven't deleted additives E XXX
added synonyms for some

update ingredients taxonomy after few hours of work

---

conf/apache-2.4/sites-available/opf.conf
conf/apache-2.4/sites-available/opff.conf
conf/nginx/expires-no-json-xml.conf
conf/nginx/sites-available/cestemballepresdechezvous
conf/nginx/sites-available/madenearme
conf/nginx/sites-available/madenearme-uk
conf/nginx/sites-available/off
conf/nginx/sites-available/off-preprod
conf/nginx/sites-available/opf
conf/nginx/sites-available/opff
conf/nginx/snippets/ssl-headers.conf
conf/nginx/snippets/ssl-params-opff.conf
conf/nginx/snippets/ssl-ssl-api-test.openfoodfacts.org
conf/nginx/snippets/ssl.openbeautyfacts.org
conf/nginx/snippets/ssl.openbeautyfacts.org.2017
conf/nginx/snippets/ssl.openfoodfacts.org.2016
conf/nginx/snippets/ssl.openpetfoodfacts.org
conf/nginx/snippets/ssl.openproductsfacts.org
conf/nginx/snippets/ssl.preprod.openfoodfacts.org

Refreshes the configuration in Git with what is currently live in production.
Closes #1170

Update configurations from production.

---

cgi/product_multilingual.pl
lib/ProductOpener/Display.pm

Display product history for admins in view mode.
Fixes #1173

Display product history

---

madenearme/madenearme-europe.html
madenearme/madenearme-uk-old.html
madenearme/madenearme-uk.html

Changes to be committed:
modified:   madenearme/madenearme-europe.html
modified:   madenearme/madenearme-uk-old.html
modified:   madenearme/madenearme-uk.html
Correct the links which wanna lead us to the right apple store download page.
The link: https://itunes.apple.com/en/app/open-food-facts/id588797948 could not be used.
I remplace that by the correct one: https://itunes.apple.com/app/open-food-facts/id588797948
Fix: #1209 

 Committer: Jie SONG <jiesong@pcjsong5.user.resel.fr>

---

cgi/product_jqm_multilingual.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/SiteQuality_off.pm

http://www.perlmonks.org/?node_id=1190789
https://stackoverflow.com/a/41192741/11963
Fixes #1227

Dereference scalars for some operations

---

lib/ProductOpener/Display.pm

This closes #488, and this closes #489

Avoid concatenating undef when building CSV

---

lib/ProductOpener/Ingredients.pm
t/ingredients.t

Treat all stops/commas as to be replaced

---

lang/en/texts/data.en.html

Add hint on where to find the delta files and how to process them.
This is a follow-up to #1153, because we have not announced how to process the delta files, yet.

Add delta files to data docs

---

lang/de/texts/code-of-conduct.html
lang/de/texts/contact.en.html
lang/de/texts/contribute.html
lang/de/texts/data.en.html
lang/de/texts/discover.html
lang/de/texts/experimental-nutrition-score-france.html
lang/de/texts/faq.html
lang/de/texts/how-to-add-a-product.html
lang/de/texts/index.en.html
lang/de/texts/index.foundation.en.html
lang/de/texts/legal.html
lang/de/texts/missions.html
lang/de/texts/nutrition-score-uk.html
lang/de/texts/open-food-hunt-2015.html
lang/de/texts/press-and-blogs.html
lang/de/texts/press.html
lang/de/texts/products.html
lang/de/texts/rateyourvendingmachine.html
lang/de/texts/scan-parties.html
lang/de/texts/terms-of-use.html
lang/de/texts/who-we-are.html

German translations for content pages

German translations for content pages

---

lang/ja/texts/code-of-conduct.html
lang/ja/texts/contact.en.html
lang/ja/texts/contribute.html
lang/ja/texts/data.en.html
lang/ja/texts/discover.html
lang/ja/texts/experimental-nutrition-score-france.html
lang/ja/texts/faq.html
lang/ja/texts/how-to-add-a-product.html
lang/ja/texts/index.en.html
lang/ja/texts/index.foundation.en.html
lang/ja/texts/legal.html
lang/ja/texts/missions.html
lang/ja/texts/nutrition-score-uk.html
lang/ja/texts/open-food-hunt-2015.html
lang/ja/texts/press-and-blogs.html
lang/ja/texts/press.html
lang/ja/texts/products.html
lang/ja/texts/rateyourvendingmachine.html
lang/ja/texts/scan-parties.html
lang/ja/texts/terms-of-use.html
lang/ja/texts/who-we-are.html

Japanese translations

---

lang/hu/texts/code-of-conduct.html
lang/hu/texts/contact.en.html
lang/hu/texts/contribute.html
lang/hu/texts/data.en.html
lang/hu/texts/discover.html
lang/hu/texts/experimental-nutrition-score-france.html
lang/hu/texts/faq.html
lang/hu/texts/how-to-add-a-product.html
lang/hu/texts/index.en.html
lang/hu/texts/index.foundation.en.html
lang/hu/texts/legal.html
lang/hu/texts/missions.html
lang/hu/texts/nutrition-score-uk.html
lang/hu/texts/open-food-hunt-2015.html
lang/hu/texts/press-and-blogs.html
lang/hu/texts/press.html
lang/hu/texts/products.html
lang/hu/texts/rateyourvendingmachine.html
lang/hu/texts/scan-parties.html
lang/hu/texts/terms-of-use.html
lang/hu/texts/who-we-are.html

Add Hungarian translations

---

lang/ru/texts/code-of-conduct.html
lang/ru/texts/contact.en.html
lang/ru/texts/contribute.html
lang/ru/texts/data.en.html
lang/ru/texts/discover.html
lang/ru/texts/experimental-nutrition-score-france.html
lang/ru/texts/faq.html
lang/ru/texts/how-to-add-a-product.html
lang/ru/texts/index.en.html
lang/ru/texts/index.foundation.en.html
lang/ru/texts/legal.html
lang/ru/texts/missions.html
lang/ru/texts/nutrition-score-uk.html
lang/ru/texts/open-food-hunt-2015.html
lang/ru/texts/press-and-blogs.html
lang/ru/texts/press.html
lang/ru/texts/products.html
lang/ru/texts/rateyourvendingmachine.html
lang/ru/texts/scan-parties.html
lang/ru/texts/terms-of-use.html
lang/ru/texts/who-we-are.html

Russian translations

---

lang/lv/texts/code-of-conduct.html
lang/lv/texts/contact.en.html
lang/lv/texts/contribute.html
lang/lv/texts/data.en.html
lang/lv/texts/discover.html
lang/lv/texts/experimental-nutrition-score-france.html
lang/lv/texts/faq.html
lang/lv/texts/how-to-add-a-product.html
lang/lv/texts/index.en.html
lang/lv/texts/index.foundation.en.html
lang/lv/texts/legal.html
lang/lv/texts/missions.html
lang/lv/texts/nutrition-score-uk.html
lang/lv/texts/open-food-hunt-2015.html
lang/lv/texts/press-and-blogs.html
lang/lv/texts/press.html
lang/lv/texts/products.html
lang/lv/texts/rateyourvendingmachine.html
lang/lv/texts/scan-parties.html
lang/lv/texts/terms-of-use.html
lang/lv/texts/who-we-are.html

Latvian translations

---

lang/ga/texts/code-of-conduct.html
lang/ga/texts/contact.en.html
lang/ga/texts/contribute.html
lang/ga/texts/data.en.html
lang/ga/texts/discover.html
lang/ga/texts/experimental-nutrition-score-france.html
lang/ga/texts/faq.html
lang/ga/texts/how-to-add-a-product.html
lang/ga/texts/index.en.html
lang/ga/texts/index.foundation.en.html
lang/ga/texts/legal.html
lang/ga/texts/missions.html
lang/ga/texts/nutrition-score-uk.html
lang/ga/texts/open-food-hunt-2015.html
lang/ga/texts/press-and-blogs.html
lang/ga/texts/press.html
lang/ga/texts/products.html
lang/ga/texts/rateyourvendingmachine.html
lang/ga/texts/scan-parties.html
lang/ga/texts/terms-of-use.html
lang/ga/texts/who-we-are.html

Add Galician translations

---

lang/es/texts/code-of-conduct.html
lang/es/texts/contact.en.html
lang/es/texts/contribute.html
lang/es/texts/data.en.html
lang/es/texts/discover.html
lang/es/texts/experimental-nutrition-score-france.html
lang/es/texts/faq.html
lang/es/texts/how-to-add-a-product.html
lang/es/texts/index.en.html
lang/es/texts/index.foundation.en.html
lang/es/texts/legal.html
lang/es/texts/missions.html
lang/es/texts/nutrition-score-uk.html
lang/es/texts/press-and-blogs.html
lang/es/texts/press.html
lang/es/texts/products.html
lang/es/texts/rateyourvendingmachine.html
lang/es/texts/scan-parties.html
lang/es/texts/terms-of-use.html
lang/es/texts/who-we-are.html

Spanish translations for content pages

Spanish translations for content pages

---

lang/ro/texts/code-of-conduct.html
lang/ro/texts/contact.en.html
lang/ro/texts/contribute.html
lang/ro/texts/data.en.html
lang/ro/texts/discover.html
lang/ro/texts/experimental-nutrition-score-france.html
lang/ro/texts/faq.html
lang/ro/texts/how-to-add-a-product.html
lang/ro/texts/index.en.html
lang/ro/texts/index.foundation.en.html
lang/ro/texts/legal.html
lang/ro/texts/missions.html
lang/ro/texts/nutrition-score-uk.html
lang/ro/texts/open-food-hunt-2015.html
lang/ro/texts/press-and-blogs.html
lang/ro/texts/press.html
lang/ro/texts/products.html
lang/ro/texts/rateyourvendingmachine.html
lang/ro/texts/scan-parties.html
lang/ro/texts/terms-of-use.html
lang/ro/texts/who-we-are.html

Add Romanian translations

---

lang/da/texts/code-of-conduct.html
lang/da/texts/contact.en.html
lang/da/texts/contribute.html
lang/da/texts/data.en.html
lang/da/texts/discover.html
lang/da/texts/experimental-nutrition-score-france.html
lang/da/texts/faq.html
lang/da/texts/how-to-add-a-product.html
lang/da/texts/index.en.html
lang/da/texts/index.foundation.en.html
lang/da/texts/legal.html
lang/da/texts/missions.html
lang/da/texts/nutrition-score-uk.html
lang/da/texts/open-food-hunt-2015.html
lang/da/texts/press-and-blogs.html
lang/da/texts/press.html
lang/da/texts/products.html
lang/da/texts/rateyourvendingmachine.html
lang/da/texts/scan-parties.html
lang/da/texts/terms-of-use.html
lang/da/texts/who-we-are.html

Danish translations

---

nl_NL/texts/code-of-conduct.html
nl_NL/texts/contact.en.html
nl_NL/texts/contribute.html
nl_NL/texts/data.en.html
nl_NL/texts/discover.html
nl_NL/texts/experimental-nutrition-score-france.html
nl_NL/texts/faq.html
nl_NL/texts/how-to-add-a-product.html
nl_NL/texts/index.en.html
nl_NL/texts/index.foundation.en.html
nl_NL/texts/legal.html
nl_NL/texts/missions.html
nl_NL/texts/nutrition-score-uk.html
nl_NL/texts/open-food-hunt-2015.html
nl_NL/texts/press-and-blogs.html
nl_NL/texts/press.html
nl_NL/texts/products.html
nl_NL/texts/rateyourvendingmachine.html
nl_NL/texts/scan-parties.html
nl_NL/texts/terms-of-use.html
nl_NL/texts/who-we-are.html

Dutch translations

---

lang/pl/texts/code-of-conduct.html
lang/pl/texts/contact.en.html
lang/pl/texts/contribute.html
lang/pl/texts/data.en.html
lang/pl/texts/discover.html
lang/pl/texts/experimental-nutrition-score-france.html
lang/pl/texts/faq.html
lang/pl/texts/how-to-add-a-product.html
lang/pl/texts/index.en.html
lang/pl/texts/index.foundation.en.html
lang/pl/texts/legal.html
lang/pl/texts/missions.html
lang/pl/texts/nutrition-score-uk.html
lang/pl/texts/open-food-hunt-2015.html
lang/pl/texts/press-and-blogs.html
lang/pl/texts/press.html
lang/pl/texts/products.html
lang/pl/texts/rateyourvendingmachine.html
lang/pl/texts/scan-parties.html
lang/pl/texts/terms-of-use.html
lang/pl/texts/who-we-are.html

polish-translation

---

lang/pt/texts/code-of-conduct.html
lang/pt/texts/contact.en.html
lang/pt/texts/contribute.html
lang/pt/texts/data.en.html
lang/pt/texts/discover.html
lang/pt/texts/experimental-nutrition-score-france.html
lang/pt/texts/faq.html
lang/pt/texts/how-to-add-a-product.html
lang/pt/texts/index.en.html
lang/pt/texts/index.foundation.en.html
lang/pt/texts/legal.html
lang/pt/texts/missions.html
lang/pt/texts/nutrition-score-uk.html
lang/pt/texts/open-food-hunt-2015.html
lang/pt/texts/press-and-blogs.html
lang/pt/texts/press.html
lang/pt/texts/products.html
lang/pt/texts/rateyourvendingmachine.html
lang/pt/texts/scan-parties.html
lang/pt/texts/terms-of-use.html
lang/pt/texts/who-we-are.html

Portuguese translations

---

taxonomies/ingredients.txt

* Update ingredients.txt
* Update ingredients.txt
* Update ingredients.txt
#{Issue Number}

Update ingredients.txt (#1297)

---

lang/fr/texts/score-nutritionnel-france.html

Correction de la documentation de la formule de calcul du Nutriscore
et lien vers la version de référence sur Légifrance

Mise à jour de la doc du Nutriscore

---

lang/de/texts/contact.en.html
lang/de/texts/contribute.html
lang/de/texts/discover.html
lang/de/texts/nova-groups-for-food-processing.html
lang/de/texts/open-food-hunt.html
lang/de/texts/press-and-blogs.html
lang/de/texts/who-we-are.html

de content

---

lang/da/texts/code-of-conduct.html
lang/da/texts/contact.en.html
lang/da/texts/contribute.html
lang/da/texts/data.en.html
lang/da/texts/discover.html
lang/da/texts/faq.html
lang/da/texts/how-to-add-a-product.html
lang/da/texts/index.en.html
lang/da/texts/index.foundation.en.html
lang/da/texts/legal.html
lang/da/texts/missions.html
lang/da/texts/nova-groups-for-food-processing.html
lang/da/texts/nutrition-score-uk.html
lang/da/texts/open-food-hunt-2015.html
lang/da/texts/open-food-hunt.html
lang/da/texts/press-and-blogs.html
lang/da/texts/press.html
lang/da/texts/products.html
lang/da/texts/rateyourvendingmachine.html
lang/da/texts/scan-parties.html
lang/da/texts/terms-of-use.html
lang/da/texts/who-we-are.html

Da Content update

---

lang/sk/texts/code-of-conduct.html
lang/sk/texts/contact.en.html
lang/sk/texts/contribute.html
lang/sk/texts/data.en.html
lang/sk/texts/discover.html
lang/sk/texts/experimental-nutrition-score-france.html
lang/sk/texts/faq.html
lang/sk/texts/how-to-add-a-product.html
lang/sk/texts/index.en.html
lang/sk/texts/index.foundation.en.html
lang/sk/texts/legal.html
lang/sk/texts/missions.html
lang/sk/texts/nova-groups-for-food-processing.html
lang/sk/texts/nutrition-score-uk.html
lang/sk/texts/open-food-hunt-2015.html
lang/sk/texts/open-food-hunt.html
lang/sk/texts/press-and-blogs.html
lang/sk/texts/press.html
lang/sk/texts/products.html
lang/sk/texts/rateyourvendingmachine.html
lang/sk/texts/scan-parties.html
lang/sk/texts/terms-of-use.html
lang/sk/texts/who-we-are.html

sk content

---

lang/hu/texts/code-of-conduct.html
lang/hu/texts/contact.en.html
lang/hu/texts/contribute.html
lang/hu/texts/data.en.html
lang/hu/texts/discover.html
lang/hu/texts/experimental-nutrition-score-france.html
lang/hu/texts/faq.html
lang/hu/texts/how-to-add-a-product.html
lang/hu/texts/index.en.html
lang/hu/texts/index.foundation.en.html
lang/hu/texts/legal.html
lang/hu/texts/missions.html
lang/hu/texts/nova-groups-for-food-processing.html
lang/hu/texts/nutrition-score-uk.html
lang/hu/texts/open-food-hunt-2015.html
lang/hu/texts/open-food-hunt.html
lang/hu/texts/press-and-blogs.html
lang/hu/texts/press.html
lang/hu/texts/products.html
lang/hu/texts/rateyourvendingmachine.html
lang/hu/texts/scan-parties.html
lang/hu/texts/terms-of-use.html
lang/hu/texts/who-we-are.html

Hu Content

---

lang/bg/texts/code-of-conduct.html
lang/bg/texts/contact.en.html
lang/bg/texts/contribute.html
lang/bg/texts/data.en.html
lang/bg/texts/discover.html
lang/bg/texts/experimental-nutrition-score-france.html
lang/bg/texts/faq.html
lang/bg/texts/how-to-add-a-product.html
lang/bg/texts/index.en.html
lang/bg/texts/index.foundation.en.html
lang/bg/texts/legal.html
lang/bg/texts/missions.html
lang/bg/texts/nova-groups-for-food-processing.html
lang/bg/texts/nutrition-score-uk.html
lang/bg/texts/open-food-hunt-2015.html
lang/bg/texts/open-food-hunt.html
lang/bg/texts/press-and-blogs.html
lang/bg/texts/press.html
lang/bg/texts/products.html
lang/bg/texts/rateyourvendingmachine.html
lang/bg/texts/scan-parties.html
lang/bg/texts/terms-of-use.html
lang/bg/texts/who-we-are.html

Bulgarian content

---

lang/cs/texts/code-of-conduct.html
lang/cs/texts/contact.en.html
lang/cs/texts/contribute.html
lang/cs/texts/data.en.html
lang/cs/texts/discover.html
lang/cs/texts/experimental-nutrition-score-france.html
lang/cs/texts/faq.html
lang/cs/texts/how-to-add-a-product.html
lang/cs/texts/index.en.html
lang/cs/texts/index.foundation.en.html
lang/cs/texts/legal.html
lang/cs/texts/missions.html
lang/cs/texts/nova-groups-for-food-processing.html
lang/cs/texts/nutrition-score-uk.html
lang/cs/texts/open-food-hunt-2015.html
lang/cs/texts/open-food-hunt.html
lang/cs/texts/press-and-blogs.html
lang/cs/texts/press.html
lang/cs/texts/products.html
lang/cs/texts/rateyourvendingmachine.html
lang/cs/texts/scan-parties.html
lang/cs/texts/terms-of-use.html
lang/cs/texts/who-we-are.html

Czech content

---

lang/lt/texts/code-of-conduct.html
lang/lt/texts/contact.en.html
lang/lt/texts/contribute.html
lang/lt/texts/data.en.html
lang/lt/texts/discover.html
lang/lt/texts/experimental-nutrition-score-france.html
lang/lt/texts/faq.html
lang/lt/texts/how-to-add-a-product.html
lang/lt/texts/index.en.html
lang/lt/texts/index.foundation.en.html
lang/lt/texts/legal.html
lang/lt/texts/missions.html
lang/lt/texts/nova-groups-for-food-processing.html
lang/lt/texts/nutrition-score-uk.html
lang/lt/texts/open-food-hunt-2015.html
lang/lt/texts/open-food-hunt.html
lang/lt/texts/press-and-blogs.html
lang/lt/texts/press.html
lang/lt/texts/products.html
lang/lt/texts/rateyourvendingmachine.html
lang/lt/texts/scan-parties.html
lang/lt/texts/terms-of-use.html
lang/lt/texts/who-we-are.html

lt content

---

lang/it/texts/code-of-conduct.html
lang/it/texts/contact.en.html
lang/it/texts/contribute.html
lang/it/texts/data.en.html
lang/it/texts/discover.html
lang/it/texts/faq.html
lang/it/texts/how-to-add-a-product.html
lang/it/texts/index.en.html
lang/it/texts/index.foundation.en.html
lang/it/texts/legal.html
lang/it/texts/missions.html
lang/it/texts/nova-groups-for-food-processing.html
lang/it/texts/nutrition-score-uk.html
lang/it/texts/open-food-hunt.html
lang/it/texts/press-and-blogs.html
lang/it/texts/press.html
lang/it/texts/products.html
lang/it/texts/rateyourvendingmachine.html
lang/it/texts/scan-parties.html
lang/it/texts/terms-of-use.html
lang/it/texts/who-we-are.html

Italian content

---

lang/pl/texts/code-of-conduct.html
lang/pl/texts/contact.en.html
lang/pl/texts/contribute.html
lang/pl/texts/data.en.html
lang/pl/texts/discover.html
lang/pl/texts/experimental-nutrition-score-france.html
lang/pl/texts/faq.html
lang/pl/texts/how-to-add-a-product.html
lang/pl/texts/index.en.html
lang/pl/texts/index.foundation.en.html
lang/pl/texts/legal.html
lang/pl/texts/missions.html
lang/pl/texts/nova-groups-for-food-processing.html
lang/pl/texts/nutrition-score-uk.html
lang/pl/texts/open-food-hunt-2015.html
lang/pl/texts/open-food-hunt.html
lang/pl/texts/press-and-blogs.html
lang/pl/texts/press.html
lang/pl/texts/products.html
lang/pl/texts/rateyourvendingmachine.html
lang/pl/texts/scan-parties.html
lang/pl/texts/terms-of-use.html
lang/pl/texts/who-we-are.html

Polski content

---

lang/et/texts/code-of-conduct.html
lang/et/texts/contact.en.html
lang/et/texts/contribute.html
lang/et/texts/data.en.html
lang/et/texts/discover.html
lang/et/texts/experimental-nutrition-score-france.html
lang/et/texts/faq.html
lang/et/texts/how-to-add-a-product.html
lang/et/texts/index.en.html
lang/et/texts/index.foundation.en.html
lang/et/texts/legal.html
lang/et/texts/missions.html
lang/et/texts/nova-groups-for-food-processing.html
lang/et/texts/nutrition-score-uk.html
lang/et/texts/open-food-hunt-2015.html
lang/et/texts/open-food-hunt.html
lang/et/texts/press-and-blogs.html
lang/et/texts/press.html
lang/et/texts/products.html
lang/et/texts/rateyourvendingmachine.html
lang/et/texts/scan-parties.html
lang/et/texts/terms-of-use.html
lang/et/texts/who-we-are.html

Estonian content

---

lang/mt/texts/code-of-conduct.html
lang/mt/texts/contact.en.html
lang/mt/texts/contribute.html
lang/mt/texts/data.en.html
lang/mt/texts/discover.html
lang/mt/texts/experimental-nutrition-score-france.html
lang/mt/texts/faq.html
lang/mt/texts/how-to-add-a-product.html
lang/mt/texts/index.en.html
lang/mt/texts/index.foundation.en.html
lang/mt/texts/legal.html
lang/mt/texts/missions.html
lang/mt/texts/nova-groups-for-food-processing.html
lang/mt/texts/nutrition-score-uk.html
lang/mt/texts/open-food-hunt-2015.html
lang/mt/texts/open-food-hunt.html
lang/mt/texts/press-and-blogs.html
lang/mt/texts/press.html
lang/mt/texts/products.html
lang/mt/texts/rateyourvendingmachine.html
lang/mt/texts/scan-parties.html
lang/mt/texts/terms-of-use.html
lang/mt/texts/who-we-are.html

Maltese content

---

lang/hr/texts/code-of-conduct.html
lang/hr/texts/contact.en.html
lang/hr/texts/contribute.html
lang/hr/texts/data.en.html
lang/hr/texts/discover.html
lang/hr/texts/experimental-nutrition-score-france.html
lang/hr/texts/faq.html
lang/hr/texts/how-to-add-a-product.html
lang/hr/texts/index.en.html
lang/hr/texts/index.foundation.en.html
lang/hr/texts/legal.html
lang/hr/texts/missions.html
lang/hr/texts/nova-groups-for-food-processing.html
lang/hr/texts/nutrition-score-uk.html
lang/hr/texts/open-food-hunt-2015.html
lang/hr/texts/open-food-hunt.html
lang/hr/texts/press-and-blogs.html
lang/hr/texts/press.html
lang/hr/texts/products.html
lang/hr/texts/rateyourvendingmachine.html
lang/hr/texts/scan-parties.html
lang/hr/texts/terms-of-use.html
lang/hr/texts/who-we-are.html

HR Content

---

lang/ga/texts/code-of-conduct.html
lang/ga/texts/contact.en.html
lang/ga/texts/contribute.html
lang/ga/texts/data.en.html
lang/ga/texts/discover.html
lang/ga/texts/experimental-nutrition-score-france.html
lang/ga/texts/faq.html
lang/ga/texts/how-to-add-a-product.html
lang/ga/texts/index.en.html
lang/ga/texts/index.foundation.en.html
lang/ga/texts/legal.html
lang/ga/texts/missions.html
lang/ga/texts/nova-groups-for-food-processing.html
lang/ga/texts/nutrition-score-uk.html
lang/ga/texts/open-food-hunt-2015.html
lang/ga/texts/open-food-hunt.html
lang/ga/texts/press-and-blogs.html
lang/ga/texts/press.html
lang/ga/texts/products.html
lang/ga/texts/rateyourvendingmachine.html
lang/ga/texts/scan-parties.html
lang/ga/texts/terms-of-use.html
lang/ga/texts/who-we-are.html

GA content

---

lang/ro/texts/code-of-conduct.html
lang/ro/texts/contact.en.html
lang/ro/texts/contribute.html
lang/ro/texts/data.en.html
lang/ro/texts/discover.html
lang/ro/texts/experimental-nutrition-score-france.html
lang/ro/texts/faq.html
lang/ro/texts/how-to-add-a-product.html
lang/ro/texts/index.en.html
lang/ro/texts/index.foundation.en.html
lang/ro/texts/legal.html
lang/ro/texts/missions.html
lang/ro/texts/nova-groups-for-food-processing.html
lang/ro/texts/nutrition-score-uk.html
lang/ro/texts/open-food-hunt-2015.html
lang/ro/texts/open-food-hunt.html
lang/ro/texts/press-and-blogs.html
lang/ro/texts/press.html
lang/ro/texts/products.html
lang/ro/texts/rateyourvendingmachine.html
lang/ro/texts/scan-parties.html
lang/ro/texts/terms-of-use.html
lang/ro/texts/who-we-are.html

Ro content

---

lang/pt/texts/contact.en.html
lang/pt/texts/contribute.html
lang/pt/texts/discover.html
lang/pt/texts/index.en.html
lang/pt/texts/index.foundation.en.html
lang/pt/texts/nova-groups-for-food-processing.html
lang/pt/texts/open-food-hunt-2015.html
lang/pt/texts/open-food-hunt.html
lang/pt/texts/press-and-blogs.html
lang/pt/texts/terms-of-use.html
lang/pt/texts/who-we-are.html

Portuguese translations update

Portuguese translations update

---

lang/id/texts/code-of-conduct.html
lang/id/texts/contact.en.html
lang/id/texts/contribute.html
lang/id/texts/data.en.html
lang/id/texts/discover.html
lang/id/texts/experimental-nutrition-score-france.html
lang/id/texts/faq.html
lang/id/texts/how-to-add-a-product.html
lang/id/texts/index.en.html
lang/id/texts/index.foundation.en.html
lang/id/texts/legal.html
lang/id/texts/missions.html
lang/id/texts/nova-groups-for-food-processing.html
lang/id/texts/nutrition-score-uk.html
lang/id/texts/open-food-hunt-2015.html
lang/id/texts/open-food-hunt.html
lang/id/texts/press-and-blogs.html
lang/id/texts/press.html
lang/id/texts/products.html
lang/id/texts/rateyourvendingmachine.html
lang/id/texts/scan-parties.html
lang/id/texts/terms-of-use.html
lang/id/texts/who-we-are.html

Indonesian content

---

lang/it/texts/discover.html
lang/it/texts/faq.html
lang/it/texts/nova-groups-for-food-processing.html

Italy static refresh

---

po/common/de.po

German common translations

---

docker/backend/Dockerfile

Update Dockerfile according to Docker best practices https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Update backend dockerfile

---

lang/en/texts/missions-texts.html
lib/ProductOpener/MissionsConfig.pm

Remove s from aperçus.
Fixes #856

Fixes #856: Remove s from aperçus

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
docker/README.md

I used this [linter](https://github.com/DavidAnson/vscode-markdownlint) for updating the markdown's files.
Then, "http" to "https" to avoid some redirection.

update according to good pratices

---

docker/backend-dev/conf/Config.pm
docker/backend-dev/conf/Config2.pm
docker/productopener/requirements.lock
docker/productopener/requirements.yaml
docker/productopener/templates/backend-conf.yaml
lib/ProductOpener/Cache.pm
lib/ProductOpener/Config2_sample.pm
lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opf.pm
lib/ProductOpener/Config_opff.pm
lib/ProductOpener/Display.pm

Let's move the memcached server address to Config/Config2, so that it does not _have to_ live at 127.0.0.1

Add memcached to config

---

lib/ProductOpener/Display.pm

I hope that it's ok for the selector.

overflow tag list #246

---

lang/obf/it/texts/contribute.html
lang/obf/it/texts/discover.html
lang/obf/it/texts/faq.html
lang/obf/it/texts/index.html
lang/obf/it/texts/press-and-blogs.html

Translation of OBF static in Italian

Translation of OBF static in Italian

---

taxonomies/ingredients.txt

Added the language prefixes en: to the wikipedia and wikidata entries.

en: repairs

---

taxonomies/ingredients.txt

* Added bread crumbs
* Added E471

Added bread crumbs & E471(#1)

---

taxonomies/ingredients.txt

Un premier test d'ajout dans la taxonomie
**Checklist:**

Ajout carbonfoodprint foodges 3 aliments poulet

---

taxonomies/ingredients.txt

Update taxonomy for carbon foot print estimation

---

taxonomies/ingredients.txt

Ajout poisson et produit laitier FoodGES dans la taxonomie
**Checklist:**

taxonomie FoodGES Victor 2

---

taxonomies/ingredients.txt

Herbes de Provence

---

t/ingredients.t
taxonomies/ingredients.txt

Typo in ingredients

---

taxonomies/ingredients.txt

Tomato translations and cleanup

Ingredients taxonomy patch 10

---

cgi/manifest.pl

Add prefer_related_applications

---

.editorconfig
scripts/checkbot.pl

Code documentation, for those who doesn't already know EditorConfig (which was my case).

Code documentation + Checkbot tweaks

---

packager-codes/get_packager_code_from_html_ireland.py

The main function (ireland_correction_of_1_dataframe) should be usable for most other countries as well
**Checklist:**

To get html table of packager codes for ireland

---

cgi/search.pl

add `and ($sort_by ne 'product_name')` in search.pl line 166
Fix #1608

correction_sort_by_product_name

---

lib/ProductOpener/Display.pm

Apparently, one problem in the world map is that some country codes are used multiple times. By using a hash map and the JSON module to encode the hash to JavaScript, duplicate keys should be avoided.
Fixes #196

Use JSON module for #world-map data

---

lang/fr/texts/decouvrir.html

Correct issue #1619.

---

.gitignore

Some files are local databases created by the app on each environment: *.sto, top_translators.csv. They have to be ignored by git.

Add local databases

---

scripts/checkbot.pl

Add parameters to the command line to make the bot more efficient -- see issue #1606.
**Next step, add to cron**
* `0 12 * * * /path/to/script/checkbot.pl --max-sendings=2 --country=France --order=random --channel=#fr`
* `0 13 * * * /path/to/script/checkbot.pl --max-sendings=5 --channel=#bot-alerts`

Add --max_sendings, --country, --order, --channel options

---

html/css/product-multilingual.css

Small CSS3 improvement to let tag boxes be resizable (#1322).

Let tag boxes be resizable. Issue #1322.

---

taxonomies/ingredients.txt

I'll redo the updates by hand. Automatic filemerge does not work: to many changes.

Merge #1569

---

lib/ProductOpener/Data.pm
lib/ProductOpener/Display.pm
scripts/refresh_products_tags.js

1. create products_tags collection with script refresh_products_tags.js
2. modify files Data.pm and Display.pm to use products_tags collection in aggregate.
3. schedule refresh of products_tags collection
**Related issues and discussion:** #1610

improve aggregations perf

---

scripts/export_database.pl

Trim trailing whitespaces to conform to .editorconfig and increase future diff readability.
Code doesn't change at all.

Trim trailing whitespaces (see OFF .editorconfig)

---

lib/ProductOpener/Display.pm

Updated the regex to match a single character that matches a "Nutriscore" value. Fixes #1637

Fix 404 nutriscore-not-applicable.svg

---

taxonomies/ingredients.txt

merge master into branch

---

lib/ProductOpener/Food.pm
t/food.t

Added some Chinese SI unit names to `g_to_unit`, `unit_to_g`, `normalize_serving_size`, and `normalize_quantity`.
**Related issues and discussion:** #1618

Support some SI weights in Chinese

---

html/js/product-multilingual.js
lib/ProductOpener/Images.pm

To enable file selection on Android , the `capture` attribute just needs to removed.  Also see https://developers.google.com/web/fundamentals/media/capturing-images/#file_input
**Related issues and discussion:** Fixes #653

Remove `capture` attribute to allow file selection

---

scripts/run_cloud_vision_ocr.pl

labelAnnotations contains annotations of detected objects in images, including "face", "selfie",...

Request labelAnnotations from Google Cloud Vision

---

lib/ProductOpener/Config_off.pm

Disable Nutri-Score for products waiting to be moved to other projects

Disable Nutri-Score for products waiting to be moved to other projects

---

cgi/nutrients.pl
lib/ProductOpener/Food.pm

**Description:** Exposes nutrient structure for the current subdomain as a JSON structure.
**Related issues and discussion:** Fixes #1689

Nutrients JSON API

---

taxonomies/ingredients.txt

Patch 17 - ingredients taxonomy

---

docker/backend-dev/conf/Config.pm
docker/backend-dev/conf/Config2.pm
docker/productopener/templates/backend-conf.yaml
html/js/display-product.js
lib/ProductOpener/Config2_sample.pm
lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opf.pm
lib/ProductOpener/Config_opff.pm
lib/ProductOpener/Display.pm
po/common/common.pot
po/common/de.po
po/common/en.po

**Description:** Adds Robotoff questions for the displayed product as an alert/overlay.
**Related issues and discussion:** Fixes #1701

Display Robotoff on product pages

---

cgi/search.pl

**Description:** When using `search.pl` with a parameter that requires structured data, do not redirect to a product's HTML page, even if the search looks like a product barcode.
**Related issues and discussion:** Fixes #1732

Don't redirect if JSON is requested

---

taxonomies/ingredients.txt

Ingredients patch 19

---

taxonomies/ingredients.txt

Foodges pois haricot asperge

---

taxonomies/ingredients.txt

add Tomatoes GES

---

lib/ProductOpener/SiteQuality_off.pm
t/sitequality.t

As discussed on Slack: https://openfoodfacts.slack.com/archives/C7FPRUXGB/p1557247920048200

Quality tag for max energy

---

lib/ProductOpener/Display.pm

**Description:** I replaced the custom CSV output with the `Text::CSV` package that is currently being used in `ProductOpener::Import`. Because the format is identically, the output is compatible with the previous export and should not cause any problems with consumers.
**Related issues and discussion:** I believe this fixes #161, because `Text::CSV` will take care of escaping CSV values. Additionally, output will be sped up, because less strings will be built to produce the output.

Use Text::CSV for CSV output

---

taxonomies/ingredients.txt

The 20th set of ingredients patches.

Ingredients patch 20 aleene

---

taxonomies/categories.txt

test pull request

---

taxonomies/categories.txt

For some ingredients I can copy the translations to the categories.

translations

---

taxonomies/categories.txt

Added "calissons" and "Physalis séchées"

---

lang/fr/texts/presse.html

Minimal press fix

---

taxonomies/categories.txt

Small enhancement:
```
+<en:Instant beverages
en:Powdered capuccino
```

Powdered cappuccino under <en:Instant beverages

---

taxonomies/categories.txt

Changes in pasta

---

lib/ProductOpener/Display.pm

**Description:** Try to avoid Apache's built-in error page.
**Related issues and discussion:** #1813

Flush HTTP headers and tell Apache that everything is OK

---

lib/ProductOpener/Ingredients.pm

death-by-a-thousand-cuts

---

conf/nginx/sites-available/off

**Description:** Redirect as requested in the issue.
**Related issues and discussion:** Fixes #301

Add windowsphone.openfoodfacts.org redirect

---

cgi/search.pl
lib/ProductOpener/Products.pm
po/common/common.pot
po/common/de.po
po/common/en.po
t/products.t

**Description:** Compute `$product_ref->{completeness}` as a score from 0-100% (0.0-1.0) and allow search results to be sorted by this value.
**Related issues and discussion:** Fixes #20

Sort by completeness

---

po/common/common.pot

fix-typo-in-translation

---

lang/fr/texts/qui-sommes-nous.html

Typo in Qui Sommes Nous

---

lib/ProductOpener/Ingredients.pm

More cutting words for spanish

---

cgi/product_multilingual.pl

Currently live on the dev server: https://fr.openfoodfacts.org/cgi/product.pl?type=edit&code=3484700000978

use javascript to set width of fixed save bar, fixes #1287

---

cgi/product_image_crop.pl
cgi/product_jqm_multilingual.pl
lib/ProductOpener/Products.pm

try to set language for Spanish products uploaded by Yuka, bug #1837

---

html/js/display-product.js

Put the buttons at the left, remove the product thumbnail.

display the robotoff buttons to the left, fixes bug #1788

---

taxonomies/allergens.txt

Added sojaeiwitten

---

lib/ProductOpener/Config_off.pm

replaced ( ) by { } to get a reference to the manifest options

fix manifest.cgi that did not compile

---

cgi/product_multilingual.pl

Should fix null dereferencing (issue #1890)

---

cgi/product_multilingual.pl
html/js/product-multilingual.js
yarn.lock

Fixes 1244

---

taxonomies/additives.txt

for additives authorized in organic food
useful for bug #1807 and to show on the page of each additive

Added a organic_eu:en:authorized property

---

lib/ProductOpener/Display.pm

Fix for #1889

---

lib/ProductOpener/Food.pm
lib/ProductOpener/Ingredients.pm

remove old invalid co2 computations

---

cgi/ingredients.pl
cgi/nutrition.pl
lib/ProductOpener/Food.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Ingredients.pm

This is to run OCR of nutrition facts images, in order to try later to extract the nutrition facts from them.

Nutrition OCR on nutrition facts images

---

lib/ProductOpener/Ingredients.pm
t/ingredients_clean.t

Fix "demi - écrémé" instead of "demi-écrémé" issue.

additional fix for bug #1880, extra spaces around dash

---

crowdin.yml

Remove Crowdin config for states taxonomy

Remove Crowdin config for states taxonomy

---

cgi/recent_changes.pl
lib/ProductOpener/Display.pm

Fixes issue #1139 and extract pagination to a sub to be reusable.

Pagination links for recent changes

---

cgi/product_multilingual.pl
lib/ProductOpener/Display.pm

add if for barcode, fixes #1921

---

po/common/common.pot
po/common/en.po
po/tags/en.po
po/tags/tags.pot
scripts/scanbot.pl

This is a new popularity facet based on scan logs, to be used in particular for quality review.
Details are on bug #1943
It is not perfect, but it does the job. When we have a scans database, we can make a better system.

log processing to populate a new popularity facet, bug #1943

---

lib/ProductOpener/SiteQuality_off.pm

Added quality facets

---

taxonomies/categories.txt

Added "crèmes d'artichaut" and "Crèmes dessert café"

---

cgi/product_multilingual.pl
po/common/ru.po

Misc fixes

---

lib/ProductOpener/Display.pm
po/common/en.po
scss/_off.scss

Made recent changes aggregate edits made on the same product by the same user
Fixes #1140

Made recent changes aggregate edits

---

cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
lib/ProductOpener/Food.pm

Fix salt and sodium issues

---

cgi/suggest.pl

Make suggest.pl return strings that contains the word.
Related to #1734

Partial fix for issue 1734

---

lib/ProductOpener/Ingredients.pm
t/additives.t
t/additives_tags.t
t/ingredients_parsing.t
taxonomies/additives.txt

Added tests for additives detection.

tests for ins / sin additives, bug #1133

---

cgi/product_jqm_multilingual.pl
lib/ProductOpener/Food.pm
lib/ProductOpener/Ingredients.pm
lib/ProductOpener/SiteQuality_off.pm
lib/ProductOpener/Tags.pm
scripts/update_all_products.pl
taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

A few small changes to @RonanMorgan 's implementation of carbon footprint computation from all known ingredients found in FoodGES, in addition to meat and fish.

Carbon footprint

---

lib/ProductOpener/Config_off.pm
lib/ProductOpener/Display.pm
lib/ProductOpener/Products.pm
lib/ProductOpener/Store.pm
lib/ProductOpener/Tags.pm
scripts/update_all_products.pl
t/tags.t

This is to attribute changes made by Yuka users to each invidivual Yuka user, using their UUID provided by Yuka.
You can test it on the dev server: https://world.dev.openfoodfacts.org/editor/yuka.V0trZkdxMWNwTnhUeXNRQjR3ajY1TTh2dzZLVmVraVpKZlFOSVE9PQ
The full UUID is not displayed on the web page, but it is in the links and urls (and in the editors_tags etc.). "yuka - user" is displayed instead.

Issue 1912/UUID

---

README.md

**Checklist:**
Update data according "Open Food Facts - the Android application" repos.  A kind of _minor_ effort to synchronize data between repositories
There is no related or lateral issue

Update data according "Open Food Facts - the Android application" repo

---

taxonomies/categories.txt

Clarification of ambiguites related to the multiple uses of the word "Galette" in French.

Correction related to "Galettes"

---

lib/ProductOpener/Tags.pm
t/additives_tags.t
t/tags.t

change exists_taxonomy_tag so that it does not return synonyms

---

lib/ProductOpener/Images.pm
lib/ProductOpener/Ingredients.pm
scripts/update_all_products.pl

Initial implementation to:
1. run ingredients and nutrition images through google cloud vision
2. compute the image orientation
3. autorotate the images
in batch mode, through update_all_products.pl

compute image orientation, autorotate, bug #1991

---

cgi/product_multilingual.pl
scripts/update_all_products.pl

Issue 2000/salt sodium

---

lib/ProductOpener/Food.pm
taxonomies/categories.result.txt
taxonomies/categories.txt

Flavored spring waters should not have Nutriscore A.

fix for flavoured spring waters and nutriscore, fixes #2016

---

taxonomies/ingredients.txt

last ingredient modifications for carbon footprint ingredients

---

lib/ProductOpener/Images.pm
lib/ProductOpener/Ingredients.pm

load the Tesseract module in the right file

Image::OCR::Tesseract get_ocr, fixes #2032

---

lib/ProductOpener/Config_off.pm
lib/ProductOpener/Products.pm
scripts/update_all_products.pl

+ new Apps and App - nameofapp values for data_sources facet

add elcoco, ethic-advisor + new Apps values in data sources, bug #1912

---

crowdin.yml
html/files/presentations/index.txt
lang/en/texts/presentations.html

[Content] How to present Open Food Facts

---

docker/docker-compose.dev.yml
docker/frontend/Dockerfile

Hopefully fixes the Docker frontend image not being built on Azure DevOps right now.

Fix frontend Dockerfile

---

taxonomies/categories.txt

added "kiwi nectars"

---

po/common/fr.po

Bring the French file in the official order of Crowdin. Please don't force edit the French po in the future.

Bring the French file in the official order of Crowdin.

---

po/common/common.pot
po/common/en.po
po/common/fr.po
t/ingredients_analysis.t
taxonomies/ingredients.txt

Fixes for vegan / vegetarian / palm oil.

Issue 1930/ingredients classes

---

taxonomies/ingredients.txt

After 8 months it is time to review and update this section

Ferments etc updates

---

taxonomies/categories.txt

**Checklist:**
Overwhelmingly, the category guesses for Maraschino cherries are incorrect - very few american products are chocolate coated.
Related search: https://world.openfoodfacts.org/cgi/search.pl?action=display&search_terms=Maraschino%20Cherries&tagtype_0=states&tag_contains_0=contains&tag_0=categories-to-be-completed&tagtype_1=countries&tag_contains_1=contains&tag_1=United%20States%20of%20America&sort_by=unique_scans_n&page_size=100&axis_x=energy&axis_y=products_n&action=display
Not quite sure the best way to add in wikidata for it:
https://www.wikidata.org/wiki/Q1078150
**Related issues and discussion:** https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/32

Add a categorisation for "Maraschino cherries"

---

taxonomies/additives.txt
taxonomies/ingredients.txt

Cleanup of enzymes and merging into additives

Enzymes updates

---

cpanfile
lib/ProductOpener/Users.pm

**Description:** Replace the email validation with a different module. See tests by @CharlesNepote [on slack](https://openfoodfacts.slack.com/archives/C045H3K57/p1549476230033000) for more background information.
**Related issues and discussion:** Removes some warnings upon startup, see #315

Replace Email::IsEmail with Email::Valid

---

taxonomies/ingredients.txt

Butter update

---

taxonomies/categories.txt

added "Chocolate covered cranberries"

---

package.json
yarn.lock

Bump stylelint-scss from 3.8.0 to 3.9.1

---

docker/backend-dev/conf/Config.pm
docker/productopener/templates/backend-conf.yaml

Adds taxonomy fields etc. from Config_off.pm to the Config.pm for docker/helm.

Update Config.pm in Docker to match current Config_off.pm fields.

---

taxonomies/categories.txt

added "Fricadelles" and "Physalis"

---

lang/en/texts/nutriscore.html

Keep a copy of the old Nutri-Score page, so that the old translations are kept as well, and that we can possibly refresh them in the future, and point people to it for advanced explanations.

Keep a copy of the old Nutri-Score page

---

taxonomies/categories.txt

added "Mochi", "Croquettes aux crevettes"

---

taxonomies/categories.txt

Huge changes in Creams

---

taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

put back changes erased by mistake

Aleene mousquetaires

---

taxonomies/ingredients.txt

added new ingredients from Barilla

Ingredients from Barilla

---

docker/README.md
docker/backend-dev/conf/po-foreground.sh
docker/backend-dev/scripts/import_sample_data.sh
docker/build_yarn.bat
docker/build_yarn.sh
docker/docker-compose.dev.yml
docker/docker-compose.yml
docker/frontend/Dockerfile

- Updated base images
- Added script for sample data
- Solved issue with symlinks
- Updated readme to add hints about building frontend assets without installing yarn locally

Docker updates and fixes

---

taxonomies/ingredients.txt

Performed an update of the creams section

Reviewed  creams

---

gulpfile.js
lib/ProductOpener/Display.pm
lib/ProductOpener/Images.pm
package.json
yarn.lock

**Description:** Swapped out IOLazy in favour of the new `loading="lazy"` image attribute.
**Related issues and discussion:** Fixes #1198, and probably also fixes #1853

Migrate lazy-loading of images to HTML5 `loading` attribute.

---

taxonomies/labels.txt

Wine labels to improve Robotoff detection

adding wine related labels

---

po/common/common.pot

Add SVG versions of badges

---

lang/en/texts/mobile-app-open-food-facts.html

Add vector Google and Apple Store logos.
Translation can be done using Crowdin easily

Add vector Google and Apple Store logos

---

lib/ProductOpener/Display.pm

fix bug #2155, images HTML code in head

---

crowdin.yml

workaround-turkish since we don't support xx_XX

workaround-turkish

---

taxonomies/categories.txt

de:Bananen

---

taxonomies/labels.txt

found http://www.hechshers.info/hechshers/165.htm on a product

Kosher label addition

---

scripts/remove_empty_products.pl

The script was failing, it's now fixed and is being run.

fix remove_empty_products.pl bug #2167

---

crowdin.yml

shitty values in tags slow merge each time. I'm disabling sync for them.

tmp disabling of tags to restore my sanity

---

lib/ProductOpener/Products.pm

prevent empty users, fixes #2169

---

lib/ProductOpener/Products.pm

fix unaccenting issue in product url

---

scripts/update_all_products.pl

fixes bug #2191(non taxonomized tag fields deleted by update_all_products.pl)

---

taxonomies/labels.txt

Fix in GitHub since the translation wasn't available in the web interface

polish fix

---

taxonomies/nutriments.txt

Added caffeine unit

---

taxonomies/categories.txt

Added rårörda

---

lang/en/texts/rateyourvendingmachine.html

rateyourvendingmachine

---

lib/ProductOpener/Food.pm

Added mg to caffeine
**Related issues and discussion:** #2206

Food.pm caffeine mg

---

lib/ProductOpener/Config_off.pm

Added chewing gums, aromatic herbs and sugar substitutes

Nutriscore exempts

---

crowdin.yml
lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html

crowdfunding-intl

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Tags.pm
t/food.t

Not perfect, but better. Less repeated code in regexp.

improve handling of EC emb codes, bug #2241

---

lib/ProductOpener/SiteQuality_off.pm

Fix issue #2190 reported by @zigouras

fix #2190, nutrition-data-per-serving-missing-serving-size

---

lang/en/texts/mobile-app-open-food-facts.html

Fixes to the App page 
- fixes urls
- adds the crowdsourcing banner in English. 
TODO:
- We need to make sure the URL matches the new crowdsourcing pages. 
- Do we host the June article on the blog or a static page ?
- We need to translate the SVG into English, and then other languages

[WIP] Fixes to the App page

---

taxonomies/categories.txt

Added lingonberries and cloudberries jams

---

po/common/common.pot

add missing strings in common.pot, already in en.po

add strings for ingredients analysis

---

taxonomies/categories.txt

translation swedish

---

taxonomies/categories.txt

Creation of Dessert sauces and Chocolate sauces

---

lib/ProductOpener/Food.pm
t/food.t

fix issue #2279 reported by @aleksejrs

add Russian units, bug #2279

---

taxonomies/categories.txt

Jelly is a common dessert in Spain.

added Jellies (dessert), Raw creams

---

scripts/export_csv_file.pl
scripts/update_all_products.pl

added count and ability to filter on fields that exist

new options for update and export scripts, bug #2311

---

taxonomies/categories.txt

Currently 13 products fitting this category: https://world.openfoodfacts.org/category/de:eierlik%C3%B6re

add advocaats category

---

lang/en/texts/nutriscore.html

fix nutriscore 404 - will close #2268

fix nutriscore 404 - will close #2268 #2126

---

cgi/search.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Tags.pm

going through modperl_error_log to remove unitialized warnings etc.

changes to remove warnings

---

taxonomies/stores.txt

Not for deep integration, just to get a JSON for Robotoff

Stores taxonomy

---

taxonomies/packagings.txt

Not for deep integration, just to get a JSON for Robotoff

Packaging taxonomy

---

lib/ProductOpener/Display.pm

fix to vertically align icons and text for Vegan / Vegetarian

---

lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html

Paypal form

---

.devcontainer/devcontainer.json
docker/backend-dev/conf/Config.pm
docker/backend-dev/conf/Config2.pm
docker/docker-compose.admin-uis.yml
docker/docker-compose.yml
docker/productopener/templates/backend-conf.yaml

I added PostgreSQL to the Docker configuration, so that we can hopefully test Minion etc. locally.

Update Docker to support producers branch

---

.travis.yml
cpanfile
docker/backend/Dockerfile
docker/docker-compose.yml

Installs the `DBD::Pg` CPAN module during Travis CI and Docker build.

Install DBD::Pg

---

lib/ProductOpener/Ingredients.pm
t/ingredients.t
t/ingredients_analysis.t
t/ingredients_parsing.t
t/ingredients_tags.t
taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

handle things like "graisse végétale bio (colza)"
bug #2339

better parsing for oils, bug #2339

---

taxonomies/ingredients.txt

Went through all ingredients from https://de.openfoodfacts.org/ingredients?status=unknown with unknown status and more than 50 occurrences and added where necessary.

add German ingredients, issue #2231

---

html/files/app/ingredients-analysis.json
taxonomies/ingredients_analysis.txt

Icons and colore for the ingredient analysis

Icons and colors for the ingredient analysis

---

lib/ProductOpener/Food.pm
scripts/test_food.pl
taxonomies/additives.txt

- fix the gGlucide food typo
- fixes unicode issues for the food perl test
- add synonyms for E445

Fixed typos for Romanian translation + added E445 synonyms

---

lang/en/texts/nutriscore.html
lang/fr/texts/nutriscore.html

fix nutriscore link to http

---

taxonomies/additives.txt

This commit adds some missing romanian additive translations. Also, it makes sure that other romanian additives start with a capital letter.

Added missing RO additive translations

---

taxonomies/ingredients.txt

es and it ingredients

---

taxonomies/allergens.txt
taxonomies/ingredients.txt

Added "en:wheatflour" for better allergen detection.

Wheatflour

---

taxonomies/additives.txt

- added additive names that were missing
- added synonyms to existing additives
- capitalised existing additives

Added missing RO additives

---

po/common/common.pot

Fix non existing link to /faq#pictures_and_data_from_other_sites

Closes #453

---

po/common/common.pot

Fixing cancel button + 1 other string

Fixing cancel button + 1 other string

---

taxonomies/categories.txt

These romanian category translations were missing.

Added some RO category translations

---

html/files/robots.txt

[WIP] adding MJ12bot to robots.txt

---

.github/workflows/pull_request.yml

**Description:** Additionally to Travis CI, use GitHub Actions for PR validation.
**Related issues and discussion:** N/A

Validate Pull Requests with GitHub Actions

---

.github/workflows/pull_request.yml

trying to find the missing library

postgres libraries

---

html/images/misc/openfoodfacts-logo-no-tagline-dark-mode.svg

Dark mode logo with no tagline made for the iOS version

Dark mode logo with no tagline

---

cgi/import_file_process.pl
cgi/import_file_select_format.pl
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Display.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Import.pm
lib/ProductOpener/Producers.pm
po/common/common.pot
po/common/en.po

used when there is a column for one specific label or category, with a value like 1, Y or Yes

support for columns for specific labels or categories

---

crowdin.yml
lang/en/texts/dev-android.html
lang/en/texts/dev-artificial-intelligence.html
lang/en/texts/dev-general.html
lang/en/texts/dev-ios.html
lang/en/texts/dev-server.html
lang/en/texts/development.html

development page that is using the include system

Development page

---

lib/ProductOpener/MissionsConfig.pm

I was bored during my flight. The gamification system is not actually working anymore.

More missions in English

---

lib/ProductOpener/Nutriscore.pm

more documentation for Nutriscore.pm

---

lang/obf/en/texts/discover.html

Update discover.html for Open Beauty Facts

Update discover.html for Open Beauty Facts

---

lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po

Made number of products localized

---

lang/en/texts/open-food-facts-and-the-nutriscore.html

Switch urls to static. and use language agnostic images

Switch urls to static. and use language agnostic images

---

taxonomies/additives.txt

added catalan syn without diacritics

---

lib/ProductOpener/DataQualityCommon.pm
lib/ProductOpener/DataQualityFood.pm
scripts/update_all_products.pl

Should fix:
https://github.com/openfoodfacts/openfoodfacts-server/issues/2269
https://github.com/openfoodfacts/openfoodfacts-server/issues/2524
https://github.com/openfoodfacts/openfoodfacts-server/issues/2523

Data quality warning for products with main language set to unknown + 5 consonants

---

po/common/common.pot

typos in common.pot

---

taxonomies/categories.txt

Vegetables

---

lib/ProductOpener/Config_off.pm

fix for salt with anti-caking agent
removed milk powder, added gluten
http://archive.wphna.org/wp-content/uploads/2016/01/WN-2016-7-1-3-28-38-Monteiro-Cannon-Levy-et-al-NOVA.pdf

adjustments for nova based on nova paper

---

package-lock.json
package.json

Updated NPM dependencies to their latest versions. Made `stylelint` update on patches and minors.

Updated NPM dependencies

---

lang/en/texts/logo.html

Adding new promo images to the logo include (fix unclosed tag)

---

lang/es/texts/logo.html

Translate the logo page to Spanish

Translate the logo page to Spanish

---

lang/ar/texts/logo.html
lang/ca/texts/logo.html
lang/de/texts/logo.html
lang/el/texts/logo.html
lang/fa/texts/logo.html
lang/fr/texts/logo.html
lang/he/texts/logo.html
lang/it/texts/logo.html
lang/ja/texts/logo.html
lang/nl/texts/logo.html
lang/no/texts/logo.html
lang/pl/texts/logo.html
lang/pt/texts/logo.html
lang/ro/texts/logo.html
lang/ru/texts/logo.html
lang/th/texts/logo.html
lang/uk/texts/logo.html
lang/vi/texts/logo.html
lang/zh_CN/texts/logo.html
lang/zh_TW/texts/logo.html

German translation for the logo include

German translation for the logo include

---

lang/en/texts/keyfacts.html

fixes-to-keyfacts

---

lang/en/texts/keyfacts.html
lang/en/texts/logo.html
lang/en/texts/press-kit.html
lang/en/texts/presskit_selection.html

Reorder in context photos of the app, and remove French ones

Reorder in context photos of the app, and remove French ones

---

lang/en/texts/keyfacts.html

we-learn-from-bold-mistakes

---

html/donate/en.html

French is in /srv/off/html/donate/fr.helloasso.html

Add message and link while form is being loaded

---

cgi/import_photos_upload.pl
cgi/product_image_upload.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Producers.pm
po/common/common.pot
po/common/en.po

This is to easily load images in bulk. They need to have the barcode in their name.
It's for the producers platform, but it could also be used by power contributors, for scan parties etc.

bulk upload of images on producers platform

---

lang/en/texts/mobile-app-open-food-facts.html

fix the link to the app blogpost

fix the link to the app blogpost

---

crowdin.yml
lang/en/texts/index-pro.html
lang/fr/texts/index-pro.html

index page for the producers platform

---

lang/en/texts/data.en.html

Adding a link to the experimental documentation and making it clear that the API is actually rather stable.

Adding a link to the experimental documentation

---

lang/en/texts/nutriscore.html

HTTPS for the last 2 HTTP links on the Nutriscore page

HTTPS for the last 2 HTTP links on the Nutriscore page

---

lang/en/texts/index-pro.html

Fix extra slash character

---

html/donate/en.html

fix to the embed

---

lang/en/texts/science.html

Make the science page more accessible

Make the science page more accessible

---

cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
lib/ProductOpener/Food.pm
lib/ProductOpener/Import.pm

Fixes issue #2574 identified by @zigouras in bug #2574

remove useless calls to remove_tags_and_quote(), bug #2574 #2563

---

html/donate/en.html
html/donate/fr.helloasso.html
lib/ProductOpener/Display.pm
po/common/common.pot

quick and dirty to get banners up in French and English, we will need to add more languages (in a better way) later.

donate text banner

---

lib/ProductOpener/Store.pm

Some optimizations for `get_string_id_for_lang` and `get_fileid`.
In my test runs, it "only" reduced the inclusive time of `get_string_id_for_lang` from 235s to 202s. Replacing most `s/` calls with `tr/`, and the trimming of leading/trailing `-` sped up each statement by about 50%. Here's the latest output of `Devel::NYTProf` of this branch, which shows where most time is spent now: ![image](https://user-images.githubusercontent.com/87124/68777532-180f2a80-0632-11ea-8fe9-971a1adf509d.png)![image](https://user-images.githubusercontent.com/87124/68777447-f7df6b80-0631-11ea-9782-1c50d0ce96d3.png)
**Related issues and discussion:** Related to performance discussion in #2053

Replace some regular expressions

---

lib/ProductOpener/Display.pm

Removed colored additives

---

lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html

Fix for the old donate page

---

conf/nginx/sites-available/off

added-spanish-donation-page

---

cpanfile
lib/ProductOpener/Tags.pm
t/additives.t
t/tags.t

10x speed increase, see  bug #2607 for details.
also added some tests.

speed up remove_stopwords()

---

cpanfile
lib/ProductOpener/Ingredients.pm
lib/ProductOpener/Tags.pm
t/additives.t
t/tags.t

Too slow and not very good. This is way too costly for the small benefit it provides. Disabling until we get a better spell correction solution.

Issue 2609/disable spellchecking

---

lang/es/texts/presskit_es_ES_selection.html
po/common/nl.po
po/common/sr.po
po/common/zh.po

fix-alt-and-img-size

---

po/common/nl.po
po/common/sr.po

Resolves some failing unit tests that were introduced by a PR.
**Related issues and discussion:** #2614

Change bad translations

---

lang/fr/texts/ingredients-issus-de-l-huile-de-palme.list.html

Signalé le  31 juillet 2013 par Agamitsudo sur le wiki (Le Bazar)

Correction faute

---

html/js/display-product.js

@raphael0202 would like to add user authentication for robotoff. To force browsers to send their session cookie to the robotoff subdomain, the `fetch` statement needs to be [modified](https://stackoverflow.com/a/38935838/11963).

Send credentials when talking to robotoff

---

taxonomies/additives.txt

"ecetsav" is E260
**Checklist:**

E650 had an ambiguous alias (ecetsav) in Hungarian

---

docker/docker-compose.yml

Probably a copy & paste error. My bad.

Use correct image from GitHub packages for the frontend

---

lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html

Fix space in front of url

---

lang/ca/texts/nutriscore-quick.html
lang/ku/texts/nutriscore.html
lang/pl/texts/nutriscore-quick.html
lang/sl/texts/nutriscore-quick.html

https fix for nutriscore

---

lang/el/texts/press-and-blogs.html

el-press from Wiki

---

cgi/product_multilingual.pl

Made energy-kJ and energy-kcal have only one unit, removed select

---

cgi/product_multilingual.pl

I made a mistake which broke the product edition javascript for non moderators.

fix broken javascript

---

lib/ProductOpener/Ingredients.pm
t/ingredients.t
t/ingredients_clean.t
t/ingredients_parsing.t
t/ingredients_tags.t

No functional changes, just adding to the regular expressions to improve the cutting of the ingredient list.

ingredient parsing: improve Finnish parsing

---

.github/workflows/containerimage.yml
docker/docker-compose.dev.yml
docker/docker-compose.yml

Copies the minified CSS/JS/SVG to the docker host, so that they'll be copied to the backend container image.
**Related issues and discussion:** Fixes #2661

Fix SVG icons for Docker

---

lib/ProductOpener/Food.pm

Made NOVA score 1 for waters

---

cgi/product_jqm_multilingual.pl

Add CORS headers to the write API

---

lib/ProductOpener/Display.pm

Don't categorize dietary supplements as 'Products'
**Related issues and discussion:** Fixes #15

Add 'DietarySupplement' microformat 

---

lib/ProductOpener/Display.pm
po/common/common.pot
po/openbeautyfacts/openbeautyfacts.pot

Add a promo for Open Beauty Facts

Add a promo for Open Beauty Facts

---

lib/ProductOpener/Producers.pm

- ignore empty header lines in excel files

Small fixes

---

crowdin.yml

reduce-pointless-work-for-pierre

reduce-pointless-work-for-pierre

---

po/common/common.pot

fix pot file

---

lang/en/texts/discover.html

Updates to discover
- adding links to new content pages
- updating figures

Updates to discover

---

lang/fr/texts/produits.html

fixes-to-product

---

crowdin.yml

Overwritting obsolete file with the right copy.

Overwritting obsolete file with the right copy.

---

taxonomies/additives.txt

Modified starch

---

taxonomies/ingredients.txt

ro translations.txt

---

po/common/common.pot

fix-pot-file as there was a syntax error preventing sync

fix-pot-file

---

html/data/data-fields.txt

data-fields.txt

---

taxonomies/categories.txt

- Add onions subcategories (yellow, white, red) : https://world.openfoodfacts.org/category/onions
- Add loukum category : https://world.openfoodfacts.org/category/fr:loukoums
- Add kiwi jam (https://world.openfoodfacts.org/category/fr:confitures-de-kiwis)

Add new categories

---

taxonomies/categories.txt

Update category taxonomy. See commits for full details.

Update category taxonomy

---

taxonomies/ingredients.txt

Hungarian translation of ingredients

---

lib/ProductOpener/Food.pm

solves bug #1737 and makes ios app work (hopefully)

make nova_group a int, and nova_groups a string, bug #1737

---

lib/ProductOpener/Display.pm

Made "Remember me" input checked by default.

---

scripts/gen_feeds_daily_off.sh
scripts/update_packager_codes.pl
scripts/update_packager_codes_fsa_ratings.pl

Filter out bad coordinates. It doesn't fix the input CSV files though.
de-bb-ec        invalid lat     Landwirt Detlef Henry Simon
de-bb-ec        invalid lng     Waldecker Straße  26
de-be-ec        invalid lat     natürlich essen Berlin-Brandenburg GmbH
de-be-ec        invalid lng     Bitterfelder Str. 19 c
de-bw-ec        invalid lat     Universitätsklinikum Freiburg Zentralküche
de-bw-ec        invalid lng     Hartmannstraße 1
de-by-ec        invalid lat     Stadt Ingolstadt. Amt für Sport und Freizeit
de-by-ec        invalid lng     Friedhofstraße 4 1/2
de-hb-ec        invalid lat     PTC Germany GmbH. Niederlassung Tuna
de-hb-ec        invalid lng     Am Lunedeich 40
de-he-ec        invalid lat     Mittagsmenü und Partyservice ""Söhre"
de-he-ec        invalid lng     Fahrenbach Str. …

filter out bad coordinates, #bug 2768

---

cgi/product_multilingual.pl
conf/nginx/sites-available/off

CORS issue + missing admin var.

fix issues with product edit script

---

cgi/search.pl
cpanfile
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po
po/common/fr.po

Added an option to create XLSX files to download search results. Hopefully that will cut a lot the number of people who tell us they can't load the CSV files or have broken accents. :)

Excel export format for search results, bug #2666

---

lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po
po/common/fr.po

display a warning for products in the en:alcoholic-beverages category, fixes bug #60

alcohol warning, fix #60

---

html/data/data-fields.txt

update field list

---

lib/ProductOpener/Display.pm

Update to HTTPS. HTTP returns a 503

Update to HTTPS. HTTP returns a 503

---

cgi/top_translators.pl

Only add rows to the `dataSource` if there were no errors parsing the CSV row.
**Related issues and discussion:** Fixes #2777

Don't add errored parsed results

---

html/js/display-product.js

See issue https://github.com/openfoodfacts/openfoodfacts-server/issues/2794

Send server_domain field when requesting questions from robotoff

---

lib/ProductOpener/DataQualityFood.pm

Added check for alcoholic beverages

---

html/files/app/ingredients-analysis.json

leaf icon for vegan

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Tags.pm

Would allow links like http://world.openfoodfacts.org/category/wikidata:en:Q7802 to display http://world.openfoodfacts.org/category/breads, based on the present linked data.
**Related issues and discussion:** Fixes #449

Wikidata link

---

po/common/sq.po

Removed incomplete translation that fails tests

fix: Translations needs to contain site_name tag

---

taxonomies/allergens.txt

Added dutch singular for all nut varieties.

nuts update

---

lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opf.pm
lib/ProductOpener/Config_opff.pm

also created analytics properties for OPF and OPFF

update analytics script to gtag.js, fixes #2671

---

lib/ProductOpener/Ingredients.pm
t/allergens.t

fix allergens parsing, bug #2598

---

conf/nginx/expires-no-json-xml.conf
conf/nginx/sites-available/off

disable serving a static /1.json, issue #2834

---

lib/ProductOpener/Products.pm

don't wait for robotoff if it is unresponsive

---

lib/ProductOpener/Ingredients.pm
t/allergens.t

fix allergen parsing bug #2719

---

lib/ProductOpener/Food.pm
lib/ProductOpener/ImportConvert.pm
lib/ProductOpener/Producers.pm
scripts/import_systemeu.pl
t/import.t
t/producers.t

Support parsing plain text nutrition facts with serving size. + test

fixes for systeme u import

---

docker/build_npm.bat
docker/build_npm.sh
docker/docker-compose.admin-uis.yml
docker/docker-compose.dev.yml
docker/docker-compose.yml
docker/frontend/Dockerfile

Updates docker dependencies to the most recent (LTS) versions.
The currently referenced tag of phpmemcachedadmin doesn't seem to exist any more.

deps(docker): Bump dependencies

---

lib/ProductOpener/Ingredients.pm
t/ingredients_clean.t

Fixes #2096, #2305 and a few others.

Fix too aggressive ingredients list cutting in Spanish, Polish and other languages

---

lib/ProductOpener/Products.pm

somehow there are some images that were assigned to nutrition_nl_be and compute_language() think they are related to the be language.

should fix nl_be buggy fields, #2489

---

lib/ProductOpener/Products.pm

fixing stupid mistake.
in the process of reprocessing the affected products (~5000)

fix compute_languages(), bug #2880

---

lib/ProductOpener/Import.pm
lib/ProductOpener/ImportConvert.pm
lib/ProductOpener/Ingredients.pm
t/ingredients_clean.t

Needed for some producers imports.

added split_generic_name_from_ingredients() function

---

taxonomies/labels.txt

Update yearly contests for 2019, 2020

Update yearly contests for 2019, 2020

---

lib/ProductOpener/Ingredients.pm

fix or operator

---

lib/ProductOpener/Ingredients.pm
t/ingredients_clean.t

This bug prevents products with ingredients in Russian to be saved.

fix regular expression and add tests, bug #2895

---

cgi/export_products.pl
cgi/product_multilingual.pl
lib/ProductOpener/Import.pm

See bug #2904 for the description
+ bug  #2086 for the protection of imported fields.

Producers - Import fields only once, protect imported fields

---

taxonomies/ingredients.txt

Unilever ingredients

---

taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

built the taxonomy with @aleene's changes

built ingredients taxonomy, added rutabaga

---

cgi/product_image_upload.pl
lib/ProductOpener/Images.pm

This needs a specially compiled ImageMagick, see also bug #1793
Should solve #1663 and add support for HEIC #2851

HEIC / HEIX images support + fix colorspace issue

---

scripts/scanbot.pl

add scans by country + top 95 percent #2918, fixes #2397

---

lib/ProductOpener/Display.pm

should solve bugs on the android app

disable nested ingredients in queries with multiple products, bug #2883

---

cgi/product_image_crop.pl

Added access control allow origin in product image crop

---

cgi/product_image_move.pl
cgi/product_image_upload.pl
cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
lib/ProductOpener/Import.pm
lib/ProductOpener/Products.pm
scripts/import_fleurymichon.pl
scripts/import_sodebo.pl
scripts/import_systemeu.pl
scripts/upload_photos.pl

change default country to country of subdomain instead of geoip

---

html/files/tagline-off.json

order-tagline-off-android

---

cgi/product_image_upload.pl
lib/ProductOpener/Images.pm

create tmp directory if it does not exist

---

cgi/product_jqm_multilingual.pl
lib/ProductOpener/DataQualityFood.pm
lib/ProductOpener/Display.pm
lib/ProductOpener/Products.pm
scripts/update_all_products.pl

Important fix. See bug #2945 for details.

Important fix - avoid too small salt values, bug #2945

---

cgi/export_products.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Ingredients.pm
lib/ProductOpener/Users.pm
scss/_off.scss
t/ingredients_clean.t

Producers - small fix for ingredients, admin mode to see all products +

---

html/files/tagline-off.json

All EU languages

---

html/files/app/tagline/tagline-off-ios.json

all-EU-languages

---

lib/ProductOpener/DataQualityFood.pm
lib/ProductOpener/Display.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Ingredients.pm
lib/ProductOpener/Nutriscore.pm
po/common/common.pot
po/common/en.po
scripts/update_all_products.pl
t/ingredients.t
t/ingredients_percent.t
t/nutriscore.t

replace old nutriscore algorithm by new algorithm, bug #2957

---

lib/ProductOpener/Display.pm

fix issue with graphs reported by @aleene

fix graphs

---

po/common/common.pot
po/common/en.po

better wording for combined nutriscore warning

---

lib/ProductOpener/Display.pm
scss/_off.scss

**Description:** Use the same color for all ingredients analysis by using a single set of CSS classes for it.
**Related issues and discussion:** Fixes #2929

Use same color for ingredients analysis

---

cpanfile
docker/build_npm.bat
docker/build_npm.sh
docker/docker-compose.admin-uis.yml
docker/docker-compose.dev.yml
docker/docker-compose.geolite2.yml
docker/docker-compose.yml
docker/frontend/Dockerfile
gulpfile.js
package-lock.json
package.json

Updates cpan, npm, and docker dependencies to the most recent versions.

Bump dependencies

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Ingredients.pm
po/common/common.pot
po/common/en.po
t/ingredients.t
t/ingredients_percent.t

Issue 2980/ingredients analysis

---

html/files/app/tagline/tagline-off-ios.json

massify-ios-tagline

---

html/files/tagline-off.json

massify-tagline

---

cgi/product_image_upload.pl

new pull request as the previous one shows lots of changes https://github.com/openfoodfacts/openfoodfacts-server/pull/2976

Issue 2975/select newly uploaded images

---

lib/ProductOpener/Display.pm

I made a silly mistake earlier.

fix double display of nested ingredients, bug #2980

---

lib/ProductOpener/Products.pm
po/common/nl_NL.po
scripts/update_all_products.pl

fix old product without created_t, bug #185

---

lib/ProductOpener/Ingredients.pm
t/ingredients_analysis.t

labels overrides for ingredients analysis, bug #3015

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Export.pm
lib/ProductOpener/Food.pm
lib/ProductOpener/Import.pm
lib/ProductOpener/ImportConvert.pm
lib/ProductOpener/Producers.pm
scripts/convert_nestle_nutrition_data.pl
t/food.t
t/import.t

In particular fixes an issue with import of nutrition data for prepared product.

Small changes for Nestlé import

---

taxonomies/ingredients.txt

Spanish ingredients

---

taxonomies/labels.txt

adding wheat free

---

taxonomies/categories.txt

CIQUAL addition test

---

lang/zh/texts/index.html.old

commit old Chinese index

---

cgi/product_image_crop.pl
cgi/product_image_upload.pl
cgi/product_multilingual.pl
gulpfile.js
lib/ProductOpener/Export.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Import.pm
package.json
scripts/import_fleurymichon.pl
scripts/import_systemeu.pl
scripts/update_all_products.pl

See bug #3031 and discussion in #ingredients and #productopener for details.

updated cropper to make it easier to use, bug #3031

---

package-lock.json

Updated deps to fix vulnerabilities

---

cgi/test_ingredients_analysis.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Ingredients.pm
t/ingredients_nesting.t
t/ingredients_parsing.t

- support for 'ingredient (46%) (A, B, C)'
- better handling of ingredients with more than 1 label, processing, percent etc.
- and a new web interface to test ingredient analysis: https://fr.openfoodfacts.dev/cgi/test_ingredients_analysis.pl

Ingredients analysis improvements + test web interface

---

html/js/product-multilingual.js

I had forgotten to commit html/js/product-multilingual.js :(

updated cropper, bug #3031 - added missing product-multilingual.js changes

---

docker/dev-environment-quick-start-guide.md

Added the link for localhost when the docker container runs on another port
**Related issues and discussion:** #3014

Add localhost link in Changing Ports

---

lib/ProductOpener/Ingredients.pm

small fixes for uninitialized values

fix warnings

---

lib/ProductOpener/Products.pm

there was a broken product without a lc field that could not be updated, this fixes it.

fix warning

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

fix for French mono - et diglycérides d'acides gras

---

.stylelintrc
.stylelintrc.json
package-lock.json
package.json

Also renamed .stylelintrc -> .stylelintrc.json for editor syntax.
Fixes [this issue](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1584440388074000?thread_ts=1584440384.073900&cid=C02LDQDDD) (on Slack).

Added css stylelint config

---

lib/ProductOpener/Text.pm
t/text.t

Fixes #3039 
New test cases added.

[WIP] Added: new tests for Text.pm

---

html/js/product-multilingual.js
po/common/common.pot
po/common/en.po

Prevents unwanted zooms triggered by either the trackpad scroll or the mouse wheel. cc @bredowmax

add checkbox to enable zoom on wheel, bug #3031

---

cgi/product_multilingual.pl
html/js/product-multilingual.js
po/common/common.pot
po/common/en.po

see bug #3062 and please test on .dev

move data and selected photos to another language, bug #3062

---

lib/ProductOpener/Text.pm

Signed-off-by: Areesha Tariq <areeshatariq02@gmail.com>
Documentation of the ProductOpener::Text.pm module in perlpod format.
**Related issues and discussion:** 
fixes #3045 
#2203

Document the ProductOpener::Text.pm module

---

taxonomies/categories.txt

Added seasonality info for France

Seasons of fruits

---

html/js/product-multilingual.js

Signed-off-by: Areesha Tariq <areeshatariq02@gmail.com>
Fixes Unexpected use of undefined
**Related issues and discussion:** fixes #3088

Fix lint warning

---

taxonomies/ingredients.txt

laos added

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t
t/ingredients_tags.t

turn "A & B" to "A and B", bug #3100

handle & in ingredients lists, bug #3100

---

taxonomies/labels.txt

Some translations

---

lib/ProductOpener/Tags.pm

it should help running the taxonomy building in github

fix warnings bug #3126, comment out STDERR logs bug #3125

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

due to a bug, it's currently the number one unknown ingredient in German.

fix bug for German  Mono - und Diglyceride

---

taxonomies/labels.txt

Geo-labels

---

lang/en/texts/contribute.html
lang/en/texts/help-complete-products.html

Please help approve this review.

help to xyz -> help xyz

---

cgi/product_multilingual.pl
cgi/user.pl
lib/ProductOpener/Users.pm

fixes #2673
the following works after this PR on sending 
1 `Username or email : abc@xyz.com `
goes to autofill on `cgi/user.pl` as 
<pre>
Name : abc
e-mail address : abc@xyz
User name(non-accented letters, digits and/or dashes) : abc
</pre>
2 `Username or email : abc `
goes to autofill on `cgi/user.pl` as 
<pre>
Name : abc
e-mail address : 
User name(non-accented letters, digits and/or dashes) : abc
</pre>
3 if the password field is set then that gets auto-filled too.
@stephanegigandet Please review
Thanks

Added: Create account button

---

lib/ProductOpener/Images.pm

Signed-off-by: Areesha Tariq <areeshatariq02@gmail.com>
Added language code for the ingredient image that is being displayed.
**Related issues and discussion:** 
fixes #3105

Give a hint of the language of the image to users

---

t/ingredients_processing.t
taxonomies/ingredients_processing.txt

de:gezuckert and other

---

taxonomies/categories.txt

Test for IGP integration

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

small fix for "Ingrédient(s) issu(e)(s)"

---

taxonomies/labels.txt

Adding EU Organic codes outside EU.
It will enable to add more organic labels, and will enable a coarse sense of origin.

Adding bio codes outside EU

---

po/tags/en.po
po/tags/fr.po
po/tags/tags.pot

fix issue with data quality links, bug #3194

---

cgi/product_multilingual.pl
lib/ProductOpener/Display.pm

ids are good:
* ease debugging (allows to compare HTML page and perl code)
* ease Product Opener Front end development (styling, front features...)
* ease third party software (user scripts...)

Add ids to ease front dev

---

taxonomies/ingredients.txt

Update ingredient taxonomy.
Add 'sel gris marin' and 'sel gris de Guérande' ingredient.

Add 'sel gris' ingredient

---

taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

Continuing on @raphael0202 's work.

more salts

---

taxonomies/categories.txt

Suppressed "Fruit jams", "Vegetable jams"
Created "Moussaka", "Carrot cakes", "Brookies"

Jams and other changes

---

lib/ProductOpener/Export.pm
scripts/export_csv_file.pl

need for experiments for Léa Nature

small improvements for exports

---

lib/ProductOpener/Food.pm

Update Food.pm (Handling added sugars)

---

taxonomies/categories.txt

CIQUAL PR clone from Eric

---

lib/ProductOpener/Producers.pm

fix typo in error message

---

lib/ProductOpener/Producers.pm
t/producers.t

recognize ug in units

---

html/js/product-multilingual.js
po/common/common.pot
po/common/en.po

currently live on .dev if you want to test

add checkbox to load low res images, bug #3232

---

lib/ProductOpener/Config_off.pm
po/common/common.pot

Adding a brand owner field for the US import

Adding a brand owner field for the US import

---

scripts/export_database.pl

convert scientific notation to decimal 

---

cgi/product_image_upload.pl
lib/ProductOpener/Images.pm

A lot of app developers have issues to upload images to OFF, this is to return more information to debug it.

add a debug field in error response for images uploads from apps

---

lib/ProductOpener/Display.pm

Add HTML id to user id

---

lib/ProductOpener/Products.pm

handle both kinds of apostrophe characters for index and search, 

---

lib/ProductOpener/Display.pm

Replace count_documents by estimated_document_count for https://world.openfoodfacts.org/

Use estimated_document_count for world root URL

---

taxonomies/ingredients_processing.txt

Small additions, dutch and synonyms

Small additions

---

scripts/update_all_products.pl

repairs Spanish products that had their ingredients lists thrown away by bug #3081

Spanish ingredientes - put back ingredients that were cut too much, fixes #3081

---

po/common/common.pot

small fix for brand owner add

---

cgi/import_file_select_format.pl
lib/ProductOpener/Export.pm
lib/ProductOpener/Import.pm
lib/ProductOpener/Producers.pm
po/common/common.pot
po/common/en.po

support for external source specific fields + fixes

---

lib/ProductOpener/Display.pm

add $fields_ref for HTML pages results
Issue #1560

Limit fields returned by MongoDB

---

lib/ProductOpener/Display.pm

will fix the miniature issue #3280

add lc to fields requested, fixes #3280

---

scripts/refresh_products_tags.js

it will make the /teams page available if not logged

added teams_tags

---

cgi/export_products.pl
lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po

Small fixes for US + way to export only products matching a given query

Producers - add query filters for exports, fix manufacturer

---

lib/ProductOpener/Ingredients.pm

https://static.openfoodfacts.org/images/products/351/269/000/4987/ingredients_fr.10.full.jpg
```
farine de _BLE_, eau, huiles et graisses végétales (palme, colza), sucre, sel, jus de citron concentré, levure désactivée, conservateur : sorbate de potassium. Produit
``` 
to 
```
farine de _BLE_, eau, huiles et graisses végétales (palme, colza), sucre, sel, jus de citron concentré, levure désactivée, conservateur : sorbate de potassium. 
```

improve cutting

---

scripts/update_all_products.pl

needed to remove a bunch of wrongly detected labels in the US import

feature to remove a label

---

cgi/product_image_upload.pl
html/js/product-multilingual.js

do not overwrite selected images when uploading images from the web

---

lib/ProductOpener/Display.pm

all thumbnails are currently broken on the producers platform..

add owner field for mongo queries, needed for producers platform

---

taxonomies/ingredients.txt

Add new ingredients:
- blood orange
- sauce blanche
- flax floor
- blue poppy seed

Add new ingredients

---

lib/ProductOpener/Display.pm

I'm hoping this will solve a lot of the downtimes that are reported in the #infrastructure channel.
Details in #3318

fix export limit, solve performance issue, bug #3318

---

lib/ProductOpener/Display.pm

may fix #3124 , also remove not useful log that can be printed 10000 times for a single page

disable or remove some logs that fill test results and debug logs

---

html/robots.txt

Amazonbot is making tons of queries (to train Alexa)

add MegaIndex & Amazonbot

---

t/ingredients_processing.t
taxonomies/ingredients_processing.txt

Salted synonyms and translations

Salted synonyms and translations

---

crowdin.yml

make the "Help complete products" page translatable

make the "Help complete products" page translatable

---

cgi/export_products.pl
lib/ProductOpener/ImportConvert.pm
t/ingredients_clean.t

- performance fix to make query use right index
- HTML entities decoding for imports

Producers - performance fix + HTML entities

---

cgi/remove_products.pl

use owners_tags index

---

lib/ProductOpener/Food.pm
t/food.t

Normalize Finnish packager codes and test it.

Normalize Finnish packager codes

---

lib/ProductOpener/Food.pm
lib/ProductOpener/Tags.pm
po/common/common.pot
po/common/en.po
po/tags/en.po
po/tags/tags.pot
scripts/update_all_products.pl

Details in bug #3353 
Being tested on dev server: 
https://fr.openfoodfacts.dev/etat/categories-completees/ciqual-food-names

New ciqual_food_name facet

---

t/tags.t
taxonomies/categories.result.txt
taxonomies/categories.txt

Association CIQUAL AGB (starting from line 997)

---

taxonomies/categories.txt

CIQUAL ericwang2

---

scripts/equadis-import/README.md
scripts/equadis-import/dereference.sh
scripts/equadis-import/equadis-data/README.md
scripts/equadis-import/equadis-xml2csv.js
scripts/equadis-import/equadis2off.sh

Preliminary version of an import script for Equadis data.
Tested on Unilever data for French products.

Import equadis

---

taxonomies/categories.result.txt

With the latest changes from @moon-rabbitOFF

build categories taxonomy

---

lib/ProductOpener/Tags.pm
scripts/update_all_products.pl

Also add a way to remove bogus _debug_tags that have been added to products.

Issue 3380/restore deleted values

---

taxonomies/ingredients_processing.txt

candied, deodorized

---

README.md

small README fixes

---

taxonomies/categories.txt

Updated the categories.txt file with the proper WikiData codes.
**Related issues and discussion:** Fixes #3399

Fix Broth and Radish WikiData

---

taxonomies/categories.txt
taxonomies/ingredients.txt
taxonomies/minerals.txt
taxonomies/nucleotides.txt
taxonomies/nutriments.txt

Fix malformed wiki-links

---

t/ingredients_nesting.t
taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

Added a few common ingredients.

more ES and IT entries

---

cgi/import_photos_upload.pl

solves very slow adding of thousands of images in the producers platform

remove some calls to equalizer reflow, fixes bug #3410

---

taxonomies/categories.txt

category fusion

---

taxonomies/ingredients.txt

There were some regressions (probably due to a merge, I'm not sure how it happened), I'm putting back fixes that were deleted by error.

put back wikidata fixes

---

taxonomies/categories.txt

Changes to fresh vegetables, ignames, chocolates

Fresh vegetables

---

lib/ProductOpener/Ingredients.pm
t/ingredients.t
taxonomies/ingredients.txt

Bug #3432 
Expand the abbreviated words so they don't match country codes.

ingredients-analysis: expand abbreviated fi stopwords

---

cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
scripts/build_tags_taxonomy.pl
scripts/update_all_products.pl

This should solve the issue of the docker environment not computing the Nutri-Score.

use $options{product_type} instead of "food" in $server_domain

---

lang/en/texts/ingredients-analysis.html

ingredients-analysis

---

docker/backend-dev/conf/Config.pm

Needed in particular to get the Nutri-Score computed.

update docker Config.pm file to make it same than production

---

lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po

Make the details available to all (including not logged in users) + add a call for help when there are unknown ingredients.
Screenshot in #3451

Display ingredients analysis call for help, bug #3451

---

lib/ProductOpener/Display.pm
po/common/common.pot
po/common/en.po

Added wiki link + ids for HTML code

Ingredients analysis details

---

lang/en/texts/data.html

add Laravel and NodeJS + alphabetical order. Also, we need to make sure production copies don't have the word experimental API anymore

add Laravel and NodeJS + alphabetical order

---

html/data/data-fields.txt

fix-data-fields

---

t/ingredients_processing.t
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

- made different entries for pepper and bell pepper (and removed bell pepper as a synonym of pepper)
- removed a few entries for grilled bell peppers, pepper powder, smoked pepper etc. --> those should now be taken care of by the ingredients_processing taxonomy
- added a few entries in Spanish and other languages in the ingredients_processing taxonomy

differentiate pepper and bell pepper

---

taxonomies/ingredients.txt

Suero láctico de Oveja

---

taxonomies/ingredients_processing.txt

Add a new process: pressed

---

lib/ProductOpener/ImportConvert.pm
lib/ProductOpener/Producers.pm
po/common/common.pot
po/common/en.po
po/common/fr.po
t/import.t

this will solve the issue of the organic label ("bio") being recognized in a product name that has "sans antibiotique"

Producers - support for comma separated CSV + fix match of labels in product names

---

lib/ProductOpener/Import.pm
lib/ProductOpener/Producers.pm

small changes for iglo import in Germany

support empty lines + values without units

---

taxonomies/labels.txt

Adding Haute Valeur Environnementale to labels

Adding Haute Valeur Environnementale to labels

---

lib/ProductOpener/Config_opff.pm

Use dynamically produced manifest for Open Pet Food Facts

Use dynamically produced manifest for Open Pet Food Facts

---

taxonomies/additives_classes.txt

Correction mix up in translations

---

html/files/tagline-off.json

Update the taglines since the petition is over

Update the taglines

---

html/data/data-fields.txt

propose clarification for Energy

propose clarification for Energy

---

taxonomies/labels.txt

Added organic label Nature et Progrès

Added Nature et Progres (without logo)

---

taxonomies/categories.txt

Small changes related to https://fr.openfoodfacts.org/ciqual-food-name/unknown/categorie/boissons/categories

Unknown CIQUAL codes in taxonomie Boissons

---

taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/labels.txt

Spanish translation of the ingredients taxonomy (2)

---

taxonomies/ingredients.txt

Update ingredients.txt with additional Spanish translations

---

t/ingredients_processing.t
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Adding spanish test and process

Tests for spanish ingredient processing taxonomy

---

lang/en/texts/better-food-choices-for-a-better-health-lets-mobilize.html

make the page edge to edge

---

lib/ProductOpener/Display.pm
po/common/fr.po

display NOVA groups histogram for /nova-groups, fix #3540

---

lib/ProductOpener/Tags.pm
scripts/refresh_taxonomies.js
taxonomies/ingredients_processing.txt

Get output (errors) from the taxonomy build in the travis test logs

---

.github/FUNDING.yml

Try setting up GitHub sponsors

Try setting up GitHub sponsors

---

taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/labels.txt

Spanish translations and additions

---

lang/en/texts/who-we-are.html

This page needs extra refactoring

fix contributor link in the Who We Are page

---

cgi/export_products.pl
cgi/import_file_process.pl
lib/ProductOpener/Images.pm
lib/ProductOpener/Import.pm
po/common/common.pot
po/common/en.po
scripts/import_fleurymichon.pl
scripts/import_systemeu.pl
scripts/obsolete/upload_photos.pl
scripts/obsolete/upload_photos_2018_liege.pl

support for apps data and photos upload through the producers platform

---

cgi/product_multilingual.pl

I forgot to commit this change.

new argument for process_image_upload()

---

lang/en/texts/advanced-user-guide.html

Fix for the advanced user guide

fix-to-the-guide

---

lang/en/texts/index-pro.html
lib/ProductOpener/Display.pm
po/common/common.pot

Add an initial producer funnel:
1. Add a footer link
2. Add a little CTA to send an email in the producer homepage

Add an initial producer funnel

---

html/data/data-fields.txt

Reverts openfoodfacts/openfoodfacts-server#3525

Revert "propose clarification for Energy"

---

cgi/product_image_upload.pl
lib/ProductOpener/Images.pm

I forgot to commit this script when I changed the args of the image upload function.

fix new argument

---

taxonomies/ingredients.txt

Some more Danish improvements.

Danish ingredients improvements, part II

---

taxonomies/additives.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/minerals.txt
taxonomies/vitamins.txt

Spanish translations for taxonomies

---

cgi/search.pl
lib/ProductOpener/Tags.pm

add editors etc. to tags_fields, fixes #3579

---

cgi/product_multilingual.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Food.pm
scripts/update_all_products.pl

This will change values of the energy-kcal, energy-kcal_100g and energy-kcal_serving fields so that they are in kcal instead of kJ (currently all energy fields are converted to kJ).
Please see #3561 for details.
The update_all_products.pl needs to be run to update the fields for all products in the database.

use kcal instead of kj for the energy-kcal field

---

lang/en/texts/nutriscore.html

remove the EU petition as it is now over

remove the EU petition as it is now over

---

lang/en/texts/faq.html

changes to the FAQ to redirect more producers towards us

changes to the FAQ to redirect more producers towards us

---

lang/en/texts/help-us-fill-up-on-fiber.html

New mission to help fill the fiber value

New mission to help fill the fiber value

---

taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Spanish unknowns

---

lib/ProductOpener/Ingredients.pm
taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

See #3568
Not very pretty fix for Spanish, but it works.

add sal tree oil in taxonomy + special handling for Spanish, fixes #3568

---

po/common/en.po

correct missing strings since we do not export from pot to po

correct missing strings since we do not export from pot to po

---

lib/ProductOpener/Ingredients.pm
t/additives_tags.t
t/ingredients_parsing.t

better parsing of INS additives, fixes #3618

---

lib/ProductOpener/Store.pm
t/store.t

fixes #3615, thanks @Ban3 for the suggestion of Unicode::Normalize

normalize strings to Unicode form NFC, fixes #3615

---

cgi/import_photos_upload.pl
cgi/product_multilingual.pl
gulpfile.js

used by image upload form in producers platform

copy all js, including minified script

---

lib/ProductOpener/Display.pm
templates/nutrition_facts_table.tt.html

Changes:
- added a ?debug_template=nutrition_facts_table parameter so that we can easily see the data structure passed to the template
- simplified the data structure passed to the template
- separated nutrition and ecological impact in 2 different tables

Simplify data structure and template for nutrition facts table, add debug mode

---

lib/ProductOpener/Display.pm
templates/nutrition_facts_table.tt.html

Remove comments from nutrition table template

---

t/ingredients_nesting.t
taxonomies/additives.txt
taxonomies/additives_classes.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/labels.txt
taxonomies/minerals.txt
taxonomies/vitamins.txt

First batch of unknown ingredients from the dk, fi, is, no and sv domains.
I'll add the Perl parts (abbreviations, traces, processing...) in a later pull request.

Nordic unknown ingredients

---

cgi/search.pl
lib/ProductOpener/Display.pm

- Search criteria now includes number of additives, ingredients (including known and unknown)
- Made list of criteria alphabetical
- Added select2 to easily find fields
Fixes #3630, #3604

improve search form: new fields, abc order, select2

---

taxonomies/ingredients.txt

added Harina de trigo enriquecida s/ley 25630

added Harina de trigo enriquecida s/ley 25630

---

taxonomies/categories.txt

https://docs.google.com/spreadsheets/d/0B2Z-7cB-sMWOY0hybHNoY1pqaXoyMi1nblI1V1g0aTlvVXFF
Work in Progress (as of May 18th)

Extra lines from TODO Association CIQUAL/AGB

---

t/ingredients.t
taxonomies/ingredients.result.txt
taxonomies/ingredients.txt

more French synonyms for sal tree oil

Added "sal tree oil" to ingredients taxo, rebuilt taxonomies

---

taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Spanish and Catalan (and some others) additions

Spanish,Catalan and other language updates to ingredients

---

taxonomies/additives.txt
taxonomies/ingredients.txt

Language updates and additions

Spanish,Catalan and other updates

---

cgi/search.pl

Now works: https://world.openfoodfacts.org/cgi/search.pl?search_terms=897580000168&search_simple=1&action=process

search 12 digit barcode

---

lang/opff/en/texts/index.html

OPFF index to avoid OFF index

---

crowdin.yml
lang/opf/en/texts/index.html

OPF index to avoid OFF index

---

lib/ProductOpener/Display.pm

I forgot one file in this PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/3672

Missing file for producer platform self-registration of pro accounts

---

taxonomies/additives.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Spanish, catalan and more

---

po/common/common.pot

Please mind the GetText syntax: Double quotes to start and end a line, \ to escape double quotes and nothing else

Please mind the GetText syntax

---

lib/ProductOpener/Display.pm

fix energy-kcal in graphs, bug #3688

---

lang/opf/en/texts/index.html

Fix Pet Food vs Product typo in Open Products Facts

fix opf homepage typo

---

taxonomies.obf/brands.txt

Brands taxonomy for OBF

---

taxonomies/additives.txt
taxonomies/additives_classes.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/vitamins.txt

Spanish Catalan and more taxonomy

---

lib/ProductOpener/Config_off.pm

unaccent Catalan, fixes #3615

---

taxonomies/additives.txt
taxonomies/ingredients.txt

Spanish, Catalan taxonomy updates

---

taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Updates plus a first pass at a cleanup

Spanish and Catalan plus cleanup of ingredients

---

taxonomies.obf/brands.txt

Fix a compilation error in the brands taxonomy for Open Beauty Facts

Fix a compilation error in the brands taxonomy for Open Beauty Facts

---

README.md

@stephanegigandet @hangy It's a draft to get developers more engaged with the repository, and give them a better sense of what the priorities are. 
For now the priorities are blank, so this PR is still a draft.

Improve the README to create more engagement with the server

---

taxonomies/categories.txt

Add category: Maïs frais
Add category: Raisins frais
Add category: Courges fraîches
Add en translation: Black radishes
Add category: Radis noirs frais
Add alternate name: Radis roses
Add category: Radis roses frais
Add wikidata and ciqual for: Radis rouges

My label taxonomies

---

taxonomies/additives.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

Spanish and Catalan plus tidy up of ingredients

---

templates/nutrition_facts_table.tt.html

Nutrition table for categories - small fix for #3742

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

fixes #3635 and fixes #3744
added more text and refactored a bit the code + added some code documentation

better and slightly cleaner additives parsing, fix #3635 #3744

---

taxonomies/additives.txt
taxonomies/ingredients.txt

Spanish and catalan Taxonomy updates

---

.github/workflows/stale.yml

Stale PR checker

---

cgi/search.pl
lib/ProductOpener/Products.pm
scripts/update_all_products.pl

This is a new search order key, for the Personal Search project.
Please see #3702 for details.

add search_key, bug #3702

---

taxonomies/additives.txt
taxonomies/additives_classes.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt
taxonomies/vitamins.txt

Spanish and Catalan taxonomy

---

lib/ProductOpener/Display.pm

add support to order search results by popularity_key

sort search result by popularity_key

---

taxonomies/categories.txt

Per: https://twitter.com/EUAgri/status/1278293861274734592

add new PGI

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

fix regexp for Portuguese addtives parsing bug #3771

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

Better inclusion of stopwords in enumeration of allergens.
Fixes #3770

Better allergens regexp

---

lib/ProductOpener/Images.pm

fixes #3788
This should prevent duplicate images in the future, and it will also speed up product re-imports.

prevent duplicate product images, fixes #3788

---

html/files/app/tagline/tagline-off-ios.json

Remove the petition from the iPhone tagline

Remove the petition from the iPhone tagline

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Images.pm
lib/ProductOpener/Import.pm
lib/ProductOpener/ImportConvert.pm
lib/ProductOpener/Products.pm
scripts/equadis-import/README.md
scripts/equadis-import/dereference.sh
scripts/equadis-import/equadis-xml2csv.js
scripts/equadis-import/equadis2off.sh
scripts/equadis-import/run_equadis_import.sh
scripts/update_all_products.pl

For the Unilever import and others.

Automate Equadis import, support for importing to OBF

---

html/images/svg/crowdsourcing-obf-round-smartphones.svg

Crowdsourcing icon for Open Beauty Facts

Adding an OBF version of the Crowdsourcing illustration

---

cgi/product_jqm_multilingual.pl
cgi/product_multilingual.pl
cgi/search.pl
lib/ProductOpener/Display.pm
lib/ProductOpener/Products.pm
po/common/common.pot
po/common/en.po

This is to prevent entry of barcodes with less than 8 or more than 24 digits.

prevent short barcodes, bug #3793

---

lib/ProductOpener/Ingredients.pm
t/ingredients_percent.t

Fixes somes issues reported by @AcuarioCat and @teolemon 
fixes #3762

improve parsing for min. 5%, fixes #3762

---

lib/ProductOpener/Products.pm

I made a mistake and put obsolete products first instead of last. :-|

fix sort key

---

html/js/product-multilingual.js

Fixes the ESLint warning "Unexpected use of undefined"

fix: eslint warning

---

taxonomies/categories.txt

Added category under Sweet corn : Maïs doux frais

ADD: Maïs doux frais

---

taxonomies/categories.txt

ADD Polémos frais (Fresh grapefruit)

---

taxonomies/categories.txt

- No additions, besides a few synonyms, just running the translations through spell checker.
- Additionally fix undefined parents reported by the build process

Finnish category spelling corrections

---

lang/en/texts/contribute.html
lang/obf/en/texts/contribute.html
lang/obf/en/texts/discover.html

Discover page fixes for Open Beauty Facts

(Discover/contribute) page fixes for Open (Food/Beauty) Facts

---

taxonomies/labels.txt

Added origins constraints to the Labels taxonomy for a future way to auto-add values based on other values

Added origins constraints to the Labels taxonomy

---

taxonomies/brands.txt

Start adding properties to brands for a future constraints system

Start adding properties to brands

---

taxonomies/categories.txt

Start for WHO categories
I have used this to start: https://docs.google.com/spreadsheets/d/1KCTh5DzeoOOntFOVYC5_GqrkCXFARw-Qz475OxV14eg/edit#gid=458604824

Start for WHO categories

---

taxonomies/labels.txt

Preliminary attempt to categorize labels into clusters so that we can display them into wide categories in the website and the app.

Preliminary attempt to categorize labels into clusters

---

lib/ProductOpener/Import.pm
po/common/en.po
scripts/equadis-import/equadis2off.sh
scripts/import_csv_file.pl

Many small changes to deal with multiple organizations from one data provider.

changes for Equadis import, bug #3772

---

scripts/run_ocr.py

Add a new Python script to regenerate corrupted or missing OCR JSON.
This script has already run successfully in production.
Solve issue #3779.

Add script to generate missing OCR JSON (#3779)

---

taxonomies/materials.txt

Added Italian translations for materials taxonomies.

Italian translations for materials taxonomies

---

lib/ProductOpener/Display.pm
templates/search_and_display_products.tt.html

Index page where the products are displayed is templatized using Template::Toolkit

Search and display products templatization 

---

taxonomies/stores.txt

Added country property to stores. Note that more countries need to be added for Carrefour and other multi-country store, but the property does not bear any consequences yet

Add countries to the Store taxonomy

---

.github/workflows/codeql-analysis.yml

Hello! I'm on the GitHub team behind code scanning. We love that you're using the feature! We recently did some work to optimize how often the feature runs to save some compute, and this PR reflects that. I've filtered the Actions runs to only pushes on your default branch, and PRs to your default branch. Let me know if you have any questions here!
**Checklist:**

Optimize CodeQL Action

---

cgi/export_products.pl
cgi/minion_job_status.pl
lib/ProductOpener/Producers.pm
scripts/export_and_import_to_public_database.pl
scripts/gen_feeds_daily_off.sh

+ a bit more documentation for the code

Changes to run Equadis import automatically

---

lib/ProductOpener/Display.pm
templates/display_new.tt.html

Areesha display new

---

lib/ProductOpener/Food.pm
scripts/add_agribalyse_food_codes_to_taxonomy.pl
scripts/agribalyse_food_codes.csv
scripts/update_all_products.pl
taxonomies/categories.result.txt
taxonomies/categories.txt

add new agribalyse_food_code property

---

docker/backend-dev/conf/Config.pm
lib/ProductOpener/Config_obf.pm
lib/ProductOpener/Config_off.pm
lib/ProductOpener/Config_opf.pm
lib/ProductOpener/Config_opff.pm

Add missing $producers_email configuration settings

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

not pretty but I don't have a better solution right now

special case for 'fer élémentaire', fixes #3837

---

lib/ProductOpener/Display.pm
templates/search_and_display_products.tt.html

Issue 3885/search links

---

lib/ProductOpener/Ingredients.pm
taxonomies/additives_classes.txt
taxonomies/categories.txt
taxonomies/ingredients.txt
taxonomies/labels.txt

More ingredients stuff found in Belgium.

More ingredient stuff

---

taxonomies/nutriments.txt

Added `unsaturated fat`, which I encountered on a product.

Added Unsaturated fat

---

scripts/packager-codes/fr-packagers-refresh.pl

Change CSV separator to `;` and fix a broken row automatically
**Related issues and discussion:** #3912

Fix FR separator

---

taxonomies/materials.txt
taxonomies/packagings.txt

Fixes for the packaging & materials taxos (should compile)

Fixes for the packaging & materials taxos (should compile)

---

taxonomies/materials.txt

Fix for the materials taxonomy

Fix for the materials taxonomy

---

lib/ProductOpener/Ingredients.pm
taxonomies/additives.txt
taxonomies/categories.txt
taxonomies/labels.txt

Checking on unknown ingredients in Belgium

Belgian ingredients adaptations

---

taxonomies/categories.txt

Fixes for the WHO id
https://docs.google.com/spreadsheets/d/1KCTh5DzeoOOntFOVYC5_GqrkCXFARw-Qz475OxV14eg/edit#gid=1082192589

Fixes for the WHO id

---

lib/ProductOpener/Display.pm
templates/ingredients_analysis.tt.html

HTML Templatization of Ingredients Analysis using Template::Toolkit

Ingredients Analysis Templatization

---

lib/ProductOpener/Display.pm
templates/ingredients_analysis_details.tt.html

HTML Templatization of Details of Ingredients Analysis using Template::Toolkit

Ingredient Analysis Details Templatization

---

lib/ProductOpener/Display.pm

**Related issues and discussion:** https://github.com/openfoodfacts/openfoodfacts-server/pull/3317#issuecomment-664549326

Add a CSS class for weblinks

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t

fix (e160a(ii)) parsing, fixes #3883

---

lib/ProductOpener/Ingredients.pm
taxonomies/categories.txt
taxonomies/ingredients.txt

Dutch entries from the unknown dutch ingredients.

Some dutch entries

---

templates/search_and_display_products.tt.html

Fixed broken link of 'Explore by' button. 
**Related issues and discussion:** fixes #3919

Fix for broken blue "Explore by" button link

---

cgi/search.pl
templates/search_form.tt.html

HTML Templatization of cgi/search.pl (Search form) using Template::Toolkit

Search Form Templatization

---

.github/workflows/pull_request.yml
lib/ProductOpener/Display.pm
templates/display_product.tt.html

Small fixes for @areeshatariq 's product page templatization.

Areesha product page

---

taxonomies/categories.txt

Updates for Spain

---

lib/ProductOpener/Display.pm

https://fr.openfoodfacts.dev/label/bio?fields=product_name_fr,categories_tags,categories_tags_fr,categories_tags_de&json=1
https://fr.openfoodfacts.dev/api/v0/produit/3760049798029/tartines-quinoa-et-graine-la-boulangere-bio?fields=product_name_fr,categories_tags,categories_tags_fr,categories_tags_de

return translated tags to the API, bug #3983

---

taxonomies/categories.txt

Beer proxy for Agribalyse

---

taxonomies/additives.txt
taxonomies/ingredients.txt

Started repairing taxonomy errors
**Related issues and discussion:** #3990

Taxonomy errors

---

lib/ProductOpener/Display.pm
lib/ProductOpener/Tags.pm
t/tags.t

fix translate taxonomy interface, bug #3954

---

lib/ProductOpener/Ingredients.pm
t/ingredients_parsing.t
taxonomies/additives.txt
taxonomies/additives_classes.txt
taxonomies/ingredients.txt
taxonomies/ingredients_processing.txt

de:unknown inspiration

---

cgi/search.pl
templates/search_form.tt.html

simplify template and fix small issues, fixes #3999

---

taxonomies/ingredients.txt

**Related issues and discussion:** #3990

Taxonomy error repairs

---

lib/ProductOpener/Display.pm
templates/display_product.tt.html

$html needs to be empty before we call the template processing.

small fixes for product page template

---

lib/ProductOpener/Display.pm

Show Get the app on 13inch laptops, so that people get a chance to see it.

Show Get the app on 13inch laptops

---

lang/fr/texts/decouvrir.html

close stray <b> tag

---

lang/en/texts/sendinblue.html

use IANA sanctioned example domain name for email

use IANA sanctioned example domain name

---

.dockerignore
scripts/refresh_taxonomies.js

Fixes a CodeQL issue and speeds up Docker build by removing some large non-essential files from the build context.

Minor Changes

---

lib/ProductOpener/Display.pm
templates/display_product.tt.html

**Related issues and discussion:** fixes #4015

Display barcode bug fix

---

taxonomies/additives.txt
taxonomies/categories.txt
taxonomies/ingredients.txt

Adding ingredient spellings seen in photos. Changing Vitamines to Vitamins in English.

Taxonomy edits

---

taxonomies/categories.txt

Spain changes that I had commited but not pushed.

Small categories changes for Spain

---

taxonomies/categories.txt
taxonomies/ingredients.txt

More anomalies found while editing records.
Not sure if the merge being in there is a bad thing. I had to resolve a conflict.

Taxonomy edits - ingredients and categories

---

taxonomies/additives.txt
taxonomies/ingredients.txt

More unrecognised terms while editing, a few corrections/de-duplications.

Taxonomy edits - ingredients and additives

---

.github/workflows/perlcritic.yml

Update perlcritic Action to v2

---

taxonomies/categories.txt

merge 1st part of categories translations + put back some agribalyse codes that were deleted somehow

merge 1st part of categories translations + put back some agribalyse codes

---

taxonomies/categories.txt
taxonomies/ingredients.txt

This partly reverts commit aeeca450e68267986fe6927e6e3442bac2c9f22b.
Related: #4067

Revert agribalyse_food_codes back

---

taxonomies/ingredients.txt

unrecognised ingredients in the data. 
(splitting the branch into additions and dedupes for clarity)

Taxonomy edits 5 - ingredient additions

---

taxonomies/ingredients_analysis.txt

Here are translations from the server for ingredient analysis

[READY] ingredients_analysis translations

---

po/common/he.po

Hebrew hotfix

---

taxonomies/additives.txt
taxonomies/additives_classes.txt
taxonomies/categories.txt
taxonomies/ingredients.txt
taxonomies/labels.txt
taxonomies/minerals.txt
taxonomies/vitamins.txt

mostly unrecognised ingredient terms from editing records.

Taxonomy edits 7 - additions only this time ;)
