- lib/ProductOpener/Ingredients.pm
Let's just unify all newline chars to `\n` before parsing the ingredients.
> Workaround for Unicode newline chars from OCR

- html/js/product-multilingual.js
Fixes #386 again, also fixed 'kJ'/'kcal' not being selectable for 'Energy from Fat'.
> Automatically populate the unit options based on the selected nutrient.

- lib/ProductOpener/Lang.pm
Force French colon separator to be a 'NO-BREAK SPACE' (U+00A0).
> separator_before_colon as NO-BREAK SPACE

- cgi/search.pl
Apparently, the page_size in the JSON search result wasn't always numeric. This should fix that problem.
> Numeric page size in search JSON

- .travis.yml
Fixes #885 by using binaries from the node_modules directory.
Previously, this was somehow done automatically. Maybe Travis changed something.
> Update Travis CI build definition

- po/openpetfoodfacts/openpetfoodfacts.pot
ingredients_text_example is from https://github.com/openfoodfacts/openfoodfacts-server/blob/master/po/common/common-web.pot , but I removed cocoa.
> Pet-specific examples in the product editor

- html/js/jquery-interestingviews-selectclip.js
- ingredients/additifs/authorized_additives.txt
- ingredients/additifs/extract_additives.pl
- lang/es/tags/labels.txt
- lang/fr/tags/categories.txt
- lang/fr/tags/labels.txt
Git on Windows finally supports symlinks, so I enabled those and found some dead symlinks, that actually point to absolute paths.
All of these files do not exist on the production server either, so I think it should be save to delete them.
> Remove dead symlinks

- lib/ProductOpener/Display.pm
Apparently, the problem described in #941 was, that the `product_name` and `url` properties already were in UTF8 (not the other internal Perl format), `encode_json` also applied `encode_utf8` (or similar) internally, and thus the encoding got messed up.
> Unicode problem

- lib/ProductOpener/Display.pm
Example: http://world.productopener.localhost/categories.json
`{"count":4,"tags":[{"id":"en:pizza-with-ham-and-cheese","name":"Pizza
with ham and
cheese","products":1,"url":"http://world.productopener.localhost/category/pizza-with-ham-and-cheese"},{"id":"en:pizzas","name":"Pizzas","linkeddata":{"wikidata:en":"Q177"},"products":1,"url":"http://world.productopener.localhost/category/pizzas"},{"id":"en:pizzas-pies-and-quiches","name":"Pizzas
pies and quiches","linkeddata":{"pnns_group_2:en":"Pizza pies and
quiche"},"products":1,"url":"http://world.productopener.localhost/category/pizzas-pies-and-quiches"},{"id":"en:meals","name":"Meals","linkeddata":{"pnns_group_2:en":"One-dish
meals"},"products":1,"url":"http://world.productopener.localhost/category/meals"}]}`
> Add linked data array to JSON tags API.

- lib/ProductOpener/SiteQuality_off.pm
Tags quantities that contain stuff like "200 mg e", "300 ml e", and so on, but not "℮" as "quantity-contains-e".
I recently noticed that some products contain quantities like "500 g e", even though the packaging reads "500 g ℮". This new quality rule helps us find products like that, so that this issue can be fixed.
> Detect quantities with "e"

- cgi/product_multilingual.pl
- html/js/product-multilingual.js
Expands upon 6e741e2fae2ad96b3d039beb3bb2f6c4d43646a7 and closes #352.
The basics were already done, but IU/UI was not selectable when adding "Vitamin A" or "Vitamin D" to a product initially.
> Finish IU support

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- Ensure that $Nutriments{$nid} exists before trying any %DV/IU calculation.
- Add %DV/IU to selecatable units if it was selected previously.
> Fix 'Attempt to access disallowed key'

- t/lang.t
Added new regex based unit test for known links that might be mistranslated.
Note that the build probably fails because of a failing test (ie. incorrect translation), not because of an issue in this change.
> Tests for translated URIs

- scripts/update_all_products.pl
I just noticed the comment in `update_all_products.pl` regarding the cursor possibly timing out when processing a _lot_ of products. Making the cursor immortal should take care of this. It should still be safe, because it will be cleaned up if it runs out of scope.
http://search.cpan.org/dist/MongoDB/lib/MongoDB/Cursor.pm#immortal
> Ordinarily, a cursor "dies" on the database server after a certain length of time (approximately 10 minutes), to prevent inactive cursors from hogging resources. This option indicates that a cursor should not die until all of its results have been fetched or it goes out of scope in Perl.
> Make $cursor immortal

- lib/ProductOpener/Display.pm
Closes #1018
Note that I did not find a single reference to `remove_tags_and_quote` or `xml_escape` where leaving surrounding whitespace would make sense, which is why I'm applying it here.
> Remove surrounding whitespace for tags/xml

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
For #1112 
Added Contributing.md for new comers.
Add Issue Template and Pull Request Template so that standards are followed in development.
> Add Contributing.md and ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE

- lib/ProductOpener/Display.pm
For some reason, #972 was closed by 9626d6e42aea15d65b2daca2bc7c4b25679dc7e8 in conjunction with #968.
```
{
"count":4,
"tags":[
{
"id":"en:wines",
"products":1,
"name":"Wines",
"sameAs":[
"https://www.wikidata.org/wiki/Q282"
],
"url":"http://world.productopener.localhost/category/wines"
},
{
"id":"en:alcoholic-beverages",
"products":1,
"name":"Alcoholic beverages",
"url":"http://world.productopener.localhost/category/alcoholic-beverages"
},
{
"id":"en:wines-from-greece",
"products":1,
"name":"Wines from Greece",
"sameAs":[
"https://www.wikidata.org/wiki/Q1779616"
],
"url":"http://world.productopener.localhost/category/wines-from-greece"
},
{
"id":"en:beverages",
"products":1,
"name":"Beverages",
"sameAs":[
"https://www.wikidata.org/wiki/Q40050"
], …
```
> Use "sameAs" instead of "linkeddata".

- cgi/product_multilingual.pl
If we don't have a label for a nutrient in the current language for auto complete, use the countries other languages as a fallback, and, if there is no label for that either, use English. Closes #427
> Workaround for Chinese nutrient auto complete

- lib/ProductOpener/SiteQuality_off.pm
This quality asset allows users to find plant milks that are also categorized as dairies, because of the former categories taxonomy. In conjunction with the updated taxonomy, I think this should be enough to close #73.
> plant milks/dairies

- lib/ProductOpener/Display.pm
Use the site name (from translations) as the logo's alt text. Otherwise, all sites would use "Open Food Facts".
> Fix logo's alternative text

- docker/backend-git/conf/Config.pm
- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Tags.pm
- t/tags.t
Allow users (in reality probably rather APIs) to enter `https://www.wikidata.org/wiki/Q470974` or `wikidata:en:Q470974` as taxonomy tags and convert it to the known taxonomy tag.
I think that this could be a good approach to work on taxonomies. For example, auto-suggest could be updated to also query Wikidata for some taxonomy tags. As a follow-up to this change, we could also consider adding a taxonomy tag automatically from Wikidata, if the types and hierarchy match some expectations.
> Wikidata for input

- lib/ProductOpener/Display.pm
If we are displaying a single tag, and one of the structured response fields (`$request_ref->{json}`, `$request_ref->{jsonp}`, `$request_ref->{xml}`, or `$request_ref->{jqm}`) are set, then re-add the file extension to the URL, so that the requesting user agent gets the data in the correct format, instead of getting redirected to a HTML page. Closes #894
> Re-add file suffix for read API

- scripts/mongodb_dump.sh
Add delta export for the products collection. Closes #153
Dumps all products with a `last_modified_t` in the last day or since the last run of the script into the /data directory. Using [`mongoimport --mode=upsert`](https://stackoverflow.com/a/29776292/11963), this could be used to refresh a previous import.
> Delta Product Export

- cpanfile
- lib/ProductOpener/Index.pm
I removed all references to the `HTML::Defang` module, and `ProductOpener::Index` still compiles, so apparently it was unused.
Fixes #1226
> Remove HTML::Defang

- cpanfile
- lib/ProductOpener/Data.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Missions.pm
- lib/ProductOpener/Products.pm
Instead of having a custom retry logic for every query, I moved it to the `ProductOpener::Data` module, so that it can be reused properly. I also added `Action::Retry` to allow for a slight delay between retries, and implemented `Action::CircuitBreaker` on top of it, so that we don't query an already unresponsive MongoDB server.
> Update MongoDB retry handling (with Log::Any)

- lang/en/texts/data.en.html
The current syntax of "Links :" with spaces around the separator looks weird, and having a separate paragraph for each link is superfluous. Therefore, I would like to propose using a definition list instead. This should also help translators in Crowdin.
I also replaced the domain `world.openfoodfacts.org` with `static.openfoodfacts.org` in this page, because the content should be identical for all regions/languages, and thus does not need translation.
> Update data URLs in data.en.html

- lib/ProductOpener/Display.pm
Suggest browsers to spell out barcodes based on their digits. Otherwise, they might try to read "22151476" as "two million ...". https://www.w3.org/TR/2018/NOTE-css3-speech-20180605/#speaking-props-speak-as
> Improve A11Y for barcodes in the product page

- cgi/product_multilingual.pl
- cgi/reset_password.pl
- cgi/user.pl
- cpanfile
- docker/backend-dev/conf/Config.pm
- docker/backend-dev/conf/Config2.pm
- lib/ProductOpener/Config2_sample.pm
- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Users.pm
- po/common/common.pot
- po/common/de.po
- po/common/en.po
- po/common/obsolete.pot
Removed all references to `WWW::CSRF` and replaced it with `SameSite=Lax` cookies.
Due to browser enhancements, manual token checks are not the single most useful defense against CSRF [any more](https://scotthelme.co.uk/csrf-is-dead/). Also see [OWASP](https://www.owasp.org/index.php?title=Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet&oldid=242455#Alternate_CSRF_Defense:_SameSite_cookie_attribute).
I believe that this fixes #1147 while retaining security precautions.
> Use SameSite cookie for CSRF defense

- conf/nginx/sites-available/cestemballepresdechezvous
- conf/nginx/sites-available/combiendesucres
- conf/nginx/sites-available/howmuchsugar
- conf/nginx/sites-available/madenearme
- conf/nginx/sites-available/madenearme-uk
- conf/nginx/sites-available/obf
- conf/nginx/sites-available/off
- conf/nginx/sites-available/off-preprod
- conf/nginx/sites-available/opf
- conf/nginx/sites-available/opff
- conf/nginx/sites-available/whatsinmyshampoo
- conf/nginx/sites-available/whatsinmyyogurt
Simply enables HTTP/2 for the configured sites. As OFF is now deployed on Debian Stretch (as far as I know), HTTP/2 should be available in the `nginx-full` package. Using HTTP/2 should allow for better parallel download of static resources and fixes #745.
> Enable HTTP/2

- lib/ProductOpener/Display.pm
Re-adds missing opensearch `link` tag. Follow up to the discussion in #1182.
> Re-add opensearch

- cpanfile
- t/additives.t
- t/allergens.t
- t/display.t
- t/food.t
- t/ingredients.t
- t/ingredients_clean.t
- t/lang.t
- t/perlcritic.t
- t/products.t
- t/store.t
- t/tags.t
- t/text.t
Apparently, using `print` in unit tests is against [best practices](https://perldoc.perl.org/Test/More.html#Diagnostics) of the test module. I replaced manual logging to `STDERR` with `diag` and `Data::Dumper` with the mentioned `explain`.
> Test logging

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Products.pm
- scripts/export_database.pl
1. Encode URIs for RDF export (see #811).
2. Filter bad chars which break CSV and log it in a file (prevent but doesn't resolve #1585).
It seems to work with a test dataset of 177 products, but you might try it before deploying in production. I don't know how to test on the whole database.
You should review commit by commit if you want to see clearly what I've done. Commit 9fb9f6f is a mistake and I'm not very confident on commit deletion.
> Correct rdf data export (#811) and prevent broken CSV (#1585)

- cgi/manifest.pl
Resolves a warning from Chrome. which warns us that `prefer_related_applications` is ignored, because it's not an actual boolean value:
> manifest.pl:1 Manifest: property 'prefer_related_applications' ignored, type boolean expected.
> Fix "prefer_related_applications" being ignored

- lib/ProductOpener/Import.pm
- lib/ProductOpener/Products.pm
- scripts/convert_ferrero_data.pl
- scripts/import_csv_file.pl
- scripts/process_new_image_off.sh
- scripts/run_cloud_vision_ocr.pl
See https://github.com/openfoodfacts/openfoodfacts-server/issues/1661
There's another change on Images.pm that I have commited to master that creates a symlink in /srv/off/new_images whenever an image is uploaded : https://github.com/openfoodfacts/openfoodfacts-server/commit/cd4701ad189de63c940c33c31da247c2174ed26f
Then there is an incrontab that watches that directory:
incrontab -l -u off
/srv/off/new_images IN_CREATE /srv/off/scripts/process_new_image_off.sh $@/$#
This in turns calls /srv/off/scripts/run_cloud_vision_ocr.pl (which calls cloud vision and robotoff for ocr analysis etc.)
Logs are in /srv/off/logs# more run_cloud_vision_ocr.log
> Issue 1661/ocr onthefly : run Cloud Vision and call robotoff for all newly uploaded images

- cgi/product_jqm_multilingual.pl
**Description:** We should only overwrite `no_nutrition_data` if it is present in the POST/GET request. This avoids that this value is changed accidentally, because it was omitted from the request.
**Related issues and discussion:** Fixes #1191
> Don't overwrite `no_nutrition_data` if a value was given in the request

- cpanfile
- docker/backend-dev/conf/Config.pm
- docker/backend-dev/conf/Config2.pm
- docker/backend/Dockerfile
- docker/productopener/templates/backend-conf.yaml
- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/GeoIP.pm
- lib/ProductOpener/Products.pm
- scripts/gen_users_emails_list.pl
- scripts/obsolete/update_all_products_countries_add.pl
- scripts/obsolete/update_all_products_countries_fix.pl
The original GeoLite database was [discontinued at the beginning of this year](https://support.maxmind.com/geolite-legacy-discontinuation-notice/). In order to keep server-side geolocation, we need to migrate to an alternative. ie. [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/). As GeoLite2 isn't packaged for Linux distributions (yet?), we need to download it manually and configure where the `.mmd` file is located. (See the updated `Dockerfile` for an example.)
> Migrate to GeoIP2

- lib/ProductOpener/Food.pm
- t/food.t
**Description:** The regex was replaced by a fixed version that ignores the optional "CE" or "EC" in Spanish product opener numbers. See https://github.com/openfoodfacts/openfoodfacts-server/issues/424#issuecomment-471314441 for the bugfix.
**Related issues and discussion:** Fixes #424
> Fix ES packager code normalization

- lib/ProductOpener/Display.pm
**Description:** `rel='nofollow'` should avoid crawlers indexing the second level of facets.
**Related issues and discussion:** Fixes #938
> Use rel='nofollow' for nested faceted search

- lib/ProductOpener/Display.pm
**Description:** Results in the `$subdomain` of the search page in the CSV export, instead of the country without a language code.
**Related issues and discussion:** Fixes #263
> Use `$subdomain` for CSV export of search results

- lib/ProductOpener/Products.pm
**Description:** There were a few cases where the OFF development server pushed it's images to the productive Robotoff instance. This should only be done if the `$robotoff_url` was configured correctly.
**Related issues and discussion:** #1707
> Use $robotoff_url

- lib/ProductOpener/SiteQuality_off.pm
- t/sitequality.t
**Description:** Based on the [GS1 Specs](https://www.gs1.org/docs/barcodes/GS1_General_Specifications.pdf), add quality tags that help with identifying non-food products or non-products (refunds/coupons).
**Related issues and discussion:** Fixes #1129
> Add quality tags for GS1 prefixes

- cgi/product_image_crop.pl
- cgi/product_jqm_multilingual.pl
https://github.com/openfoodfacts/openfoodfacts-server/issues/1810
> disallow edits from apps to product data and images sent by manufacturers

- docker/backend/Dockerfile
- docker/docker-compose.dev.yml
- docker/docker-compose.yml
- docker/frontend/Dockerfile
- Use fixed image versions to avoid unintentional changes.
- Build apache2-mod-perl from source, because the @testing version in edge is compiled against a newer version than Alpine 3.9.4 (stable).
> Fix mod_perl not working in Docker

- lib/ProductOpener/SiteQuality_off.pm
- t/sitequality.t
**Description:** Adds the `ingredients-($lc-)over-30-percent-digits` quality tag to a product if the `ingredients_text` or a language-specific text (ie. `ingredients_text_de`) contains >30% digits.
**Related issues and discussion:** Closes #1861
> Set `ingredients-($lc-)over-30-percent-digits` quality tag

- lang/en/texts/index.en.html
- lang/en/texts/index.foundation.en.html
**Description:** As discussed in #1848 and on Slack, the index page does not show the latest added products, but latest modified products with complete products first. Because of that, the front page should not claim it's showing the latest added products.
**Related issues and discussion:** Fixes #1848
> Update index page caption

- lib/ProductOpener/Tags.pm
**Description:** The `$parentid eq 'fr:` check does not seem to be used/required. I replaced the `$log` statement with a `die` statement and rebuilt `categories.txt` and `labels.txt` without getting an error. Basically, this PR removes some dead code.
**Related issues and discussion:** Closes #970
> Removed `$parentid eq 'fr:'` check

- scripts/build_tags_taxonomy.pl
**Description:** Replaced bare word file handle `OUT` with the used file handle `$OUT`.
**Related issues and discussion:** Fixes #1963
> Fix typo when building tags

- lib/ProductOpener/Display.pm
**Description:** Instead of sending 200, actually send 404, so that the status can be parsed using common RESTful practices. Same status trick as in #1815.
**Related issues and discussion:** Fixes #976
> Send an actual 404 status if a product does not exist

- lib/ProductOpener/Display.pm
- package.json
- yarn.lock
**Description:** The 404 requests to `/undefined` are caused by `meta` and `link` elements generated by [ManUp.js](https://github.com/boyofgreen/manUp.js) dynamically: boyofgreen/ManUp.js#7. Since all relevant browsers (including current versions of iOS) do implement the [Web App Manifest spec](https://w3c.github.io/manifest/) to a good enough extent, I believe that we simply don't need ManUp.js any more. It was really useful two years ago, but the browser landscape has improved since then.
**Related issues and discussion:** Fixes #1968
> Remove ManUp.js

- cgi/madenearyou.pl
- cgi/top_translators.pl
- conf/nginx/sites-available/obf
- conf/nginx/sites-available/off
- conf/nginx/sites-available/off-preprod
- conf/nginx/sites-available/opf
- conf/nginx/sites-available/opff
- docker/frontend-git/conf/nginx.conf
- gulpfile.js
- lib/ProductOpener/Display.pm
- package.json
- yarn.lock
I removed the `bower_components` directory by adding some simple copy tasks to the `gulpfile.js`. This removes the need to symlink directories in the `postinstall` step and simplifies the package restore step, too. Visually and functionally, this is identical to the previous version in the `master` branch.
> Remove bower_components

- scss/templates/_icons.scss
**Description:** Applies the same line-height to the custom icon font as Foundation Fonts did: https://github.com/zurb/foundation-icon-fonts/blob/d0cf672fb32ba3db65d0ce6bb3b6b17ed820ac36/_foundation-icons.scss#L308
**Related issues and discussion:** Fixes #1984
> fix icon's line-height

- docker/backend-dev/conf/log.conf
- log.conf
Turns out that the structured data from `Log::Any` is copied to `Log::Log4perl::MDC` locally. Using the format of  `Data::Dumper::Concise`, we can simply dump the data to the text file using a custom cspec `S`.
> Log structured data in the text log

- lib/ProductOpener/Display.pm
This is a new feature to compute and display stats for tags: how many unique ones exist, and how many occurences they represent, for known tags and unknown tags (not recognized in the taxonomy).
https://fr.dev.openfoodfacts.org/editeur/scamark/ingredients&stats=1
This feature is very useful for ingredients, but it's available for all types of tags. And it can be used on subsets of products.
> new stats feature for tags, bug #2028

- lib/ProductOpener/Store.pm
- t/store.t
replace a bunch of regexps by a call to tr() in get_fileid
there seem to be some kind of memory leak in those regexps (which may be fixed in perl 5.26 and up, but we have 5.24 in prod and dev).
> replace regexps by tr, alleviate regexp memory leak, bug #2053

- taxonomies/labels.txt
**Checklist:**
This adds a few country entries to specific labels. 
Ecocert Canada -> Assumption is they would only certify canadian goods
Bio Austria -> As above
French brands -> Assuming they are products of France
Champion beers -> assuming they are only open to beers produced in that country.
**Related issues and discussion:** Closes https://github.com/openfoodfacts/openfoodfacts-ai/issues/45
> Add a number of country defaults

- taxonomies/categories.txt
**Checklist:**
A common mismatch between a product name ("Whole almonds") and a guessed category is to assume Whole Almonds are Whole Almond Puree.
This (I think is the right syntax) to add an alias.
**Related issues and discussion:** https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/32
> Add an alias for "Whole Almonds" -> almonds

- lib/ProductOpener/Display.pm
Perl displayed a warning that the @ char in the regexp was interpolated. cc @VaiTon
> fix interpolation of @ in regex

- yarn.lock
> [Security] Bump lodash from 4.17.11 to 4.17.14

- po/common/common.pot
Common.pot wasn't sound, thus the issue in Crowdin. This is why all changes should occur in common.pot and Crowdin should do the rest, including for French.
> Common.pot wasn't sound, thus the issue in Crowdin

- scripts/update_all_products_from_dir_in_mongodb.pl
The update script currently causes an error if an up-to-date version of the MongoDB driver is used:
```
\033[32m------------------ 3/ Import products -------------------\033[0m
Tags.pm - loading geofile villes-geo-france-galichon-20130208.csv
Tags.pm - loading geofile villes-geo-france-complement.csv
[Mon Aug  5 20:46:22 2019] update_all_products_from_dir_in_mongodb.pl: main::find_products() called too early to check prototype at /opt/product-opener/scripts/update_all_products_from_dir_in_mongodb.pl line 85.
1 products - 3900000419772
200 products to update
updating product 3900000419772 -- 3900000419772
[Mon Aug  5 20:46:22 2019] update_all_products_from_dir_in_mongodb.pl: #
[Mon Aug  5 20:46:22 2019] update_all_products_from_dir_in_mongodb.pl: # *** DEPRECATION WARNING ***
[Mon Aug  5 …
```
> Replace deprecated MongoDB::Collection::save method

- taxonomies/nutriments.txt
Added to measures for the bitterness of beers, as found on beer bottles.
> EBU and IBU added

- lib/ProductOpener/Config_off.pm
All food additives are exempt from Nutriscore. This will include yeast, gelatin and flavourings, which are mentioned explicitly the the NutriScore articles.
> Nutriscore exempt edit

- taxonomies/additives.txt
- taxonomies/additives_classes.txt
Additives classes are used for additives and ingredients parsing, so we need both singular and plurals, as well as synonyms used in ingredients lists.
> added plurals for Polish additives classes, bug #2177

- yarn.lock
Apparently, #2186 introduced a bad package hash: https://gist.github.com/rajo/26d634d817f2217fa15d05404965e8a4
Fixed by running `yarn install --update-checksums`
> Fix bad hashes in yarn.lock

- docker/backend-dev/conf/Config.pm
- docker/backend-dev/conf/apache.conf
- docker/backend-dev/conf/po-foreground.sh
- docker/backend/Dockerfile
- docker/build_yarn.bat
- docker/build_yarn.sh
- docker/docker-compose.dev.yml
- docker/docker-compose.yml
- docker/frontend/Dockerfile
- docker/productopener/templates/backend-conf.yaml
- docker/productopener/templates/backend-deployment.yaml
Instead of using Alpine Linux as the base image for our backend container image, we now use [bitnami/minideb](https://hub.docker.com/r/bitnami/minideb). The alpine based image is smaller and can be faster, but as we had to mix stable and edge packages to get apache2's mod_perl, it broke down too easily.
Also contains:
- fix: New `%ProductOpener::Config::string_normalization_for_lang` option had not been added, yet.
- build: Updates to 3rd party container images.
> Use minideb base container image

- lib/ProductOpener/Food.pm
- t/food.t
We were missing a unit (which is null) for the nova group, so it got multiplied / divided in the nutriments hash.
> fix nova issue #2230, set a null unit for nova group + add test

- taxonomies/additives_classes.txt
Added plurals for some additives in german
**Related issues and discussion:** #2231
stephane in Slack:
Could someone add the German plurals of additives classes in this file https://github.com/openfoodfacts/openfoodfacts-server/blob/master/taxonomies/additives_classes.txt ? e.g. Säureregulator -> Säureregulator, Säureregulatoren
This helps a lot to correctly parse ingredients, to recognize additives, compute NOVA etc.
> add plurals of additives (de)

- taxonomies/ingredients.txt
de:Raps (en:Rapeseed) could be used as an ingredient of it's own and isn't required to be used as an oil.
To be fair, this mostly applies to [Open Pet Food Facts](https://world.openpetfoodfacts.org/).
> Add rapeseed as an ingredient of it's own

- taxonomies/categories.txt
**Description**
Made minor changes to _taxonomies/categories.txt_ to improve the hierachy and help with api usage and searching.
**Issues resolved :**
1. Changed "en:Whole tunas" to be a sub-category of Tunas and Fishes
Causes some items to be categorized as "whole tuna" without being categorized as "Tuna" or "fish".
Example: https://world.openfoodfacts.org/product/3250392332808/odyssee-thon-entier-au-naturel-112-g-net-egoutte-odysee-intermarche
2. Added Dragées as a sub-category of Confectioneries
For similar reasons
3. Added "Two-crust Pies, 2 crust pies" as a sub-category of "Pies"
For similar reason as above
> Corrections to categories.txt in "taxonomies"

- .devcontainer/devcontainer.json
- docker/backend/Dockerfile
- docker/docker-compose.vscode.yml
Adds the `.devcontainer` directory for Visual Studio Code.
This allows vscode with [an extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) to build and automatically start the dev container.
> Add vscode .devcontainer

- lib/ProductOpener/Food.pm
- t/nutriscore.t
Added a 100% estimate of fruits/vegetables/nuts for products in the colza / walnut / olive oils category.
+ tests.
Olive oils and Walnut oils are now C instead of D.
> Issue 2296/nutriscore : colza / walnut / olive oils are now considered as fruits/vegetable/nuts

- cgi/product_jqm_multilingual.pl
- lib/ProductOpener/Products.pm
**Description:** If the computed `%diff` of the product is `undef` or empty, do not actually store the product changes on disk (neither `.sto` files, nor MongoDB). To enable reporting this to end users, `store_product` now returns `1` if the save was successful; otherwise it returns `0`.
**Related issues and discussion:** Fixes #374
> Don't save empty edits

- lib/ProductOpener/Display.pm
fix locale issues with minus sign in different characters for percent differences.  Use numeric compare instead of string.
**Related issues and discussion:** #2273
> fix for issue 2273

- lib/ProductOpener/Display.pm
As discovered by @zigouras in #2010, the pagination of `recent_changes.cgi` was lost when the MongoDB Perl driver was updated.
> Re-add pagination for recent changes

- lib/ProductOpener/Products.pm
The compute history function is not reliable enough and we are losing actual edits.
> reenable empty edits, bug #2318 #374

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
changes for issue 2010 ... page_size aka limit is not persisted through pagination method and navigation links on the recent changes page
also removed unused method canonicalize_taxonomy_2tag_link from Tags.pm
**Related issues and discussion:** #2010
> fix for issue #2010: continue page size in recent change pagination

- lib/ProductOpener/Products.pm
- scripts/update_all_products.pl
This fixes the autorotate bug where the rev was not correctly incremented in the saved product file.
There is also a script to fix that revision for the products that have not yet been edited after the autorotate.
For products that have already been edited, the next change has unfortunately been merged with the autorotate in a single product file.
> fix for autorotate rev bug #2321, related to #2318

- t/ingredients_tags.t
- taxonomies/additives.txt
- taxonomies/ingredients.txt
- taxonomies/minerals.txt
* add many German translations, spelling corrections for additives (mainly capitalisation)
* carotenoids, carotene, beta-carotene marked as maybe vegetarian and maybe vegan, see e.g. [here](https://www.vrg.org/blog/2012/02/15/beta-carotene-in-us-beverages-not-stabilized-with-gelatin-unlike-some-products-in-the-uk) and [there](https://www.coca-cola.co.uk/faq/ingredients/coca-cola-drinks-suitable-for-vegans-vegetarians)
* calcium carbonate marked as maybe vegetarian and maybe vegan, see e.g. [here](https://en.wikipedia.org/wiki/Calcium_carbonate#Biological_sources) and [there](https://www.vrg.org/blog/2011/12/12/calcium-carbonate-in-most-soy-rice-beverages-and-in-calcium-supplements-derived-from-a-mineral-source-not-oyster-shell-source-does-not-have-to-be-labeled)
* rename …
> German translations, spelling corrections for additives

- cgi/import_file_upload.pl
- html/js/product-multilingual.js
- lib/ProductOpener/Images.pm
Forces image uploads to be done [sequentially](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#sequentialuploads) instead of in parallel. This should help with some [image uploading problems](https://github.com/openfoodfacts/openfoodfacts-server/issues?utf8=✓&q=label%3A"image+upload"), ie. race conditions.
**Related issues and discussion:** Possibly helps with #304
> Enable sequential uploads for blueimp-file-upload

- html/files/robots.txt
We could allow bots to index the OpenSearch description, so that search engines know how to redirect search requests to OpenFoodFacts. Also, it might be a good idea to have image info pages to be index for better link rank and to get the image license and attribution "out there".
**Related issues and discussion:** N/A
> Robots.txt allow some /cgi URLs

- .github/workflows/pull_request.yml
- lib/ProductOpener/Food.pm
- lib/ProductOpener/Nutriscore.pm
I reimplemented the Nutri-Score computation in a separate module.
I separated what is related to Product Opener (e.g. which category the product is in), and what is purely related to the Nutri-Score computation.
At this point, I kept the old Nutri-Score computation too, to check if we get the same results. I fixed a few things related to the number of digits that values need to be rounded to for computing Nutriscore, so there is a very small amount (about 0.25%) where we have a different nutrition score (and thus an even smaller number of different nutrition grades).
I'm testing it on the dev server:
https://world.openfoodfacts.dev/data-quality/nutriscore-computations-different-score
https://world.openfoodfacts.dev/data-quality/nutriscore-computations-same-score
> separate Nutriscore computation to Nutriscore.pm module, bug #2427

- .github/workflows/pull_request.yml
- cgi/product_multilingual.pl
- lib/ProductOpener/Products.pm
- po/common/common.pot
- po/common/en.po
- scripts/gen_top_tags_per_country.pl
- scripts/update_all_products.pl
Issue #1592 introduced the possibility for admins to mark products as not being sold anymore ("obsolete"). The products were completely removed from MongoDB, but kept in the file system so that we could show them if they were scanned.
This issue is to improve the handling of obsolete products:
1. Brand owners will be able to mark products as obsolete
2. Obsolete products will be kept in MongoDB, but:
3. The sort order will put them last
4. They will be grayed out in the product list
5. Obsolete products won't be taken into account in category stats
> better support for obsolete products, bug #2442

- lang/en/texts/dev-general.html
Docs -> Code (I'm guessing that it's a mistake since there's no such thing as Summer of Docs).
> Typo fixed

- .travis.yml
If no language is defined, Travis CI falls back to Ruby. For some reason, it now tries to run `rake`, which fails because we have no Ruby files. Since we use Perl and node.js in our CI build, using the [`generic`](https://docs.travis-ci.com/user/languages/minimal-and-generic/) language seems like a good alternative.
**Related issues and discussion:** #2506
> ci: Build Travis CI as a generic script

- .travis.yml
Just checking. For some reason the slack notification makes https://config.travis-ci.com/explore not work.
> removing lines that make travis-lint not respond

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Text.pm
I noticed that `ProductOpener::Text::normalize_percentages` took a lot of time during the CSV import. According to `Devel::NYTProf` that was caused by creating new instances of `CLDR::Number` and it's formatters in loops.
<table>
<tr><th scope="col">What?</th><th scope="col">Before</th><th scole="col">After</th></tr>
<tr><th scope="row">Subroutine list</th><td><img src="https://user-images.githubusercontent.com/87124/68681800-55a58200-0564-11ea-9cf8-0a86a9456f5d.png"></td><td><img src="https://user-images.githubusercontent.com/87124/68681886-838ac680-0564-11ea-93b0-04d8c627c2f4.png"></td></tr>
<tr><th scope="row">Sub <code>normalize_percentages</code></th><td><img src="https://user-images.githubusercontent.com/87124/68682034-c482db00-0564-11ea-91c9-a8a81c07e36e.png"></td>< …
> Cache CLDR and it's formatters

- lib/ProductOpener/Text.pm
If the main body of normalize_percentages is only run if a known percent sign is present, then a lot of sub calls related to CLDR and formatting can be avoided. Performing the check using `index` is much faster than doing anything else.
In my benchmarks, this brought down the time for `normalize_percentages` from 2.25s exclusive/7.13 inclusive to 647ms exclusive/963ms inclusive.
**Related issues and discussion:** #2589
> Conditionally run normalize_percentages

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Food.pm
This change is to introduce new energy-kj and energy-kcal nutrients. Please see bug #2396 for the explanation of why we need this.
We need to be careful as we need to handle several situations:
1. I will run the update_all_products.pl script to run compute_serving_size_data() that will populate either energy-kj or energy-kcal from the energy field. But it is going to take hours.
2. In the mean time, there will be the new product edit form on the web site, which will first run compute_serving_size_data() before displaying the form, so that we don't have empty values.
3. There is also the apps: they will still have access to the energy value, and when they update the "energy" field (and not "energy-kj" and "energy-kcal"), we will in fact use the unit they pass to set the energy-kj or -kcal …
> Issue 2396/energy in kj and kcal -- huge change, please review

- docker/build_npm.sh
- docker/start_dev.sh
Docker apparently does not like relative paths to be used as volumes. Thus, we resolve the path manually.
> Use bash trick to resolve relative path

- cgi/product_image_move.pl
- cgi/product_image_upload.pl
- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Users.pm
- po/common/common.pot
- po/common/en.po
very simple system to assign users to groups (e.g. moderators, producers etc.), that we can use to enable special features.
> add support for user groups to define permissions, bug #2085

- lib/ProductOpener/Display.pm
In 6ebac4478b30d65b1f81c58c468577d8dd443d22, the following block was added, which made the previous `if..elsif..else` decision tree work differently.
https://github.com/openfoodfacts/openfoodfacts-server/blob/a5d02f9439e0bdc5602947a1aa58a97c4a070bfd/lib/ProductOpener/Display.pm#L558-L562
For some cases, this caused the `text` property to the `$request_ref` to be set to `undex` instead of `"text"`.
**Related issues and discussion:** Fixes #2652
> Replace 'index' text later

- lib/ProductOpener/Config2_sample.pm
- lib/ProductOpener/Users.pm
While we don't have #1204, other APIs might need to pass the session cookie. This adds a server option to whitelist IPs for all cookies.
**Related issues and discussion:** Fixes #2637
> Add server option to whitelist IPs for all session cookies

- po/openbeautyfacts/de.po
Fix the unit test that started failing at some point in time.
```
Wide character in print at /usr/share/perl/5.26/Test2/Formatter/TAP.pm line 105.
t/i18n.t ......................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/355 subtests 
```
> Fix unit tests

- taxonomies/categories.txt
Right now, in production, https://world.openfoodfacts.org/category/croutons redirects to https://world.openfoodfacts.org/category/breads. Also, the "breads" category is linked to https://www.wikidata.org/wiki/Q1197400 instead of https://www.wikidata.org/wiki/Q7802.
> Make croutons a separate category

- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
Makes the NOVA Group info title translatable.
**Related issues and discussion:** Fixes #2144
> Move info title to translation

- taxonomies/allergens.txt
As pointed by Juho on Slack a while ago, the gluten wikidata link is currently broken. I don't know if the wikidata property ever supported the comma syntax, but it doesn't seem to matter in this case, as neither of the items actually point to gluten. Fixed by replacing with a link to a item pointing to gluten.
> allergens: fix gluten wikidata link

- gulpfile.js
The `buildJs` task needs to be run in the `default` task to produce `html/js/dist/display.js` and it's friends.
> Run buildJs task in gulp

- lib/ProductOpener/Display.pm
the user_id and user_session context was kept from previous sessions, so it made quite puzzling log messages.
> clear the log context

- lib/ProductOpener/Products.pm
Added `rev` to the list of properties that should be numbers.
https://github.com/openfoodfacts/openfoodfacts-server/blob/92ef4366e3dc440677c3b595b1877f65297776cf/lib/ProductOpener/Products.pm#L750-L755
Should fix #2800.
> Cast $rev number when saving the product.

- lib/ProductOpener/Display.pm
Replaces the static string `Open Food Facts` in the footer with the configured site name.
> Fix footer site name

- docker/README.md
- docker/backend/Dockerfile
- docker/docker-compose.geolite2.yml
- lib/ProductOpener/GeoIP.pm
Remove download of the GeoLite2 image in the Dockerfile. Also, don't fail everything if the file does not exist, making geolocation an optional feature.
**Related issues and discussion:** Fixes #2828
> Make the download of GeoLite2 optional

- lib/ProductOpener/Products.pm
- t/products.t
I removed a matching regex that was too dangerous, we will now only extract UUIDs from known apps configured in Config.pm.
Also added some tests.
> fix too aggressive uuid extraction from edit comments, fixes #2835

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
Sorry @hangy , I changed my mind: it's too dangerous to expect all callers to have called init_emb_codes(), nearly all the scripts in /scripts actually need it. So let's put back an initialization on demand, but keeping the unless clause so that the function is called only once.
> call init_emb_codes() on demand, bug #2204

- lib/ProductOpener/Display.pm
The ingredient warning labels (palm oil free, vegan,...) were not displayed correctly on Firefox (text not centered), the first commit fixes it.
The colors are quite flashy, the second commit brings more natural colors to the labels.
Before (Firefox):
After (Firefox):
> Fix ingredient warnings UI

- lib/ProductOpener/Display.pm
fix deployed on the server, as the android app was not displaying products if the ingredients had nested sub-ingredients.
> delete nested ingredients in api version < 2, bug #2883

- lib/ProductOpener/Products.pm
- scripts/find_and_replace_user_id_in_products.pl
This is to rename all occurences of a userid in a product, including the history.
It will be useful in particular for users who want to delete their account: we can rename them to openfoodfacts-contributors.
> allow renaming users in product history, bug #253

- cgi/product_jqm_multilingual.pl
More overrides to reduce language transfer work when an app is sending French photos and data while the image and data are actually in another language
> More overrides to reduce language transfer work

- lib/ProductOpener/Display.pm
Disable double-encoding an UTF-8 string by encode_json.
**Related issues and discussion:** Fixes #2972
> Fix encoding of map labels

- scripts/print_all_translations.pl
useful for debugging translations:
/srv/off/scripts# ./print_all_translations.pl n_products | grep '%d'
pt %d produtos
> script to print all translation of a string, for debugging

- docker/dev-environment-quick-start-guide.md
Adds a hint about running the dev docker container on a different port than `80`.
> About running the docker container on another port

- taxonomies/countries.txt
English should be kept as the default language for Indian pages as discussed in the comments 
#1109
> Fixes #1109: Change default language from Hindi to English on in.openfoodfacts.org (Open Food Facts India)

- lib/ProductOpener/URL.pm
Documentation of the ProductOpener::URL.pm module in perlpod format
**Related issues and discussion:** #3044
> Document the ProductOpener::URL.pm module

- cpanfile
- scripts/generate_perl_html_doc_from_pod.pl
Now that we have quite a few modules with at least some POD documentation, I'm looking into ways to present it. This is the result of pod2html:
https://world.openfoodfacts.org/files/doc/perl/index.html
It doesn't look very nice yet, but it's probably possible to make it nicer with some CSS styles etc.
> script to call pod2html to generate perlpod html doc, issue #2203

- crowdin.yml
should fix the overwritten by crowdin symlink issue and force us to move completely to symlinks for nl
> fix-for-nl

- lib/ProductOpener/Food.pm
- t/food.t
(please test before)
**Related issues and discussion:** #1618
> Add 公克 for metric grams in chinese, see #1618

- lib/ProductOpener/Display.pm
2 changes:
/ingredients.json now includes a known : 1 or 0 property that indicates if the ingredient exists in the taxonomy
/ingredients?stats=1&json=1 now includes a percent property, so that we can display it easily in graphana
> added percent info in ingredients stats json for monitoring

- lib/ProductOpener/Ingredients.pm
- t/allergens_tags.t
- t/ingredients_tags.t
We currently handle things like "traces de lait et de gluten" in ingredients list, but not if they have been flagged as allergens with underscores "traces de _lait_", which we can get through manual input or from producers imports. This fixes it.
> handle 'traces: _mustard_' with underscores

- lib/ProductOpener/ImportConvert.pm
recursive_list() is being called recursively, early prototype declaration fixed the warning
**Related issues and discussion:** 
fixes #3122
> ImportConvert.pm: ProductOpener::ImportConvert::recursive_list() called too early to check prototype

- refresh_taxonomies.js
- t/ingredients_processing.t
- taxonomies/categories.txt
- taxonomies/ingredients.txt
- taxonomies/ingredients_processing.txt
****Description:**
- Added process de:püree and synonyms
- Removed püree entries from ingredients taxonomy
- Created two tests for `ingredientpüree` and `ingredient püree`.
**Issues
Are more tests required? 
- Synonym tests? 
- `püreeingredient` tests
`de:Apfel-Püree konzentriert` has been left in taxonomy
> Process de:püree

- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
Signed-off-by: Areesha Tariq <areeshatariq02@gmail.com>
The status is separated as 'To Do' and 'Done', based on whether the status indicates something is done ("Nutrition facts completed" etc.) or not done ("Characteristics to be completed").
**Output:**
When Done does not contain any entry, only To Do is displayed:
When To Do does not contain any entry, only Done is displayed:
**Related issues and discussion:** 
fixes #2866
> Divide status between: TO DO and DONE

- cgi/user.pl
This fixes a problem when editing users (the user name and user id fields were reset to empty values).
> fix issue when editing users, related to bug #2673

- html/js/product-multilingual.js
related to bug #3031.
With the new cropper, the full image is loaded, but there is no easy way to get a link to it or to save it (without using the inspector)
> put back link to full res image in product edit form

- lib/ProductOpener/Ingredients.pm
- t/ingredients_parsing.t
- taxonomies/ingredients.txt
We currently treat the . in S. thermophilus as a separator, which results in a "S" ingredient and a "thermophilus" ingredient.
> parse S. thermophilus, L. acidophilus etc.

- lib/ProductOpener/Products.pm
> fix for teams tags

- ingredients/additives.txt
- taxonomies/additives.txt
- taxonomies/additives_classes.txt
- taxonomies/ingredients.txt
- taxonomies/labels.txt
- taxonomies/nutriments.txt
The spelling errors were detected by comparing all FR ingredient tokens with Wikipedia tokens. Corrections were manually applied.
> Fix FR spelling errors in ingredient taxonomy

- lib/ProductOpener/Ingredients.pm
- t/ingredients_processing.t
changed the parsing algorithm so that the ingredients processing is recognized if it's in parenthesis after the ingredient. e.g. "Piment (en poudre)".
> parse garlic (powdered)

- lib/ProductOpener/Display.pm
fixes #3329
This was partly responsible for some very long mongodb queries as we were also missing an index on the owners_tags field.
> Remove useless mongo query on producers platform when not logged in

- scss/_off.scss
I edited the _off.scss file to add a margin-top to the dropdown menu. This way, the dropdown no longer overlaps the text and makes it easier to read and click on the arrow button. 
**Related issues and discussion:** #3354
> Fixed overlap in country dropdown

- lib/ProductOpener/Display.pm
This is a continuation of @syl10100 's PR : https://github.com/openfoodfacts/openfoodfacts-server/pull/3310
When  we have less than 10000 tags (which for almost all tags type is always the case, except for ingredients, editors, possibly categories), we can avoid making a separate count query: we know the number of results from the query that fetches them.
> tags pagination: do not create a 2nd count mongod query if less than 10k results

- lib/ProductOpener/Data.pm
At the start of the project, I was retrying MongoDB queries once, and @hangy made a better system with Action::Retry. But when the MongoDB server is overloaded (as was the case a week ago), retrying queries make things worse, so I think we should turn off retries, unless at some point we put more than one MongoDB server.
> set max_retries_number to 0 for MongoDB queries, bug #3350

- conf/nginx/sites-available/off
- lang/en/texts/hunger-game.html
Removed `/hunger-game` page;
Added redirect to `hunger.openfoodfacts.org` to nginx config.
To not break the userscript we need to wait for it to update to the new URL.
> Update linking to hunger-games

- lib/ProductOpener/Ingredients.pm
- t/ingredients_parsing.t
- t/ingredients_tags.t
Fixing a silly mistake I have made earlier of postfixing the vitamin code instead of prefixing it, like it should have been done.
> ingredient parsing: normalize Finnish vitamins correctly

- docker/backend-dev/scripts/import_sample_data.sh
- docker/backend/Dockerfile
Makes it easier to run perl scripts, because the dependencies from CPAN are then already included.
> Add PERL5LIB environment variable to the docker images

- cgi/export_products.pl
Small change to attribute changes to users of the form org-producer-name in order to avoid conflicts with existing user names that may be from different organizations.
> add org- to the source_id

- scripts/check_perl.js
This avoids ERR_CHILD_PROCESS_STDIO_MAXBUFFER being called if we have too much output.
> Use spawn to check perl scripts

- taxonomies/ingredients.txt
Corrected Swedish translation for Propellent gas (Drivgas) from preservative (Konserveringsmedel)
> Corrected Swedish translation for Propellent gas

- taxonomies/labels.txt
Health Star Rating System claims to be used by more 10,000 products in Australia.
At least we could add these labels.
http://healthstarrating.gov.au/
> Add Health Star Rating System from Australia

- po/common/common.pot
Fix unescaped string in ingredient analysis msg that prevented synchronisation
> Fix unescaped string in ingredient analysis

- lib/ProductOpener/Food.pm
- t/food_digits.t
This is a function to solve bug #3483
> Keep significant digits, remove insignificant digits for nutrition facts

- po/common/common.pot
A standard po file is 
msgctxt "
msgid "
and then msgstr "
> Fix syntax error in the ingredient analysis file

- scss/_off.scss
I edited the _off.scss file by adding a media query that responds to a mobile device. The styles center the products, dropdown, and pagination. It also gets rid of the white-space as mentioned in the issue. 
**Related issues and discussion:** #3420
> Mobile Fix for Product List layout

- lang/en/texts/partners.html
Turn the contact us into a more visible CTA on the partners page
> Turn the contact us into a more visible CTA on the partners page

- taxonomies/ingredients.txt
Three main enhancements in Danish.
* ingredienser is more (only) used in comparison to indeholder
* Favre seems to be never used -> Farvestof
* krydderi seems always in the plural way krydderier
> Danish enhancements

- .gitattributes
- cpanfile
- docker/backend-dev/conf/po-foreground.sh
- docker/backend/Dockerfile
- lib/ProductOpener/Display.pm
- templates/nutrition_score.tt
HTML Template has been created for Nutrition Score Calculation Details using Template::Toolkit
The template file is used for the presentation purpose only, while all the logic has been kept in /lib/ProductOpener/Display.pm
> NutritionScore Calculation Details HTML Template

- lib/ProductOpener/Display.pm
- templates/nutrition_facts_table.tt.html
Changes:
- moved $template_data_ref definition at the start of the function, so that we announce at the start what structure we are building, and what it will look like
- simplified the structure for the list of comparisons (removed array with only one element, and hash with only one key)
- moved the generation of checked="checked" to the template, instead of the Perl code
> simplify template data structure for nutrition table

- lib/ProductOpener/Food.pm
- t/nova.t
- taxonomies/categories.result.txt
- taxonomies/categories.txt
- taxonomies/ingredients.result.txt
- taxonomies/ingredients.txt
Ingredients, additives, categories etc. used to determine NOVA are currently configured in the Config_off.pm file. This adds logic to allow moving the config to nova:en properties in each taxonomy. It makes it easier to keep it in synch (e.g. if we change the canonical name of an entry in the taxonomy).
Also added en:sauces en:cheeses en en:bread as triggers for NOVA 3 for bug #3605
> starting to move nova config from Config_off.pm to taxonomies

- taxonomies/categories.txt
Errors in the categories taxonomy definition:
3618
ERROR - en:cooked-rabbit-meat is a parent of itself
3619
ERROR - en:cooked-kidneys is a parent of itself
3620
ERROR - en:salad-without-dressing has an undefined parent
3621
Errors in the categories taxonomy definition at lib/ProductOpener/Tags.pm line 1608.
3622
[categories] child process exited with code 25
> Categories fix

- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Tags.pm
- t/additives_tags.t
- t/allergens_tags.t
- t/ingredients_analysis.t
- t/ingredients_processing.t
- t/tags.t
- taxonomies/amino_acids.txt
- taxonomies/ingredients.result.txt
- taxonomies/ingredients.txt
We have been historically quite aggressive when matching tags: if it did not match in the target language, we tried in some other languages. The risk of false positives was low, but as we have now very extended taxonomies, the risk of false positives is higher (and it is less useful because our data is cleaner).
This issue is to introduce stricter rules, so that we specify which site tries which language for only a very limited set of taxonomies:
"la" is Latin, it's quite useful for species in ingredients, and the mysterious "aqua" ingredient in beauty products :)
```perl
if ($options{product_type} eq "food") {
if ($tagtype eq "ingredients") {
@test_languages = ("la");
}
elsif ($tagtype eq "additives") {
@test_languages = ("en");
}				
}
elsif ($options{product_type} eq "beauty") {
if …
```
> restrict cross language tag matching, fixes #3626

- lib/ProductOpener/Ingredients.pm
- t/ingredients_percent.t
- Support for "some ingredient: min 10%" (previously we matched only "some ingredient: 10% min"
- Made a $percent_regexp to avoid repeating the same complex regexp 10 times
- Added some support for Spanish (e.g. "Cacao: 57% mínimo.")
> better percent parsing, fixes #3667

- cgi/product_jqm_multilingual.pl
- lib/ProductOpener/Ingredients.pm
- lib/ProductOpener/Products.pm
- lib/ProductOpener/Tags.pm
- t/tags.t
Fixed add_tags_to_field to prevent mix up of languages when all the fields added are already there.
Call compute_field_tags() directly from add_tags_to_field, only when fields have changed.
See #3675 for details.
Adding more tests to verify that the add_tags_to_field() function works correctly.
> Fix add_tags_to_field()

- lib/ProductOpener/Tags.pm
It's probably a good idea to keep matching tags in English when they don't match the local language. Fixes #3679 
Bug introduced by #3638
> always match tags in English, fixes #3679

- lib/ProductOpener/Tags.pm
- t/ingredients_tags.t
this is to match things like "E330 citric acid" and "citric acid E330" where we have both the E-number and one of the additives names / synonyms.
> match E-number + name, fixes #3694

- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
Fixes #3620 reported by @aleene 
I'll also add a prompt like "If this product has a list of ingredients in [language of the interface], you can add it by editing the product page".
> show the language of the ingredients displayed, fixes #3620

- lib/ProductOpener/ImportConvert.pm
- lib/ProductOpener/Ingredients.pm
- po/common/en.po
- t/additives.t
- t/ingredients_clean.t
Fixes #2239 
Separating ingredients cutting from cleaning is necessary because ingredients cutting needs to happen only once (just after we do OCR).
Cleaning on the other hand could be done multiple times (e.g. if we improve the cleaning).
This will make it also easier to integrate ingredients spelling. cc @raphael0202
> separate ingredients cutting from cleaning, bug #2239 (and needed for Equadis import)

- lib/ProductOpener/Display.pm
- templates/nutrient_levels.tt.html
HTML Templatization of Nutrient levels using Template::Toolkit
> Nutrient Levels Templatization

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Products.pm
- scripts/update_all_products.pl
Add a way to mark products matching a given query as obsolete using the update_all_products.pl script. Details: #3874
> add --mark-as-obsolete-since-date , fixes #3874

- scripts/packager-codes/fr-packagers-refresh.pl
Script to update FR packager codes and also the resulting CSV.
I used some modules that are not dependencies of ProductOpener for convenience:
- `Data::Table`: for tabular data processing.
- `Geo::Coder::Google`: for geocoding.
- `Future`, `Future::Utils`, `Net::Async::HTTP`, `IO::Async`: for async processing of the sections. Geocoding is awfully slow and this makes it a bit more bearable.
**Related issues and discussion:** #3852
> Refresh FR packager codes

- scripts/list_taxonomy_entries.pl
`list_taxonomy_entries.pl` - list all entries in a taxonomy that have a specific property
Usage:
`
list_taxonomy_entries.pl --type ingredients --property vegan:en=null`
-> list all ingredients that do not have a value for the vegan:en property
`list_taxonomy_entries.pl --type ingredients --property vegan:en=exists`
-> list all ingredients that have a value for the vegan:en property
`list_taxonomy_entries.pl --type ingredients --property vegan:en=yes`
-> list all ingredients that have the value "yes" for the vegan:en property
`list_taxonomy_entries.pl --type ingredients --inherited-property vegan:en=yes`
-> list all ingredients with an inherited value "yes" for the  vegan:en property
closes #3878
> new script to list / explore taxonomy properties

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- cgi/search.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Products.pm
I was a bit too aggressive in banning barcodes with less than 8 digits, we actually have some with less digits (e.g. 4 or 6) mostly used in small stores.
The barcodes now require at least 4 digits (3 digits and less cause problems in the current path structure)
> fix for short barcodes

- lib/ProductOpener/Display.pm
- templates/ingredients_analysis.tt.html
- fixed analysis icons that did not display
- moved a span + style for the icon from the perl code to the template
- moved lang() calls in the Perl code, added separator_before_lc() call
- renamed some variables
> small fixes for ingredients analysis templates

- cgi/user.pl
- templates/user_form.tt.html
HTML Templatization of User form using Template::Toolkit
> User Form Templatization

- lib/ProductOpener/Ingredients.pm
in Perl strings between "" are interpreted (e.g. escape sequences). Here we don't want to interpret them, so we need to use single quotes.
> fix regexp, remove warnings

- cgi/search.pl
- cgi/user.pl
Since $tt is now an exported variable, we don't need to initialize it separately in CGI Scripts
**Related issues and discussion:**
@stephanegigandet and @hangy suggested in PR #3897 
$tt is made an exported variable in PR #3985
> Removed template initialization from CGI Scripts

- scripts/packager-codes/es-packagers-html2csv.pl
- scripts/update_packager_codes.pl
Updated ES codes and a script to convert them.
Small change to the dataset from @teolemon: The RGSEAA Excel downloads are actually HTML files with XLS extension. Corrected the extension to avoid confusion.
[Here's the 641 rows that didn't receive coordinates](https://gist.github.com/Ban3/8f7d53361cc0b1d43687eb7381bd8877). Special prize to this "address":
``
23.004363/GC;Santana Cárdenes, Salvador; #$%;SANTA BRIGIDA;Palmas, Las;Canarias;;
``
> Refresh ES packager codes

- po/common/common.pot
Make EMB and packager codes wording more generic since "EMB codes" is French-only and "packager codes" not very explicit.
> Make EMB and packager codes wording more generic

- .gitignore
This also makes SonarCloude ignore them according to https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/#header-2
> Ignore some 3rd party dependencies from git's change detection

- lib/ProductOpener/Ingredients.pm
- t/ingredients.t
- t/ingredients_parsing.t
As a special case of a label, Finnish organic label often appears at the start of a compound word ingredient ([There's plenty of these](https://fi.openfoodfacts.org/ingredients?status=unknown&filter=luomu)). This change separates it as a separate word during preparsing so it will be properly detected later. Desired result:
`luomumaito` -> `luomu maito` -> `'id' => 'en:milk', 'labels'  => 'en:organic'`
> Preparse fi organic label from compound words

- html/js/product-multilingual.js
it looks like we updated the version of cropper.js and my guess is that it started to make cross origin checks. disabling them for now, until we find a way to fix the nginx config to send the right headers for the right requests.
Better solution will be to fix the CORS headers: https://github.com/openfoodfacts/openfoodfacts-server/issues/4073
> P1 bug fix -- Fix broken cropper, do not require cross origin check, fixes #4070

- taxonomies/languages.txt
...at least in languages where it changes the sort order.
Translations from https://www.wikidata.org/wiki/Q9129, and any short forms from the infobox on languages' own wikipedia entries for "greek language".
For https://github.com/openfoodfacts/openfoodfacts-server/issues/4070
> Changing "Modern Greek" to "Greek", fixes #4070

- taxonomies/additives.txt
- taxonomies/categories.txt
- taxonomies/ingredients.txt
More of the same, although 66f6e90 assumes that the ingredients list is _always_ used case insensitively, and doesn't need both upper and lower case versions of names.
> Taxonomy edits 6 - ingredients & additives

- scripts/import_fleurymichon.pl
Fixes #4108
calling `HTML::Entities->decode_entities` will return a list where
the first value is the class name and second is the actual return value.
**Related issues and discussion:** #4108
> fix: use HTML::Entities instead of require

- lib/ProductOpener/Store.pm
- scripts/delete_old_cropped_images.pl
- scripts/extract_images.pl
- scripts/extract_nutrition_images_and_crop_data.pl
- scripts/import_fleurymichon.pl
- scripts/import_systemeu.pl
- scripts/obsolete/import_sodebo.pl
- scripts/obsolete/remove_deleted_products_from_db.pl
- scripts/tag_stores_magasins_u.pl
- scripts/update_all_products.pl
Applying the lessons from #4109.
Change `->` to `::` to avoid passing the left hand side to the subroutine.
> Don't use method invocation where it isn't needed

- lib/ProductOpener/Ingredients.pm
- t/ingredients_parsing.t
Adds the missing final period so that the ingredient isn't split there.
> ingredients parsing: add missing '.' to 'bl. a.' abbreviation

- lib/ProductOpener/Ingredients.pm
- t/ingredients.t
Require a space after 'pur' or 'de' in the regex. Fixes #3827, #3706, #3826
**Related issues and discussion:** #3827 #3706 #3826
> ingredient parsing: don't truncate purée after percentage

- lang/pt/texts/dados.html
Dangling symlink pointing to data.en.html, which was deleted in https://github.com/openfoodfacts/openfoodfacts-server/commit/53ca24735b29a787af59e529028b40974bde83a4
> Remove dangling symlink lang/pt/texts/dados.html

- lib/ProductOpener/Display.pm
fixes #4134 
add support for queries like https://world.openfoodfacts.org/api/v0/product/8410422407028/salsa-picante-louisiana-chovi?rev=28
> support rev for product read API, #4134

- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Lang.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
For more background and details, please see #4105 and https://wiki.openfoodfacts.org/Product_Attributes
This is the start of the implementation of product attributes, that will be used by the new Flutter app and the personal search project.
This is an alpha phase. We will incrementally code and deploy the attributes. A lot of things may change as we add new attributes and use them in the new app (and possibly as a new function to personalize search results on the web site as well). To retrieve the attributes, they need to be explicitly requested (&fields=attributes_en) so it will not confuse existing apps.
Sample output:
https://fr.openfoodfacts.dev/api/v0/produit/3700214614266/chocolat-noir-perou-90-fruite-et-boise-alter-eco?fields=product_name,code,attributes_en
``````
{
product: { …
> Start of Product Attributes implementation, #4105

- lib/ProductOpener/Ingredients.pm
- t/ingredients_clean.t
Editing records, a often ingredients lists still have a bit of "nutrition..." tacked on ([example](https://uk.openfoodfacts.org/product/4771189250086/chef-tomato-ketchup)), both when OCRing and in the ingredients analysis.
This is my attempt to reduce that a bit, if I haven't completely misunderstood the code/tests.
> add terms to ignore on the end of ingredients list for english

- lib/ProductOpener/Display.pm
I made another mistake when I changed the way query parameters are parsed. This fixes it.
fixes #4163
> fix .json, fixes #4163

- lib/ProductOpener/Ingredients.pm
- t/allergens_tags.t
- t/ingredients_tags.t
Several of the top unknown ingredients for the UK are variations of these. These patterns match 1423 lines in the CSV dump.
(also a random comment from me working out how the code worked, and how "suitable for vegetarians" could be in an ingredient text but not parsed...)
Looking at the CSV, French has a similar issue ("Pour les allergènes, voir les ingrédients indiqués en gras" etc), but I'm not as familiar with the ingredient conventions. But if this PR is the right way to do this, I could have a go.
> ingredients parsing - ignore "allergy advice" in ingredients lists

- lib/ProductOpener/Lang.pm
I'm assuming the sleep is just there to make the debug message easier to read?
> performance - stop Lang.pm sleep(1)-ing every time it's loaded

- taxonomies/ingredients_processing.txt
Rearranging terms to be accented-first. 
Don't know if there's a wider issue about the parsing of accented terms in ingredients_processing.txt.
> ingredients processing - Quick fix for example in #3753

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
- t/tags.t
As part of playing with NYTProf, I discovered why unit tests took so long to run for me.
The population of %tags_texts and %tags_levels happens every time Tags.pm is loaded, and number-of-languages * number-of-tag-types = 9600 file exists checks, for variables that are only used in 3 places in Display.pm. 
This probably isn't noticeable most of the time, but I was running over a network share, where this added 39 seconds to running each unit test file...
I took inspiration from https://github.com/openfoodfacts/openfoodfacts-server/pull/2833, but may have got the perl wrong...
> performance - Make Tags.pm perform its 9600 file-exists checks on demand instead of on load

- lib/ProductOpener/Tags.pm
Building the categories taxonomy, according to NYTProf the modified code is run approx **141 million times**. (3 regexps, so approx 422 million calls.) 
Borrowing a trick from PHP optimisation, I tried replacing the regexp comparisons with builtin string functions. Sadly, perl's builtin functions are more limited, hence the clumsy "does the string end with this" test - "is the start point of the last match + the length of the needle string equal to the length of the haystack string".
For me, this change reduced the taxonomy build times to 1/5 of the original time for all the taxonomies (apart from the tiny ones, where startup time is larger).
It seems to produce identical .results.txt files (and the same complaints/errors to the console), but different but identical-size .sto files. I …
> performance - make build_tags_taxonomy() use string comparisons instead of regexps

- cgi/display.pl
- html/js/product-preferences.js
- lang/en/texts/product-preferences.html
- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
New APIs to retrieve possible values for preferences and all supported product attributes
- https://fr.openfoodfacts.dev/api/v0/preferences
- https://fr.openfoodfacts.dev/api/v0/attribute_groups
New user interface to set preferences that are saved using localstorage in the browser:
- https://world.openfoodfacts.dev/product-preferences
One drawback of localstorage is that it is subdomain specific (but that should not be an issue for most users).
This is just a start, hopefully someone can make a nicer looking UI etc.
> Personal Search - Selection and local storage of user product preferences, #4119

- lib/ProductOpener/Tags.pm
so that it can be called from Display.pm without prefixing with ProductOpener::Tags::
Otherwise we get an error when accessing a product page:
Software error:
Undefined subroutine &ProductOpener::Display::init_tags_texts_levels called at /srv/off/lib/ProductOpener/Display.pm line 7549.
> declare &init_tags_texts_levels

- lib/ProductOpener/Ingredients.pm
- t/allergens_tags.t
- t/ingredients_tags.t
See #4161.
Simpler patterns, as there are fewer instances. Probably mostly from english-language products translated into french? (e.g. M&S)
> ingredients parsing - ignore french "allergy advice" in ingredients lists

- lib/ProductOpener/Ingredients.pm
"Use of uninitialized value in concatenation (.) or string at /home/runner/work/openfoodfacts-server/openfoodfacts-server/lib/ProductOpener/Ingredients.pm line 4764."
Caused by $product_ref->{$field} being undefined.
> Ingredients.pm - try to silence a repeated warning in unit tests

- lib/ProductOpener/Tags.pm
Improvement for #4198, until someone decides the best way to handle those lines.
> Building Taxonomies - log the fact we're discarding lines, rather than just causing an unhelpful perl warning.

- taxonomies/categories.txt
I simply changed the word "Flammkueche" (which isn't a German word" to "Flammkuchen".
> Fixed spelling for German Flammkuchen

- cgi/suggest.pl
There's no need for the browser to fetch the same data over and over for tags that only change occasionally.
vs
> Add HTTP caching header to suggest.pl

- lib/ProductOpener/Food.pm
- lib/ProductOpener/Tags.pm
- lib/startup_apache2.pl
The variables packager_codes and geocode_addresses are only used from within functions in Display.pm, not top level code that runs during BEGIN, and in cgi/ & scripts/ code that will only use them on executing anyway.
For one thing, this shaves approx 1 second off syntax checking each script in the pull request workflow, and there are 150 scripts...
(Usual perl-n00b caveat applies, I'm getting my understanding from https://perldoc.perl.org/perlmod.html#BEGIN%2c-UNITCHECK%2c-CHECK%2c-INIT-and-END )
Neither of the variables are referenced directly in any unit tests, but they're loaded conditionally anyway.
```
if (-e "$data_root/packager-codes/packager_codes.sto") {
```
The other big chunk of Storable::* is the loop of ``` retrieve_tags_taxonomy($taxonomyid); ``` in Tags.pm, but it …
> performance - Move two Storable loads from BEGIN to INIT phase, to speed up syntax check

- lib/ProductOpener/Ingredients.pm
- t/ingredients_processing.t
- t/ingredients_tags.t
Currently only the synonyms for a single process are in sorted order, but the whole array for a language is not. I bumped into this while enabling processing for the Nordic languages and couldn't match `fi:jauhettu` because `fi:jauhe` appeared before it.
I removed other `sort`s from the subroutine because I couldn't see the point in sorting the canonical tags or the languages.
> Sort processing regexes by length

- .gitignore
- lib/ProductOpener/Ingredients.pm
- scripts/update_all_products.pl
Some low-hanging-fruit in avoiding looping over CORE:regcomp. It feels like there's more to squeeze out, but I don't know the data structures well enough. It's also hard to compare like with like, if you let the code actually update the stored data.
A section that still has slow regexes looped over a lot is the
```
($new_ingredient =~ /(^($regexp)\b|\b($regexp)$)/i)
($new_ingredient =~ /($regexp)$/i) )
($new_ingredient =~ /(^($regexp)|($regexp)$)/i)
```
expressions in: 
https://github.com/svensven/openfoodfacts-server/blob/01235cb7d8e77b7d62e44efba8528898e828ba19/lib/ProductOpener/Ingredients.pm#L1245-L1263
Also, preparse_ingredients_text() is called twice, presumably with the same inputs:
```
```
from update_all_products.pl:
```
extract_ingredients_from_text($product_ref); …
```
> performance improvements for scripts/update_all_products.pl

- templates/display_new.tt.html
This is an incorrect escape sequence, that was carried over from the Perl source, but is not require in `Template::Toolkit`. It causes issues with Google's structured data and search. (See Google Search Console.)
> Remove incorrect escape sequence

- gulpfile.js
When the SVG gets inlined, search engines actually index this, so that search keys like "IcoFont Icons" are uselessly used for all OFF pages.
> Remove title and metadata from SVGs

- lib/ProductOpener/Display.pm
Finding synonyms of each term was using the wrong key to look up entries in the hash, thus not finding any, and the Translate link is populated with the list of synonyms.
Although now it's ugly, because the first shown synonym is the term itself. I'm not sure what the correct behaviour is re link and synonyms:
> fix google translate link in taxonomy translation page - for #4004

- lib/ProductOpener/Ingredients.pm
- t/ingredients_nesting.t
extend the workaround fix for "carbonate de magnésium, fer élémentaire" to unnaccented "CARBONATE DE MAGNESIUM, FER ELEMENTAIRE"  (bug #3838)
> do not add carbonate to FER ELEMENTAIRE #3838

- t/additives.t
- t/allergens.t
- t/food.t
- t/import.t
- t/ingredients.t
- t/ingredients_clean.t
- t/ingredients_nesting.t
- t/ingredients_nutriscore.t
- t/ingredients_parsing.t
- t/ingredients_parsing_todo.t
- t/ingredients_percent.t
- t/ingredients_processing.t
- t/ingredients_tags.t
- t/lang.t
- t/tags.t
- t/vitamins.t
The testing process should allow TODO tests to fail without complaining, but they're a way to track known issues, and see if they get fixed in the process of doing something else.
https://perldoc.perl.org/Test/More.html#*TODO%3a-BLOCK*
Also normalised the leading whitespace in the test files to be the tabs .editorconfig says they should be. 
(We could probably lose the first level or two of indentation, as in some other test files, but I thought I'd at least start out trying to be Correct.)
> Experimentally add some TODO tests

- taxonomies/categories.txt
Renamed German category to 'Müsli', this is the word everyone in Germany uses, see https://de.wikipedia.org/wiki/M%C3%BCsli
> Renamed German category to 'Müsli'

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Food.pm
- scripts/gen_top_tags_per_country.pl
I tried running this script with both a 10k and 100k limit on what it queries from mongodb, and either way, it seems to spend a large chunk of its time on generating "Use of uninitialized value" warnings. Maybe those are down to not having the full dataset from mongodb, I don't know. The 10k run generated 262MB of stderr output.
```
1000086  Use of uninitialized value in numeric comparison (<=>) at scripts/gen_top_tags_per_country.pl line 710.
555391  Use of uninitialized value in addition (+) at scripts/gen_top_tags_per_country.pl line 490.
193331  Use of uninitialized value in numeric comparison (<=>) at scripts/gen_top_tags_per_country.pl line 854.
1320  Use of uninitialized value $value in string ne at /opt/product-opener/lib/ProductOpener/Display.pm line 8581.
1320  Use of …
```
> performance - gen_top_tags_per_country.pl

- cgi/display.pl
- html/js/product-preferences.js
- html/js/product-search.js
- lang/en/texts/product-preferences.html
- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
- scss/_off.scss
- templates/search_and_display_products.tt.html
- templates/search_results.tt.html
- Displays warnings and descriptions for attributes in the user preferences selection UI
- Creates a new /search endpoint for the new search API (with a dedicated display_search_results() function instead of abusing the display_tag() function
- Solves small issues for pagination
- Start of the /search?user_preferences=1 interface to have the client request search results from the API, and ranking, filtering and displaying on the client. #4121
> New /search endpoint + start of local display of results for personal search

- lib/ProductOpener/Display.pm
- scripts/gen_top_tags_per_country.pl
As pointed out by @svensven in https://github.com/openfoodfacts/openfoodfacts-server/pull/4258#issuecomment-699492604, `products_p` is not defined in the gettext catalog. Switch references to it to the actually defined `products`.
Also, noticed that `$series_n{$seriesid}` can be undefined when using nutrition grade colors for a graph and the grade has 0 products. Initialize it to 0 before interpolating it.
> Fix use of undefined translation

- lib/ProductOpener/ImportConvert.pm
- lib/ProductOpener/Producers.pm
- lib/ProductOpener/Products.pm
- lib/ProductOpener/Tags.pm
- t/additives.t
- t/food.t
- t/import.t
- t/products.t
- t/tags.t
There are still 2 uses of a "test" taxonomy in tags.t that cause
> Use of uninitialized value $path in concatenation (.) or string at /home/runner/work/openfoodfacts-server/openfoodfacts-server/lib/ProductOpener/Tags.pm line 2171.
Dunno if that's an intentional test of a bogus taxonomy, as the test expects the incorrect URL it gets.
> clear most of the warnings on the unit tests

- scripts/export_database.pl
A quick workaround, re #3857.
Although if the script just dies part way through, this won't really help.
(The assumption being that the data set will only ever grow, even with occasional deletions. Manually deleting the old dump should cause the new dump to be used regardless.)
> export_database.pl - only overwrite previous export if the new one is bigger

- .github/workflows/pull_request.yml
- cpanfile
- docker/backend/Dockerfile
This is an attempt to speed up the pull request workflow (and building the backend docker image) by installing as many of the perl cpan dependencies from apt instead of through cpanm, because it's much faster.
The risk is that apt often has slightly older packages, especially on the Ubuntu 18.04 LTS image the pull request workflow uses, as opposed to the Debian Buster the docker image uses. (Some that were _really_ out of date, i didn't bother to add.)
However, if cpanfile specifies a version number, or the perl module itself specifies a version number in its dependencies, cpanm will download a newer version of the package from cpan, even if it's also installed through apt. I'm _assuming_ perl uses the newest installed version of a module if there's more than one.
AFAICT, this shaves 1-2 …
> Perl modules from apt

- scripts/refresh_taxonomies.js
Lately the taxonomy build script has been sporadically exiting with a null exitcode. This change logs the received signal when the exit code is null for more information about the failure.
I suspect it's getting killed with SIGKILL from the oomkiller, and it's probably something that should be taken into account when waiting for the spawned processes to exit.
> Capture signal when refreshing taxonomies

- lib/ProductOpener/Food.pm
- lib/ProductOpener/Numbers.pm
- t/numbers.t
New convert_string_to_number function so that we avoid replacing comma by a dot in many places while forgetting that some numbers may be formatted differently.
This function is not perfect, we may very well find examples where it doesn't work (e.g. numbers in India). It is designed to work for numbers that we actually see on product labels, not any possible number in any possible language and numbering convention.
So it's more an improvement on what we have today, that we may need to improve again in the future (but at least we have a defined place to improve it).
> new convert_string_to_number function, fixes #4312

- lib/startup_apache2.pl
currently, if one of the data load functions errors out, it doesn't show up in the modperl_error_log.
I had to find `/var/lib/docker/overlay2/adffa9fb9f296d41361990c3b653a8acb26d1f9d0c0ef79f3b0c1d29ee452fa4/diff/var/log/apache2/error.log` to find out why apache wasn't starting.
> startup_apache2.pl - setup error log before running code

- docker/backend-dev/conf/po-foreground.sh
load_agribalyse_data() in startup_apache2.pl was failing:
> Could not open agribalyse CSV /mnt/podata/ecoscore/agribalyse/AGRIBALYSE3.0.1_vf.csv.2: No such file or directory at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 120.\nCompilation failed in require at (eval 2) line 1.\n
> po-foreground.sh - add ecoscore folder into dev docker

- scripts/gen_top_tags_per_country.pl
fixes #4321
also removed old code that created countries.html and product_countries.html that are not used anymore (replaced by the countries facet)
> fix world category stats, remove code to create now unused texts

- lib/ProductOpener/Ingredients.pm
- lib/ProductOpener/Store.pm
After [learning about tr/// the other day](https://github.com/openfoodfacts/openfoodfacts-server/pull/4316#discussion_r499659223), this seemed like a good candidate, _assuming I'm understanding how it works correctly_.
For a test of 1500ish records, it went from 13.4s to approx 3s for 644k calls.
> ![image](https://user-images.githubusercontent.com/5736616/95516977-0ce68b00-09b8-11eb-9161-e745806e97c1.png)
vs
> ![image](https://user-images.githubusercontent.com/5736616/95517060-32739480-09b8-11eb-99cb-84ff05d0669f.png)
This is called twice with the same inputs for each product. 
> ![image](https://user-images.githubusercontent.com/5736616/95517479-fb51b300-09b8-11eb-9a7e-79ef5340ee8e.png)
Adding a simple cache using state variables means we can return immediately on the 2nd invocation, as …
> more performance tweaks for update_all_products.pl

- .github/workflows/pull_request.yml
- scripts/check_perl.js
Adapted from the refresh_taxonomies.js script.
The syntax checking is slow (5-6 mins on github), but checking over 100 scripts simultaneously is also unworkable:
https://github.com/openfoodfacts/openfoodfacts-server/pull/3368
The limit is configurable, in case the environment running the checks ever has more than the 2 cores it currently does. Increasing the limit on 2 cores works (at least with 3 & 4), but is no faster.
Should shave another 2-3 mins off the pull request workflow.
Update: With the changed files workflow plugin, it removes the whole 5-6 mins.
> perl syntax checking in parallel, but limit the number of processes.

- scripts/refresh_taxonomies.js
Applying the same quick fix as in #4328. See https://github.com/openfoodfacts/openfoodfacts-server/pull/4328#discussion_r501245467
After the previous change, this Travis run now logs that one of the processes had been SIGKILLed, but the script still counted it as running. https://travis-ci.org/github/openfoodfacts/openfoodfacts-server/builds/733734997
> [additives] child process exited with signal SIGKILL
> refresh_taxonomies.js - handle signals & limit parallelism (for Travis)

- .github/workflows/pull_request.yml
- package.json
Github/Travis VMs have 2 CPUs, so we can run 2 tests at once.
Should shave 1-2 more mins off the pull request workflow.
> Run unit tests in parallel

- html/images/icons/contains-palm-oil.svg
- html/images/icons/ecoscore-a.svg
- html/images/icons/ecoscore-b.svg
- html/images/icons/ecoscore-c.svg
- html/images/icons/ecoscore-d.svg
- html/images/icons/ecoscore-e.svg
- html/images/icons/may-contain-palm-oil.svg
- html/images/icons/maybe-vegan.svg
- html/images/icons/maybe-vegetarian.svg
- html/images/icons/non-vegan.svg
- html/images/icons/non-vegetarian.svg
- html/images/icons/palm-oil-content-unknown.svg
- html/images/icons/palm-oil-free.svg
- html/images/icons/vegan-status-unknown.svg
- html/images/icons/vegan.svg
- html/images/icons/vegetarian-status-unknown.svg
- html/images/icons/vegetarian.svg
- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Config_off.pm
This adds attributes for vegan, vegetarian and palm oil. The attributes can then be used to rank products according to user defined preferences.
Related issues: #4105 #4266
e.g.
``````
{
attributes: [
{
icon_url: "https://static.openfoodfacts.dev/images/icons/non-vegan.svg",
title: "Non végétalien",
status: "known",
setting_name: "Végétalien",
match: 0,
id: "vegan",
name: "Végétalien"
},
{
icon_url: "https://static.openfoodfacts.dev/images/icons/vegatarian-status-unknown.svg",
title: "en:vegatarian-status-unknown",
status: "unknown",
match: null,
id: "vegatarian"
},
{
match: null,
id: "palm_oil_free",
icon_url: "https://static.openfoodfacts.dev/images/icons/palm-oil-content-unknown.svg",
status: "unknown",
title: "Présence d'huile de palme inconnue"
}
],
name: "",
id: …
> added ingredients analysis attributes: vegan, vegetarian, palm oil free #4105 #4266

- lib/ProductOpener/Display.pm
See #4292. This is so that the OFF app (or other apps) can request a field like images_to_update_en to know which images should be taken or re-taken (because they are too old, or possibly too small / blurry) by users.
https://fr.openfoodfacts.dev/api/v0/produit/3483130043180/beurre-cru-a-la-baratte-les-petites-laiteries?fields=images_to_update_fr
It returns a hash of image types + language code (only for the requested language code -> the language of the app user). The value is 0 for images we don't have, or the age of the image (in seconds) for apps that want to add some context like "Our photo of the ingredients is 14 months old, could you take a new one?".
```````
product: {
images_to_update_fr: {
packaging_fr: 0,
front_fr: 83734290,
ingredients_fr: 83734290
}
},
> Read API: new images_to_update_[lc] field, fixes #4292

- cgi/user.pl
This is to allow to create links to change the logged in user profile without putting the userid explicitly in the link.
In particular, we can create links for moderators of the producers platform of the form
https://fr.pro.openfoodfacts.dev/cgi/user.pl?action=process&type=edit_owner&pro_moderator_owner=org-carrefour-espana
to change the org to org-carrefour-espana
> default userid for logged in users

- html/js/product-multilingual.js
- set data-language when adding a language, to allow power user script ingredient analysis to work on new languages without saving and reloading.
- handle failures in ajax post requests. currently, when the server's timing out, the page will hide buttons and just sit in an "in progress" state, needing a refresh to work again.
> Handle edit page ajax failures

- lib/ProductOpener/Tags.pm
- po/common/en.po
- po/common/fr.po
- po/tags/en.po
- po/tags/tags.pot
This facet will be useful for admins of the producers platform, so that they can see products from the different producers.
It is to be used in combination with the "all" owner that allows admins to see all products of all owners.
Here is how it looks like on the test server:
> create owners facet (for producers platform administration)

- docker/backend-dev/conf/Config.pm
- docker/backend-dev/conf/Config2.pm
- docker/productopener/templates/backend-conf.yaml
- lib/ProductOpener/Config2_sample.pm
- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Data.pm
- scripts/update_all_products.pl
The default timeout for waiting for mongodb to respond is 30s, after which the script will die with a socket error.
https://metacpan.org/pod/MongoDB::MongoClient#socket_timeout_ms
Long running scripts may want to wait a bit longer, in case mongodb is just temporarily overloaded.
Also `get_database()` was hard-coded to `$mongodb`, despite being called with a parameter in `get_collection()`.
There's an argument for increasing the default to 50s or something, given nginx will timeout after 60s.
(I may have got my `$`/`%`/`@`s confused, but it _seems_ to work in my docker instance.)
I thought about passing in a general options hash, and then forcibly setting any options like `host`, but got scared off by https://perldoc.perl.org/perlsub#Pass-by-Reference, and also I'm not sure there are any …
> Add ability to pass a wait timeout to the mongodb connection

- html/images/icons/0-additives.svg
- html/images/icons/1-additives.svg
- html/images/icons/10-additives.svg
- html/images/icons/2-additives.svg
- html/images/icons/3-additives.svg
- html/images/icons/4-additives.svg
- html/images/icons/5-additives.svg
- html/images/icons/6-additives.svg
- html/images/icons/7-additives.svg
- html/images/icons/8-additives.svg
- html/images/icons/9-additives.svg
- html/js/product-preferences.js
- html/js/product-search.js
- icons/food-cog.svg
- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Config_off.pm
- po/common/common.pot
- po/common/en.po
The icons help to make the radio buttons less frightening. The next step will be to use input range with steps to have a slider instead of the buttons.
I was trying to add an accordion but couldn't get it to work with our old version of Foundation (it's supposed to work though). It has to do with the fact that the accordion is dynamically created. But in fact I kind of like to have all options shown without having to click multiple times on the accordion so I guess I'll leave it like that. :)
To test:
https://world.openfoodfacts.dev/search?user_preferences=1&categories_tags_en=sausages&labels_tags=en:organic&fields=product_name,ecoscore_data,images#attribute_group_processing_a
(login and pass : off )
> Icons, accordion and styling for user food preferences

- html/js/display.js
adding undefined worldresult breaks searching for a country.
> display.js - fix searching in country dropdown

- html/js/product-preferences.js
- html/js/product-search.js
- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
This is a start to personalize (and later redesign) the product page (see #4391 )
What it does is to display some colored boxes on top of the individual product page to show the information that users have selected to be important.
Users can edit their preferences on page, and see the changes right away without reloading the page.
Those are the default preferences:
Of course the more preferences are selected, the more crowded it can get at the top:
> Display "at a glance" attributes on top of product page based on user preferences

- lib/ProductOpener/Ingredients.pm
- t/allergens.t
The cause for the bug was that as we now recognize "0" as "no allergens", 0 is also matched when looking for allergens in ingredients.
fixes #4365
> fixes #4365, allergen 0%

- cgi/product_multilingual.pl
- lib/ProductOpener/Food.pm
- scss/_off.scss
* fixes #4377 : the mg value is preferred as the FDA changes the reference values for %DV
* display the unit as mcg/µg instead of just µg (US labels show "mcg")
> new US labels: use mg instead of %DV, #4377

- cgi/user.pl
This is for URLs like https://world.pro.openfoodfacts.dev/cgi/user.pl?action=process&type=edit_owner&pro_moderator_owner=org-some-org that moderators of the producers platform can use to see the products of a specific organization. There was a permanent redirect to / after the update, which means nginx would bypass the cgi entirely after the first time.
> temporary redirect instead of permanent

- t/expected_test_results/ingredients/en-flavour-synonyms.json
- t/expected_test_results/ingredients/fi-additive.json
- t/expected_test_results/ingredients/fi-additives-origins.json
- t/expected_test_results/ingredients/fi-additives-percents.json
- t/expected_test_results/ingredients/fi-do-not-match-myanmar.json
- t/expected_test_results/ingredients/fi-labels.json
- t/expected_test_results/ingredients/fi-organic-label-part-of-ingredient.json
- t/expected_test_results/ingredients/fi-origins.json
- t/expected_test_results/ingredients/fi-percents.json
- t/expected_test_results/ingredients/fr-additive.json
- t/expected_test_results/ingredients/fr-chocolate-cake.json
- t/expected_test_results/ingredients/fr-label-and-multiple-origins.json
- t/expected_test_results/ingredients/fr-labels.json
- t/expected_test_results/ingredients/fr-marmelade.json
- t/expected_test_results/ingredients/fr-origins-labels.json
- t/expected_test_results/ingredients/fr-palm-kernel-fat.json
- t/expected_test_results/ingredients/fr-percents-origins-2.json
- t/expected_test_results/ingredients/fr-percents-origins.json
- t/expected_test_results/ingredients/fr-percents.json
- t/expected_test_results/ingredients/fr-processing-multi.json
- t/expected_test_results/ingredients/fr-starred-label.json
- t/expected_test_results/ingredients/fr-truncated-puree.json
- t/expected_test_results/ingredients/fr-vegetal-origin.json
- t/expected_test_results/ingredients/label-and-multiple-origins.json
- t/expected_test_results/ingredients/single-letters.json
- t/expected_test_results/ingredients/xx-single-letters.json
- t/ingredients.t
A lot of the test files like ingredients.t have a simple input product, on which we run functions like processing ingredients.
The expected test result is inside the ingredients.t file which makes it very big, and also very difficult to update when the expected results change.
For instance, I'm implementing #4423 which is going to add a new "percent_estimate" to all ingredients and sub ingredients, and that will make all tests fail. Updating them is a very lengthy and error prone process with a lot of copy and paste.
So I'm refactoring the tests so that each test result is saved in an individual JSON file. When the tests run, the actual results are also saved as JSON files in a separate directory. So to see and update the diffs, we can just copy the output files over the expected files, …
> refactor ingredient.t - move expected test results to JSON files

- t/ecoscore.t
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/unknown-category.json
This is the same refactoring as the one I did for ingredients: the expected test results are now stored in files outside the test file, so that they can easily be updated.
This allows also to test all Eco-Score values (computations details etc.) and not just the final score, which makes it easier to see what changed if we get different results.
It is also very useful for updates as I'm adding components of the Eco-Score computation one by one, and some parts of all existing expected test results are going to change for each new component added.
> convert Eco-Score tests to new system

- html/js/product-preferences.js
- html/js/product-search.js
- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
This enables displaying the attributes that correspond to user preferences on top of product pages.
The feature is quite new and will need polishing, so it will be enabled only for moderators for now. (if you are not a moderator yet, let me know your OFF username so that I can add you)
> Display attributes on top of product page (for moderators for now), i18n + small visual changes

- t/expected_test_results/ingredients/fr-origins-agriculture-ue-non-ue.json
- t/ingredients.t
- taxonomies/origins.result.txt
- taxonomies/origins.txt
- added "agriculture" as a stopword (often found in phrases like "agriculture France").
- added a few more regions (the most represented on https://fr.openfoodfacts.org/origines?status=unknown )
> A few more French regional origins

- po/common/ko.po
- po/common/nl_BE.po
- po/common/nl_NL.po
- po/common/ru.po
- po/common/tr.po
- t/i18n.t
Noticed mismatched A tags on the turkish site, turning everything after them into a link.
Also the slack channel name was translated, despite the comment saying not to.
Added tests to prevent recurrence, which showed up 2 more errors. Fixed on crowdin too.
Update: Added test to check _all_ A tags are matched, and consequently found another error.
> Fix translations breaking html & translating slack channel name

- .github/workflows/translation-check.yml
- po/common/common.pot
This is a standard action that executes a classic GetText command `msgfmt "$filename"`. We can tweak the arguments of the command to be more or less aggressive.
https://www.gnu.org/software/gettext/manual/html_node/msgfmt-Invocation.html
Already it has flagged many double strings definitions, and possibly false positive in the Crowdin LOL locale.
I'd very much like to add PoFilter, which I've used over the years:
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/guides/using_pofilter.html
http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/index.html#commands-quality-assurance
Occurence 1:
https://github.com/openfoodfacts/openfoodfacts-server/blob/master/po/common/th.po#L4117
Occurence 2: …
> Perform GetText checks on all translation files

- html/js/product-preferences.js
- html/js/product-search.js
- scss/_off.scss
- scss/_settings.scss
- templates/display_new.tt.html
This is currently only for the new /search endpoint, to test personal search.
Each product is shown on a card with the photo + name, as well as small icons for the attributes that correspond to selected user preferences.
The background of the card is green, red or grey, depending on whether the product matches the user preferences.
Once we finalize this display, the goal is to make it the display for facets as well, not just search results.
With a lot of attributes selected:
"normal" usage would have much less attributes selected. By default it would be Nutri-Score + NOVA + Eco-score.
> Display search results with cards using user preferences

- html/js/product-search.js
- lib/ProductOpener/Display.pm
As we changed how we parse query parameters, the sort key was not properly passed to Mongo for the search API v2.
Also changed the client-side ranking code so that we keep the original sort order of results when no preferences are set at all.
> Fix search sort key for search API v2

- .github/workflows/containerimage.yml
- .github/workflows/pull_request.yml
see https://github.com/actions/checkout/blob/main/CHANGELOG.md.
the other workflows are already using v2.
for one thing it's a tiny bit faster, because of:
>Improved fetch performance
>    The default behavior now fetches only the SHA being checked-out
> update github workflows using checkout@v1 to v2

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Ecoscore.pm
- lib/ProductOpener/Packaging.pm
- po/common/common.pot
- po/common/en.po
- scripts/update_all_products.pl
- t/ecoscore.t
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/packaging/packaging_text_en_plastic_bottle.json
- t/expected_test_results/packaging/packaging_text_en_plurals.json
- t/expected_test_results/packaging/packaging_text_en_quantity_1_l_plastic_bottles.json
- t/expected_test_results/packaging/packaging_text_en_quantity_25_cl_bottles.json
- t/expected_test_results/packaging/packaging_text_en_quantity_6_plastic_bottles.json
- t/expected_test_results/packaging/packaging_text_fr_quantity_6_bouteilles_plastiques_de_25_cl.json
- t/packaging.t
- templates/display_product.tt.html
This continues the work to extract and structure packaging data outlined in https://wiki.openfoodfacts.org/Packagings_data_structure
- The number of units of a packaging component is now extracted (e.g. "6 bottles")
- The quantity contained (volume or weight) is now extracted (e.g. "25 cl plastic bottles")
- The product page now displays a table that indicates the packaging components that have been extracted
Here what it looks like (the packagings data is extracted from the French packagings text, and displayed in the language of the interface (here English)):
> Better packaging parsing (quantity contained and number of units) and display #219

- lib/ProductOpener/DataQualityCommon.pm
This adds some simple quality facets for packagings data. (#4501) 
In particular, we need to know which products do not have complete packaging data.
In order to determine if the packaging data is complete, we can test the extracted packagings data structure: if all packaging components are complete (they have a number of units, a shape and a material), then we know that a contributor edited the product and added the number of units (e.g. 1 PET plastic bottle), and hopefully made sure all components are listed.
In the future, we could introduce more facets (e.g. for "1 plastic bottle", it would be helpful to add the type of plastic).
> add quality tests for packaging data

- lib/ProductOpener/Display.pm
the Eco-score is currently not publicly deployed, and only available to moderators on the web site and alpha testers of the Open Food Facts app
Until the public launch of the Eco-score, we will disable ecoscore fields in the API, except if the app is also asking for the ecoscore_alpha field (which can be turned on by the app with a specific parameter)
That way we can deploy an "Eco-score ready" app that asks for ecoscore fields, and once we turn it on on the server, the app will start to display the Eco-score instantly, without having to deploy an updated app.
Currently live on the dev server:
https://fr.openfoodfacts.dev/api/v0/produit/26003887/carottes-1kg-cat-1-la-madrague?fields=product_name,ecoscore_grade,ecoscore_data
https://fr.openfoodfacts.dev/api/v0/produit/26003887/carottes-1kg- …
> server option to turn on ecoscore + ecoscore_alpha override

- html/images/icons/match-no.svg
- html/images/icons/match-unknown.svg
- html/images/icons/match-yes.svg
- html/js/product-search.js
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
- scss/_off.scss
- templates/search_and_display_products.tt.html
- templates/search_results.tt.html
This makes the new products cards view the default (only for moderators at this point) for facets pages and search results.
Currently live on the dev server, product images not shown because their are not on the dev server)
In practice the search results are still generated as HTML, but also added as JSON data so that they can be displayed with cards. (that way we still display results when javascript is OFF, and search engines can continue to easily index them).
This is only for moderators so that we can use it, see how well it works in practice (for regular users but also for contributors).
Some caveats:
1. The ranking according to user preferences only applies to the results loaded on the page. (I changed the number of results per page from 20 to 24 so that we have full rows for all …
> Personal search - Enable user preferences for facets pages and search results

- scss/_off.scss
On my screen the button icons are so small (13x13) that it's very hard to see what they are. 
Before:
After:
> bigger button icons, fixes #4494

- lib/ProductOpener/Display.pm
- templates/display_new.tt.html
fixes #4528
this adds a class to the body tag, e.g. <body about="/produit/26018423/farine-de-ble-bio-type-65-bon-et-bio" typeof="food:foodProduct" class="product_page">
> add class for page type, fixes #4528

- lib/ProductOpener/Ecoscore.pm
- lib/ProductOpener/Packaging.pm
- lib/ProductOpener/Tags.pm
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-shape-sepcific-materials.json
- t/expected_test_results/packaging/packaging_text_en_biobased.json
- t/expected_test_results/packaging/packaging_text_fr_biosource.json
- templates/ecoscore_details.tt.html
- better Ecoscore details on product page
- support for shape specific materials (e.g. "PET bottle" is more recyclable than "PET")
- better parsing of packaging (extended synonyms)
> Ecoscore & packaging fixes / improvements

- lib/ProductOpener/Import.pm
- scripts/equadis-import/dereference.sh
- new packaging fields (mostly ignored for now, it's not clear what they refer to)
- change to import script needed to reupload images when we remove all products from the producers platform (e.g. when testing an import)
> small fixes for Ferrero import

- templates/ecoscore_details.tt.html
small change to display which label (e.g. organic, fair trade etc.) triggered a production system bonus
> add production system label to Eco-score template

- cgi/export_products.pl
- lib/ProductOpener/Import.pm
- lib/ProductOpener/Producers.pm
- lib/ProductOpener/Products.pm
- po/common/common.pot
- po/common/en.po
- scripts/minion_producers.pl
- scripts/minion_producers_test.pl
- templates/export_products.tt.html
This will be used on the producers platform to display information about which products have changes that have not been exported to the public database, and also allow exporting only such products.
> keep track of exported products, bug #4560

- scripts/update_all_products_revisions_from_dir_in_mongodb.pl
This script is to import all revisions of all products (and not only the last revision) in a MongoDB collection.
The _id of each revision is "[code].[rev]".
This is for a student project where students will look at the history of changes (by users, by products etc.).
It does not use the ProductOpener modules so that it can be used more easily, just with a dump of all the .sto files for the products revisions.
> script to import all products revisions in mongodb

- po/common/common.pot
Correct invalid pot file. Such mistakes would not happen every time if the files were compiled with poedit or checked with translatetoolkit.
msgctxt "list_of_sources"
msgid "Some of the data for this product has been collected in collaboration with %s"	msgid "Some of the data and/or photos for this product come from those sources:"
msgstr "Some of the data for this product has been collected in collaboration with %s"	msgstr "Some of the data and/or photos for this product come from those sources:"
> Correct invalid pot file

- lib/ProductOpener/Tags.pm
- t/tags.t
- taxonomies/ingredients.result.txt
When taxonomies are built, synonyms are pre-generated for all entries.
For ingredients and additives, I had limited it to one pass, as it took a lot of time.
e.g. "zumo de soja" generates "zumo de soya" and "jugo de soja".
If we add one more pass, we also get "jugo de soya".
In the mean time, @svensven made a lot of performance improvements that resulted in much faster taxonomy builds. So I think we could enable 2 passes again.
It took 8 minutes to build the ingredients taxonomies on the dev server.
Related: https://github.com/openfoodfacts/openfoodfacts-server/pull/4622
> enable 2 pass synonyms for ingredients and additives taxonomies

- t/additives_tags.t
- taxonomies/additives.txt
- taxonomies/ingredients.result.txt
- taxonomies/ingredients.txt
When caramel is used not only to color, but also to give a taste, it is not considered to be an additive (even though it is the same substance than E150a).
> aromatic caramel should not be recognized as additive E150a

- po/common/common.pot
- po/common/en.po
This is a string needed when displaying the food preferences form, the id was wrong so it wasn't used.
> fix id for attribute_group_ingredients_analysis_name

- scripts/generate_dump_for_offline_apps_off.py
fix export for Nutri-Score rename
> fix export for Nutri-Score rename

- lib/ProductOpener/DataQualityFood.pm
- lib/ProductOpener/Ecoscore.pm
- t/dataqualityfood.t
- t/ecoscore.t
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- t/expected_test_results/ecoscore/unknown-category.json
- taxonomies/origins.result.txt
- taxonomies/origins.txt
- Add an "Unspecified" entry in the origins taxonomy. That way we can add "Unspecified" in the origins of ingredients field if the origins are not specified in the label. It will be different than the "Unknown" entry which means we don't have data.
- Add a warning in the ecoscore_data structure when 100% of the origins of ingredients are "Unknown" (the warning won't be triggered if the origin is "Unspecified" or if we have at least one origin for an ingredient).
- Add a corresponding data quality warning so that we can easily identify the products with 100% unknown origins.
This will partially solve #4686 .
> Ecoscore - add Eco-Score warning when origins are 100% unknown

- lib/ProductOpener/Ecoscore.pm
- lib/ProductOpener/Packaging.pm
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-no-packaging.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- t/expected_test_results/ecoscore/unknown-category.json
- t/expected_test_results/packaging/merge_en_merge_packaging_tag_and_packaging_text_2.json
- t/expected_test_results/packaging/packaging_text_fr_unknown_shape.json
- taxonomies/packaging_materials.txt
- taxonomies/packaging_shapes.txt
When we don't have packaging information, we now count an unknown shape of an unknown material which results of a malus of -10 (the malus for packaging can range from 0 to -15). This is a much better default than a malus of 0 (which happens only for products that really do not have a packaging and are sold in bulk).
This also adds warnings in the ecoscore_data structure + associated data-quality-warnings tags.
It will also allow us to add better prompts to add data in the Eco-score details template.
> add default unknown packaging for ecoscore ° better warnings #4686

- lib/ProductOpener/Ecoscore.pm
- t/expected_test_results/ecoscore/origins-of-ingredients-empty-ingredients-specified-origin.json
If the ingredients array does not exist or is empty, consider that 100% of the ingredients are coming from the origins in the origins field.
> Ecoscore fix for products without ingredients, use origin from origins field

- lib/ProductOpener/Display.pm
- scripts/refresh_products_tags.js
or if we are on the producers platform.
This will help large queries like https://fr.openfoodfacts.org/labels made by logged in users: they will be run on the smaller products_tags collection.
> Always use smaller products_tags collection for MongoDB aggregate queries unless nocache is set

- lib/ProductOpener/Ecoscore.pm
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- t/expected_test_results/ecoscore/unknown-category.json
needs ?nocache=1 at the end of the URL, or results will be from the small product collection generated every night
en:ecoscore-computed | 58 | *
en:ecoscore-missing-data-warning | 57 | *
en:ecoscore-not-computed | 33 | *
https://mq.openfoodfacts.dev/misc?nocache=1
> add misc tags for ecoscore

- cgi/import_file_select_format.pl
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Import.pm
- lib/ProductOpener/ImportConvert.pm
- lib/ProductOpener/Producers.pm
- lib/ProductOpener/Products.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- add an abbreviated_product_name language field as a lot of producers send us the identifier that is found on receipts.
e.g.
BQ 2X75g +20%OFT.LARDON CND FUME LG
BQ 2 ESC. FINES PLT S/ATM (GAUL)
- use this field as the display field if we don't have a full non abbreviated product name
> add abbreviated_product_name field + changes for LDC import

- .github/workflows/stale.yml
Label issues with no activity for 90 days as `stale`. Does not close or comment on issues.
> ci: Label stale issues automatically

- taxonomies/categories.txt
see issue "en:Fruit sodas" category is incorrectly translated as "ru:Напитки на основе фруктов" #3892
> removed incorrect Russian translation in categories.txt

- crowdin.yml
remove press-and-blogs from translatable pages. This is superseded by press.
> remove press-and-blogs from translatable pages

- crowdin.yml
Disable translation of the "vending-machines" page since it's mostly a collections of Humorous tweets in French. 
The translations are consistently bad and we need to create similar but homegrown page for various countries.
> Disable translation of the "vending-machines" page

- lib/ProductOpener/Food.pm
fixes #4766
also add /misc tags with more details:
https://mq.openfoodfacts.dev/misc?nocache=1
> better tags for nutriscore status unknown/not-applicable, fixes #4766

- cgi/product_multilingual.pl
Suggestion from @CharlesNepote in https://github.com/openfoodfacts/openfoodfacts-server/pull/4777#issuecomment-764697968
"Small suggestion: all buttons are blue but this can lead to confusion. For example, I often click on "Save" instead of "Validate and/or resize image" because there are not far from each other (see below)... Maybe the "non-return" buttons should be different ("Save", "Erase something", "Delete product", etc.)."
> make save button green in product edit form

- scripts/minion_producers.pl
The minion processes that process imports did not load all the data needed to process packagings and the Eco-Score, and it was causing issues.
fixes #4791
> Imports - Load data needed for packaging and ecoscore, fixes #4791

- lib/ProductOpener/Ecoscore.pm
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- taxonomies/categories.result.txt
- taxonomies/categories.txt
Better agribalyse matches. In particular, we need to use the agribalyse categories that correspond to the reconstituted product (e.g. coffee with water or chocolate powder with milk)
> ecoscore fixes : orange juice, coffee/tea/chocolate

- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
The Eco-Score display was already disabled on the product pages on the web site for countries other than France, but it was still visible through the attributes if it was selected.
This change disables the Eco-Score and the forest footprint attributes unless the query or subdomain indicates France. For apps, that means API queries will not return the ecoscore in attributes, unless they are sent to fr.openfoodfacts.org or the cc parameter is set to "fr".
@aleene @VaiTon : do the OFF apps and Foodviewer use the attribute_groups field to display the Eco-Score, or they use the ecoscore_grade or ecoscore_data fields directly?
--
for logged-in users that have moderator status, the ecoscore will still be shown for all countries
> disable ecoscore for other countries than France

- .github/workflows/crowdin.yml
Probably another personal hell week in perspective…
It seems that many translations are bortched on the repo, and some are bortched on Crowdin. 
I want to avoid mutual reinfection.
> Migrate Crowdin to GitHub actions

- lib/ProductOpener/Display.pm
- Adds a new /products endpoint similar to /product, but with multiple products:
e.g.https://world.openfoodfacts.dev/products/8024884500403,3263855093192,3045320001570,3021762383344,4008400402222,3330720237255,3608580823513,3700278403936,3302747010029,3608580823490,3250391660995,3760020506605,8722700202387,3330720237330,3535800940005,20000691,3270190127512
- Adds the corresponding support in Search API V2 with the ?code=a,b,c parameter -- fixes #4399
https://world.openfoodfacts.dev/api/v2/search?code=8024884500403,3263855093192&fields=code,product_name
- As usual, adding .json is also supported, as well as passing extra parameters:
https://world.openfoodfacts.dev/products/8024884500403,3263855093192,3045320001570,3021762383344,4008400402222,3330720237255,3608580823513,3700278403936,3302747 …
> Allow displaying a list of products specified by barcodes - fixes #4399

- lib/ProductOpener/Display.pm
just to make queries work if someone passes "FR" instead of "fr"
fixes #4833
> lowercase cc and lc query parameters, fixes #4833

- cgi/export_products.pl
- cgi/remove_products.pl
- lib/ProductOpener/Display.pm
- mongodb_indexes.txt
- scripts/export_and_import_to_public_database.pl
> query owner field instead of owners_tags, fix #4827

- lib/ProductOpener/Images.pm
When images are moved, a new JSON is extracted, but we kept the old json in the old product.
fixes #1708
> delete old Cloud Vision OCR json of moved images

- lib/ProductOpener/Ecoscore.pm
- t/ecoscore.t
- t/expected_test_results/ecoscore/energy-drink.json
- t/expected_test_results/ecoscore/milk.json
- taxonomies/categories.result.txt
- taxonomies/categories.txt
- milk should be considered as a beverage for the ecoscore
- energy drinks should not an ecoscore computed
> Ecoscore fixes for milks and energy drinks

- taxonomies/additives.txt
- taxonomies/additives_classes.txt
- taxonomies/ingredients.txt
Adding more of Russian ingredients, additives and additives classes.
In the `additives.txt` file the `E-` additives are sometimes duplicated by this PR, but that's intentional.
For example, in next line:
```
ru:E322, Лецитины, е322
```
...the first `E322` starts with a latin `E`, and the second `е322` starts with a cyrillic `e`.
They have different unit codes in all encodings I worked with.
> Add more of Russian ingredients, additives and additives classes

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Export.pm
- scripts/export_csv_file.pl
fixes #4932 
- make all fields available for filtering in the Search API V2
- use the same filter parsing code than the Search API V2 for the export_csv_file.pl script
- support advanced query filters (similar to the search V2 API : products without a tag, with multiple tags, with one of many tags etc.)
- exporting data for a specific set of barcodes (from a file)
- exporting fields that are not at the root of the product structure
e.g. it's now possible to do things like this:
./export_csv_file.pl --query 'additives_tags=en:e101|en:e102' --query ecoscore_grade=exists --fields=code,ecoscore_grade,ecoscore_data.score,ecoscore_data.agribalyse.agribalyse_food_code --query-codes-from-file codes
The corresponding changes will also make it easier to do things like this through a web interface …
> Make exports more flexible, fixes #4932

- lib/ProductOpener/Ingredients.pm
- lib/ProductOpener/Tags.pm
- t/additives_tags.t
- t/ingredients_parsing.t
converts the Russian character to the latin "e" when it looks like an E-number additive.
fixes #4931 reported by @blazern
> fix: handle cyrillic e character in Russian additives names

- lib/ProductOpener/Ecoscore.pm
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-bulk.json
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- t/expected_test_results/ecoscore/unknown-category.json
- templates/ecoscore_details.tt.html
- templates/ecoscore_details_simple_html.tt.html
fixes a bug in the template and provides slightly more specific messages about what's missing (e.g. no packaging info or information that is not precise enough)
> better missing data warnings for Eco-Score (easy reviews)

- cgi/user.pl
This is to make it easier for admins to edit/delete user profiles when requested by users.
> User edit form for admins: allow passing email in userid field

- cgi/export_products.pl
- cgi/org.pl
- icons/material/publish-24px.svg
- icons/publish.svg
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Users.pm
- templates/display_product.tt.html
- templates/export_products.tt.html
- templates/org_form.tt.html
- Org edit form now has an administrator section to enable organization members to:
--  launch exports to the public platform
-- indicate that data should be exported every night (not in use yet)
-- list GS1 GLNs that should be associated to the organization (not in use yet)
- Org owners can now launch exports to the public database directly, if authorized. If not authorized, we send an email to producers admins.
- Localized the export / import / update status for the minion jobs, and display them to org owners
- Display a message on the index of the pro platform if some products have data that has not been exported yet
- Display a link to the product on the public database on product pages on the producers platform
> Producers platform improvements

- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Food.pm
- po/common/fr.po
- t/attributes.t
- t/expected_test_results/attributes/en-attributes.json
- t/expected_test_results/attributes/fr-palm-kernel-fat.json
- t/expected_test_results/attributes/fr-palm-oil-free.json
- t/expected_test_results/attributes/fr-palm-oil.json
- t/expected_test_results/attributes/fr-vegetable-oils.json
There is currently a mistmatch in the attributes_groups definition and the attributes returned on products for the palm_oil_free attribute, which makes it not work at all currently.
This fixes #5007
And it also introduce tests for attributes.
> Fix palm oil attributes, add tests

- .github/workflows/codeql-analysis.yml
`HEAD^2` is now unnecessary according to https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/671276345
> git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
The CodeQL config is now updated to match https://github.com/github/codeql-action/blob/97a70e6013beb841a16b2660ce2c5a30982128c1/README.md#usage.
> Fix warning during execution of CodeQL workflow

- taxonomies/packaging_materials.txt
Added and fixed some Portuguese translations to packaging_materials.txt
Added and fixed some Portuguese translations about packaging materials since most of them didn't exist.
Please someone just take a quick look to check if it's OK, just de code and not the translations since I'm a Portuguese native speaker. I've checked and rechecked to see if I've made some mistake like deleting other translations.
Practically it's the first time I use github and I don't understand most of it. I'm not a programmer. Sorry if I made some mistake. By the way, I didn't discuss this change first as seen in [contribution guidelines](https://github.com/openfoodfacts/openfoodfacts-server/blob/master/CONTRIBUTING.md) because I don't have …
> New Portuguese translations in packaging_materials.txt

- scripts/update_all_products_from_dir_in_mongodb.pl
The script is used to load the .sto files in MongoDB. (e.g. if we want to retrieve deleted products)
> Fix update_all_products_from_dir.pl script for producers platform

- taxonomies/packaging_shapes.txt
New Portuguese translations and a few fixes in Portuguese existing translations.
**Removed**:
> en:Mold
> fr:Moule
since they were duplicates (line 113 and line 124). Please check. Thank you.
By the way, I could also add a few translations in Brazilian Portuguese, but how should I do that?
-Add to "pt:"? Since most of the words are the same with a few exceptions.
-Add to "pt-br:" or "pt-BR:"? In this case it will have also some words used in "pt:" translation.
Example of one of those exceptions:
> pt:Carica, rolha
> pt-BR:Chapinha, rolha
But I don't see a problem using just one translation:
> pt:Carica, chapinha, rolha
I'm asking this because in Crowdin we have both Portuguese and Brazilian Portuguese translations.
> Portuguese translation in packaging_shapes.txt

- cgi/export_products.pl
- cgi/org.pl
- lib/ProductOpener/GS1.pm
- lib/ProductOpener/Import.pm
- lib/ProductOpener/Users.pm
- po/common/common.pot
- po/common/en.po
- templates/export_products.tt.html
- templates/org_form.tt.html
- Org profiles have an extra checkbox for admins to disable CodeOnline imports
- Org profiles allow admins to input a list of GLNs. The GS1 org ids (GLN) are now stored in a hash (orgs_glns.sto), and they are used to force the match of a GLN to an org during Equadis / CodeOnline imports.
- Imports to the public platform now skip products that would result in an owner change
- The export form has an extra checkbox to allow overwriting owners
- When editing an org profile, admins can now create the org profile if it does not exist yet (and they are warned that they are editing an unknown org profile)
- The side column form for admins to switch to a specific org now defaults to organizations if the entered it does not start by user- or org-. i.e. it's possible to just input "nestle-france".
> Many small improvements for the producers platform

- lib/ProductOpener/Ingredients.pm
- t/expected_test_results/ingredients/ru-russian-oil.json
- t/ingredients.t
- t/ingredients_parsing.t
- t/ingredients_tags.t
- taxonomies/ingredients.result.txt
- taxonomies/ingredients.txt
We have some ingredients parsing code for French to transform ingredients that are specified with a category + some types (e.g. vegetable oils (olive, palm and sunflower) to individual ingredients: olive vegetable oils, palm vegetable oils, sunflower vegetable oils.
This PR is to make this code more generic, so that it can be applied or adapted more easily to other languages.
I added a few examples for English and Russian (from @blazern : #5017 ).
We can add more categories and more types gradually (and more corresponding tests too).
We can also probably extend the system to more languages easily (e.g. Italian, Portuguese, Spanish). I'm not sure about the languages with compound words like Dutch, Finnish or German, but I'm guessing we can find a way.
> Make ingredients categories+types (e.g. oils (rapeseed, oil) -> rapeseed oil, olive oil) more generic

- taxonomies/categories.txt
From Rochus Wessels on Slack in #taxonomies :
The German translation of "Pickles" should be "Eingelegte Lebensmittel" (pickled food) or something like that, but not "Gurken", because that is "Cucumbers" and a lot of pickled foods are no cucumbers.
The other one is the categorization of "Liquorice" as sub-category of "Hebal teas". Liquorice teas exist, but the category is mostly used for the sweets/candies/sugary snacks and those are definitely no teas, so it would probably be better a subcategory of "Sugary snacks" and have a separate category for "Liquorice teas".
> Categories taxonomy: put liquorice under candies, fix German entry for pickles

- scripts/add_nutriscore_to_scanbot_csv.pl
This scripts adds columns to the output of scanbot.pl about the % of products that have a Nutri-Score computed.
It's been done to process already existing outputs, but for the future, we should update scanbot.pl so that it adds those columns on the fly, that would be much easier.
The script also computes some stats and prints them on STDERR:
off1:/srv/off/scripts# ./add_nutriscore_to_scanbot_csv.pl < scanbot.2020_fr/scanbot_fr.products.csv > scanbot.2020_fr/scanbot_fr.products.nutriscore.csv 
products: 399339
scans: 4169276
unique_scans: 2627876
found_products: 220217 - 55.15
found_scans: 3840435 - 92.11
found_unique_scans: 2396592 - 91.20
nutriscore_products: 124560 - 31.19
nutriscore_scans: 3159908 - 75.79
nutriscore_unique_scans: 2006105 - 76.34
> Script to generate Nutri-Score stats from scanbot.pl output

- lang/fr/data_sources/database-codeonline.html
- lang/fr/data_sources/database-equadis.html
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Export.pm
- lib/ProductOpener/Products.pm
- templates/display_product.tt.html
This will add a link at the bottom of product pages to indicate that some data comes from CodeOnline, or from Equadis. The link will lead to a page with a small text about each, plus the list of corresponding products. Essentially it's just 2 additional values to the /data-sources facet.
> Indicate source of data for CodeOnline and Equadis + dedicated pages

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Food.pm
- lib/ProductOpener/Images.pm
- lib/ProductOpener/Import.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- scripts/convert_carrefour_data.pl
This is to fix small issues with the Carrefour import, and to allow importing a CSV file that looks like this:
EAN | URL | ANGLE
-- | -- | --
8012666520305 | https://basephoto-cdn.carrefour.com/product_pictures/304155 | Front
3046300001085 | https://basephoto-cdn.carrefour.com/product_pictures/1028813 | 3/4
3046300001085 | https://basephoto-cdn.carrefour.com/product_pictures/1028814 | Front
3046300001085 | https://basephoto-cdn.carrefour.com/product_pictures/1028815 | Back
3046300001245 | https://basephoto-cdn.carrefour.com/product_pictures/1028816 | 3/4
3046300001245 | https://basephoto-cdn.carrefour.com/product_pictures/1028817 | Front
> Allow imports of files that contain the URL of an image + its type in another column + small fixes for Carrefour import

- cron/import_carrefour.sh
- cron/import_fleurymichon.sh
- cron/import_systemeu.sh
- scripts/convert_carrefour_data.sh
- scripts/convert_carrefour_data_off1.sh
- scripts/export_producers_platform_data_to_public_database.sh
- scripts/import_carrefour.sh
- scripts/import_carrefour_pro_off1.sh
- scripts/import_carrefour_test.sh
Removing old scripts and adding new ones.
The main change is that instead of importing Carrefour data and photos directly to the public platform, they now go first to the pro platform.
>  scripts updates for Carrefour import on pro platform

- taxonomies/recycling_bins.txt
Adding Portuguese translations for recycling_bins.txt
Since is not possible to have pt-br translations as said in https://github.com/openfoodfacts/openfoodfacts-server/pull/5039#issuecomment-804919894, and I should add them to pt: I can't do that in this case because colors containers are different in Portugal and Brazil, (same color to different materials), and may be even in Angola, Mozambique and other Portuguese countries. For example:
-red container = plastics in Brazil; batteries in Portugal
-yellow container = metals in Brazil; plastics in Portugal
Any suggestion/solution?
> Translations for recycling_bins.txt

- po/common/common.pot
- po/common/en.po
- templates/display_new.tt.html
Description:
Issue 1.1.1: Changed the alt text for the logo.
Related issue  https://github.com/openfoodfacts/openfoodfacts-server/issues/4640
> Fixed accessibility issue 1.1.1

- cpanfile
- lib/ProductOpener/Store.pm
- scripts/scanbot.pl
We need scans data to be available for each product. While it would be cool to have data by year, months, days etc. (see #1501), it would be already be very useful to have it by year and by country.
This update to scanbot creates a new scans.sto file with aggregated scan data by year and country.
Example:
```
./sto_to_xml.pl /srv/off/products/800/227/001/4901/scans.sto 
/srv/off/products/800/227/001/4901/scans.sto$VAR1 = {
'2020' => {
'unique_scans_n_by_country' => {
'world' => 4,
'fr' => 2,
'be' => 2
},
'unique_scans_n' => 4,
'scans_n' => 4,
'unique_scans_rank_by_country' => {
'fr' => 19,
'world' => 1,
'be' => 1
}
}
};
```
It also changes the way we compute the top products per country, to make it more accurate. Currently the top lists of products per country are derived from the top …
> Improve scanbot, store each product scans in scans.json files

- lib/ProductOpener/GeoIP.pm
Description: Updated the `GeoIP.pm` file to add its documentation in perlpod format.
Fixes: https://github.com/openfoodfacts/openfoodfacts-server/issues/5089
Related Issue: #2203
> Document the ProductOpener::GeoIP.pm module

- lib/ProductOpener/Mail.pm
Description: Updated the `Mail.pm` file to add its documentation in perlpod format.
Fixes: https://github.com/openfoodfacts/openfoodfacts-server/issues/5084
Related Issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/2203
> Document the ProductOpener::Mail.pm module

- lib/ProductOpener/Ecoscore.pm
We pre-compute transportation scores and final eco-score for all available Eco-Score countries, and when a request is made through the API, it takes into account the requested country (passed either through the subdomain or the cc field) to return the localized Eco-Score.
> Fix to return different Eco-Score values based on the requested country

- taxonomies/ingredients.txt
I added German synonyms for 'yellow pepper' and 'cumin'. On-the-fly I fixed some misspellings in the other synonyms of these ingredients.
> added German synonyms for yellow pepper and cumin

- cgi/org.pl
- lib/ProductOpener/Import.pm
- lib/ProductOpener/ImportConvert.pm
- lib/ProductOpener/Orgs.pm
- t/import.t
- remove "BONS.MAYENNAIS" from the product name when we have a "Bons Mayennais" brand. (done in a generic way)
- when an org is created through a GS1 import, we now assign the ownership of the GLN to it, so that we don't get multiple orgs for the same GLN because the import file contains multiple variations of the party name.
> Improvements for CodeOnline import

- taxonomies/labels.result.txt
- taxonomies/labels.txt
We have ~100 products with ingredients listing some food dyes that may have adverse effect on children. Adding it to the labels taxonomy will make ingredients analysis work for those products.
"eau, sucre, tartrazine. peut avoir des effets indésirables sur l’activité et l’attention chez les enfants"
e.g. https://fr.pro.openfoodfacts.dev/cgi/test_ingredients_analysis.pl?ingredients_text=eau%2C+sucre%2C+tartrazine.+peut+avoir+des+effets+ind%C3%A9sirables+sur+l%E2%80%99activit%C3%A9+et+l%E2%80%99attention+chez+les+enfants&type=add&action=process&submit=Envoyer
> added adverse effect on children warning

- taxonomies/categories.txt
Purpose is to describe alcoholic beverages that have been mixed. These can be based on other liquors, like wine, beer, etc.
The idea is to have a place where we can pit the Bacardi Breezers, Smirnoff ice and other premixed (designer) drinks.
This category is not very well defined on Wikipedia, but is related to [Ready to Drink](https://en.wikipedia.org/wiki/Ready_to_drink), [Alcopop](https://en.wikipedia.org/wiki/Alcopop), [Wine cooler](https://en.wikipedia.org/wiki/Wine_cooler), etc.
There might be an overlap with flavoured drinks, like flavoured beers, vodka based beers, etc.
> Added alcoholic beverage categories

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Users.pm
- templates/emails/user_new_pro_account.tt.txt
- templates/emails/user_new_pro_account_admin_notification.tt.html
- templates/emails/user_new_pro_account_org_request_validated.tt.txt
- added a new /templates/emails directory to store email templates (either in .txt or .html)
- email templates:
-- user_new_pro_account.tt.txt : mail template to email producers after a few days
-- user_new_pro_account_org_request_validated.tt.txt : mail template when we accept their request to join an org
-- user_new_pro_account_admin_notification.tt.html : HTML notification email sent to the producers platform admins, with 2 mailto: links that embed the first 2 emails
Fixes #5208 #5200 
Will help to do #5182
> Templatize emails for the producers platform

- cgi/org.pl
- lib/ProductOpener/Import.pm
- po/common/common.pot
- po/common/en.po
We can't import GS1 data from producers as-is because it contains errors. This adds 2 checkboxes on the org edit form for admins to mark that an organization needs special processing of GS1 data:
- gs1_product_name_is_abbreviated : the product name field contains abbreviations (like the ones on receipts)
- gs1_nutrients_are_unprepared : the producer has entered nutrition data for the prepared product, but it's a product that is consumed as sold, without preparation
This just adds the checkboxes, the code to use them will come later.
> new checkboxes to fix GS1 data issues

- lib/ProductOpener/Orgs.pm
this is to make it easier to work on organization in dev environments.
> create orgs directory if it does not exist

- lib/ProductOpener/Display.pm
- lib/ProductOpener/ImportConvert.pm
- lib/ProductOpener/Products.pm
- t/import.t
For imports, when we had a generic name but not a product name, we used to copy the generic name to the product name (because in most cases the generic name was also the product name).
But with the current GS1 imports, it's very frequent that the product name is in fact an abbreviated product name, so I made an organization checkbox to assign the GS1 product name to the abbreviated product name. That means we don't have a product name for many products.
So this:
- remove the automatic generic name copy to product name when it does not exist
- changes the display of products to display the generic name when we don't have a product name
> Imports: do not overwrite product name with generic name

- cgi/auth.pl
This is for the folksonomy engine project (and possibly other projects).
This endpoint returns status 200 or 403 if the user is authentified, either through the "session" cookie, or with the user_id and password parameters.
> new auth.pl API endpoint

- lib/ProductOpener/Users.pm
This is to make life simpler for admins of the producers platform, instead of using the organization name to access it, they can also use the GS1 GLN id.
> Allow producers platform admins to use GS1 GLN as orgid

- lib/ProductOpener/Display.pm
- templates/display_product.tt.html
This is to solve the issue of texts that have different urls in different languages, and how we can link to them easily. (see #1818)
This is just a start. It solves #5260, but with an hardcoded mapping structure.
The goal is to generate the mapping structure at startup, using the available translations in the texts directory (we could create a new one, and move texts gradually).
> very small start of a refactoring for handling links of texts translations

- lib/ProductOpener/Ingredients.pm
- t/allergens_tags.t
- t/expected_test_results/attributes/en-attributes.json
We currently detect allergens using the allergens taxonomy. This adds detection through the ingredients taxonomy, so that we can catch more ingredients containing allergens. e.g. in the allergens taxonomy, we have some common ingredients containing gluten listed as synonyms of gluten, but we don't have all possible ingredients containing gluten (e.g. "durum wheat semolina").
On the other hand, thanks to the ingredients taxonomy, we know that "durum wheat semolina" is a child of "wheat", and that "wheat" has the "allergens:en: en:gluten" property.
Main issue: #3297
Will also fix: #5250
> Detect allergens using the ingredients taxonomy and ingredients analysis

- taxonomies/ingredients.txt
With #3297, the allergens:en: property is now used to add allergens detected in ingredients list.
That means that the allergens:en: property must be used only when we are sure the ingredient contains an allergen.
so for entries like this one that can in fact be gluten-free:
en:pizza base
de:Pizzaboden
fi:pizzapohja
fr:fond de pizza
nl:pizzabodem
sv:pizzabotten
allergens:en: en:gluten
We can use likely_allergens:en: en:gluten instead. (which we could later use to make checks, to populate the /data-quality facet)
> Transform some allergens properties into likely_allergens, #3297

- lib/ProductOpener/Display.pm
fixes #5276
This changes links like` <a href="/ecoscore">` in the generate HTML for a page to their localized version.
It is an extension of the url_for_text("ecoscore") that we introduced for links in templates, that works not only in links in templates, but also links from other sources (e.g. translations in .po files)
> Localize URLs for texts in links, 

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Food.pm
- t/expected_test_results/nutriscore/beverage-with-80-percent-milk.json
- t/expected_test_results/nutriscore/breakfast-cereals.json
- t/expected_test_results/nutriscore/colza-oil.json
- t/expected_test_results/nutriscore/cookies.json
- t/expected_test_results/nutriscore/dairy-drink-with-80-percent-milk.json
- t/expected_test_results/nutriscore/dairy-drink-with-less-than-80-percent-milk.json
- t/expected_test_results/nutriscore/dairy-drinks-without-milk.json
- t/expected_test_results/nutriscore/honey.json
- t/expected_test_results/nutriscore/milk.json
- t/expected_test_results/nutriscore/mushrooms.json
- t/expected_test_results/nutriscore/olive-oil.json
- t/expected_test_results/nutriscore/sunflower-oil.json
- t/expected_test_results/nutriscore/walnut-oil.json
- t/nutriscore.t
- taxonomies/ingredients.txt
This is to fix a nutriscore issue signaled on twitter for https://world.openfoodfacts.org/product/7610900251759/caffe-latte-double-zero-macchiato-emmi
Beverages that contain 80% of milk are considered food for the nutriscore. We rely on the ingredients analysis to determine if there is milk and how much there is in it.
> improve milk recognition, fix nutriscore issue

- templates/web/pages/product/product_page.tt.html
- templates/web/pages/user_form/user_form_page.tt.html
Removing an inactive style that was needed in the previous version of the form, where we had a table with rows.
> Remove unneeded CSS style in user form

- templates/web/common/includes/donate_banner.tt.html
- templates/web/common/includes/error_list.tt.html
related to https://github.com/openfoodfacts/openfoodfacts-server/pull/5297 and #5261 #5248 
we use to need [% component.name %] instead of [% template.name %] in order to have the name of included template, and not the page level template.
see http://www.template-toolkit.org/docs/manual/Variables.html#section_component
We should do the same for all included templates.
> included templates need to use component.name instead of template.name

- docker/README.md
Added the link to the [dev environment quick start guide](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/dev-environment-quick-start-guide.md) in the "Local Development" section of  Docker `README.md` file. 
The [dev environment quick start guide](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/installation/dev-environment-quick-start-guide.md) is the detailed step-by-step guide to set up the project using Docker on the local machine. Hence, it will be good to add the link in this section.
> Added link to the quick-start guide

- cgi/org.pl
- lib/ProductOpener/Export.pm
- lib/ProductOpener/Import.pm
- lib/ProductOpener/Producers.pm
- po/common/common.pot
- po/common/en.po
- scripts/convert_csv_file.pl
- scripts/convert_usda.sh
- scripts/convert_usda_small.sh
- scripts/import_csv_file.pl
- scripts/import_usda.sh
- scripts/import_usda_small.sh
I closed https://github.com/openfoodfacts/openfoodfacts-server/pull/5302 and opened this new PR as I changed a lot of things on the branch.
This implements the mechanism described in #5304 
It will be used for both CodeOnline and USDA imports.
> Add authorized import sources for orgs for USDA and CodeOnline

- docker/frontend-git/conf/nginx.conf
I'm not sure why, but the query string was no longer appended to the proxy_pass directive. It's probably when I changed the config to use "backend" and "backend-pro". Adding query_uri seems to work.
> Docker config: add query_uri to backend redirect

- cgi/export_products.pl
- templates/web/pages/export_products_results/export_products_results.tt.html
**Description**:
The `export_products.pl` was including the HTML code for the results. These results are shown when users submit the form. Shifted that code to the template file.
> Templatization of export_products.pl

- installation/Developer-guide.md
Updated the developer guide to add the new subheading "Running minion jobs" under the heading "Running Docker in bash".
> Added new subheading "Running minion jobs"

- cgi/org.pl
- cgi/product_image_crop.pl
- cgi/product_jqm_multilingual.pl
- lib/ProductOpener/Import.pm
- lib/ProductOpener/Products.pm
- po/common/common.pot
- po/common/en.po
fixes #5325
Instead of protecting by default all "producer" data, we now require a manual activation of the protection, as a lot of producer data comes from 3rd parties like CodeOnline or the USDA and might be outdated or of not so good quality.
> Protect data provided by some organizations, 

- lib/ProductOpener/Ecoscore.pm
- t/expected_test_results/attributes/en-attributes.json
- t/expected_test_results/ecoscore/carrots-plastic.json
- t/expected_test_results/ecoscore/carrots.json
- t/expected_test_results/ecoscore/grade-a-with-non-recyclable-label.json
- t/expected_test_results/ecoscore/grade-a-with-recyclable-label.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/milk.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-bulk.json
- t/expected_test_results/ecoscore/packaging-en-multiple.json
- t/expected_test_results/ecoscore/packaging-en-pet-bottle.json
- t/expected_test_results/ecoscore/packaging-en-plastic-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-bottle.json
- t/expected_test_results/ecoscore/packaging-en-unspecified-material-can.json
- t/expected_test_results/ecoscore/sum-of-bonuses-greater-than-25.json
The "transportation less" Eco-Score grade and score we have today in the ecoscore_tags and ecoscore_grade fields is not meaningful, and far from the actual Eco-Score for any country.
It is better to use the Eco-Score for France instead, as there will be much less differences. We can try to find a better system later. Unfortunately we are constrained by the number of possible indexes in MongoDB (64) so we can't index all the Eco-Score values for all countries.
> Use Eco-Score for France in fact instead of Eco-Score missing transportation bonus

- t/ingredients_processing.t
- taxonomies/ingredients.txt
Just fixed a spelling mistake, so that 'Papaya' gets recognized.
> Fixed spelling for German 'Papaya'

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Images.pm
This is to serve product images from ovh3 instead of off1.
@cquest has setup an automated copy of images from off1 to ovh3, and ovh3 can serve images locally if it has them, or get them from off1 and cache them otherwise (e.g. for new product images that have not been copied to ovh3 yet).
details in #5359
> serve product images from images.openfoodfacts.org

- installation/Developer-guide.md
Fixed the file name in the command under the heading "Restarting docker backend without quitting the running environment".
> Fixed a mistake in Developer guide

- lib/ProductOpener/Ecoscore.pm
- t/ecoscore.t
- t/expected_test_results/attributes/fr-palm-kernel-fat.json
- t/expected_test_results/attributes/fr-palm-oil-free.json
- t/expected_test_results/attributes/fr-palm-oil.json
- t/expected_test_results/attributes/fr-vegetable-oils.json
- t/expected_test_results/ecoscore/empty-product.json
- t/expected_test_results/ecoscore/fresh-vegetable.json
- t/expected_test_results/ecoscore/frozen-vegetable.json
- t/expected_test_results/ecoscore/ingredient-palm-oil-rspo.json
- t/expected_test_results/ecoscore/ingredient-palm-oil.json
- t/expected_test_results/ecoscore/known-category-butters.json
- t/expected_test_results/ecoscore/known-category-margarines.json
- t/expected_test_results/ecoscore/label-organic.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested-2.json
- t/expected_test_results/ecoscore/origins-of-ingredients-nested.json
- t/expected_test_results/ecoscore/origins-of-ingredients-not-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-partly-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified-multiple.json
- t/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unknown-origin.json
- t/expected_test_results/ecoscore/origins-of-ingredients-unspecified-origin.json
- t/expected_test_results/ecoscore/packaging-en-multiple-over-maximum-malus.json
- t/expected_test_results/ecoscore/packaging-unspecified-no-a-eco-score.json
- t/expected_test_results/ecoscore/packaging-unspecified.json
- t/expected_test_results/ecoscore/unknown-category.json
Some fixes / changes related to recent changes in the Eco-Score formula:
1.  we do not compute an Eco-Score for fresh fruits and vegetables. This is temporary, to avoid showing a A Eco-Score for out of season vegetables and fruits. Ultimately the formula will take the seasonality into account and we can compute the Eco-Score again for those.
2. when we don't have packaging information, we now give a -15 malus (the maximum) instead of considering 1 unknown packaging component of unknown material (which gave a -10 malus).
> Ecoscore changes for unknown packaging and fresh fruits and vegetables

- t/ecoscore.t
- t/expected_test_results/ecoscore/foie-gras.json
- taxonomies/categories.result.txt
- taxonomies/categories.txt
We now use a more realistic proxy for foie gras.
> Changed Agribalyse category proxy for Eco-Score foie gras

- templates/web/pages/product/includes/ecoscore_details.tt.html
- templates/web/pages/product/includes/ecoscore_details_simple_html.tt.html
Instead of assuming we have an unknown packaging component with an unknown material, we now directly give the maximum malus (-15).
> Adapt the Eco-score details display to the new way to handle missing packaging data

- taxonomies/categories.result.txt
- taxonomies/categories.txt
delete the wrong agribalyse association, so that we get the good association from the parent "foies gras"
> Fix goose foie gras Eco-Score property

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Web.pm
Related to : https://github.com/openfoodfacts/openfoodfacts-server/issues/5205
> Re-architecturing the Open Food Facts Perl modules and functions

- .github/workflows/container-deploy.yml
`git clone` doesn't switch to the cloned dir on it's own, so that `git checkout ${{ github.sha }}` didn't work. I only switched around the order of those command, and added an addition `git pull`, so that the newest commits are also pulled, even if the directory `openfoodfacts-server` directory existed previously.
> Fix order of deploy commands

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Web.pm
Moved the function `display_login_register()` from `Dispaly.pm` to `Web.pm`.
**Related to:** #5205
**Note:** This PR might arise merge conflicts with https://github.com/openfoodfacts/openfoodfacts-server/pull/5435 but I'll solve them.
> Moved display_login_register() to Web.pm

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Web.pm
- templates/web/common/includes/display_my_block.tt.html
**Description:** 
Moved the function display_my_block() from `Dispaly.pm` to `Web.pm`.
**Related to :** https://github.com/openfoodfacts/openfoodfacts-server/issues/5205
> Moved the function display_my_block() to Web.pm

- html/images/misc/additives-efsa-evaluation-overexposure-risk-icon-no.svg
> add icon for additives without overexposure risk

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Web.pm
**Description:** 
Moved the function `display_product_search_or_add()` from `Display.pm` to `Web.pm`.
**Related to:** #5205
> Moved the function display_product_search_or_add() to Web.pm

- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/story.md
- .github/ISSUE_TEMPLATE/task.md
Add issue templates to support the scrum methodology. The immediate need is the fellowship with Google but other groups collaborating in this way can benefit from them too, of course.
These are exact copies of the default templates located in the .github repository, https://github.com/openfoodfacts/.github/tree/main/.github/ISSUE_TEMPLATE. They need to be replicated here because this repository already has a .github/ISSUE_TEMPLATE directory, which overrides completely the one in the organisation's default repository entirely. (documentation ref: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files)
**Alternative considered:**
The alternative would be to create …
> Add issue templates to support the scrum methodology

- lib/ProductOpener/Display.pm
- templates/web/common/includes/display_recent_changes.tt.html
> Templatization of display_recent_changes() in Display.pm

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Web.pm
**Description:** 
Moved the function `display_data_quality_description()` from `Display.pm` to `Web.pm`.
**Related to:** #5205
> Moved display_data_quality_description() to Web.pm

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Tags.pm
- t/tags.t
fixes part of #5463
When a taxonomy like additives refer to another taxonomy for some properties (e.g. additives_classes), we now canonicalize the value (e.g. if we have additives_classes:en: en:stabilizer for an additive, we change it to en:stabiliser which is the canonical name in the additives_classes taxonomy).
This currently work only for properties that have exactly the same name as an already loaded taxonomy.
We'll also need to do it for mandatory_additive_class (and we will probably rename it to additives_classes.mandatory or something so that we can make the match).
> Canonicalize properties that refer to other taxonomies

- .github/dependabot.yml
moving dependabot to daily with the idea that -as a result- the flow of PRs to merge will be more evenly distributed through time
> moving-dependabot-to-daily

- t/expected_test_results/ingredients/fr-starred-label.json
- t/ingredients_processing.t
- t/tags.t
- taxonomies/ingredients.txt
- taxonomies/ingredients_processing.txt
Initial attempt at mapping CIQUAL categories to ingredients.
- Agribalyse categories being CIQUAL categories, this should pave the way for refined computations.
- We should also be able to recompute approximate nutritional values from the nutritional values of each ingredient, multiplied by the CIQUAL nutritional values.
- https://github.com/openfoodfacts/offf/issues/14
> Initial attempt at mapping CIQUAL categories to ingredients

- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- templates/api/knowledge-panels/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/ecoscore/ecoscore.tt.json
- templates/api/knowledge-panels/ecoscore/ecoscore_unknown.tt.json
This is an implementation of the Eco-Score Agribalyse sub panel with LCA impacts for the different steps. (see #5541 )
I tried a different approach for this one: instead of using Perl code to generate the expected structure for the panel, the Perl code just passes the necessary data to a template that generates JSON for the structure.
It's a bit more tricky than templates to generate HTML code, but it works.
The goal is to have a better separation between model/data and display logic and form, and to allow non programmers to change, reorder etc. the panels just by changing the templates.
- #2938
> Use JSON template to generate Eco-Score Agribalyse LCA knowledge panel 

- .github/workflows/crowdin.yml
I believe we don't need to reupload translations everytime. Not only does it slow down the process, but it recontaminates translations from the old source code translations.
> Disable translation upload

- .gitattributes
GitHub incorrectly shows that the Roff programming language is used in this project.
This happens, because [files fulfilling `*.csv.<number>` pattern in this repo](https://github.com/search?q=repo%3Aopenfoodfacts%2Fopenfoodfacts-server+language%3ARoff&type=Code&l=Roff) are classified by [github-linguist](https://github.com/github/linguist) as Roff programming language files:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L5126-L5157 
This PR fixes the classification of the `*.csv.<number>` files.
After the fix they are classified as CSV files, not Roff files and the fix is done by overriding github-linguist defaults in .gitattributes.
Final effect: Roff language is no more detected in the project.
Running github-linguist on `openfoodfacts-server` **before** …
> github-linguist: Treat .csv.<number> files as CSV, not Roff

- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- po/common/en.po
- templates/api/knowledge-panels/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/ecoscore/ecoscore.tt.json
- templates/api/knowledge-panels/ecoscore/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/ecoscore/packaging.tt.json
- templates/api/knowledge-panels/ecoscore/production_system.tt.json
- templates/api/knowledge-panels/ecoscore/threatened_species.tt.json
- templates/web/pages/product/includes/ecoscore_details.tt.html
- templates/web/pages/product/includes/ecoscore_details_simple_html.tt.html
This PR creates mostly empty sub-panels for the Eco-Score adjusments (maluses and bonuses for packaging, production mode, origins of ingredients and threatened species).
This is so that we have the right structure in place, we can create the actual panels one by one in other PRs.
> add placeholder panels for ecoscore adjustments #5541

- .github/workflows/container-deploy.yml
Can be re-enabled once `restructure-docker` branch is merged (https://github.com/openfoodfacts/openfoodfacts-server/pull/5544)
> Disable deploy on main branch (temporarily)

- icons/consumption.svg
- icons/distribution.svg
- icons/transportation.svg
- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- lib/ProductOpener/Web.pm
- po/common/common.pot
- po/common/en.po
- templates/api/knowledge-panels/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/ecoscore/packaging.tt.json
- templates/web/common/includes/display_field.tt.html
- templates/web/common/site_layout.tt.html
- templates/web/pages/product/product_page.tt.html
- templates/web/panels/panel.tt.html
- See #5633
This PR:
- shows the Eco-Score panel next to the Eco-Score on product page when ?panels=1 is added to the URL.
- implements some basic functions to display panels and subpanels (currently just the text and table elements)
At this point, it is mostly for demo and development purposes, but the goal is to eventually replace the current Eco-Score + Eco-Score details display with the Eco-Score knowledge panel.
This is just a sample implementation to display the panels structure and data, the actual implementation of how we display panels on the web might be very different (e.g. using accordions, dropdowns, or modals to display panels and subpanels).
> Display knowledge panels on the web

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
fixes #5644
This is to make it clear that the Nutri-Score of tea bags apply to the prepared product with water only.
> Display note for Nutri-Score of teas and herbal teas bags

- html/js/product-multilingual.js
**Description:** Use the `right` position as the anchor when a RTL language is selected.
- **Related issues and discussion:** #5640
> fix: Differentiate between rtl and ltr for the image position

- lib/ProductOpener/Attributes.pm
- po/common/common.pot
- po/common/en.po
**Description:** Introduces a new translation key `g_per_100g`, which can be used to translate the text `'%.2f g / 100 g'` into other languages. This is useful if a language uses other formatting, ie. RTL languages (as opposed to LTR languages).
- **Related issues and discussion:** #5640
> i18n: Make 'X g / 100 g' translatable

- cgi/product_multilingual.pl
**Description:** In addition to front, ingredients, and nutrition, also copy the selected packaging image when changing a product's main language.
**Related issues and discussion:** Fixes #5657
> fix: Move selected packaging photos to new main language

- .github/workflows/daily.yml
- Makefile
- docker/mongodb.yml
- docker/prod.yml
This makes sure that the `mongorestore` command will not go OOM. 
Proxmox VM size has been increased from 4GB to 16GB since the process takes at least 14GB of RAM to run. Disk space has also been increased by ~60GB.
Also:
> Fix daily MongoDB task + add refresh_products_tags.js cron

- conf/incron.conf
Summary:
- Running incrond -n was working (I could symlink an image into /opt/product-opener/new_images and it was processed properly)
- Running incrond starts it as a service, and nothing was triggered when I symlinked
The incrontab conf we were using was:
`/mnt/podata/new_images IN_CREATE /opt/product-opener/scripts/process_new_image_off.sh $@/$# /opt/product-opener`
I wanted to figure out what was going on so I redirect the output to a log file:
`/mnt/podata/new_images IN_CREATE /opt/product-opener/scripts/process_new_image_off.sh $@/$# /opt/product-opener > /mnt/podata/logs/test.log`
and to my surprise after doing this the incron job is working ...
What was going on actually is that incrond tries to write to `/var/log/syslog` (there is no way to change this in `/etc/incrond.conf` ...) …
> Fix incron job

- lib/ProductOpener/Ecoscore.pm
- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- po/common/en.po
- scss/_off.scss
- templates/api/knowledge-panels/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/ecoscore/ecoscore_unknown.tt.json
- templates/api/knowledge-panels/ecoscore/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/ecoscore/packaging.tt.json
- templates/web/panels/panel.tt.html
Improvements to the Eco-Score panels.
- Enhance the backticks feature to escape quotes in JSON templates
- Allow comments in the JSON templates
- Move the logic to decide if an adjustment is a plus or minus directly in the template for each adjustment.
- Add some warnings when packaging info is missing.
- Added origins of ingredients table
- Support for colored percent bars
> Improvements for Eco-Score knowledge panels #5541

- gulpfile.js
If svg icons have the width and height attributes set, instead of the viewBox attribute, it makes it harder to display them at different sizes using CSS styles.
e.g. with viewBox:
icons are resized to 18px through CSS
with with and height set to 24 px:
icons are not resized
> make svgmin remove width/height and keep/add viewBox

- .env
- installation/dev-environment-quick-start-guide.md
Change `productopener.localhost` to `openfoodfacts.localhost` to guarantee operability between local installations of Robotoff and Product Opener (Robotoff need them to run on the same domain otherwise requests are rejected..)
> fix: change local domain to openfoodfacts.localhost

- lib/ProductOpener/Users.pm
- templates/emails/user_new_pro_account_admin_notification.tt.html
The template for the email was broken (it expected Subject: something as the first line) and a HTML comment was added before.
Made the logic more resilient and we now send a warning email if the template is broken.
- fixes #5712
- #5730 
- #5521
> fix: producers emails - fixes #5712

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/GS1.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- t/expected_test_results/import_gs1/equadis_brasseries_kronenbourg_tourtel.off.json
- t/expected_test_results/import_gs1/equadis_nestle_france_ricore.off.json
- templates/web/pages/product_edit/display_input_field.tt.html
Related to #5713
We already have a "origin" language field, used for some imports like Carrefour, to store strings like "Made in Germany with almonds from Turkey". There is a similar field provenanceStatement in GS1 data, so we can map it to our "origin" field.
The field is now also displayed and editable in the product edit form, so contributors can also type it in and/or copy/paste it from the ingredients OCR.
> Map GS1 provenanceStatement to origin field, add it to product edit form

- conf/apache.conf
- conf/nginx.conf
- docker/prod.yml
Deployment of `nginx_exporter` failed because `/nginx_status` endpoint (healthcheck) was not added to NGINX config.
> fix: add nginx_status section to run the nginx_exporter correctly

- lib/ProductOpener/Display.pm
fixes #5778
This is needed to run the ecoscore impact estimator.
> sort_by=nothing option to remove the sort of product queries, 

- lib/ProductOpener/Ingredients.pm
- t/expected_test_results/recipes/nectars.missing-ingredients.json
This is to remove some fields for products that have an empty ingredient list, as those fields don't make sense for them.
e.g. the number of unknown ingredients is 0.
> Remove ingredients related fields when ingredients are empty

- lib/ProductOpener/Display.pm
> fix: url for public product link on pro platform

- lib/ProductOpener/Images.pm
- scripts/run_cloud_vision_ocr.pl
- scripts/run_ocr.py
- Change endpoint for the ingredients OCR. Also Requires a secret change in the config file.
- I already fixed it in production. 
- #5512
> fix: Change endpoint for the ingredients OCR

- cgi/display.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
Fixes #5785 
This is a new API to get an extract of a taxonomy for specific tags, specific fields/properties, in specific languages.
example: https://world.openfoodfacts.dev/api/v2/taxonomy?type=labels&tags=en:organic,en:fair-trade&fields=name,description,children&include_children=1&lc=en,fr
> feat: new taxonomy API

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
Requested by @gspencergoog for the category picker in the Flutter app.
e.g. https://world.openfoodfacts.dev/api/v2/taxonomy?tagtype=packaging_materials&tags=en:plastic&include_root_entries=1
For categories: https://world.openfoodfacts.dev/api/v2/taxonomy?tagtype=categories&include_root_entries=1
Note: we have many entries without parents that probably should have one.
> feat: add include_root_entries option to taxonomy API, fixes #6039

- scripts/scanbot.pl
fixes #4870
The add_tags_to_field() from Tags.pm is the safe way to add some tags to a field like countries, as the "countries" field could be in any language, and not necessarily in the main language of the product (it is in the language last used to update the product).
> fix: add countries correctly in scanbot

- installation/dev-environment-quick-start-guide.md
The extra $ at the start on the line is copied when clicking on the copy icon in GitHub.
> doc: Docker guide: remove $ in command lines to make it easier to copy

- taxonomies/additives.txt
Hello!
Glycerol is not always vegan and vegetarian.
Source: https://www.veganfirst.com/article/qa-is-glycerin-vegan
Same with E472: https://doublecheckvegan.com/ingredients/e472b/
> Change vegan and vegetarian statuses of Glycerol

- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- templates/api/knowledge-panels/environment/carbon_footprint.tt.json
- templates/api/knowledge-panels/environment/environment_card.tt.json
- templates/api/knowledge-panels/environment/packaging_recycling.tt.json
- templates/web/common/includes/donate_banner.tt.html
- templates/web/pages/product/product_page.tt.html
- templates/web/panels/panel.tt.html
- Fixed some icons paths (the Eco-Score ones existed in prod but not in github)
- Using the result of a FILTER to set a variable in Template::Toolkit works in the dev server, but not in production and in the docker environment. Now exposing the sprintf function directly.
- Fixed the display of packaging components by recycling types
- Fixed the display of environmental labels panels when we don't have an Eco-Score (no Agribalyse category) but when we have organic labels.
- Now showing the panels in the product page for all moderators, in order to uncover issues before we set it for all users.
> Small fixes for knowledge panels

- scripts/mongodb_dump.sh
The delta export command fails with MongoDB 4.4 and throws the error: `Failed: error parsing query as Extended JSON: invalid JSON input`.
This results in empty delta exports for a long time now.
Putting the query parameters in quotes fixed the error. 
I'm not 100% sure if MongoDB 4.4 is used on the server, got the info from https://github.com/openfoodfacts/openfoodfacts-server/issues/4928
**Related issues and discussion:** #4928
> Fixes #4928 Delta export command fails

- taxonomies/languages.txt
- I've removed "Língua" (language) from strings like "Língua portuguesa" in Portuguese translations to fix a issue while editing products in Open Food Facts website. Because at this moment, pressing the key "P" in keyboard, it jumps to another language and not "Portuguese" or the first one having the "P" letter.  This also affects sorting. (See  #6046)
- Fixed a few Portuguese translation errors.
- In some cases (4 or 6 of them) I've changed the first existing translation in each string to show simultaneously Brazilian Portuguese and Portuguese (or European Portuguese) in the string shown in interface (where they differ) to reach all Portuguese speaking variations, since the interface is currently not available in Brazilian Portuguese. For example "Thecho / checo" (pt-br …
> Change pt and pt-br in languages.txt +notes

- html/js/display-tag.js
- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- templates/api/knowledge-panels/environment/carbon_footprint.tt.json
- templates/api/knowledge-panels/environment/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/environment/ecoscore/ecoscore.tt.json
- templates/api/knowledge-panels/environment/ecoscore/ecoscore_unknown.tt.json
- templates/api/knowledge-panels/environment/ecoscore/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/environment/ecoscore/packaging.tt.json
- templates/api/knowledge-panels/environment/ecoscore/production_system.tt.json
- templates/api/knowledge-panels/environment/ecoscore/threatened_species.tt.json
- templates/api/knowledge-panels/environment/ecoscore/total.tt.json
- templates/api/knowledge-panels/environment/environment_card.tt.json
- templates/api/knowledge-panels/environment/label.tt.json
- templates/api/knowledge-panels/environment/manufacturing_place.tt.json
- templates/api/knowledge-panels/environment/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/environment/packaging_recycling.tt.json
- templates/api/knowledge-panels/environment/palm_oil.tt.json
- templates/api/knowledge-panels/root.tt.json
- templates/web/pages/product/product_page.tt.html
- templates/web/panels/panel.tt.html
- Added a new "map" element to the knowledge panel API, with a list of pointers with geo coordinates
- Web implementation of the map element (reusing the code we have for packaging codes on pages like https://uk.openfoodfacts.org/packager-code/uk-uw020-ec ) --> this uses leaflet and openstreetmap.
- Added a manufacturing place knowledge panel, with the coordinates of the first packaging code of the product (a few products have more than one packaging code, but it's very rare)
- Added an origins of ingredients knowledge panel (slightly different from the one for the Eco-Score bonus for origins of ingredients)
To test:
https://uk.openfoodfacts.dev/product/3266980033613/l-escalope-cordon-bleu-de-poulet-x2-le-gaulois
Knowledge panels JSON: …
> Feat: manufacturing place + origins of ingredients knowledge panels + Normalize all panels

- icons/material/warning_black_24dp.svg
- icons/warning.svg
- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- po/common/en.po
- templates/api/knowledge-panels/environment/environment_card.tt.json
- templates/api/knowledge-panels/health/health_card.tt.json
- templates/api/knowledge-panels/health/ingredients/additives.tt.json
- templates/api/knowledge-panels/health/ingredients/allergens.tt.json
- templates/api/knowledge-panels/health/ingredients/ingredients.tt.json
- templates/api/knowledge-panels/health/nutriscore/nutriscore.tt.json
- templates/api/knowledge-panels/health/nutriscore/nutriscore_warnings.tt.json
- templates/api/knowledge-panels/health/nutrition/nutrition_facts_table.tt.json
- templates/api/knowledge-panels/root.tt.json
- templates/web/pages/product/includes/nutrient_levels.tt.html
- templates/web/pages/product/includes/nutriscore.tt.html
- templates/web/pages/product/includes/nutriscore_details.tt.html
- templates/web/pages/product/product_page.tt.html
- templates/web/panels/panel.tt.html
This is to prepare to create a Nutri-Score knowledge panel:
- Created a nutriscore.tt.html template to remove the hardcoded HTML that was in Display.pm
- Separated the preparation of data to be displayed for Nutri-Score and nutrient levels in a new function data_to_display_nutriscore_and_nutrient_levels(). We will also use the result of this data preparation for the corresponding knowledge panels.
- Added new warnings to inform users why the Nutri-Score is not displayed: category exempted  from Nutri-Score, missing category, or missing nutrition data
- Small changes to the nutriscore_details template so that we can reuse it in a knowledge panel
- Added https://static.openfoodfacts.org subdomain to icons URLs to make them absolute
- Added a Health card knowledge panel + Nutri-Score panel
> Improve web template for Nutri-Score and nutrient levels + Create Nutri-Score knowledge panel

- Makefile
- docker-compose.yml
- lib/ProductOpener/Display.pm
Fixes issue when running dev environment in docker:
after a clean repo checkout, make clean, make dev
```
Creating po_backend_run ... done
Status: 500
Content-type: text/html
<h1>Software error:</h1>
<pre>mkdir /mnt/podata/tmp/templates: Permission denied at /opt/perl/local/lib/perl5/x86_64-linux-gnu-thread-multi/Template/Provider.pm line 378.
```
> fix: use /tmp for compiled templates

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Food.pm
- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- scripts/create_small_categories_nutriments_per_country_for_testing.pl
- scripts/gen_top_tags_per_country.pl
- scss/_off.scss
- templates/api/knowledge-panels/health/health_card.tt.json
- templates/api/knowledge-panels/health/nutrition/nutrition_facts_table.tt.json
- templates/web/pages/product/includes/nutrition_facts_table.tt.html
- templates/web/pages/product_edit/product_edit_form_display.tt.html
- templates/web/panels/panel.tt.html
This PR is in preparation for creating a new knowledge panel to display the nutrition facts table.
- Change gen_top_tags_per_country.pl to generate data in $data_root/data/ instead of $data_root/index/ (so that we can eventually put all internal data generated by product opener in the data/ directory) (done now otherwise the script can't be run in the docker dev environment)
- Separated the template data generation in a new data_to_display_nutrition_table() function, so that we can reuse it to generate the upcoming nutrition table knowledge panel
- Removed a bunch of code related to the outdated carbon footprint (bug #6108)
- More comments
- Added a nutrition facts table knowledge panel
- Added "level" and "style" parameters to the knowlege panel API, in order to display sub nutrients
New …
> Refactor nutrition table generation, remove carbon footprint, add nutrition table panel

- lib/ProductOpener/Display.pm
Somehow I can't get compiled templates to be created in /tmp on the small dev openfoodfacts server, so putting back the compiled templates in $data_root/tmp/templates
> fix: put back compiled templates dir in data_root/tmp

- Makefile
Small fix to avoid problems with init_backend, which needs to first have build (and needs to be before `up`)
> Ag docker fixes

- html/donate/fr.helloasso.html
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- templates/web/common/includes/donate_banner.tt.html
- Remove some hardcoded translations from the donation banner template
- Make the year and the number of employees variables so that we don't have to update the translations every year
> Simplify donation banner translations

- Makefile
- taxonomies/Makefile
if sucessful, this will replace scripts/check_perl.js and scripts/refresh_taxonomies.js
@ocervell this will enable running make test, and all the workflow in docker.
I didn't change the pull_request.yml yet.
should help fix #6148
> ops: new check_perl and build_taxonomies targets

- lib/ProductOpener/Display.pm
I didn't understand why we had a warning:
Useless use of string eq in void context at /opt/product-opener/lib/ProductOpener/Display.pm line 9533.
That's because of the very weak precedence of the "or" operator:
https://perldoc.perl.org/perlop#Logical-or-and-Exclusive-Or
```
$x = $y or $z;              # bug: this is wrong
($x = $y) or $z;            # really means this
$x = $y || $z;              # better written this way
```
> fix precedence issue with or statement

- templates/web/common/includes/donate_banner.tt.html
Some browsers like Chrome actually replace the text character by a colored icon which is red, but others like Chromium do not, in which case we can still style it.
> Make the heart character in the donation banner red

- lib/ProductOpener/Ecoscore.pm
This is so that we can compute environment knowledge panels for the origins of ingredients even if we don't have an Eco-Score because we are missing a category.
> Localize Eco-Score data even if we don't have an Eco-Score category, for the origins of ingredients knowledge panel

- .github/workflows/daily.yml
- Makefile
We had a problem of disk space on preprod.
This is linked to daily failing, and as we did not remove previous archive before using wget, it was uploading archive with a new name, saturating disk space…
Task are failing because of a timeout which was, it seems, too short.
> fix: fix daily tasks

- Makefile
To have more than one project on my computer, I use direnv with `export COMPOSE_PROJECT_NAME=po2` but the Makefile makes the assumption that container name begin with `po_`.
This change makes it compatible with a project name change.
> ops: makefile should not depend on project prefix

- lib/ProductOpener/Food.pm
- templates/web/pages/product_edit/product_edit_form_display.tt.html
This fixes an issue with my recent refactoring of the code to handle nutrition facts edit from the web product edit form and the API.
The issue is that when a checkbox is unchecked on a form, the browser actually does not send the field at all. So if the parameter is not there, we don't know if it's because it is not set on purpose (e.g. the API is changing something else), or the box is there but has been unset (through the web edit form).
The trick is to add a hidden field with the same name of the checkbox on the web form. That way we do get the hidden value if the box is unchecked, and the checked value if it is checked.
> fix: allow unchecking checked boxes in product edit form

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
fixes #6250
This is to allow queries like https://de.openfoodfacts.org/api/v0/product/example to get back data from a sample product that can be different based on country or language.
The products are specified in Config_off.pm, I just put a few for testing purposes.
In practice it is very likely that we will put fake products with specific fake barcodes, so that we can get exactly the data we want for the onboarding of Smoothie.
> feat: example product in API with code=example

- lib/ProductOpener/KnowledgePanels.pm
some producers have imported ingredients lists with \r\n sequences, and that broke the JSON used by knowledge panels.
this fixes the generation of the panels.
we probably need another fix to normalize newlines when we edit products / import data.
> fix: ensure windows newlines don't break panels

- taxonomies/categories.txt
some producers send "apéritif" for wine, we should not have it as a translation for "appetizers" which contains food.
> fix: French translation for appetizers

- taxonomies/ingredients.txt
Needed in particular to recognize "fruits and vegetables content : 45%", which is needed for Nutri-Score.
Also removed "base" from stopwords, so that "base XYZ" is not considered to be XYZ, and added "sachet" so that things like "sachet d'épices" are considered to be "épices".
> add 'fruits and vegetables' entry + fr stopwords change

- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- templates/api/knowledge-panels/health/health_card.tt.json
- templates/api/knowledge-panels/health/ingredients/additives.tt.json
- templates/api/knowledge-panels/health/ingredients/ingredients.tt.json
- templates/web/panels/panel.tt.html
Functional:
- list additives after the list of ingredients, as a list of small panels
- clicking on the additive name opens the additive panel
- additive panel currently consists only of the Wikipedia abstract and link (which are of very different levels of quality and relevance to food products depending on additive and language)
- to be added: a list of the additive functions (colours, raising agent etc.)
- to be added: EFSA table for the risk of overexposure (+ corresponding colors/icons in the list of additives)
Knowledge panel API changes:
- added a size="small" property to panels, so that the list of additives doesn't take a huge amount of vertical space
- added source_text / source_url / source_language to panel text elements
> feat: start of additives panels

- .github/workflows/daily.yml
- have coherent timeouts
- no git checkout as this is the job of mongo-deploy
Currently daily was failing because main branch on the preprod env had diverged !
This is not the job of daily to deploy, there is another automation for that.
> ops: fixing daily task

- .gitignore
- po/site-specific
I checked in my docker po/site-specific link by mistake. This is to remove it and add it to gitignore
> fix: ignore po/site-specific

- html/images/attributes/src/nutriscore-not-applicable.svg
- html/images/attributes/src/nutriscore-unknown.svg
- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- po/common/common.pot
- po/common/en.po
- t/expected_test_results/attributes/en-maybe-vegan.json
- templates/web/pages/product/includes/nutriscore.tt.html
Differentiate between Nutri-Score computed because we miss some data (category or nutrition facts) and Nutri-Score not applicable for a category.
Fixes #6276
> feat: different Nutri-Score icons and text for unknown and not-applicable 

- lib/ProductOpener/Food.pm
- t/expected_test_results/nutriscore/flavored-spring-water-no-nutrition.json
- t/expected_test_results/nutriscore/flavored-spring-with-nutrition.json
- t/expected_test_results/nutriscore/spring-water-no-nutrition.json
- t/nutriscore.t
- taxonomies/categories.result.txt
- taxonomies/categories.txt
Related issues #6288 #6287
Also add some tests.
But it does not solve the more general issue that typos in function names are currently undetected.
> fix: typo in function name in Food.pm 

- scripts/export_producers_platform_data_to_public_database.sh
This is to add more producers from Equadis to the daily exports from the producers platform to the public database.
We'll probably need to do this differently at some point. We have a checkbox in the org settings for daily exports, but it currently has no effect.
> add more automatic Equadis imports to public database

- scripts/scanbot.pl
This is to add a field (list of scan countries) to the list of products created by scanbot, so that it can be easily grepped for a particular country.
> add countries list to scanbot output data

- .github/workflows/daily.yml
Adds a marker to daily to avoid refreshing the database in preprod.
We want this from time to time to be able to run long experiments.
> ops: add marker to block daily update in preprod

- cpanfile
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Products.pm
- lib/ProductOpener/Tags.pm
- po/common/common.pot
- po/common/en.po
- scripts/update_all_products.pl
- t/products.t
We try to identifiy product edits that are made through apps, so that we can populate the data_sources facet. We currently do it by using the comment field that can contain an app name, and in some cases a uuid (used so that we can group contributions by the same user, for instance to check for errors), and/or the specific OFF user used by some app. This has been broken for some time.
This PR:
- refactors the identification of apps through the existing specific app OFF user ids and comments, and fixes issues - fixes #2592 - fixes #3849 - fixes #2195
- adds tests so that it does not become broken again
- add more robust ways for apps to pass their name and user uuid (app_name, app_version and app_uuid) instead of using the comment field - fixes #5195
- add an alternate way to pass the user …
> feat: Fix and improve detection of apps (name and UUID) to populate data sources

- lib/ProductOpener/Display.pm
> fix: links to previous revisions in product edit form

- lib/ProductOpener/Products.pm
This is to remove logs printed for every product change, and make them debug messages instead.
> fix: changed some log levels to debug

- lib/ProductOpener/Display.pm
- scss/_off.scss
- templates/web/pages/product/includes/ingredients_analysis.tt.html
This is to make the results of ingredients analysis less aggressive, and also to not make them look like buttons. It's also closer to the new styles from the Smoothie app. (colors etc.).
New:
One more change is that we now display the info that something is unknown (previously we didn't display anything at all), when we have ingredients, but when we are not able to make the determination.
Before:
Note that this design is temporary, it's likely that ingredients analysis results will become clickable knowledge panels.
> Change styles for ingredients analysis styles

- lib/ProductOpener/Display.pm
- templates/web/pages/product/includes/ingredients_analysis_details.tt.html
> fix: show 'we need your help' message for ingredients analysis only when needed

- lib/ProductOpener/Food.pm
- lib/ProductOpener/Ingredients.pm
Food.pm  : small fix for NOVA to remove warnings when there are no ingredients.
Today we have warnings like this:
Use of uninitialized value in division (/) at ProductOpener/Food.pm line 2418.
Use of uninitialized value in numeric gt (>) at ProductOpener/Food.pm line 2418.
updating product code: 0292471017322  (275628 / 870700)
Use of uninitialized value in division (/) at ProductOpener/Food.pm line 2418.
Use of uninitialized value in numeric gt (>) at ProductOpener/Food.pm line 2418.
updating product code: 3427290009662  (275629 / 870700)
Use of uninitialized value in division (/) at ProductOpener/Food.pm line 2418.
Use of uninitialized value in numeric gt (>) at ProductOpener/Food.pm line 2418.
updating product code: 3038680807814  (275630 / 870700)
Use of uninitialized value in …
> Ingredients analysis refactor + small NOVA fix to remove a warning

- lib/ProductOpener/KnowledgePanels.pm
There's some content in the .po files where we have relative links like <a href="/ecoscore">. But now that we use some of them in knowledge panels, we need to make the links absolute.
> fix: turn relative links to absolute links in knowledge panels

- templates/web/common/includes/display_data_quality_issues_and_improvement_opportunities.tt.html
- templates/web/common/includes/display_possible_improvement_description.tt.html
The details of the improvements opportunities where not shown anymore on the pro platform. This fixes the templates to show them again.
> fix: details of improvements opportunities

- lib/ProductOpener/Import.pm
This is to be able to set a field value for a list of barcodes like this:
./import_csv_file.pl --csv carrefour_fr_codes.20200303.csv --user_id driveoff --comment "carrefour.fr 20220303" --define stores="carrefour.fr" --skip_not_existing_products --no_source 
more scripts/carrefour_fr_codes.20200303.csv 
code
0000030000117
0000030005501
0000030005518
0000030043602
0000030075214
0000030182141
0000030182158
0000030182165
0000030182172
0000030182189
0000030182196
0000030182202
0000030182219
0000040122250
0000040122274
0000040144108
0000040144283
0000040198651
0000040198668
We don't want to change the lc / lang field (main language of the product), and we don't have want to add a new data source.
> change import_csv_file.pl to allow imports without an org and without setting lc and lang

- lib/ProductOpener/Tags.pm
This is to give us time to gradually fix errors in the categories taxonomy: #6382
> Temporarily disable checks for categories taxonomy

- taxonomies/labels.result.txt
- taxonomies/labels.txt
We now have stronger checks in the taxonomy build process to verify that the same translation in one language is not set for 2 different taxonomy entries.
This fixes the following errors:
Errors in the labels taxonomy definition:
ERROR - ru:обогащено-кальцием already is associated to en:calcium-source - ru:обогащено-кальцием cannot be mapped to entry en:high-in-calcium
ERROR - ru:низкожирный-или-обезжиренный already is associated to en:low-or-no-fat - ru:низкожирный-или-обезжиренный cannot be mapped to entry en:low-fat
ERROR - th:ไขมันต่ำ already is associated to en:low-or-no-fat - th:ไขมันต่ำ cannot be mapped to entry en:low-fat
ERROR - th:โซเดียมต่ำ already is associated to en:low-sodium - th:โซเดียมต่ำ cannot be mapped to entry en:low-or-no-salt
ERROR - he:מופחת-מלח already is …
> fix: correct errors in labels taxonomy

- taxonomies/labels.txt
> Added translations in Bulgarian in Taxonomies

- lib/ProductOpener/Tags.pm
- scripts/build_countries_taxonomy_from_wikidata.pl
- taxonomies/countries.result.txt
- taxonomies/countries.txt
> fix: rename languages:en to language_codes:en in countries taxonomy

- html/js/product-multilingual.js
- lib/ProductOpener/Images.pm
- templates/web/pages/import_file_upload/import_file_upload.tt.html
Fixes #173
The file upload buttons (for images, and data file on producers platform) have a <a href="#"> link that encapsulate a <input> button. But the button works only in the top half, clicking on the lower half makes the page jump to the top of the page.
There were 2 issues:
- the input button was only half height, fixed by height:100%
- the href="#" makes the browser go to the top of the page (as identified by @chk1).
> fix: fix image upload buttons

- Makefile
- docker/dev.yml
Make tests run in isolation.
We now have integration tests, avoid destroying dev database each time he wants to run tests.
> build: make tests run in isolation

- .github/labeler.yml
- po/common/common.pot
- po/common/en.po
- templates/api/knowledge-panels/environment/ecoscore/ecoscore_unknown.tt.json
- Fix untranslated string for Smoothie
> fix: untranslated string for Smoothie

- html/js/product-search.js
- lib/ProductOpener/Attributes.pm
- scss/_off.scss
- t/expected_test_results/attributes/en-attributes.json
- t/expected_test_results/attributes/en-ecoscore-score-at-20-threshold.json
- t/expected_test_results/attributes/en-maybe-vegan.json
- t/expected_test_results/attributes/en-nutriscore.json
- t/expected_test_results/attributes/fr-palm-kernel-fat.json
- t/expected_test_results/attributes/fr-palm-oil-free.json
- t/expected_test_results/attributes/fr-palm-oil.json
- t/expected_test_results/attributes/fr-vegetable-oils.json
- templates/web/panels/panel.tt.html
- Implements #6354
- added a new optional panel_id field in attributes (for nutriscore, ecoscore, nova, additives, vegan, vegetarian, palm oil free) to link to the corresponding knowledge panel
- implemented the link in the web interface: summary cards for attributes at the top of the product page are now clickable, and clicking them makes the page jump to the corresponding knowledge panel and opens it.
> feat: link product attributes to knowledge panels

- .github/workflows/release-please.yml
We need actions to be triggered by release please this means using a personal access token instead of the default one.
The secret is already created in the repo.
> fix: release please should trigger actions

- lib/ProductOpener/Ingredients.pm
- t/expected_test_results/ingredients/fi-additives-percents.json
- t/expected_test_results/ingredients/fr-chocolate-cake.json
- t/ingredients_percent.t
fixes #6524 
Some manufacturers list absolute % in sub-ingredients, while others list % values that are relative to the sub-ingredient.
We assume that % for sub-ingredients are absolute, this fix detects some cases where the % are relative.
> fix: handle both absolute and relative percent values for sub-ingredients

- po/common/en.po
> fix: Remove duplicate string

- templates/web/common/site_layout.tt.html
Formatted the titles of the footers as headings with an `<h3>` tag as prescribed in the [Report](https://github.com/openfoodfacts/openfoodfacts-server/files/5702582/Report.OpenFoodFact.15-12-2020.pdf)
- Fixes #6535
- A part of this issue thread #4640
> fix: Format footer titles as headings in code

- lib/ProductOpener/Display.pm
- po/common/common.pot
- po/common/en.po
- po/common/hi.po
This PR was made to fix Issue #6332
> fix: Makes "Unselect Image" button translatable

- html/js/product-search.js
Added missing double quote
n/a
https://openfoodfacts.slack.com/archives/C1G3M3D4H/p1649314340339339
> fix: Adds missing double quote to the href attribute

- lib/ProductOpener/Ecoscore.pm
Seeing:
```
Argument "Transformation" isn't numeric in addition (+) at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 139, <$io> line 8.
Argument "Emballage" isn't numeric in addition (+) at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 139, <$io> line 8.
Argument "Transport" isn't numeric in addition (+) at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 139, <$io> line 8.
Argument "Supermarch\x{e9} et distribution" isn't numeric in addition (+) at /opt/product-opener/lib/ProductOpener/Ecoscore.pm line 139, <$io> line 8.
```
Errors. This may be from adding 0 to an undefined value rather than using a default.
There was no ecoscore popping up on the products on the local dev environment. I see them on the app. Though I'm not sure how to test there. Or quite what to …
> fix: skip last header line in csv

- templates/web/common/includes/display_login_register.tt.html
- templates/web/pages/change_password/change_password.tt.html
- templates/web/pages/login_form/login.tt.html
- templates/web/pages/reset_password/reset_password.tt.html
This change makes the experience of using a screen reader better for visually impaired people. (prescribed in the [Accessibility Report](https://github.com/openfoodfacts/openfoodfacts-server/files/5702582/Report.OpenFoodFact.15-12-2020.pdf))
This ensures that assistive technology can refer to the correct label when presenting a form control.
- Fixes #6576
- A part of this issue thread https://github.com/openfoodfacts/openfoodfacts-server/issues/4640
> fix: Add explicit labels (using: for & id) to input fields 

- lib/ProductOpener/Users.pm
It's possible to create a new user account with an email address that contains spaces.
- Fixes #4549
- Modified email was not updated to variable after email validation.
> fix: Email address with space

- .github/dependabot.yml
- Ensure that Dependabot is not blocked because of unmerged deps updates
- Fix error with semantic commit: The property '#/updates/0/' contains additional properties ["commit_message"] outside of the schema when none are allowed
> ci: Ensure that Dependabot is not blocked

- lib/ProductOpener/Display.pm
I was seeing:
```
[Wed Apr 13 13:08:09 2022] -e: CGI::param called in list context from /opt/product-opener/lib/ProductOpener/Display.pm line 879, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /opt/perl/local/lib/perl5/CGI.pm line 415.
```
Which according to 
https://stackoverflow.com/questions/18668966/perl-cgi-module-passing-param-as-parameters-to-subroutines  
it can be solved by forcing a scalar; with this commit, I am no longer seeing the warning.
> fix: Setting param to return scalar

- lib/ProductOpener/Food.pm
- t/expected_test_results/nutriscore/en-orange-juice-category-and-ingredients.json
- t/expected_test_results/nutriscore/en-orange-juice-category.json
- t/nutriscore.t
- changed the order for the source of the fruits/vegetable estimate, as the estimate from the category is less reliable (a lot of examples seen in a recent producer export: wrong category + too optimistic estimates for some categories).
- added some tests
fixes #6598
> fix: Give priority to ingredients over category to estimate fruits/vegetable content for Nutri-Score

- lib/ProductOpener/Ingredients.pm
- t/ingredients_percent.t
fix for #6612
This change 2 rules to compute percent min and percent max of ingredients based on the other ingredients min and max.
You can see the difference of result in this commit as I first added a test that demonstrated the issue: https://github.com/openfoodfacts/openfoodfacts-server/commit/cba72e31ae084117f42dd8506dd9ff64c6249613
> fix: more precise estimate of ingredients percents min and max

- lib/ProductOpener/Users.pm
- scripts/delete_spam_users.pl
> fix: check for user creation spam 

- .github/workflows/github-projects.yml
- README.md
- taxonomies/additives.txt
- taxonomies/categories.txt
Wkidata entries get merged overtime. So, exceptions were generated in the Android app due to this merge. 
Affected wikidata due to merge:
- Q63534992
- Q2366206
- Fixes #6530 
- Updated additives.txt and categories.txt taxonomies with new values.
> fix: Wikidata entries to update

- lib/ProductOpener/Display.pm
Fixes "Use of uninitialized value" warning. This value didn't use a test for if it was defined but the other uses of it had a test for definition, so I added one here as well.
> fix:  warning message

- docs/introduction/dev-environment-quick-start-guide.md
Fixes #6640: Enable the Developer Mode on Windows to use Symlinks in dev-environment-quick-start-guide.md
The project requires Symlinks. On Windows, you need to enable the Developer Mode to use Symlinks.
On Windows, You have to enable the 'Developer Mode' in order to use the symlinks.
To enable Developer Mode: Go under Settings > Update & Security > 'For developers', and turn on the toggle for Developer Mode.
- Fixes #6639 
- Fixes #6640
> docs: Enabling Developer Mode on Windows to use symlinks

- cgi/user.pl
- po/common/common.pot
- po/common/en.po
- templates/web/pages/user_form/user_form_page.tt.html
Implements an additional check to see if an org associated with the user is defined before executing the code block. 
This fixes an uninitialized value warning.
`[Sun Apr 17 11:00:58 2022] -e: Use of uninitialized value in concatenation (.) or string at /opt/product-opener/cgi/user.pl line 208.
`
> fix: Add check for the definition of $user_ref->{org}

- po/common/common.pot
- po/common/en.po
- templates/api/knowledge-panels/environment/ecoscore/ecoscore.tt.json
- templates/api/knowledge-panels/health/nutriscore/nutriscore.tt.json
> feat: add link to learn more about nutriscore + ecoscore

- lib/ProductOpener/Config_off.pm
- use GA4 with as much privacy as possible
- setup Matomo to eventually replace GA4
> feat: google anaytics 4 and matomo for OFF

- lib/ProductOpener/I18N.pm
Documented the `ProductOpener::I18N.pm` file in `perlpod` format.
- Related Issue https://github.com/openfoodfacts/openfoodfacts-server/issues/2203
- Part of https://github.com/openfoodfacts/openfoodfacts-server/issues/5559
> docs: Document the I18N module using perl-pod format

- taxonomies/additives.txt
Natriumcarbonat and Ammoniumcarbonat doesn't have a "e" in German, but producers sometimes write in "Natriumcarbonate" and "Calciumcarbonate" on the packaging so I added the synonym for "Ammoniumcarbonat" and put the correct spelling first for "Natriumcarbonat".
> chore: DE Natriumcarbonat(e) and Ammoniumcarbonat(e)

- lib/ProductOpener/Display.pm
On the main page I was seeing the following warning:
```
[Sun May  1 16:45:15 2022] -e: Use of uninitialized value $current_link_query in concatenation (.) or string at /opt/product-opener/lib/ProductOpener/Display.pm line 5411.
```
And on the search page I was seeing:
```
[Sun May  1 16:54:12 2022] -e: Use of uninitialized value $current_link in concatenation (.) or string at /opt/product-opener/lib/ProductOpener/Display.pm line 5411.
```
This seems to be because they weren't being tested for definition, which was happening later on in the code.
> fix: tests if variable defined before use

- lib/ProductOpener/Tags.pm
This is to remove synonyms that are not tags from root level tags in the taxonomy.
e.g. in https://world.openfoodfacts.org/api/v2/taxonomy?tagtype=categories&include_root_entries=1&include_children=0&lc=en%2Cfr&cc=fr&fields=name
Remove entries like:
en:sandwich-made-with-french-bread: {
name: {
en: "Sandwich made with French bread"
}
},
Part of #6763
> fix: taxonomies API: remove synonyms from root level tags 

- po/common/tr.po
- t/lang.t
Related to #6702
This PR makes the tests fail if some translations removed some {variables}:
```
not ok 743 - f_app_user translation in uk contains {app_name}
Wide character in print at /opt/perl/local/lib/perl5/Test2/Formatter/TAP.pm line 125.
not ok 744 - f_energy_expenditure_for_weight_in_kg_lb translation in uk contains {kg}
Wide character in print at /opt/perl/local/lib/perl5/Test2/Formatter/TAP.pm line 125.
not ok 745 - f_energy_expenditure_for_weight_in_kg_lb translation in uk contains {lb}
Wide character in print at /opt/perl/local/lib/perl5/Test2/Formatter/TAP.pm line 125.
not ok 746 - f_nova_markers_for_nova_group translation in es contains {nova_group}
Use of uninitialized value in pattern match (m//) at lang.t line 85.
en: Elements that indicate the product is in the …
```
> feat: check {variables} are kept in translations 

- html/js/product-search.js
Food preferences set to mandatory are now counted in the score of products (same weight as "very important").
> fix: use mandatory food preferences for score

- lib/ProductOpener/KnowledgePanels.pm
- templates/api/knowledge-panels/health/health_card.tt.json
- templates/api/knowledge-panels/health/nutrition/serving_size.tt.json
Added a panel to display portion size in health panel.
- Fixes #6777
> feat: add serving size to health knowledge panel

- cgi/search.pl
In search.pl search_and_display_products is called without defining $request_ref->{current_link} resulting in a warning about an undefined variable. current_link and current_link_query appear to be the same where I see them in the logs. So defining it this way may be alright, though I haven't looked at what process_template ends up doing with template_data_ref which is where the error is coming from. I have yet to understand what current_link and current_link_query are and how they are different from another. They appear to be the path and the arguments, but I'm not sure and could use some guidance.
> fix: defining current_link

- html/js/product-search.js
- lib/ProductOpener/Attributes.pm
- t/expected_test_results/attributes/en-attributes.json
- t/expected_test_results/attributes/en-ecoscore-score-at-20-threshold.json
- t/expected_test_results/attributes/en-maybe-vegan.json
- t/expected_test_results/attributes/en-nova-groups-markers.json
- t/expected_test_results/attributes/en-nutriscore.json
- t/expected_test_results/attributes/fr-palm-kernel-fat.json
- t/expected_test_results/attributes/fr-palm-oil-free.json
- t/expected_test_results/attributes/fr-palm-oil.json
- t/expected_test_results/attributes/fr-vegetable-oils.json
Fixes #6810
- Panel ids for ingredients analysis properties are now all in this format: ingredients_analysis_[value of the ingredients_analysis_tag]
e.g. ingredients_analysis_en:may-contain-palm-oil
- Attributes link to the same panel ids
- On the website interface, some elements ids include the panel id (to create links). The : character is replaced by -.
> fix: make panel ids consistent for ingredients analysis knowledge panels

- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- lib/ProductOpener/Tags.pm
- templates/api/knowledge-panels/environment/ecoscore/ecoscore_extended.tt.json
- templates/api/knowledge-panels/environment/ecoscore/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/environment/ecoscore/packaging.tt.json
- templates/api/knowledge-panels/environment/label.tt.json
- templates/api/knowledge-panels/environment/manufacturing_place.tt.json
- templates/api/knowledge-panels/environment/origins_of_ingredients.tt.json
- templates/api/knowledge-panels/environment/packaging_recycling.tt.json
- templates/api/knowledge-panels/health/ingredients/additive.tt.json
- templates/api/knowledge-panels/health/ingredients/nova.tt.json
> fix: fallback to english for knowledge panels

- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Food.pm
- lib/ProductOpener/KnowledgePanels.pm
- lib/ProductOpener/Lang.pm
- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- t/ecoscore.t
- t/expected_test_results/ecoscore/exempted-category-sodas.json
- t/expected_test_results/nutriscore/en-beers-category.json
- t/nutriscore.t
- taxonomies/categories.txt
- templates/api/knowledge-panels/environment/ecoscore/ecoscore_not_applicable.tt.json
When a product does not have a Nutri-Score or an Eco-Score because the product category is excluded from the Nutri-Score and Eco-Score, we now explain why in the corresponding knowledge panel, and we list the category.
Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/6092 and https://github.com/openfoodfacts/openfoodfacts-server/issues/6774
> feat: add explanation with category in the Nutri-Score and Eco-Score knowledge panels when not applicable

- lib/ProductOpener/Products.pm
- t/products.t
fixes #6847
This is for Smoothie (and other apps) which sends both a user uuid + if the user is logged in, the userid. The previous code expected we would only get one or the other.
> fix: prefer real user userid to app uuid

- lib/ProductOpener/Data.pm
Documented the `execute_query()`, `get_mongodb_client()` and `get_products_collection()` subroutines.
- #6858
> docs: Add perlpod documentation for the Data module

- templates/api/knowledge-panels/health/nutrition/nutrition_facts_table.tt.json
The openfoodfacts-dart package expects a non null title for the table elements in knowledge panels. This adds back the table title that was removed in https://github.com/openfoodfacts/openfoodfacts-server/pull/6839
Hot fix deployed in production as it was breaking scanning and searching in Smoothie.
Related:
https://github.com/openfoodfacts/smooth-app/issues/2203
https://github.com/openfoodfacts/openfoodfacts-dart/issues/477
> fix: add back nutrition facts table title in knowledge panel

- cgi/search.pl
- lib/ProductOpener/Display.pm
- t/display.t
- templates/web/common/includes/list_of_products.tt.html
Potential fix for https://github.com/openfoodfacts/openfoodfacts-server/issues/6819
current_link and current_link_query appear to be the same when I saw them. The primary difference appears to have been that current_link was the current link without arguments however this was applied inconsistently. And where I saw it, it usually had arguments.
The most clear place that this difference was evident that I found was
https://github.com/openfoodfacts/openfoodfacts-server/blob/f63cb9cc0bd75ffa5526d2c1ffe63123d4633f7e/lib/ProductOpener/Display.pm#L5469
As pages can be reached both by url/<number> or url?page=<number>. The former was used when "current_link" was defined and the latter when "current_link_query" was defined. Since both were possible, it seemed reasonable to drop the index function …
> refactor: Refactor and document current_link / current_link_query

- lib/ProductOpener/Food.pm
- t/food.t
I made a mistake 6 months ago when removing nutrients from Food.pm to use the nutrients taxonomy instead, and the nutrients added with %DV (daily values) or IU (International Units) were not converted correctly to grams.
This fixes it and adds some tests.
Fixes #6882
> fix: use correct unit for nutrients expressed in IU or %DV 

- cgi/suggest.pl
- lib/ProductOpener/Tags.pm
fixes: https://github.com/openfoodfacts/openfoodfacts-dart/issues/465
Also add fuzzy searching.
> feat: suggest fuzzy + limit as a param

- conf/nginx/sites-available/off
redirect to https://blog.openfoodfacts.org/en/press-release-new-mobile-app
> feat: redirect the press to new app blog post (nginx config)

- cgi/search.pl
- lib/ProductOpener/Display.pm
$request_ref->{count} shows up 4 times in the code. Though it never appears to be used as three of the times that it appears it is only to define it. The remaining instance that it appears such that it is referenced, does not seem to benefit from the previous three instances where the value is defined. As such this appears to be unused. This commit removes all four instances.
> fix: $request_ref->{count} not used

- lib/ProductOpener/Display.pm
- t/display.t
$lc appears to default to German (de), though how would we test other language codes? Changing $lc in display.t doesn't seem to have an effect. How might we test other languages?
> test: unit test for url_for_text

- t/display.t
I made a few unit tests for `display_preferences_api`, however it doesn't technically work yet. It only works when [line 9889](https://github.com/openfoodfacts/openfoodfacts-server/blob/e03e2e196fd27d5f18cabcb1ad073c7a3400d8c3/lib/ProductOpener/Display.pm#L9889) is commented out.
Without it commented out I get this error:
`Can't locate object method "request" via package "Apache2::RequestUtil" at /opt/product-opener/lib/ProductOpener/Display.pm line 10414.`
But I'm not quite sure how to fix it.
> test: display_preferences_api unit tests

- cgi/search.pl
Add conditional as without it this will make a dead link resulting in a 404
It is not clear to me what the link in this section does and it is not visible on the page. It may be used for search engines? 
If `$request_ref->{current_link_query_display}` isn't defined, and we select the link in the source, it leads to a 404. As it stands without that defined it appears to be broken, though I'm not certain that we don't want this information here even with a dead link. Perhaps we want something more like `$request_ref->{current_link}`?
> fix: uninitialized value

- t/tags.t
- taxonomies/ingredients.txt
This PR adds a unit test for checking the implemented fix and appends _"edible"_ to the list of English **_"stopwords"_**
Observing in issue #6941, most of the unknown-tagged ingredients could be fixed if we ignore the word **_edible_**.
- commit-1: Added a test that should break unless a fix is implemented. **[Confirmed it breaks]**
- commit-2: Added edible to the list of English stopwords
- Fixes #6941
> feat: "edible" should be recognized as a stop word

- t/ingredients_analysis.t
- taxonomies/categories.txt
- taxonomies/ingredients.txt
- Refined wheat flour and _maida_ are two terms that are used interchangeably to refer to white colored/all-purpose flour in the Indian subcontinent.
- Related Discussion #6540
> fix: "refined wheat flour" and "maida" should be recognized as a type of flour

- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
The panel can be reactivated by passing activate_knowledge_panel_physical_activities=1
> feat: deactivate physical activities equivalence panel

- lib/ProductOpener/Tags.pm
This function is defined, but doesn't seem to be used.
> refactor: remove capitalize_tag

- lib/ProductOpener/ImportConvert.pm
This function appears to only be defined, but never called.
> refactor: remove apply_global_params_to_all_products

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Orgs.pm
1. `display_top_block()` only had a usage in some commented-out code.
2. `org_link()` seems to be unused.
> refactor: removing possibly redundant subs

- lib/ProductOpener/Display.pm
There seemed to be two of the same if statements:
`if (defined $jsonp) {`
So I combined the two
> fix: display_structured_response syntax

- lib/ProductOpener/Tags.pm
This function gets defined, but never used.
> refactor: remove display_tags_list_orig

- lib/ProductOpener/Ingredients.pm
normalize_fr_a_de_enumeration gets defined, but not used.
> refactor: remove normalize_fr_a_de_enumeration

- lib/ProductOpener/Users.pm
Cleans up
- `save_user()`
- ` create_user()`
- `user_path()`
These methods are still declared and in the code but they are not being used currently due to revisions to the code over time and creation of some methods like `user_init()`
> refactor: clean up redundant methods from `User.pm`

- lib/ProductOpener/Index.pm
This function gets defined and exported, however, it doesn't get called.
> refactor: remove decode_html_utf8

- lib/ProductOpener/Orgs.pm
The associated function was removed in 6d2d1ba74ec8e475b9094b6204f62030d08d516b, cleaning up leftover export line.
> refactor: removing unused export

- lib/ProductOpener/Text.pm
This function gets defined and exported, however, no functions call it.
> refactor: remove remove_tags_except_links

- lib/ProductOpener/Products.pm
add_users_team gets exported but there is no associated function. Possibly a typo from 0dc31de78cd, supposed to be add_user_teams not add_users_team?
> refactor: remove add_users_team unused export

- lib/ProductOpener/Ecoscore.pm
This variable appears to be defined, but not used.
> refactor: headers_ref unused variable

- lib/ProductOpener/Lang.pm
This export doesn't seem to have a matching function.
> refactor: init_languages unused export

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Tags.pm
Having helper functions where ever we have multiple calls to a function (let's say to `has_tag` like in this case).
I think it makes the if statements look much cleaner and keep the code organized. Also, this offers somewhat better reusability because we can simply add another parameter to the list (in this case, of brands)
_Not sure if I've declared it at the appropriate place. Should it be in `tags.pm`?_
> refactor: add helper function to identify if a product bears a certain tag from a passed list

- lib/ProductOpener/Food.pm
This function gets defined and exported, but it doesn't get called nor does it call another function.
> refactor: remove kcal_to_unit

- .gitbook.yaml
telling gitbooks that docs are in the /docs directory
cf https://www.baseten.co/blog/docs-as-code
> docs: add .gitbook.yaml

- lib/ProductOpener/Ingredients.pm
- t/expected_test_results/ingredients/en-origin-field.json
- t/expected_test_results/ingredients/fr-origin-field.json
- t/ingredients.t
Fixes partially #4461 (we could add support for more ways to describe ingredients, like "Strawberries from Spain").
Needed in particular for one producer who sent us data in the origins of ingredients field, in order to have it used for the Eco-Score computations.
> feat: parse origins of ingredients field

- lib/ProductOpener/Recipes.pm
Replacing the "shift" perl prototypes to perl signatures in Recipes.pm
> refactor: replace perl "shift" prototype in `Recipes.pm`

- lib/ProductOpener/Index.pm
- lib/ProductOpener/Products.pm
- lib/ProductOpener/Users.pm
- Documenting `products.pm` and `user.pm` methods
- removal of a possibly unused sub in `Index.pm`
- proposal to remove[ this ](https://github.com/openfoodfacts/openfoodfacts-server/compare/docs/po-modules?expand=1#diff-d6b9a7ba08e9ecb060d8284b1bd62bcd2861eccd7d3f65f479830b915c679761R2201) (has only been utilized in an obsolete script)
> docs: add documentation for some methods in `user.pm` and `products.pm` 

- lib/ProductOpener/Display.pm
Since https://github.com/openfoodfacts/openfoodfacts-server/pull/7009/files was merged, I figured we should start replacing the Perl prototypes with Perl signatures. I replaced a few of the "shift" prototypes in Display.pm
> refactor: replace perl "shift" prototype in `Display.pm`

- lib/ProductOpener/Test.pm
Switching "shift" prototypes to perl signature
> refactor: replace perl shift prototype in Test.pm

- lib/ProductOpener/Display.pm
We use Perl 5.24 in production today, and state arrays and hashes can't be initialized:
off@off1:/srv/off-pro/scripts$ perl ../lib/startup_apache2.pl  
Initialization of state variables in list context currently forbidden at ProductOpener/Display.pm line 10153, near ");"
Reverting to a normal variable for now.
> fix: Initialization of state variables in list context currently forbidden (perl version < 5.28)

- CONTRIBUTING.md
- README.md
- docs/how-to-guides/use-gitpod.md
- docs/introduction/dev-environment-quick-start-guide.md
Document setting up a functional remote `openfoodfacts-server` development environment on gitpod.io.
- Fixes `nil`
> docs: Add how-to for remote dev (Gitpod)
