openfoodfacts/openfoodfacts-server

lib/ProductOpener/Ingredients.pm
Adding explicit return statements to subroutines without them in `Ingredients.pm`
=> fix: explicit return statements in `Ingredients.pm`

lib/ProductOpener/Attributes.pm
Adding explicit return statements to subroutines without one in Attributes.pm
=> fix: explicit return statements in `Attributes.pm`

lib/ProductOpener/ForestFootprint.pm
Adding explicit return statements to subroutines without them. I'm planning on putting the rest of the return statements all in one PR
=> fix: explicit return statements in `ForestFootprint.pm`

lib/ProductOpener/APITest.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/Food.pm, lib/ProductOpener/FoodGroups.pm, lib/ProductOpener/ForestFootprint.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/ImportConvert.pm, lib/ProductOpener/ImportConvertCarrefourFrance.pm, lib/ProductOpener/MainCountries.pm, lib/ProductOpener/Orgs.pm, lib/ProductOpener/PackagerCodes.pm, lib/ProductOpener/Packaging.pm, lib/ProductOpener/PerlStandards.pm, lib/ProductOpener/Recipes.pm, lib/ProductOpener/Test.pm, lib/ProductOpener/Users.pm
Adding return statements to subroutines without them. There should be no more subroutines without return statements at the moment.
=> fix: return statements

.perltidy_excludes, cgi/ingredients.pl, cgi/login.pl
Implementing perltidy to `cgi/ingredients.pl`, `cgi/login.pl`, `cgi/manifest.pl`
=> refactor: adding perltidy to files

lib/ProductOpener/Producers.pm
Recognize some columns automatically in file provided by Packtic
=> fix: columns synonyms for Packtic import

.perlcriticrc, lib/ProductOpener/Tags.pm
Adding `BuiltinFunctions::RequireBlockGrep` and `BuiltinFunctions::RequireBlockMap` to .perlcriticrc
=> refactor: require grep and map blocks

Makefile
The example command to make a single test was outdated
=> fix: fix the old usage example in makefile

lib/ProductOpener/Ingredients.pm
I'm planning on adding `[Variables::ProhibitReusedNames]` after fixing all of its warnings. There are 2 more reused variable warnings, however I wanted to make sure that I was doing this correctly before working on them
=> fix: `Ingredients.pm` reused variables

cgi/login.pl, cgi/product_image.pl, cgi/reset_password.pl, cgi/session.pl
fixes an issue related to the init_request refactor: https://github.com/openfoodfacts/openfoodfacts-server/pull/7106
fixes #7125
=> fix: finish cookie / init_request refactor

.perlcriticrc
Adding `[ControlStructures::ProhibitDeepNests]` to .perlcriticrc and limiting nesting to 12 (12 appears to be the most amount of nesting done). I'm planning on adding this for now so that no one can add deeper nesting
=> feat: Deep nest limit 12

.perlcriticrc
Adding `[ControlStructures::ProhibitCascadingIfElse]` to .perlcriticrc and limiting the amount of if's/elsif's to 13 (13 appears to be the highest amount of if's/elsif's). I'm planning on adding this for now so that no one can add even more than 13
=> feat: Cascading elsif limit 13

lib/ProductOpener/APITest.pm, tests/integration/create_user.t
Manually making requests to urls in code could be error prone.
We can pass a prefix and the target path to construct a url to make an http request
=> chore: add construct url sub for tests

lib/ProductOpener/Config2_docker.pm
This fixes the activation of the producers platform (using setenv-pro.sh).
It also removes a lot of warnings when the producers platform is not activated (the variable is expected to have a value, we don't check if it's defined when we use it in the code to activate specific producers platform features.
=> fix: activate the producers platform with PRODUCER_PLATFORM env variable

lib/ProductOpener/Ingredients.pm
Planning on adding `[Variables::ProhibitReusedNames]`, currently cleaning up all of its warnings before adding it in.
Edit: For more info -> https://metacpan.org/pod/Perl::Critic::Policy::Variables::ProhibitReusedNames
=> refactor: reused variables in Ingredients.pm

.perlcriticrc, lib/ProductOpener/KnowledgePanels.pm
Adding `[ValuesAndExpressions::ProhibitMixedBooleanOperators]` to .perlcriticrc
This policy doesn't allow low-precedence booleans to be combined with high-precedence boolean operators in the same expression.
=> refactor: Prohibit mixed boolean operators policy

html/js/folksonomy.js
fix: Fix typos in the Folksonomy JS code
=> fix: Fix typos in the Folksonomy JS code

cgi/import_file_select_format.pl
I was checking for some reused variables and found these two variables defined twice. I assume that this is a typo?
=> refactor: repeated lines typo

lib/ProductOpener/ImportConvert.pm
Replacing "shift" prototypes with perl signatures.
There are a few lines like this:
```
shift @{$xml_fields_mapping_ref};
```
And I'm not sure what to do with them. Could they be deleted?
=> refactor: enable perl signatures in ImportConvert.pm

taxonomies/ingredients.txt
Made two edits to ingredients list, to add breading as a synonym for bread crumbs, and added whole grain flour blend as a child of flour blend. Fixes issue on entry for [Trader Joe's chickenless crispy tenders](https://world.openfoodfacts.org/product/00978996/chickenless-crispy-tenders-trader-joe-s)
=> taxonomy: add breading and whole grain flour blend

lib/ProductOpener/Export.pm
Taking the most deeply nested part of Export.pm and putting it into a separate function.
=> refactor: reduce nesting in Export.pm

lib/ProductOpener/Display.pm, tests/unit/display.t
fixes #7161
There's something different between docker and production:
in Docker, the QUERY_STRING environment variable is prefixed by / , but not in production. This caused issues with redirect URLs reconstructed with the query string.
=> fix: pb with initial slash in query string of redirects 

cgi/import_file_upload.pl, cgi/import_photos_upload.pl, cgi/import_products_categories_from_public_database.pl, cgi/ingredients.pl, cgi/login.pl
Replacing `Modern::Perl` and `utf8` with `PerlStandards`
=> refactor: perl signature cgi files

cgi/manifest.pl, cgi/minion_job_status.pl, cgi/nutrients.pl, cgi/nutrition.pl, cgi/opensearch.pl
Replacing `Modern::Perl` and `utf8` with `PerlStandards`
=> refactor: `cgi/` perl signatures

lib/ProductOpener/Display.pm
the session cookie was not sent in 302 redirects
This is needed in particular for Kratos auth: https://github.com/openfoodfacts/openfoodfacts-server/pull/7071
=> fix: send set-cookie headers in redirects

lib/ProductOpener/Products.pm, scripts/update_all_products.pl
There was an issue for barcode changes, the mongodb _id field got a number long type instead of a string.
This:
- fixes the issue so that _id is always stored as a string
- adds a --fix-non-string-ids command to the update_all_products.pl script
Once deployed, we need to:
run ./update_all_products.pl --fix-non-string
issue the MongoDB command indicated at the end of the script run:
products stored in MongoDB with a non string _id have been reloaded from .sto files (if the products still exist) and stored with a string _id.
products with non string ids can now be deleted from MongoDB with this command:
db.products.remove({_id : { $type : "long" }})
Fixes #4667
=> fix: mongodb _id must be a string

tests/integration/search_test.t
@yuktea : I added error messages in the test so that if something fails, we can see in the test logs what failed exactly.
Here the test shows that we can't decode the JSON response of the API because in fact we did not get a response.
You could do something similar when you call get() in order to catch errors.
See: https://metacpan.org/pod/LWP::UserAgent#get
Instead of calling get() directly, you can call 
my $res = $ua->get( $url );
That way you can check the status code of the response etc. in the test, and print it in the test log if it fails.
=> refactor: show more info in test logs

scripts/export_database.pl
Should fix #2426.
Script not tested, in itself, but I have done some successful tests with:
`perl -ne 'print if /(\xE2\x80\xA8|\xE2\x80\xA9|[\000-\007\013-\037])/' en.openfoodfacts.org.products.csv`
I suggest to control in production.
=> fix: broken CSV (#2426)

taxonomies/categories.txt
• Link all **Poularde*** to new generic parent Poulardes and assign Chapons Agribalyse proxy
• Move Agribalyse code to parent en:**artichokes** categ : all other fruits and veg. have the "fresh" subcateg linked to the parent, and it is the parent that has the Agribalyse code
• fr:**morbier** had double entry [removed] ; Wikidata for double entry was wrong : moved to correct place in Tomme de Savoie
• Create **Cerfeuil tubéreux** with Agribalyse proxy on Parnips
=> taxonomy: Create generic categ Poulardes

cgi/display.pl, cgi/export_products.pl, cgi/import_file_process.pl, cgi/import_file_select_format.pl, cgi/import_file_upload.pl, cgi/import_photos_upload.pl, cgi/import_products_categories_from_public_database.pl, cgi/org.pl, cgi/product_image.pl, cgi/product_multilingual.pl, cgi/remove_products.pl, cgi/reset_password.pl, cgi/search.pl, cgi/user.pl, lib/ProductOpener/Display.pm, lib/ProductOpener/Users.pm
Fixes #7330 .
Also fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/7288 which should help https://github.com/openfoodfacts/smooth-app/issues/2793#issuecomment-1234184480
I renamed display_error() to display_error_and_exit() to make it more clear what the function actually does.
I tried a bunch of different ways to make Apache / mod_perl send back a non 200 status code while not appending a default error body, and the only solution that seems to work is to output the 404 status code and tell Apache it is a 200.
=> fix: prevent default mod_perl error message to be appended

po/common/common.pot, po/common/en.po, po/openbeautyfacts/en.po, po/openbeautyfacts/openbeautyfacts.pot
- fix: Change the URL of the blog in the footer
- The URL in the footer is still en.blog.openfoodfacts.org
- The SSL for en.blog.openfoodfacts.org has not been renewed https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/137
- We're loosing visitors due to the combination of those 2 bugs
=> fix: Change the URL of the blog in the footer

conf/nginx/sites-available/off
for non french countries
- fixes: #7389 
de.openfoodfacts.org/ecoscore did a wrong redirect to french page, as well as any non french country…
I changed the nginx redirect rule (yes this is one of the case [where a if is ok](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/))
**this is already deployed on production (off1)**
=> fix: fix /ecoscore redirect

taxonomies/categories.txt
Some tags lists had orphan commas (empty tag)
=> taxonomy: fix typos

taxonomies/countries.txt
Added missing countries in HR
FYI, I used wikidata, wikipedia and the Croatian encyclopedia (https://www.enciklopedija.hr/, from the Miroslav Krleža Lexicographic Institute) as sources.
=> taxonomy: added some missing countries in HR

cgi/auth.pl, lib/ProductOpener/Display.pm
This is to address #7361 so that the Flutter app can get the username and name of an user who authenticated with an email address.
but it could also be a step to have a more uniform handling of errors in the API (specifically errors related to users not identified or bad logins and passwords supplied).
I'm proposing that we extend the /cgi/auth.pl API which currently:
- checks if an user is identified (either through a session cookie on the *.openfoodfacts.org domain, or by passing user_id and password)
- returns a 200 status code if the user is logged in, or a 403 otherwise
The extension would be to add a JSON body:
- when the user is logged in:
```json
{
"status": 1,
"status_verbose": "user signed-in",
"user": {
"email": "my email",
"name": "Stéphane Gigandet"
},
"user_id": "test2"
} …
```
=> feat: API to login and get user username, name and email 

templates/web/common/includes/donate_banner.tt.html
This is to make the donate banner less tall on small screens.
Small screen:
No change for medium screens and large screens:
=> fix: more responsive donate banner

taxonomies/categories.txt
Improvements of the category taxonomy, spotted when working on the category matching algorithm.
- en:Teas should be below en:Tea-based beverages instead of the more generic category en:Beverages
- en:Cereal pastas are also en:Pastas
- add italian translations
=> taxonomy: improve category taxonomy

cgi/auth.pl
This is to fix https://github.com/openfoodfacts/smooth-app/issues/3118
auth.pl?body=1 --> returns a JSON body
auth.pl --> does not return a body
Plan:
- update openfoodfacts-dart to call auth.pl?body=1 and expect a JSON body
- deploy new Flutter app
Possibly:
- wait until most instances of the apps have been updated
- make sending a body the default for auth.pl
cc @M123-dev @monsieurtanuki
=> fix: add body parameter to auth.pl

templates/web/pages/product_edit/product_edit_form_display.tt.html
=> fix: display front image first in product edit form 

.github/labeler.yml
ci: Labeler on templates to help with fixing the redesign
- #5512
=> ci: Labeler on templates to help with fixing the redesign

.env, cpanfile, lib/ProductOpener/Products.pm, lib/ProductOpener/Redis.pm
As in dev people don't necessarily have openfoodfacts-search running
We also changed lib to Redis which is better maintained, and handle connection timeout.
=> fix: default redis url to empty and handle reconnects

html/data/data-fields.md, html/data/data-fields.txt, lib/ProductOpener/Config_off.pm, scripts/export_database.pl
CSV refactoring
- documentation refactoring + .md file
- added:
- ingredients_analysis_tags
- additives_tags
- nutrient_levels_tags
- product_quantity
- owner
- data_quality_errors_tags
- unique_scans_n
- popularity_tags
- completeness
- last_image_t
- Enhance #2325
=> feat: more fields in CSV (issue 2325)

taxonomies/categories.txt
Add description and comment as taxonomy fields.This way, we can display category description (and optional comments about tricky classification decisions about this category) in Hunger Games.
Category description could be used to on mobile apps and on web.
I only converted comments to taxonomy fields, other descriptions/comments can be added later.
=> taxonomy: add descriptions and comments as taxonomy fields

.github/labeler.yml, po/README.md
Update documentation to create translatable strings.
=> docs: update GetText doc

taxonomies/ingredients_processing.txt
Add Swedish plural form of "dried" to taxonomies
Triggered by "torkade dadlar" (dried dates) not being recognized in https://world.openfoodfacts.org/product/7310240001785/granola-kakao-och-hallon-pauluns
=> taxonomy: Add Swedish plural form of "dried"

.github/labeler.yml
ci: fix small typo that created a second dependencies label
=> ci: fix small typo that created a second dependencies label

conf/nginx/sites-available/off
fix: reorder existing entries alphabetically
fix: add Czech entry
- #5720
=> fix: add Czech donation page

lib/startup_apache2.pl
A (bad) workaround for #7695 but I didn't find another solution (and I didn't find the actual reason for the issue either)
=> fix: do not preload Minion module 

.env, Dockerfile, Makefile, cpanfile, cpanfile_dev, docker/dev.yml
Trying to fix https://github.com/openfoodfacts/openfoodfacts-server/issues/7699
This removes some modules that are not needed by GitHub actions, and creates a "make install_perl_dev_modules" to install them.
=> fix: make command to install perl dev modules

lib/ProductOpener/DataQualityFood.pm
**Important**: changes are applied **only** after editing the products that are wrongly reported by the data quality issue (i.e. product that are listed with this data quality issue will be removed only after editing them again).
Replaced ```$product_ref->{alcohol_value}``` by ```$product_ref->{nutriments}{alcohol_value}``` in the file in _lib/ProductOpener/DataQualityFood.pm_
There are as many "en:alcoholic-beverages-category-without-alcohol-value" data quality issues (https://hr.openfoodfacts.org/data-quality/en:alcoholic-beverages-category-without-alcohol-value) as there are "en:alcoholic-beverages" products (https://hr.openfoodfacts.org/category/en:alcoholic-beverages). But many products have the alcohol value.
Screenshot of the bug (urls differ):
Screenshot before (left) and after …
=> fix: data quality alcoholic beverages category without alcohol value

lib/ProductOpener/API.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/KnowledgePanels.pm, tests/integration/api_v2_product_read.t, tests/integration/api_v3_product_read.t, tests/integration/expected_test_results/api_v2_product_read/get-attribute-groups-fr.json, tests/integration/expected_test_results/api_v2_product_read/get-attribute-groups.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-attribute-groups.json, tests/integration/expected_test_results/api_v3_product_read/get-existing-product.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels.json
- fixes #7707
- added tests to cover the issue
=> fix: access knowledge panels via API

.github/workflows/generate-doc.yml, docs/reference/api-v3.md
We have api published at https://openfoodfacts.github.io/openfoodfacts-server/reference/api/ but we also want api-v3 to be visible at https://openfoodfacts.github.io/openfoodfacts-server/reference/api-v3/
=> build: deploy v3 documentation

cgi/product_multilingual.pl, templates/web/pages/product_edit/display_input_tabs.tt.html, templates/web/pages/product_edit/product_edit_form_display.tt.html
This PR moves the "product characteristics" section above the "front image" section in the product edit form, and puts the checkbox for moderators to move data and photos to another language close to the main language field.
=> fix: move photos/data to main language

docs/reference/api.yml
- Include the sort_by parameter to the open API file
- Indicate the allowed values for sort as enum
=> docs: include sorting to search in open api

cgi/product_multilingual.pl, templates/web/pages/product_edit/display_input_tabs.tt.html, templates/web/pages/product_edit/product_edit_form_display.tt.html
This is to put back the front image first in the product edit form, above the product characteristics section.
The "main language" field is moved from characteristics to the front image section.
=> fix: put back front image first in product edit form

lib/ProductOpener/DataQualityFood.pm
* Increase detection percentage for en:energy-value-in-$unit-does-not-match-value-computed-from-other-nutrients, to avoird many false positive (10% -> 30%)
* Create a data quality warning for products upper than 15%
* Better comments
- Slightly improves #7683
=> fix: Data quality issues related to energy

cgi/generate_sample_import_file.pl, cgi/product_multilingual.pl, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Producers.pm, po/common/common.pot, po/common/en.po, po/common/fr.po, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json
This is to add fields related to packaging parts in the Excel template that is generated on the pro platform by https://fr.pro.openfoodfacts.org/cgi/import_file_upload.pl
I put a copy of the generated file for French here: https://world.openfoodfacts.org/files/openfoodfacts_import_packagings_fr.xlsx
Note that the pro platform is still running an old version of the code with the old design (without knowledge panels). So we may have to wait a bit to deploy this (but we can link to the generated file).
=> feat: add packaging parts fields to import template

docs/reference/api.yml, docs/reference/requestBodies/add_or_edit_a_product.yaml, docs/reference/responses/add_or_edit_a_product.yaml
I removed excess examples from everything except product schema. The examples in the product schema is quite bulky and confusing. I need help with it, please.
=> docs: remove excess examples from the open api

taxonomies/categories.txt
taxonomies: fix typo for the Shrimp category
=> taxonomy: fix typo for the Shrimp category

.github/workflows/github-projects-for-openfoodfacts-design.yml
feat: Ventilate issue to more GitHub projects
=> feat: Ventilate issue to more GitHub projects

docs/reference/schemas/packagings/packagings_complete.yaml, docs/reference/schemas/product.yaml, docs/reference/schemas/product_update_api_v3.yaml, lib/ProductOpener/APIProductWrite.pm, po/common/common.pot, po/common/en.po, tests/integration/api_v3_product_write.t, tests/integration/expected_test_results/api_v3_product_write/patch-packagings-complete-0.json, tests/integration/expected_test_results/api_v3_product_write/patch-packagings-complete-1.json, tests/integration/expected_test_results/api_v3_product_write/patch-packagings-complete-2.json
We have a field called packagings_complete that takes value 0 or 1 to indicate if the packagings field contains all element of the product.
This PR adds it to the API v3 WRITE product.
=> feat: allow setting the packagings_complete field through API v3

po/common/en.po
- This is the kind of errors that might happen when you don't generate en.po from common.pot using GetText commands
- fix: https for the footer
=> fix: https for the footer

lib/ProductOpener/Ingredients.pm
not sure for the label
added some stopwords in ingredients.pm, based on the following observations:
> 
>     see lib/ProductOpener/ingredients.pm
>         ignore_regexps (-> les informations en gras, etc.)
>             "u tragovima" (https://hr.openfoodfacts.org/product/3850104295072/kajen%C5%A1ki-papar-mljeveni-vegeta)
>       
>         may_contain_regexps
>             "proizvod može sadržavati" (https://hr.openfoodfacts.org/product/4337185925511/sultaninen-kaufland)
>       
>         phrases_before_ingredients_list:
>             "HR" (https://hr.openfoodfacts.org/product/3859892109134/per%C5%A1in-usitnjeni-%C5%A1afram)
>             "HR BiH " (https://hr.openfoodfacts.org/product/3858881086296/guatemala-100-arabica-franck, …
=> taxonomy: added some stopwords for ingredients in Croatian

lib/ProductOpener/KnowledgePanels.pm, templates/api/knowledge-panels/environment/environment_card.tt.json, templates/api/knowledge-panels/environment/packaging_recycling.tt.json, templates/web/panels/image.tt.html
Changes to the product display page:
- Display the weight per unit of each packaging component
- Display the packagings image in the knowledge panel - Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/7919
- Make knowledge panels images clickable to zoom - Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/7624
(i selected a random part of the image, imagine it's a packaging image :) )
=> fix: Packagings display improvements on product page

scss/_off.scss, scss/_product-list.scss
Related to https://github.com/openfoodfacts/openfoodfacts-server/issues/7499
Continuation of https://github.com/openfoodfacts/openfoodfacts-server/pull/7916
This removes CSS code that was duplicated between _off.scss and _product-list.scss
It removes some special behaviour from the old design: on small screen, we had only 1 product card per line, but now we have 2.
When we have multiple cards per line (which is now always the case), we fix some heights so that the attribute icons are vertically aligned on the different product cards.
=> fix: responsive product list css

scripts/check-translations.sh
- Modified the `check-translations.sh` shell script to check if the number of placeholders in `msgstr` and `msgid` are same.
For `en.po` (no errors)
For `aa.po`  (86 occurrences)
- Fixes #7906
=> feat: add placeholder count check to check-translations.sh

conf/nginx.conf
was forgotten for docker-compose deployment
=> fix: URGENT - add cors headers for static resources

scripts/mongodb_dump.sh
First step of https://github.com/openfoodfacts/openfoodfacts-server/issues/7962
For deployment: the new export should take the same time as the old one. About 30 minutes?
It might be necessary to **start the export a bit earlier** to be sure it won't impact other processes (eg. Mirabelle is downloading the CSV file at 5:00 CET).
=> feat: new dump, aside the current one

taxonomies/categories.txt, taxonomies/ingredients.txt
Adds ["collard greens"](https://en.wikipedia.org/wiki/Collard_(plant)), a variety of leafy green vegetable, to both the OpenFoodFacts `ingredients` and also `categories` taxonomies.
Resolves #7315
=> taxonomy: add 'collard greens' as both an ingredient and a category

lib/ProductOpener/DataQualityFood.pm
This may resolve #7984  (@CharlesNepote, @raphael0202)
1. More context
- see all of the errors: https://mirabelle.openfoodfacts.org/products?sql=select+url%2C+creator%2C%0D%0A--created_datetime%2C+last_modified_datetime%2C+product_name%2C%0D%0A%5Benergy-kj_100g%5D%2C+%5Benergy-kcal_100g%5D%2C+energy_100g%2C%0D%0A--%5Benergy-from-fat_100g%5D%2C+%0D%0Afat_100g%2C+%5Bsaturated-fat_100g%5D%2C%0D%0A--%5B-butyric-acid_100g%5D%2C+%5B-caproic-acid_100g%5D%2C+%5B-caprylic-acid_100g%5D%2C+%5B-capric-acid_100g%5D%2C+%5B-lauric-acid_100g%5D%2C+%5B-myristic-acid_100g%5D%2C+%5B-palmitic-acid_100g%5D%2C+%5B-stearic-acid_100g%5D%2C+%5B-arachidic-acid_100g%5D%2C+%5B-behenic-acid_100g%5D%2C+%5B-lignoceric-acid_100g%5D%2C+%5B-cerotic-acid_100g%5D%2C+%5B-montanic-acid_100g%5D%2C+%5B-melissic-acid_100g%5D%2C+% …
=> feat: add data quality issue for negatives values in nutrition table

po/common/common.pot
fix: add forgotten strings to the GetText template
=> fix: add forgotten strings to the GetText template

taxonomies/ingredients.txt
- two comments were not prefixed with '#', so it was part of the taxonomy
- remove useless synonym for 'fr:Mélanges de miels d'Acacia originaires et non originaires de l'Union Européenne'
=> taxonomy: fix some issue on ingredient taxonomy

taxonomies/data_quality.txt
* Sorting the entries by data-quality levels first (errors vs warnings)
* Then sub-sorting the entries by alphabetical order
* Added all errors (not warnings) to the pro-platform
Should fix #7867.
=> feat: data-quality taxonomy big update

taxonomies/labels.txt
Bee friendly was added, see #7231 but under the wrong name (the tagline instead of the real name)
=> taxonomy: fix bee friendly label name

lib/ProductOpener/HTTP.pm, tests/integration/cors.t, tests/unit/http.t
=> fix: CORS header typo Access-Control-Allow-Origin

lib/ProductOpener/DataQualityFood.pm
excluding all nutriments containing "nutrition-score" (nutrition-score, nutrition-score-fr)
Tested that negative value is still working for common nutriment. **But** it is not possible to test negative nutrition-score itself because there are no examples in the test data and I do not know how to create such negative nutrition-score.
could fix #7988
=> fix: exclude nutrition id containing nutrition-score

Makefile
Added a Check which sets the CPU_COUNT variable via sysctl instead of nproc if run on MacOS. Otherwise building via the Makefile would fail because on MacOS because nproc doesn't exist on MacOS. 
- Fixes #[8040]
=> build: When detecting MacOS then use MacOS-specific 'sysctl' command for setting CPU_COUNT

scss/_off.scss
This is to make sure links are differentiated visually, with an underline.
e.g. previously those links were almost invisible:
=> fix: underline links

scss/_off.scss
This removes the underline for links in some dropdowns (e.g. the "Explore by" button) and tables (e.g. list of tags in /categories etc.)
=> fix: remove underlined links in tables/dropdowns

lib/ProductOpener/Routing.pm
Needed for old versions of the Horizon app
test: https://world.openfoodfacts.org/api/v0/products/3017620422003/nutella-ferrero
=> fix: support /api/v0/products (with a s)

taxonomies/ingredients.txt
Adds German synonyms for plant protein, e.g. https://de.openfoodfacts.org/produkt/7610227935219/plant-based-filet-h%C3%A4hnchen-art-green-mountain
none
none
=> taxonomy: add :de: alias for plant protein

taxonomies.obf/allergens.txt
I need to watch out for Cocamidopropyl betaine because I might be allergic to it. It wasn't yet listed as a allergent. [According to Wikipedia](https://en.wikipedia.org/wiki/Cocamidopropyl_betaine#Safety) the allergent status is  controversial. 🤷
=> taxonomy: adding Cocamidopropyl betaine in allergens

lib/ProductOpener/Ingredients.pm, taxonomies/ingredients_processing.txt, tests/unit/ingredients_processing.t
WHAT?
Added Croatian language for food processing
Added 2 unit tests *
(added 1 more entry in Croatian taxonomy for processing)
(there were a couple of tests at the end in different language, there are now at the end of their respective languages => and after "make lint" it looks like a lot of things have changed in the file, sorry for that)
\* **Remark**: the case where [ingredient + processing] is a sub-ingredient in parenthesis was not yet included in the tests (like "antioksidans (ekstrakt ružmarina)"). That was a bit tricky to handle, but now it is included in the tests as well.
=> feat: added Croatian language taxonomy for processing

.github/workflows/daily.yml, .github/workflows/mongo-deploy.yml, Makefile, docker/mongodb.yml
Using new openfoodfacts-mongodbdump.gz dump to restore staging.
Also using a bind mounted directory to avoid copying files around.
Part of:
- #7962
=> ci: use mongodb new gz dump for staging

scss/_off.scss
small fix to remove underline on links in attributes
=> fix: removed underline of links in attribute cards

lib/ProductOpener/Tags.pm
File::Fetch is causing issues in the prod and dev environment (but not in docker, maybe because of different versions).
I'm removing it in favor of LWP::UserAgent (which we already use).
fixes #8172
=> fix: remove File::Fetch

.github/workflows/pull_request.yml
We have more than one step depending on it, so add it to the build step. 
Should fix Check perl failing.
=> ci: fix build taxonomy in ci

docker/README.md, docs/api/index.md, docs/api/intro-robotoff.md, docs/dev/how-to-write-and-run-tests.md, docs/dev/index.md, docs/dev/ref-docker-commands.md, docs/dev/ref-perl.md, docs/index.md, scripts/build_mkdocs.sh
- do not copy README as index anymore (too confusing)
- have a specific sleek index.md instead
- publish doc on makefile targets for docker
- add a doc on writing and running tests
fixes:
- #8104
=> docs: simple index + add docs on test / docker

scss/_off.scss
Remove CSS rule that has no obvious intent, and that hides legit content on pages like "NOVA" explanation.
fixes:
- #8188
=> fix: remove css rule hiding legit content on pages

scss/_product-page.scss
In edit mode, the scroll to top button is overlapping with the changes summary textbox when the width of device is below 1024px. So, I have added media queries specifying the max-width to 1024px where the bottom margin of the button is set to 50px to prevent overlapping:)
- It fixes #7494
=> fix: responsive-scroll-bar

templates/web/pages/product_edit/product_edit_form.tt.html, templates/web/pages/product_edit/product_edit_form_display.tt.html
Removes the barcode at the top (which was previously hidden with a display:none css rule that we removed)
=> fix: remove extra barcode in product edit form

scss/_off.scss
Links were almost invisible in the text of panels, this PR adds an underline. (related: #8216)
I believe links in general should be more obvious (e.g. with a blue color), but that's for another PR.
=> fix: underline links in panel text

docs/dev/how-to-develop-using-docker.md, docs/dev/how-to-use-gitpod.md
just simply made sure that docs reference to correct resources 
=> fix: open in Gitpod and mongo shell docs links should point to right resources

docs/dev/how-to-learn-perl.md, docs/dev/how-to-quick-start-guide.md, docs/dev/how-to-use-repl.md
Ref: https://openfoodfacts.slack.com/archives/C01USC55N67/p1678700540409499?thread_ts=1678679463.020239&cid=C01USC55N67
cc @yuktea @stephanegigandet 
- Fixes #8204
=> feat: Add Perl introductory resources to warm newbies about Perl #8204

templates/web/pages/session/signed_in.tt.html, templates/web/pages/user_form/user_form_page.tt.html
Do not show the lilo prompt in countries where it's unsupported
https://www.lilo.org/fr/open-food-facts/
https://user-images.githubusercontent.com/58003327/226471635-4f615e76-1a19-40cf-88e8-1d5c64baf575.mov
cc @yuktea @stephanegigandet @alexgarel 
- Fixes #[7905]
=> fix: Do not show the lilo prompt in countries where it's unsupported

lib/ProductOpener/Packaging.pm, tests/unit/packaging.t
This is needed because we have changed the canonical names for packaging entries like PET.
=> fix: re-canonicalize packaging component properties

docker/dev.yml
I experienced an error with make dev  or docker compose up  or any command that requires docker.
```
docker-compose --env-file=.env build 2>&1
yaml: unmarshal errors:
line 37: mapping key "<<" already defined at line 36
line 41: mapping key "<<" already defined at line 40
make: *** [Makefile:93: build] Error 15
```
There was need to merge https://github.com/openfoodfacts/openfoodfacts-server/blob/d9072f92ac0d0c0b8cbd6f7e478b3e0cba6a8700/docker/dev.yml#L36-L40  
Thanks to @alexgarel who suggested the idea 
cc @stephanegigandet @yuktea 
=> fix: docker YAML key mapping duplication 

.dockerignore, .github/workflows/container-deploy.yml, docker-compose.yml, docker/dev.yml, docker/prod.yml
1. We need taxonomy txt files in images as we build sto from them
2. We also need to have BUILD_CACHE_REPO set on the deployment to use cache
3. Use a volume for local build cache.
=> build: fix docker image build

lib/ProductOpener/KnowledgePanels.pm, lib/ProductOpener/KnowledgePanelsContribution.pm, templates/api/knowledge-panels/root.tt.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_write/patch-request-fields-updated-attribute-groups-knowledge-panels.json
Do not reference contribution_card in root card if not present.
Fixes: #8295
=> fix: avoid reference to missing panel in root card

lib/ProductOpener/Display.pm, tests/unit/display.t
I have appended `$request_ref->{groupby_tagtype}` to  the `$request_ref->{current_link}` so that there is no truncation in redirection.
I have also added tests to verify that, 
1. request is processed 
2. the second facet exists in the redirection link
cc @yuktea @alexgarel @stephanegigandet 
https://user-images.githubusercontent.com/58003327/230877303-f4caf75a-4257-4580-9fdb-93911b339b79.mov
- Fixes #7979
=> fix: loosing the second facet at the end of the url on redirection

taxonomies/categories.txt
The potatoes category will be cleanup and reorganised such that it contains only products with a single ingredient (potato) and reflects the NOVA 1 status of this category.
=> chore: cleaning up the potatoes category

taxonomies/labels.txt
These are changes brought by @alexouille123 in this previous PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/3739/
If you approve and merge this present PR, please invalidate https://github.com/openfoodfacts/openfoodfacts-server/pull/3739/ 
The following contributions have been skipped: 
- synonyms: fr:OGM, Organismes Génétiquement Modifiés
already in main currently: synonyms: fr:OGMs, Organismes génétiquement modifiés, OGM
- synonyms:en:natural, of natural origin
ignored because there are n occurrence of "of natural origin" in the taxonomy and there are no occurrence in https://uk.openfoodfacts.org/labels nor https://us.openfoodfacts.org/labels
- synonyms:en:from the end, after
ignored because there are no occurrence of "from the end" in the taxonomy and there are no …
=> taxonomy: reapply changes from previous PR

lib/ProductOpener/Store.pm
This fixes a failing test in recent PRs.
=> fix: explore files in sorted order to make tests non-random

lib/ProductOpener/KnowledgePanels.pm, templates/api/knowledge-panels/environment/carbon_footprint.tt.json, templates/api/knowledge-panels/environment/ecoscore/agribalyse.tt.json, tests/unit/knowledge_panels.t
- fixes #8339 (see screenshots in issue)
this particular wikipedia abstract is really not relevant to OFF, I would be very much in favor to creating our own additives descriptions.
- #5493
=> fix: escape issue in additives knowledge panel - remove latex formulas

cgi/export_products.pl, lib/ProductOpener/Display.pm, lib/ProductOpener/Export.pm, lib/ProductOpener/Producers.pm, po/common/common.pot, po/common/en.po, templates/web/common/includes/producers_platform_front_page.tt.html, templates/web/pages/export_products/export_products.tt.html
Show the number of products that are not exported in both products and products_obsolete collections, and export both.
=> fix: export obsolete products - draft

lib/ProductOpener/API.pm, lib/ProductOpener/APITest.pm, lib/ProductOpener/HTTP.pm, stop_words.txt, tests/integration/api_v3_product_write.t, tests/integration/cors.t, tests/integration/expected_test_results/api_v3_product_write/patch-code-test.json, tests/unit/http.t
- add the Authorization header (needed on .dev and .net)
- return a 200 response instead of 404 when we have an OPTIONS request for a product that does not exist: we don't execute the request, we just validate that the browser can make it
- added some tests
=> fix: make CORS work on dev server and API v3

lib/ProductOpener/Food.pm, taxonomies/nutrients.txt
1/ added both nitrate and sulfate as suggestion in the table (populate %nutriments_tables in Food.pm)
2/ added nitrate and sulfate to export csv because of 1/. In the comments in the beginning of the Export.pm file, it is written:
> Use the list of fields from C<Product::Opener::Config::options{import_export_fields_groups}>
and the list of nutrients from C<Product::Opener::Food::nutriments_tables> to list fields
that need to be exported.
Depending of the country:
Both are in mg:
Both are exported:
fixes #8265
=> feat: added nitrate sulfate as suggestions in table

po/common/common.pot, po/common/en.po, templates/web/pages/product_edit/product_edit_form_display.tt.js
This PR builds upon the work of @jnsereko : https://github.com/openfoodfacts/openfoodfacts-server/pull/8258
It fixes some issues with the original PR, that were found when doing more testing before pushing to production.
- We need to use parseFloat() on input values, otherwise "47" < "8"
- Commas are replaced by dots, so that French numbers like 4,7 are converted to 4.7
- Re-ordered the logic so that some warnings like the sugars > 100g warning is not cleared if carbohydrates are then modified (and are above sugars). In practice the "Please enter a value between 0 and 100" now takes priority over the other.
- Added translations in .po files.
- Allow values > 100g if nutrients are per serving and not per 100g
=> fix: nutrition edit warnings

lib/ProductOpener/Products.pm
Otherwise `diffs=HASH(...)`
Last PR I didn't test it locally...
=> fix: encode `diffs` as JSON text in send_notification_for_product_change

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
added data quality error for reversed kj and kcal
Instead of the formula in issue #8394, we can use the exact opposite of the formula used for "en:energy-value-in-kcal-does-not-match-value-in-kj" (reverse kcal and kj, and reversed < and >, so that any kcal that is in the window 3.7\*kj -2 and 4.7\*kj + 2 can be considered as reversed kcal and kj)
Also added tests for "en:energy-value-in-kcal-does-not-match-value-in-kj" (see: `# TODO: add tests in /tests/unit/dataqualityfood.t` ?!?)
- Fixes #8394
=> feat: added quality facet error for reversed kcal and kj

html/images/attributes/src/nova-group-unknown.svg
Hi everyone!
On the mobile app, [we have some issues](https://github.com/openfoodfacts/smooth-app/issues/3990) with the current version of the Unknown group's SVG file.
After regenerating it with Illustrator, it seems to be OK on our side.
Could it be possible to use this one instead?
But please check, there is no visual regression (I don't think, but always better).
=> fix: Update nova-group-unknown.svg

Makefile
Product opener needs to use locks on NFS. nolock option ensure it is done locally, and it's ok for us as the instances are currently on same server
=> ci: fix nfs volume creation to enable simple lock usage

taxonomies/additives.txt
EFSA conclusion in https://efsa.onlinelibrary.wiley.com/doi/10.2903/j.efsa.2019.5621
"Based on the above, the Panel concluded that the current ADI of 0.5 mg/kg bw would be reached in toddlers and children at the 95th percentile already for exposure estimates calculated using the currently permitted ML for ethyl lauroyl arginate (E 243)."
=> taxonomy: e-243 additive exposure

lib/ProductOpener/DataQualityFood.pm, lib/ProductOpener/Tags.pm, taxonomies/categories.txt, tests/unit/dataqualityfood.t
Added feature to bypass "Energy value in kJ does not correspond to the value calculated from the other nutrients"
Not sure what to screenshot because there is no error anymore :-D
- Fixes #8425
=> feat: bypass data quality error for citrus

package-lock.json, package.json
`snyk protect` is deprecated
https://github.com/snyk/cli/tree/master/packages/snyk-protect#migrating-from-snyk-protect-to-snykprotect
=> chore: migrate from snyk protect to @snyk/protect

lib/ProductOpener/Display.pm, lib/ProductOpener/Tags.pm
=> fix: correct the link to products added by one user

po/common/common.pot, po/common/en.po, templates/web/pages/product_edit/product_edit_form_display.tt.js
Solves most of the issues reported by @CharlesNepote and @benbenben2 in https://github.com/openfoodfacts/openfoodfacts-server/issues/8420
Does not address the tooltip below the image issue.
=> fix: on the fly nutrition edit checks #8420

scripts/preprocess_intermarche_packaging_csv_file.pl, stop_words.txt
- Packaging data from Les Mousquetaires / Intermarché contains multiple materials for the same packaging component (with different percents, totaling 100%). 
- We currently do not support multiple materials for a component, so this script pre-processes the Excel file in order to keep only the dominant material for each component.
- #5521
=> chore: script to preprocess intermarche packaging excel file

cgi/product_multilingual.pl
Added the packaging field too in cgi/product_multilingual.pm so that this field is not displayed for the tab "product characteristics" in templates/web/pages/product_edit/product_edit_form_display.tt.html !
- Fixes #7804
=> fix: Hide the Classic Packaging Field in Edit Mode

scripts/mongodb_dump.sh
We've never exported the recent_changes collection, which includes the history of all changes performed on OFF DB since the 11th of September, 2018.
It's the most interesting data source to analyze contributor/apps impacts.
This commit adds the automatic export of this collection as a JSONL gzipped file.
=> chore: export recent changes collection

Makefile, env.pro, scripts/build_lang.pl, setenv-pro.sh
I tried to make "make build_lang" build the pro platform lang file when we have run source set-env.pro.sh, by loading an extra env.pro environment file (otherwise the env variables set by set-env.pro.sh are overloaded by .env when running the make script I believe).
But it fails later on.
Anyone can help?
`stephane@stephane-jaguar-NS50-70MU:~/openfoodfacts-server$ (pro) (pro) (pro) (pro) (pro) make build_lang
🥫 Rebuild language
docker-compose --env-file=.env --env-file=env.pro run --rm -e GITHUB_TOKEN= backend perl -I/opt/product-opener/lib -I/opt/perl/local/lib/perl5 /opt/product-opener/scripts/build_lang.pl
WARN[0000] volume "po_podata" already exists but was not created for project "po". Use `external: true` to use an existing volume 
WARN[0000] volume "po_orgs" already exists but was …
=> fix: adapt Makefile to work on pro platform

taxonomies/categories.txt, taxonomies/nutrients.txt
From [product 8424644002497](https://es.openfoodfacts.org/producto/8424644002497) , there is no nutrition table, but instead a list of components weight.
Adding few translations for sugars in Spanish and Catalan, and a bit of some additional info.
=> taxonomy: Add Spanish/Catalan sugars for creatine products

lib/ProductOpener/DataQualityFood.pm, lib/ProductOpener/Tags.pm
This removes a warning caused by calling lc() on something that can be undefined.
=> fix: remove warning in get_inherited_property_from_categories_tags

taxonomies/nutrients.txt, taxonomies/other_nutritional_substances.txt
Added the German variant "Inosit" to inositol, which is often contained in beverages like energy drinks. In German, the word "Inosit" is more common than "Inositol".
=> taxonomy: Added German variant of inositol

docs/dev/how-to-write-and-run-tests.md
A bit more explanation about how to use JSON files to store expected test results.
=> docs: storing expected results of tests as JSON

taxonomies/labels.txt
Added Finnish translation for 'Crossed Grain Trademark' label. This name is used by the Finnish Coeliac Society, who issues the label for Finland: https://www.keliakialiitto.fi/kuluttajat/reseptit-ja-tuotteet/gluteenittoman-tuotteen-merkki/
=> taxonomy: add fi translation for Crossed Grain Trademark

lib/ProductOpener/Tags.pm
Also cache full.json files
- Fixes #8556
=> fix: Build Taxonomies does not cache the full json files

templates/web/pages/session/sign_in_form.tt.html
Added back the checkbox on the main sign-in form. It was still on the product edit sign-in form, but had been dropped from the main form at some point during the redesign.
- Resolves #7915
=> fix: Add back the "Remember me" checkbox

lib/ProductOpener/Data.pm, lib/ProductOpener/Display.pm
This PR adds a &timeout=[number of ms] parameter that can be used by admins in order to override the default timeout (currently 50s in production), in order to be able to run queries that run longer. This could be useful for instance for monitoring queries (e.g. getting stats on recognized ingredients).
Note that the proxy timeout in nginx is currently not set (except on the pro platform where we can have big uploads), and the default is 60 sec. So in order for the timeout to have a real effect, we would also need to change the nginx config to include something like:
```
proxy_connect_timeout       1200;
proxy_send_timeout          1200;
proxy_read_timeout          1200;
send_timeout                1200;
```
=> feat: allow admins to specify a timeout for MongoDB queries

Makefile, docker/dev.yml
- Fixes "make import_prod_data" error "Failed: stat /import/openfoodfacts-mongodbdump.gz: no such file or directory"
- Was raised by me in slack channel #api in June 22.06.2023
=> fix: "make import_prod_data" incorrect mapping on data folder

scripts/agena3000/run_agena3000_import.sh
There is a quota on the sftp account Agena3000 created for us. This is to remove the files that we have already received.
=> fix: remove source files in agena3000 sftp

.github/workflows/pull_request.yml
- We run the full CI suite on minor changes not related to perl
- use paths-ignore to not run the CI in specific files and reduce the volumetry of unecessary builds
- Please add paths that should not trigger a build
=> ci: Reduce the volumetry of unecessary builds

.github/workflows/pull_request.yml
revert the change we introduced in
d782f0a586d42d050af430bd5483607b521b187e … because we skip check that
are required.
This is discussed in
https://stackoverflow.com/questions/66751567/return-passing-status-on-github-workflow-when-using-paths-ignore
=> ci: revert path-ignore on required actions

lib/ProductOpener/Config_obf.pm, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Config_opf.pm, lib/ProductOpener/Config_opff.pm
Google analytics is not GDPR compatible (because of laws in the USA).
Remove it.
Note: On opf / obf / opff a matomo is in place but the code is in the respective branches: opf-main, obf-main and opff-main.
=> chore: remove google analytics

docs/dev/how-to-quick-start-guide.md
Adding instructions for Windows user to activate the developer mode in order to be able to create symbolic links
=> docs: instructions to activate the dev mode for Windows user

docs/dev/how-to-write-and-run-tests.md
unit-test and int-test changed respectively to test-unit and test-int in order to match Makefile targets
=> docs: update of Makefile target

tests/integration/api_cgi_suggest.t, tests/integration/expected_test_results/api_cgi_suggest/synonym-string-fr-dairy-drinks.json
adding a synonym test for the suggestion feature, in my case i used the product "Dairy Drink" in French. The input "jus de fruits au lait" should give "Boissons au fruit et au lait" as a result which is the first word in the taxonomy matching "Dairy Drink" in French.
=> test: adding a synonym test for the suggestion feature

po/common/common.pot
contributors_products was in en.po but not common.pot
fixes: #8636
=> fix: Add missing string to common.pot

lib/ProductOpener/DataQualityFood.pm, lib/ProductOpener/Units.pm, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
- Fixes #3029 
**Reminder:** serving_size is the input from the contributor, serving_quantity is the extracted quantity from the serving_size
1) Nutrition data per serving - Serving quantity is unknown
2) Nutrition data per serving - Serving quantity is not recognized
3) Nutrition data per serving - Serving quantity is 0 --> only when we actually get "0 g" or similar
1) would be exact same as: en:nutrition-data-per-serving-missing-serving-size
previously it was a warning
updated to be an error
**Remark about 2 & 3)**  
>    input "une crepe 25 grammes" -> output serving_quantity=25 (special case, supposedly due to unit_equivalences_list in Units.pm)
>     input "100 milliliter" -> output serving_quantity not in result
>     input "3 pcs" -> output serving_quantity not in result
>     2 …
=> feat: updated test for serving_size for nutrition table

lib/ProductOpener/Export.pm
a typo was preventing obsolete products to be exported
=> fix: export obsoete products from producers platform

lib/ProductOpener/Ingredients.pm, tests/unit/expected_test_results/ingredients/ca-middle-dot.json, tests/unit/ingredients.t
Updated stopwords for middle dot.
Some words in Catalan contain middle dot and should not be parsed.
Following screenshot shows middle dot without spaces around (first ingredient) and middle dot with spaces around (second ingredient). 
- Fixes #8373
=> fix: update middle dot to keep catalan words

templates/web/pages/product/includes/nutrition_facts_table.tt.html
When we copy code from perl to the template we forgot to remove the end of content marker (JS).
=> fix: remove forgotten JS marker in nutrition_facts_table.tt.html

lib/ProductOpener/Ingredients.pm, taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/allergens.txt, taxonomies/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt, taxonomies/other_nutritional_substances.txt, taxonomies/vitamins.txt, tests/unit/ingredients_processing.t
added Croatian ingredients into the taxonomies.
(remark: big block "en:chokeberry" has been deleted because it was duplicated in the taxonomy)
=> taxonomy: added Croatian ingredients in taxonomies

docs/assets/api-rapidoc.html
I did broke the API documentation because I changed the url to test it was working ok but did not restore URL afterwards...
=> docs: fix api ref url

.github/workflows/auto-assign-pr.yml, .github/workflows/codecov.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container-build.yml, .github/workflows/label.yml, .github/workflows/pull_request.yml, .github/workflows/semantic-pr.yml, .github/workflows/translation-check.yml
- ci: concurrency on translation check workflow
- What do we put concurrency on ? Everything ?
- Caveat: if you do a string of commits without waiting, you can't see where your code started failing.
- Note: When concurrency is specified at the job level, order is not guaranteed for jobs or runs that queue within 5 minutes of each other.
- See #8733
=> ci: concurrency on translation check workflow

Makefile, tests/integration/create_user.t
completing the create_user.t test in order to check if the preferences gave by the user is well saved
=> test: completing the create_user.t

cgi/display.pl, html/robots.txt, lib/ProductOpener/Display.pm, lib/ProductOpener/Routing.pm, stop_words.txt, tests/integration/facet_page_crawler.t, tests/unit/routing.t
An analysis of nginx logs made us realize that 6% of our traffic was due to Bing bot, half of the queries were "facet" queries that involve aggregate MongoDB queries and consume a lot of resources.
See https://openfoodfacts.slack.com/archives/C1FPYCWM7/p1690454042958259 discussion for more context.
As a result, we decided to prevent known crawlers from crawling nested facet pages (2 facets). This should limit drastically the number of crawlable pages and reduce server load (especially the DB server).
I checked locally with custom User Agent, nested facet pages are blocked as expected.
=> fix: return empty noindex webpage when crawlers hit specific pages

lib/ProductOpener/Display.pm, templates/web/pages/tag/tag.tt.html, tests/integration/facet_page_crawler.t
Related to https://github.com/openfoodfacts/facets-knowledge-panels/pull/123 : we don't want to load facets knowledge panels for crawlers.
In the future, we might want to disable other things for crawlers, this PR makes is_crawl_bot available to the template engine (only for tags right now, it should be added for all templates later)
=> fix: disable facets knowledge panels for crawlers

conf/nginx/snippets/off.locations-redirects.include
added a redirect for an url that is in the signup e-mail (and maybe elsewhere, not sure where it comes from)
=> fix: redirect for donner-a-open-food-facts

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/vitamins.txt
#8752 added variants of Japanese translations of vitamins and additives, mainly with short forms and full/half-width variations. This PR expands on that.
Used [this document](https://www.hokeniryo.metro.tokyo.lg.jp/shokuhin//hyouji/files/tsuuchi-additives.pdf) as a reference to decide which ones to expand and by how.
=> taxonomy: Add Japanese form variants for vitamins and additives

lib/ProductOpener/Cache.pm, lib/ProductOpener/Display.pm, stop_words.txt
First PR to fix memcached caching error investigated in #8792. It doesn't solve the caching issue, but at least we're not trying to save a 30MB blob in memcached anymore.
It turns out this saving attempt was very costly, with this PR the main webpage loads in 600-1000ms (instead of 1500-2000s), it's deployed and can be tried on https://openfoodfacts.net.
=> fix: don't save object in memcached above allowed size 

tests/integration/modify_user.t
quick test to check if preferences are saved when an user made some edits
=> test: adding a test that check if preferences edits made by an user are saved

.github/labeler.yml, html/js/product-multilingual.js
As users are writing into Tagified content that performs autocompletion, each letter typed will result in an immediate call to API.
This amounts of requests and cancellations may overload the API service, which in turn cause that lookup takes long (+5 seconds to get response).
In order to improve this situation:
- Whenever the user types any letter, a `timeout` starts.
- If the user continues to write, the `timeout` will restart from beginning.
- If the `timeout` completes, the REST API call will be executed.
---
**NOTE:** This code is not tested. Feel free to make any additional changes required.
- #8764
=> feat: Timeout before calling autocomplete

lib/ProductOpener/Import.pm, scripts/update_all_products.pl
- When exporting obsolete products from the pro platform to the public platform, we were not updating their export status on the obsolete collection of the pro platform (and instead created them on the non obsolete collection).
- This PR fixes the export status, and also add support for selecting the obsolete collection in update_all_products.pl, + an option to remove obsolete / non-obsolete products that are not in the appropriate collection.
```
16019 products updated (pretend: ) - 0 new versions created
9227 removed from wrong collection (obsolete or current)
off@off1:/srv/off-pro/scripts$ ./update_all_products.pl --query owners_tags=org-auchan-apaw --fix-obsolete 
```
- #8814
=> fix: obsolete support in update_all_products.pl and export status fix on producers platform

lib/ProductOpener/Images.pm
In the product edit form, we now display the image uploader and upload time for all users when the mouse hovers the thumbnails.
This feature used to be for moderators only.
=> feat: show image uploader and upload time to all users

templates/web/common/includes/offdays_banner.tt.html
Have the button link to the register form instead of the blog post
=> fix: link to register for the OFF days

taxonomies/ingredients.txt
added some german translation for ingredients of More Protein Brownie (some still missing, because I could not find an english equivalent) and a second translation for pumpin seed oil, because it was still missing
=> taxonomy: adding some german translation for ingredients of More Protein Brownie

lib/ProductOpener/Ingredients.pm, tests/unit/ingredients_parsing.t
Fixes #7927, see issue for more explanations
I have some difficulties with the tests locally. Many tests not related to this PR are failing locally.
=> fix: conflict additives variants and and

lib/ProductOpener/Display.pm, lib/ProductOpener/Routing.pm, templates/web/pages/robots/robots.tt.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-ch-it.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-fr-pro-platform.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-fr.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-world-pro-platform.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-world.txt, tests/integration/page_crawler.t
- totally deny access through noindex pages to some bots on all domain (seekportbot, SEO bots, Scrapy,...)
- add more bots to the list (GPTBot, Bytespider,...)
=> fix: improve web crawler indexation blocking

lib/ProductOpener/Ingredients.pm, tests/unit/match_ingredient_origin.t
=> fix: parse origins (ingredient from origin) in German, Italian and Spanish

lib/ProductOpener/Display.pm
www.qwant.com is no longer in the User-Agent, "Qwantify" should be used according to https://help.qwant.com/bot/
=> fix: fix Qwant bot detection

.github/workflows/container-deploy.yml
It happens we fail because the container image is not immediately accessible in ghcr.io. ([like this morning](https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/6081527840/job/16497359812).
Add a step to wait for images availability.
=> ci: wait docker images to avoid failing in container deploy

taxonomies/categories.txt
=> taxonomy: viili

lib/ProductOpener/Display.pm
The new regexp to identify crawlers is a bit too aggressive (Apple matches AppleWebKit which is listed in most browser user-agents) (from this change: https://github.com/openfoodfacts/openfoodfacts-server/pull/8945/commits/b23339cbba6a1ba0c692eb07f8a7f17b4dc87853 )
e.g. Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.2 Safari/605.1.15
=> fix: allow AppleWebKit user-agent

cgi/search.pl, lib/ProductOpener/Display.pm, po/common/common.pot, po/common/en.po
Discussed in last packagings call: now that we have packaging weights, we could create graphs (histograms or scatter plots) using the packaging weights, so that it's easy to see distributions and view the corresponding products.
- Added product_quantity + packaging weights fields (for main materials: all, glass, paper, plastics, metals etc. with for each either the total packaging weight, the weight per 100g, or the weight % compared to the other materials)
- Small refactor of search graphs in order to remove duplicate code (and avoid adding more)
- #5751
=> feat: add support for product quantity and packaging weights in search graphs

scripts/gen_feeds_daily_off.sh
we will activate it on off2 after migration.
New method is too slow to be integrated here.
=> chore: disable madenearme until migration

.github/workflows/container-deploy.yml
try to fix an issue introduced by https://github.com/openfoodfacts/openfoodfacts-server/pull/8951/files : env.TAG_NAME is not set, so we get this error:
https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/6107869077/job/16575737773
```
======CMD======
waited=0
for IMAGE_TYPE in frontend backend
do
image_name=ghcr.io/openfoodfacts/openfoodfacts-server/$IMAGE_TYPE:
while ! (docker pull $image_name); do
sleep 30
waited=$((waited+30))
if [[ $waited -gt 360 ]]; then
echo "Timeout waiting for image $image_name"
exit 1
fi
done
done
======END======
err: invalid reference format
err: invalid reference format
```
=> ci: fix docker deployment

README.md, docs/api/index.md
- remove link to legacy documentation (it's now deleted)
- ask API reusers to use custom User-Agent (we said to do so on the wiki but not here)
- add a section about rate limits (as discussed here: #8818)
=> docs: add section about rate limits

taxonomies/additives.txt, taxonomies/ingredients.txt, taxonomies/vitamins.txt
As we have lots of new UK users since OFF was mentioned in The Guardian's article on ultra-processed foods, it would be a good thing to improve ingredients analysis for UK ingredients (that have sometime other names than in other English speaking countries).
I'm documenting the effort here: https://wiki.openfoodfacts.org/Ingredients_Analysis_Quality_Evaluation_-_August_2023#UK_.2B_English
The list of unknown ingredients in the UK: 
https://uk.openfoodfacts.org/popularity/top-10000-gb-scans-2022/ingredients?stats=1&no_cache=1
=> taxonomy: UK ingredients

lib/ProductOpener/Display.pm, scss/_off.scss, templates/web/common/site_layout.tt.html
Everything is related to app landing page.
=> fix: app landing page improvements

lib/ProductOpener/Export.pm
Exported Excels do not contain leading zeros for the barcode.
Adding "$worksheet->keep_leading_zeros();" seems to solve the issue.
See: https://metacpan.org/pod/Spreadsheet::WriteExcel#keep_leading_zeros()
CSV seems not having this issue:
Result locally:
- Fixes #6782
=> fix: fix export excel with leading zero

lib/ProductOpener/Ingredients.pm, tests/unit/expected_test_results/ingredients/en-illegal-division-by-zero.json, tests/unit/expected_test_results/ingredients/fr-illegal-division-by-zero.json, tests/unit/ingredients.t
=> fix: illegal division by zero in percent estimate 

lib/ProductOpener/Attributes.pm, lib/ProductOpener/Display.pm
It does not solve issue #8792 as we're still over Memcached limit for main page, but it should still be faster (payload went from 30MB to 3MB). Without images, the payload is 2.3MB, so even while rearranging images we potentially need to increase memcached limit.
Furthermore, knowing which fields to fetched to compute attributes will be necessary once search-a-licious project is deployed, as data will be fetched from Elasticsearch (and not MongoDB).
It was tested locally, all attributes work as expected (a double check should be done once merged in staging).
=> fix: limit the number of fields fetched from MongoDB

lib/ProductOpener/Ingredients.pm, taxonomies/ingredients.txt, tests/unit/ingredients_parsing.t
Added piment in %ingredients_categories_and_types in Ingredients.pm.
Because it resulted to "piments de vert, piments de rouge, piments de jaune", a new variable (boolean) was added that can be set to 0 to indicate that there is no additional word ("de" or "d' ") between the categories (piment, for example) and the type (vert, for example).
- Fixes #8890
=> fix: updated ingredients_categories_and_types

cpanfile, lib/ProductOpener/Images.pm, lib/ProductOpener/Products.pm, stop_words.txt, tests/unit/products.t
Use Perl module `GS1::SyntaxEngine::FFI` to normalize barcodes. This allows more GS1 strings to be used with search.
- Fixes #9013
=> feat: Use 'GS1 Barcode Syntax Engine' to normalize product codes

lib/ProductOpener/Ingredients.pm, stop_words.txt, tests/unit/expected_test_results/ingredients/en-quantity-per-100g.json, tests/unit/expected_test_results/ingredients/fr-quantity-per-100g.json, tests/unit/expected_test_results/ingredients/fr-specific-ingredients.json, tests/unit/ingredients.t, tests/unit/ingredients_parsing.t
Related to #9060
This adds support for parsing " tomatoes (148g per 100g)".
Also a small refactor to create $per_100g_regexp in different languages.
=> fix: parse 'some ingredient (some quantity per 100g of finished product)'

taxonomies/categories.txt
taxonomy updates for categories:
- add proxy for Tête de Moine as it's similar to Abondance type of cheese
- proxy whole duck foie gras to duck raw liver
- english translation
=> taxonomy: add proxy for Tête de Moine as it's similar to Abondance

scss/_product-page.scss, templates/web/pages/product/product_page.tt.html
Add 1rem of "margin bottom" to fix the responsive issue
**Before :** 
**After :**
- Fixes #7495
@raphael0202
=> fix: add padding between tabs

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
Added data quality errors:
- vegan label but non-vegan ingredients
- vegetarian label but non-vegetarian ingredients
Added warning:
- vegan label but could not confirm for some ingredients
- vegetarian label but could not confirm for some ingredients
Question mark about the warning, because of these 2 cases:
- some ingredients (like thickener, for example) do not have the key-value vegan and vegetarian) -> but it can be additives classes that could contain only vegan/vegetarian additives. false-positive in this case (example: https://world.openfoodfacts.org/api/v2/product/3263859506216.json)
- key-value vegan and vegetarian can be yes, no or maybe. For this latter, we could also generate a warning.
These two would need further investigations. Maybe, we can start with this error and the …
=> fix: error and warning for vegan label with non-vegan ingredients

lang-default/fr/knowledge_panels/additives/en_e100_world.html, lib/ProductOpener/KnowledgePanels.pm, lib/ProductOpener/Tags.pm, templates/api/knowledge-panels/health/ingredients/additive.tt.json, tests/unit/tags.t
Allow to easily change the knowledge content for additive knowledge panels. Content is stored in openfoodfacts-web.
Before:
After:
=> feat: add knowledge content to additive knowledge panels

lib/ProductOpener/Display.pm, lib/ProductOpener/Tags.pm, po/tags/en.po, po/tags/tags.pot, tests/integration/expected_test_results/page_crawler/get-robots-txt-ch-it.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-fr-pro-platform.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-fr.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-world-pro-platform.txt, tests/integration/expected_test_results/page_crawler/get-robots-txt-world.txt
In addition to ingredients_tags, we also have ingredients_original_tags which contains the ingredients actually listed in the ingredients text, and not their parents.
This PR adds a facet /ingredients-original that allows us to list those. It will be very useful in particular to see which ingredients are the most popular.
As ingredients_original uses the ingredients taxonomy, this PR starts to differentiate the tag type (ingredients or ingredients_original from the taxonomy : ingredients). We could continue down this path to have traces use the allergens taxonomy without copying it as we do today (same for the data quality facets)
=> fix: add ingredients-original facet, start to split tagtype and taxonomy

lib/ProductOpener/Tags.pm
continuation of https://github.com/openfoodfacts/openfoodfacts-server/pull/9127 so that https://world.openfoodfacts.org/popularity/top-1000-scans-2022/ingredients-original?stats=1 can work correctly.
=> fix: exists_taxonomy_tag for ingredients_original tag type

taxonomies/origins.txt
Adds all 47 prefectures of Japan, as the branch contains Hokkaido. Translations were extracted from Wikidata.
=> taxonomy: Add all prefectures of Japan

html/js/product-preferences.js, scss/_off.scss
Fixes #7492 
Add 1rem of margin bottom to close button and "Classify products according to your preferences"
- Fixes #7492 
@raphael0202
=> fix: more spacing in edit preferences form

lib/ProductOpener/Ingredients.pm, stop_words.txt, tests/unit/expected_test_results/ingredients/fr-marmelade.json, tests/unit/expected_test_results/nutriscore/fr-ice-tea-with-sweetener.json, tests/unit/ingredients_nesting.t, tests/unit/ingredients_processing.t, tests/unit/ingredients_tags.t
Small refactor of @benbenben2 's PR https://github.com/openfoodfacts/openfoodfacts-server/pull/9122
- removed most parameters to parse_processing_from_ingredient ( $ingredients_lc, $ingredient )
- internally made a @processings structure instead of the comma separated list of processings. In future versions of the API I think it would be best to return the array.
=> fix: small refactor of processing parsing

docs/api/index.md
There was an error in the rate limits (/s instead of /min).
=> docs: fix rate limits

templates/web/common/site_layout.tt.html
Users don't understand it, and use it as a free form.
=> fix: don't display translation widget for non logged-in users

lib/ProductOpener/Lang.pm, scripts/build_lang.pl
This is an attempt to speed up tests. Almost all tests load Lang.pm.
- removed useless sleep()
- made parsing of the po/tags/ file saved in a file (like we do for po/common)
In profiling done with nytprof, this saves about 2 seconds per initialization. As we have 100 unit + integration tests, I'm hoping this should save 3 minutes when running all tests.
=> fix: speed up Lang.pm initialization, save 2 seconds x 100 tests

lib/ProductOpener/Ingredients.pm, taxonomies/categories.txt, tests/unit/expected_test_results/nutriscore/fr-canned-pineapple.json, tests/unit/ingredients_nutriscore.t, tests/unit/nutriscore.t
small fixes to compute the % of fruits/vegetables for canned foods (exclude water from all canned plant based foods, except canned fruits)
=> fix: % of fruits/vegetables for canned foods and Nutri-Score

taxonomies/ingredients.txt
Example of a product for which the amount of fruits, vegetable and nuts was wrongly calculated https://world.openfoodfacts.org/product/6413300017861/luonto-vanilja-arla
=> taxonomy: correction fruit juice concentrate

lib/ProductOpener/Data.pm
request to Open Food Facts query service didn't have any timeout.
=> fix: add timeout to off-query

taxonomies/categories.txt
put Trappist beers under Abbey ales (fix)
[sorry I made a mistake pushing the fix and had to close the [initial PR](https://github.com/openfoodfacts/openfoodfacts-server/pull/9198) and reopen this one]
=> taxonomy: put Trappist beers under Abbey ales (fix)

conf/nginx/sites-available/obf, conf/nginx/sites-available/off, conf/nginx/sites-available/opf, conf/nginx/sites-available/opff
Seems to divide by 10 the 2500 requests per minute we had on Open Pet Food Facts from GoogleAssociationService.
https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/264
before change:
```
root@opff:/var/log/nginx# tail -n 1000000 opff-access.log | grep GoogleAssociationService | grep 2023:15:00: | wc -l
2029
root@opff:/var/log/nginx# tail -n 1000000 opff-access.log | grep GoogleAssociationService | grep 2023:15:05: | wc -l
2468
root@opff:/var/log/nginx# tail -n 1000000 opff-access.log | grep GoogleAssociationService | grep 2023:15:15: | wc -l
2510
```
after change:
```
root@opff:/var/log/nginx# tail -n 1000000 opff-access.log | grep GoogleAssociationService | grep 2023:15:30: | wc -l
136
root@opff:/var/log/nginx# tail -n 1000000 opff-access.log | grep …
```
=> fix: set caching headers for assetlinks.json

lib/ProductOpener/Numbers.pm, lib/ProductOpener/Units.pm, tests/unit/units.t
=> fix: quantities starting with a dot .33L 

lib/ProductOpener/Ingredients.pm, taxonomies/labels.txt, tests/unit/expected_test_results/ingredients/fr-viande-de-boeuf-issue-d-animaux-nourris-sans-ogm.json, tests/unit/ingredients.t
Enables to parse strings like "beef meat from animals fed without GMO" / ""Viande de boeuf issue d'animaux nourris sans OGM""
=> fix: parsing of beef meat from animals fed without GMO

conf/nginx.conf
to avoid having google hammering staging environment
=> chore: cache rule for assetlinks in nginx docker

taxonomies/categories.txt
Insert AOP Isigny en Bresse creams under the proper Agribalyse parent : fr:Crèmes épaisses entières
=> taxonomy: insert AOP Isigny en Bresse creams under proper parent

lib/ProductOpener/Ingredients.pm, taxonomies/ingredients.txt, tests/unit/allergens.t
This is due to underscores. Replacing: "_Weizen_eiweiß" by: "Weizen eiweiß" or "Weizeneiweiß" avoids having the eggs allergen.
For other allergens, the following regex seems to work:
```
$text
=~ s/(^| - |_|\(|\[|\)|\]|,|$the|$and|$of|;|\.|$)((\s*)\w.+?)(?=(\s*)(^| - |_|\(|\[|\)|\]|,|$and|;|\.|\b($traces_regexp)\b|$))/replace_allergen_between_separators($language,$product_ref,$1, $2, "",$`)/iesg;
```
However, in the case of _Weizen_eiweiß it leads to 2 allergens. Hence, suggested solution is to add (for German only to minimize probability of false positive) the case when underscore after the allergen is not at the end of the word (remove \b of the previous line. This is done only for \b after the allergen, not before, again to minimize probability of false positive).
- Fixes #8386
=> fix: fix_avoid_eiweiss_false_positive_for_allergens

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
add dq error for product quantity above 30kg
added test for it + for others quantity warning (above 10kg below 1g and in mg) 
- Fixes #9217
=> feat: add dq error for product quantity above 30kg

lib/ProductOpener/APITest.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/Routing.pm, lib/ProductOpener/Tags.pm, lib/ProductOpener/Test.pm, lib/ProductOpener/TestDefaults.pm, stop_words.txt, templates/web/pages/tag/tag.tt.html, tests/integration/expected_test_results/facets/brand_-brand1.json, tests/integration/expected_test_results/facets/brand_-unknown.json, tests/integration/expected_test_results/facets/brand_brand1.json, tests/integration/expected_test_results/facets/brand_brand2_brand_-brand1.json, tests/integration/expected_test_results/facets/brand_unknown.json, tests/integration/expected_test_results/facets/category_-apples.json, tests/integration/expected_test_results/facets/category_-apples_label_-organic.json, tests/integration/expected_test_results/facets/category_-apples_label_organic.json, tests/integration/expected_test_results/facets/category_apples.json, tests/integration/expected_test_results/facets/category_apples_label_organic.json, tests/integration/expected_test_results/facets/category_bananas_label_organic_brand_-brand1.json, tests/integration/expected_test_results/facets/category_bananas_label_organic_brand_brand1.json, tests/integration/expected_test_results/facets/contributor_tests.json, tests/integration/expected_test_results/facets/label_fair-trade_label_-organic.json, tests/integration/facets.t, tests/unit/display.t, tests/unit/routing.t
Some initial refactoring to allow to have an unlimited number of <tag type>/<tag> in URLs.
=> feat: refactor to allow unlimited facets - WIP

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
Added quality facets to find pet food as well cosmetics in Open Food Facts. 
Based on the brand's list of Open Pet Food Facts and Open Beauty Facts, respectively. It does not include ALL brands, but brands having more than 4 products for Open Pet Food Facts and 10 products for Open Beauty Facts.
I would suggest converting them to error, and to remove false positive (if any) overtime.
- Fixes #1026
- Fixes #1027
=> feat: dq_petfood_beauty_brands

conf/systemd/gen_feeds@.timer, conf/systemd/gen_feeds_daily@.timer
Before doing the change:
```bash
sudo systemctl disable gen_feeds@obf.timer gen_feeds_daily@obf.timer
```
After the change:
```bash
sudo systemctl daemon reload
sudo systemctl enbale gen_feeds@obf.timer gen_feeds_daily@obf.timer
sudo systemctl list-timers
```
=> fix: fix gen_feeds timers install target

conf/systemd/gen_feeds@.timer, conf/systemd/gen_feeds_daily@.timer
There is a bad target for timers ! They won't run as wanted !
Before doing the change:
```bash
sudo systemctl disable gen_feeds@opff.timer gen_feeds_daily@opff.timer 
```
After the change:
```bash
sudo systemctl daemon reload
sudo systemctl enbale gen_feeds@opff.timer gen_feeds_daily@opff.timer 
sudo systemctl list-timers
```
=> fix: fix gen_feeds timers

.github/labeler.yml, html/donate/en.html
The broken og:url results in a big "Error" when sharing the donation page on Facebook.
=> fix: og-url for donate page to get correct Facebook share preview, change meta title

taxonomies/categories.txt
There's already a "pommes de terre vapeur" category for potatoes that can be steamed, so renaming the one for potatoes that are already steamed.
=> taxonomy: pommes de terre cuites à la vapeur

.github/labeler.yml, docs/api/ref/schemas/product_base.yaml
add description and example for `product_quantity` field.
=> docs: improve OpenAPI documentation

lib/ProductOpener/DataQualityFood.pm, stop_words.txt, taxonomies/categories.txt, tests/unit/dataqualityfood.t
Need to be reviewed carefully.
- See comments in the issue
- see how tests had to be updated (for polyols and erythritol)
- note that honeys category is under sweeteners and en:energy-value-in-kj-does-not-match-value-computed-from-other-nutrients will be shutdown for those as well
- Fixes #7789
=> feat: dq_kcal_does_not_match_exclude_more

taxonomies/categories.txt
Fixes in category taxonomy:
- wrong translation for chicken in Khmer
- add fr translations for some vegetables/fruits
- wrong parents for some categories
=> taxonomy: fixes in category taxonomy

.sonarcloud.properties
When using the SonarLint extension locally, I noticed some warnings in Dockerfile etc. Adding those to the  `sonar.sources` to get some feedback.
=> chore: Include some files in sonarcloud analysis

lib/ProductOpener/Ingredients.pm
Added some new abbreviations, made a minor regex tweak for Nynorsk, and added an ignore_regexps for cocoa percentage that can sometimes be found at the bottom of the ingredients list for chocolates.
=> fix: ingredient additions to norwegian bokmål

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
Categories with expected nutriscore should not raise error when not enough nutrients are provided. Because it could be that picture of nutrition table is missing and it could not be fixed.
> do not trigger the error if:
> 
>     nothing is entered in the nutrition table, or
>     "Nutrition facts are not specified on the product." is checked
> 
- Fixes #9297
=> fix: dq_nutriscore_alert_and_category_rework

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, tests/integration/expected_test_results/api_v2_product_write/get-product-auth-good-password.json, tests/integration/expected_test_results/api_v2_product_write/get-product.json, tests/unit/dataqualityfood.t
remove quality warning for salt under 0.1g
remaing quality warnings: salt under 0.01g and 0.001g
note that the warnings aim to detect if values could have been given in mg instead of g.
- Fixes #9346
=> fix: dq_nutrition_rm_salt_under_01g

lib/ProductOpener/Import.pm, scripts/export_producers_platform_data_to_public_database.sh, scripts/import_csv_file.pl, scripts/imports/carrefour/images.rules, scripts/imports/carrefour/run_carrefour_import.sh, scripts/imports/imports_utils.sh, scripts/imports/intermarche/run_intermarche_import.sh
A few things to note:
- Intermarché wants us to remove the files from the SFTP as we process them, thus we move them to a backup folder, so that we can reprocess them if needed
- The files are named in DD-MM-YYYY format and sometimes we get multiple months uploaded at the same second, we rename them to YYYY-MM-DD so that can import them in order
- The CSV files are in OFF format, but they have a byte order mark which breaks Text::CSV, so we remove the mark first
=> fix: move Intermarché / Les Mousquetaires import to producers platform

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
See linked issue.
Suggested solution:
trigger error if "<" symbol is missing
do not trigger error if at least one nutriment has "<" symbol
but trigger error if there is "<" symbol and 1 nutrient (sugar or starch) is above carbohydrates (that way we can still get error if the sugar or starch too high)
- Fixes #9267
=> fix: dq_sugar_plus_starch_greater_than_carbohydrates

lib/ProductOpener/Units.pm, taxonomies/units.txt
Reviewed the Mirabelle results from the issue for serving size (see below)
> Here are 100 examples randomly: http://mirabelle.openfoodfacts.org/products?sql=select+code%2C+url%2C+creator%2C+created_datetime%2C+last_modified_datetime%2C+product_name%2C+serving_size%2C+serving_quantity%0D%0Afrom+%5Ball%5D+%0D%0Awhere+%28serving_quantity+%3D%3D+%22%22+or+serving_quantity+IS+NULL%29+and+%28serving_size+%21%3D+%22%22%29%0D%0Aorder+by+random%28%29%0D%0Alimit+100
Brazil (pt:) added "gm". 5,484 rows
xx:onz, 128 rows
en:metric teaspoon 2 rows
note that beside metric teaspoon, teaspoon or tsp depends on the country (us, uk, canada)
same for cup and tbsp which is also a factor of the density (i.e., 1 tbsp of water will be different than 1 tbsp of sugar, for example)
gg instead of g is typo, not …
=> taxonomy: dq_serving_size_parsing_improvements

html/js/display-tag.js
Value might be null leading to a console error
=> fix: fix small js error

html/js/folksonomy.js, templates/web/pages/product/product_page.tt.html
=> fix: allow folksonomy engine on dietetary products

taxonomies/labels.txt
Remove redundant `es:Calidad certificada` taxonomy label entry.
=> taxonomy: Remove redundant alias

taxonomies/nutrients.txt
Multiple "sport suplements" contain differnt proteins that can be listed.
Most commonly there is `creatine`, but there are other aminoacids that are interesting.
=> taxonomy: Add (gym) protein nutrients

.devcontainer/devcontainer.json, docker/devcontainer.yml, docker/vscode.yml, docs/dev/how-to-quick-start-guide.md
Updated to the newer [devcontainer spec](https://containers.dev/), this allows using Perl in vscode via `Perl::LanguageServer`.
Note that this doesn't have feature parity with what's available in the Makefile, yet. Notably, tests don't work, yet, and it might be beneficial to run `make dev`  before opening the devcontainer.
=> chore: Re-enable devcontainers (experimental) 

taxonomies/ingredients.txt, tests/integration/expected_test_results/api_v2_product_read/get-existing-product.json, tests/unit/expected_test_results/ingredients/fi-do-not-match-myanmar.json
fix: more CIQUAL matches and translations
=> fix: more CIQUAL matches and translations

taxonomies/labels.txt
Reported on Slack by Binzy: https://openfoodfacts.slack.com/archives/C02VDSWHT/p1703058824686139
(already fixed in production)
=> taxonomy: typo in labels taxonomy fegg -> egg

lib/ProductOpener/Ingredients.pm, taxonomies/ingredients.txt, taxonomies/vitamins.txt
In ingredients preparasing, replace Vit. by Vitamin in German.
+ added "vit." as a synonym of "vitamin" in ingredients.txt taxonomy so that it also applies if ingredients are not preparsed.
It should be a more generic solution than https://github.com/openfoodfacts/openfoodfacts-server/pull/9564
=> taxonomy: vit. abbreviation for vitamins

templates/web/pages/product_edit/product_edit_form_display.tt.html
**Problem:** If a user enters a wrong value for energy, the label explaining the warning on energy is hidden by the nutrition image.   
**Solution:** Add the property `z-index` at the label (class `.sugar_warning`).
Before fix:
After fix:
- Fixes #8477
=> fix: Add z-index for sugar warning #8477

lib/ProductOpener/Units.pm, tests/unit/units.t
This is to remove warnings when the quantity is empty:
Use of uninitialized value $unit_id in hash element at /srv/off/lib/ProductOpener/Units.pm line 312.
=> fix: remove warnings for empty/undef quantities

.github/workflows/pull_request.yml, Makefile, docker/README.md, docker/docker-livecheck.sh, docs/dev/explain-pro-dev-setup.md, docs/dev/how-to-develop-producer-platform.md, docs/dev/how-to-develop-using-docker.md, docs/dev/how-to-quick-start-guide.md, docs/dev/how-to-use-direnv.md, docs/dev/how-to-use-gitpod.md, docs/dev/how-to-use-repl.md, docs/dev/how-to-use-vscode.md, docs/dev/how-to-write-and-run-tests.md, env.pro
Docker Compose V1 (`docker-compose`)  is deprecated and should not be used any more. ([Source](https://docs.docker.com/compose/migrate/)) This replaces the old command with `docker compose`, which is Compose V2, and bundled with current Docker distributions.
=> build: Migrate to Compose V2

Makefile, scripts/mongodb_dump.sh
The name of the file was wrong in the sums files.
Also ensure creation of html/data before it is created by docker with root ownership
**NOTE** I already edited the file in production to be back on track on mongodb-dev imports
=> fix: verification md5sum and sha256sum generation on mongodb dump

lib/ProductOpener/Ingredients.pm, tests/unit/expected_test_results/ingredients_percent/percentage-range-negative-pl.json, tests/unit/ingredients_percent.t
Make sure that variables are 1) defined + 2) non equal to "", to detect specific ingredients
- Fixes #9623
=> fix: bug_ingredients_wrongly_specific_ingredients

html/js/product-search.js, scss/_off.scss, scss/_product-list.scss
The product name is truncated due to a fixed height defined in the product link. This allows you to have a list of products with a unified height.   
Several solutions are possible (such as using grids), I preferred:
- keep a fixed height by adapting it to avoid seeing part of the text truncated.   
- use the [`-webkit-line-clamp` property](https://developer.mozilla.org/fr/docs/Web/CSS/-webkit-line-clamp) to display 3 points if the text is longer. The latter is still in [WD](https://drafts.csswg.org/css-overflow-4/#line-clamp) but supported by [97% of browsers](https://caniuse.com/?search=-webkit-line-clamp) and offers gracefull degradation if not supported.  
The full product name remains accessible by screen readers and when hovering over the map (via the title attribute of the link). …
=> fix: Product name truncated #7502

scripts/gen_feeds_daily_obf.sh, scripts/gen_feeds_daily_off.sh, scripts/gen_feeds_daily_opf.sh, scripts/gen_feeds_daily_opff.sh
mongodb was moved from off3 to off1
=> fix: update mongo server ip address to off1

lib/ProductOpener/DataQualityFood.pm, taxonomies/categories.txt, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
Add quality facets for jams having too small fruit quantity:
errors:
- en:specific-ingredient-fruit-quantity-is-below-the-minimum-value-of-35-for-category-jams
- en:specific-ingredient-fruit-quantity-is-below-the-minimum-value-of-25-for-category-redcurrants-jams
- ["en:specific-ingredient-<$specific_ingredient_id>-quantity-is-below-the-minimum-value-of-$quantity_threshold-for-category-<$category_id>]
info:
- en:missing-specific-ingredient-for-this-category
Following comment from @CharlesNepote and @aleene, I tried (maybe not perfectly done) to write the thresholds values directly in the taxonomy. 
This is only for specific ingredients, only for lower than the value provided. If it works well, in future PR, it could be generalized for ingredients and nutriments and for maximal values (for …
=> feat: dq_category_specific_ingredient_percent_2

lib/ProductOpener/DataQualityFood.pm, tests/integration/expected_test_results/convert_and_import_excel_file/test/products/3270190128403.json, tests/integration/expected_test_results/convert_and_import_excel_file/test/products/4270190128403.json, tests/unit/dataqualityfood.t
Updated condition for "en:nutrition-values-are-all-identical": 
- at least 4 nutriments should be entered.
- first element of the list that contains all values should be larger than 1
- Fixes #9572
=> fix: dq_all_val_in_nutrition_are_identical_2

taxonomies/categories.txt, taxonomies/ingredients.txt
In EU,
naming jams (jellies) or extra-jams (extra-jellies) are restricted for speficic content of fruit.
marmalade is restricted for citrus fruits (i.e. marmerlade = citrus jam)
Tried to update the taxonomy for categories accordingly.
- Put jams, extra-jams, jellies, extra-jellies and marmalade, all as child of <en:Fruit and vegetable preserves
- fusioned citrus jam and marmalades
- order jams and jellies in alphabetical order 
- surprisingly, "beer jam" category products are really jam, having content of fruit written on the package
- surprisingly, "milk jam" category products does not have content of fruit written but "milk jam" is really written on the package
- I did not duplicate all entries for jams (jellies) to include their extra-jams (extra-jellies) equivalent yet but I think we …
=> taxonomy: upd categories to reflect EU regulations

.github/labeler.yml, taxonomies/ingredients_processing.txt
taxonomy: ingredients processing
=> taxonomy: ingredients processing

taxonomies/categories.txt
=> taxonomy: correction sweet spreads

conf/systemd/sync_images_s3@.service, conf/systemd/sync_images_s3@.timer, scripts/sync-s3-images/README.md, scripts/sync-s3-images/openfoodfacts-images.yaml, scripts/sync-s3-images/requirements.txt, scripts/sync-s3-images/sync_s3_images.py
- move from openfoodfacts-infrastructure to openfoodfacts-server repo
- fix the script after server migration
- add systemd service and timer configuration files
The script runs correctly on production, but the service & timer config files have not been tested.
=> fix: move script syncing images to s3 to product-opener

lib/ProductOpener/DataQualityFood.pm
Bug reported on Slack
Sometimes the unit test 'all identical values and above 1 in the nutrition table 2' in dataqualityfood.t fails.
It happens because the array "@major_nutriments_values" (see Ingredients.pm) can have values in random order. Sometimes the first value is "0.8" and since we have the condition "@major_nutriments_values[0] > 1" facet is not raised. And test fails.
See the code for suggested solution
=> fix: fix_dq_facet_all_values_identical

lib/ProductOpener/Config_obf.pm, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Config_opf.pm, lib/ProductOpener/Config_opff.pm, lib/ProductOpener/Redis.pm
After https://github.com/openfoodfacts/search-a-licious/pull/81
Now there is one stream per project (OFF, OBF,..).
=> fix: use a different redis stream depending on the project

taxonomies/categories.txt, taxonomies/data_quality.txt, taxonomies/ingredients.txt, taxonomies/packaging_materials.txt, taxonomies/packaging_shapes.txt, taxonomies/vitamins.txt, tests/unit/expected_test_results/ingredients/fr-epices-irradiees.json
=> taxonomy: fix taxonomies

taxonomies/categories.txt, taxonomies/data_quality.txt, tests/unit/dataqualityfood.t
Continuity of previous PR https://github.com/openfoodfacts/openfoodfacts-server/pull/9606.
Now, for all jams, extra-jams, jellies.
According to EU regulations: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02001L0113-20131118
For existing categories in the taxonomy only.
- Fixes #1414
=> feat: dq_category_specific_ingredient_percent_3

lib/ProductOpener/Products.pm, scripts/update_all_products.pl
Something very strange is happening:
$product_ref->{code} .= '';   worked if it was just before the store() call, but not inside the make_sure_numbers_as_stored_as_numbers() function.
This change seems to work, but I don't know why.
=> fix: code stored as string

lib/ProductOpener/Food.pm, scripts/update_all_products.pl
small fix so that we correctly remove Nutri-Score related misc_tags (and only those tags) when we recompute Nutri-Score with update_all_products.pl
=> fix: nutriscore misc_tags removal

taxonomies/ingredients_processing.txt
=> taxonomy: fermented in cs

po/common/common.pot, po/common/en.po
@teolemon, I did not know what it means "missing translations in the Data Quality action button", I had to search.
1)
In the provided example, there is another facet where the button is as expected. Let's look at it first.
We can find reference to this "action" in
- data_quality.txt -> fix_action:en: add_origins - BUT not for all facets ( EcoScore - packaging - Packaging data missing, for example)
- Products.pm -> add_origins + url suffix
- en.po -> msgtxt "action_add_origins" + message in the box
```
origins_of_ingredients.tt.json -> 
"element_type": "action",
"action_element": {
"html": `[% lang("action_add_origins") %]`,
"actions": [
"add_origins",
]
}
```
however, more generic in data_quality_tags.tt.json:
```
[% IF fix_action != 'undef' %]
{
"element_type": "action", …
```
=> fix: missing_translations_in_dq_button

scss/_off.scss
This PR removes duplicate underlines from zoom controls in the map, ensuring cleaner appearance while maintaining underlines for other elements.
- Fixes #9161
=> fix: remove underline from zoom controls.

.github/workflows/pull_request.yml, scripts/build_lang.pl
It looks like the nutrient_levels taxonomy has not already been generated when tests are run. It should work anyway but it fails for some reason.
e.g. https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/8189813679/job/22395977705?pr=9854
Container po_off_test-memcached-1  Running
Could not load taxonomy: /mnt/podata/taxonomies/nutrient_levels.result.sto at /opt/product-opener/lib/ProductOpener/Tags.pm line 2507.
Compilation failed in require at tests/unit/additives_tags.t line 9.
This seems to happen only for the first test case, and only sometimes, maybe a race condition.
=> fix: pull request action, needs build_taxonomies before running tests

templates/web/common/site_layout.tt.html
=> feat: UTM all mobile links

templates/web/pages/product/product_page.tt.html
I made a mistake and loaded the product-history script twice, which caused a JS error.
=> fix: remove JS script loaded twice

conf/nginx-docker/nginx.conf
The docker nginx log file was in to /var/log/ instead of /var/log/nginx but I'm still getting a Permission denied.
Strangely nginx seems to be able to write to error_log but not access_log...
```
root@36323da821cb:/var/log/nginx# ls -lrt
total 75196
-rw-r--r-- 1 www-data www-data 45164097 Mar  7 08:10 access.log
-rw-r--r-- 1 www-data www-data 31825385 Mar 14 08:49 error.log
root@36323da821cb:/var/log/nginx# tail -n 1 error.log 
2024/03/14 08:49:11 [crit] 38#38: *5 open() "/var/log/nginx/access.log" failed (13: Permission denied) while logging request, client: 172.23.0.1, server: openfoodfacts.localhost, request: "GET /api/v0/preferences HTTP/1.1", upstream: "http://172.23.0.8:80/cgi/display.pl?/api/v0/preferences", host: "fr.openfoodfacts.localhost", referrer: …
```
=> fix: nginx docker access_log location

conf/nginx/conf.d/expires-no-json-xml.conf, conf/nginx/sites-available/howmuchsugar, conf/nginx/sites-available/madenearme, conf/nginx/sites-available/off, conf/nginx/sites-available/off-pro, conf/nginx/snippets/expires-no-json-xml.conf
Notes:
- each site conf had a include /etc/nginx/snippets/expires-no-json-xml.conf which is in fact server wide, it's now moved to the conf.d directory
- the whole conf.d directory is symlinked to the conf.d dir in GitHub (instead of having symlinks for each file in it)
root@off:/etc/nginx# ls -lrt | grep conf.d
drwxr-xr-x 2 root root    3 Aug 17  2023 conf.d.old
lrwxrwxrwx 1 root root   26 Mar 14 15:01 conf.d -> /srv/off/conf/nginx/conf.d
- changed the way we determine which log file to use (static-access-log or proxy-access-log) using location instead of file extensions. This is because we can't use variables in log file names + buffers:
```
-nginx: [emerg] buffered logs cannot have variables in name in /etc/nginx/sites-enabled/off:36
nginx: configuration file /etc/nginx/nginx.conf test …
```
=> fix: nginx config changes for prod

cgi/auth.pl
=> fix: add some user info in /cgi/auth.pl body 

conf/nginx-docker/nginx.conf, conf/nginx/sites-available/obf, conf/nginx/sites-available/off, conf/nginx/sites-available/off-pro
[Yesterday's changes for nginx prod](https://github.com/openfoodfacts/openfoodfacts-server/pull/9919) broke nginx docker, harmonizing.
=> fix: docker nginx config

cgi/generate_sample_import_file.pl, po/common/common.pot, po/common/en.po, po/common/es.po
I added a description row to the import spreadsheet template, which now includes all the comments previously located in the header line.
- Added a new column on the right to accommodate the Description and Example rows
- Added some width to the Description cell 
- Changed the code that wrote the comments in the header row to write them in the description row 
- Fixes #9879
=> fix: Added a description line to the import spreadsheet template

lib/ProductOpener/Config_off.pm, lib/ProductOpener/Food.pm, lib/ProductOpener/Paths.pm, lib/ProductOpener/Tags.pm, scripts/build_countries_taxonomy_from_wikidata.pl, scripts/build_languages_taxonomy_from_wikidata.pl, scripts/obsolete/add_efsa_evaluations_to_additives_taxonomy.pl, scripts/obsolete/create_wikipedia_properties_for_taxonomy.pl, scripts/taxonomies/generators/add_descriptions_to_taxonomy_from_eu_translations.pl, scripts/taxonomies/generators/gen_obf_inci_functions_taxonomy_from_cosing.pl, scripts/taxonomies/generators/gen_obf_ingredients_taxonomy_from_cosing.pl, scripts/taxonomies/translate_taxonomy_with_eu_translations.pl, tests/unit/paths.t
This will avoid having current error on deployment (which breaks deployments).
It cleanly separate data from sources.
=> fix: separate taxonomy src and builds

templates/web/pages/tag/tag.tt.html, templates/web/panels/panel.tt.html
When scrolling, the map would cover other content. This PR corrects the z-index for the same for normal functioning and better UI. 
Before:
After:
- Fixes #7509
=> fix: updated z-index of map

Makefile
The fact that we user docker test (for unknown reason, but maybe a copy / paste ;-)) leads to eventual race condition in check_perl as parallel processes tries to build taxonomies and read/write at the same files…
=> ci: use normal docker compose to check for perl files

cgi/generate_sample_import_file.pl
I changed the title of the import template spreadsheet from `openfoodfacts_import.xlsx` to `openfoodfacts_import_template_en.xlsx`
The latter title is more descriptive and can help producers differentiate between files especially if they download in multiple languages.
=> fix: Add lang tag to import template title

lib/ProductOpener/Ecoscore.pm, lib/ProductOpener/FoodGroups.pm
Fix for food_groups + fix for Eco-Score origins
The test was failing probably because the origins:en property for the category en:calvados changed. I'm not sure how the corresponding change was merged without the test failing though.
=> fix: Fix ecoscore origins

po/common/de.po, po/common/es.po
Translations for https://de.openfoodfacts.org/ had already been added.
As per the changes suggested on #9658 and https://openfoodfacts.slack.com/archives/C02LDQDDD/p1707921684661859?thread_ts=1707083612.774809&cid=C02LDQDDD, added translations for https://es.openfoodfacts.org/
=> fix: Added Translations in Spanish

docs/dev/how-to-quick-start-guide.md, scripts/mongodb_dump.sh
We currently generate 3 MongoDB exports, each of them takes more than one hour to generate every day:
```
-rw-r--r--   1 off  off   4675987404 Mar 18 08:08 fr.openfoodfacts.org.products.rdf
-rw-r--r--   1 off  off   7311036936 Mar 18 09:36 openfoodfacts-products.jsonl.gz
-rw-r--r--   1 off  off   8859132762 Mar 18 10:28 openfoodfacts-mongodbdump.gz
-rw-r--r--   1 off  off           95 Mar 18 10:30 gz-sha256sum
-rw-r--r--   1 off  off           63 Mar 18 10:30 gz-md5sum
-rw-r--r--   1 off  off   8932229671 Mar 18 11:42 openfoodfacts-mongodbdump.tar.gz
```
I suggest that we completely remove openfoodfacts-mongodbdump.tar.gz which has exactly the same usage as openfoodfacts-mongodbdump.gz
I'm not sure if we should keep the jsonl. As I recall, it was added for Robotoff. Do we still need it? …
=> fix: keep only one (or two?) mongodb export

docs/dev/explain-packaging-data.md
Change to "Only the value for the main product of the language is currently analyzed." as discussed with stephanebiz.
=> docs: light copyediting: docs/dev/explain-packaging-data.md

Dockerfile, cpanfile, lib/ProductOpener/Store.pm
It appears ProductOpener::Store does not use Encode::Punycode to normalize strings but uses the tr and s instructions.
=> fix: drop Encode::Punycode (no longer used)

cpanfile, lib/ProductOpener/Images.pm
The modules were in some old code I had from past projects but were not in actual use in Product Opener.
=> fix: remove unused Graphics::Color::RGB/HSL modules

docs/dev/how-to-use-gitpod.md
=> fix: GitPod clarification

docs/dev/how-to-quick-start-guide.md
- Update URL for installing Docker CE
- Remove instructions for installing Docker Compose (which the above procedure will install) to limit confusion
- Remove dead link for Docker command completion
- Renumber toplevel sections so there's no missing section 3
- Add problem I had on Debian to troubleshooting section
=> docs: update and copyedit docs/dev/how-to-quick-start-guide.md

docs/dev/how-to-develop-using-docker.md
- More #9854 tracking
- While there, copyediting throughout
=> docs: fact-check docs/dev/how-to-develop-using-docker.md

docs/dev/how-to-develop-producer-platform.md
While there:
- reorganize surrounding text for better flow
- light copyediting throughout
=> docs: track introduction of env/setenv.sh in #9854

docs/dev/how-to-use-gitpod.md
Note on the "500 credits" bit:
It's no longer present in https://www.gitpod.io/pricing that I can see, so (after discussion with Alex G.) I removed it. Feel free to re-add it if I missed it.
=> docs: factcheck and copyedit docs/dev/how-to-use-gitpod.md

Makefile, docker/prod.yml
Because taxonomies must survive a `docker-compose down -v`
=> ci: add external volumes for build-cache

lib/ProductOpener/Config2_docker.pm, lib/ProductOpener/Config2_sample.pm, lib/ProductOpener/Config_obf.pm, lib/ProductOpener/Config_off.pm, lib/ProductOpener/Config_opf.pm, lib/ProductOpener/Config_opff.pm
Disable the `Modules::RequireFilenameMatchesPackage` rule for config files, because we have several symlinked variants of those.
=> fix: Disable RequireFilenameMatchesPackage for Config*_.pm

scripts/update_tags_per_languages.py, scripts/update_tags_per_languages_tests.py
Python code to: 
- fetch unknown tags for categories, allergens, etc.
- check if each unknown tag exists in the taxonomy in different language
- if yes, to all products having the tag in wrong language:
- add existing tag in different language 
- remove tag in wrong language 
Code is generalized to - not only categories, but also - additional tags fields.
Lots of comments in the code, which should be helpful for reviewer and user.
Instructions on how to run the code, test it, run it in dev vs prod, are provided on top of the file.
The code was run successfully - in **net** environment - for 4 different tags:
```
"en:teilentrahmte-milch" => "de:teilentrahmte-milch"
"en:trempettes" => "fr:trempettes"
"en:turrones-de-chocolate" => "es:turrones-de-chocolate"
"en:кисели-краставички" => …
```
=> feat: dq_correct_wrong_lang__for_tags

templates/web/pages/product/product_page.tt.html
The contribution tag in the navigation bar does not get highlighted even when on the page which has a contribution panel .
This issue was solved from the product_page.tt.html file where there was an anchor tag with the id="contribution" that was always being rendered on the product page even if the contribution_card_panel exists or not. I added the id="contribution" to the section tag containing the contribution panel and checked for the existence of the panel, if not the anchor tag with id="contribution" will be rendered.
https://github.com/openfoodfacts/openfoodfacts-server/assets/135853264/a06eb782-8dbd-41f7-97d1-17e039f8cf73
- Fixes #10061
=> fix: contribution tag not highlighting as part of issue #10061

cpanfile, lib/ProductOpener/APIProductRevert.pm, lib/ProductOpener/APITest.pm, lib/ProductOpener/Attributes.pm, lib/ProductOpener/Data.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/Food.pm, lib/ProductOpener/FoodGroups.pm, lib/ProductOpener/HTTP.pm, lib/ProductOpener/Ingredients.pm, lib/ProductOpener/Mail.pm, lib/ProductOpener/Nutriscore.pm, lib/ProductOpener/Packaging.pm, lib/ProductOpener/Paths.pm, lib/ProductOpener/Producers.pm, lib/ProductOpener/Products.pm, lib/ProductOpener/Redis.pm, lib/ProductOpener/Tags.pm, lib/ProductOpener/Test.pm, lib/ProductOpener/TestDefaults.pm, lib/ProductOpener/Text.pm, lib/ProductOpener/Users.pm, lib/ProductOpener/Web.pm, scripts/preprocess_intermarche_packaging_csv_file.pl, tests/unit/all_pod_correct.t, xt/README.txt, xt/all_pod_correct.t
Minor POD fixes in this PR : 
- make sure the =encoding UTF-8 directive is present when the doc uses non-ASCII chars
- always have blank lines before and after =pod directives (some old POD parsers require this)
- add a test to check for the rules above
=> fix: improve the POD documentation so that it conforms to usual Perl conventions

lib/ProductOpener/Tags.pm
A typo in a recent PR prevented additives.properties.txt to be used as a source for the additives taxonomy, so we didn't have the Wikipedia descriptions etc.
Bug uncovered with the new HTML generation tests from https://github.com/openfoodfacts/openfoodfacts-server/pull/10043
=> fix: typo preventing additives.properties.txt to be used when building taxonomies

conf/logrotate/apache2, conf/logrotate/nginx, conf/systemd/gen_feeds@.service, conf/systemd/gen_feeds_daily@.service
I have logs far to big on opf, it appears it's because gen_feeds scripts logs in syslog.
=> fix: better logs

lib/ProductOpener/Tags.pm, taxonomies/food/ingredients.txt
=> fix: remove circular parent in ingredients taxonomy

taxonomies/food/categories.txt
This should fix an issue reported on Slack: https://openfoodfacts.slack.com/archives/CDB8EJ8DB/p1712137202445779?thread_ts=1712125240.621989&cid=CDB8EJ8DB
By priority, we try to find an agribalyse_food_code, so it should not be on parent categories like "tunas" that contain both "raw tunas" and "cooked tunas" etc. So we should specifiy it is a proxy instead.
=> taxonomy: tuna - use ciqual/agribalyse proxy for ambiguous parent categories

lib/ProductOpener/Paths.pm, tests/unit/paths.t
This issue is preventing some shell scripts to work correctly, as they don't have paths exported.
=> fix: base_paths_loading_script needs to be exported

lib/ProductOpener/KnowledgePanels.pm, lib/ProductOpener/KnowledgePanelsReportProblem.pm, templates/api/knowledge-panels/report_problem/fr_report_product_signalconso.tt.json, templates/api/knowledge-panels/root.tt.json, templates/web/pages/product/product_page.tt.html, tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html, tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html, tests/integration/expected_test_results/product_read/get-existing-product.html, tests/integration/expected_test_results/web_html/fr-product-2.html, tests/integration/expected_test_results/web_html/fr-product.html, tests/integration/expected_test_results/web_html/world-product.html
Removes a warning that $panel_data_ref is redeclared
=> fix: remove warning in KnowledgePanelsReportProblem.pm, remove report problem card from pro platform

lib/ProductOpener/Ingredients.pm
=> taxonomy: romanian

cgi/auth.pl, lib/ProductOpener/APITest.pm, tests/integration/auth.t, tests/integration/expected_test_results/auth/auth-authenticated-with-userid-and-password.json
This PR changes auth.pl so that it sets the session cookie when auth.pl is called with a user_id and password (similar to what we do in login.pl)
Also added some tests.
Fixes #10140 (needed urgently for testing the new Nutri-Score knowledge panels)
=> fix: send cookie in auth.pl

templates/web/pages/org_form/org_form.tt.html
- I added a script to the `templates/web/pages/org_form/org_form.tt.html` file that toggles off the Invite Users button until at least one email address has been entered.
- This script also uses Regex to validate the value of each email address entered to ensure users are inviting valid email addresses and not just random texts.
- Fixes #10130
=> fix: disable the Invite Users button until at least one email address has been entered

cgi/auth.pl, tests/integration/expected_test_results/auth/auth-authenticated-with-userid-and-password.json
add cc field requested by @monsieurtanuki in https://github.com/openfoodfacts/openfoodfacts-dart/pull/903#event-12404120731
note that cc can also be "world"
also removed some fields if their value is undef or empty
=> fix: add cc field to auth.pl

docs/api/ref/schemas/product_tags.yaml
=> docs: Update product_tags.yaml

templates/api/knowledge-panels/health/ingredients/nova.tt.json
fix: make NOVA panel clearer
- #5519
=> fix: make NOVA panel clearer

docs/dev/how-to-quick-start-guide.md
I was having trouble building my local installation due to lacking proper permissions recently. I have added the steps to remedy permission issues on macOS. I added the commands that would allow for user to check which files lack permissions than changing such permissions via terminal.
=> docs: updated quick start guide with fix to permission issue on macOS. 

lib/ProductOpener/Display.pm, templates/web/pages/product/includes/edit_history.tt.html
Exposing the "app_version" variable from a products changes.sto file in the product edit history if populated. This allows apps to identify if data quality issues are coming from new or old versions which, in-turn, allows to track new bugs, regressions, etc in submissions.
**Discussion from slack**
=> feat: display "app_version" in  product edit history

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
fix: data quality downgrade some errors to warnings
- Fixes #10064
=> fix: data quality downgrade some errors to warnings

docs/api/tutorial-uploading-photo-to-a-product.md
docs: fixes to the Image upload documentation
=> docs: fixes to the Image upload documentation

taxonomies/food/categories.txt, tests/integration/expected_test_results/web_html/fr-categories.html
translate categories in Croatian
- Fixes #-
=> taxonomy: translate categories in Croatian

html/js/product-search.js, templates/web/common/includes/list_of_products.tt.html, tests/integration/expected_test_results/page_crawler/crawler-access-category-facet-page.html, tests/integration/expected_test_results/page_crawler/crawler-does-not-get-facet-knowledge-panels.html, tests/integration/expected_test_results/page_crawler/normal-user-access-category-facet-page.html, tests/integration/expected_test_results/page_crawler/normal-user-access-nested-facet-page.html, tests/integration/expected_test_results/page_crawler/normal-user-get-facet-knowledge-panels.html, tests/integration/expected_test_results/unknown_tags/country-france-exists.html, tests/integration/expected_test_results/unknown_tags/ingredient-apple-exists.html, tests/integration/expected_test_results/unknown_tags/ingredient-someunknowningredient-does-not-exist-but-not-empty.html, tests/integration/expected_test_results/web_html/fr-categories.html, tests/integration/expected_test_results/web_html/fr-index.html, tests/integration/expected_test_results/web_html/fr-search-results.html, tests/integration/expected_test_results/web_html/world-categories.html, tests/integration/expected_test_results/web_html/world-index-signedin.html, tests/integration/expected_test_results/web_html/world-index.html, tests/integration/expected_test_results/web_html/world-label-organic.html, tests/integration/expected_test_results/web_html/world-search-results.html
=> fix: alt tags for images on list of products 

html/js/product-search.js, lib/ProductOpener/Tags.pm, tests/integration/expected_test_results/web_html/fr-product-2.html, tests/integration/expected_test_results/web_html/fr-product.html
Missing alt attribute on images in product page: labels, Nutri-score, Ecoscore, Nova
- Fixes #10292
=> fix: product page accessibility - img alt attribute

html/js/product-preferences.js, lib/ProductOpener/Display.pm, lib/ProductOpener/HTTP.pm
This PR sets the Cache-Control: public, max-age=86400 on responses for API /api/v0/preferences and /api/v0/attribute_groups (requested on all web pages for Personal Search). It also fixes the JS so that we don't load /api/v0/preferences twice.
Related: https://github.com/openfoodfacts/openfoodfacts-server/issues/8957
=> fix: cache /api/v0/preferences and attribute_groups

taxonomies/food/ingredients.txt
Adds Cyanocobalamin  -> B12 taxonomy
https://de.openfoodfacts.org/produkt/4337256601238/vegan-soja-vanille-rewe-beste-wahl
https://www.sustagen.com.au/product/sustagen-everyday?selectedValue=12417063
Note that [AGROVOC](https://agrovoc.fao.org/browse/agrovoc/en/) mentions that [`vitamin B12`](https://agrovoc.fao.org/browse/agrovoc/en/page/c_8269) is the preferred term, this does come up in a handful of different ingredient lists.
=> taxonomy: add Cyanocobalamin -> b12

cgi/org.pl, lib/ProductOpener/Users.pm
- Fixed the issue where the orgid from the URL query string was not correctly decoded in Perl's internal string representation when it contained utf8 characters. On the professional user's side, the org .sto file could not be found for the same reason.
- Fixes #10177
=> fix: utf8 orgid support in url query string

taxonomies/food/ingredients.txt
There were 2 entries for split peas, which broke properties for it.
=> taxonomy: remove duplicate split peas entry in ingredients

lib/ProductOpener/Ingredients.pm, taxonomies/additives.txt, taxonomies/food/ingredients.txt, tests/unit/expected_test_results/ingredients/en-comma-and-pepper.json, tests/unit/expected_test_results/ingredients/en-ing1-and-ing2-processing.json, tests/unit/expected_test_results/ingredients/en-some-unknown-ingredient-and-salt.json, tests/unit/ingredients.t, tests/unit/ingredients_tags.t
A few fixes that will help in particular recognizing more ingredients when we have "A and B": previously we cut it to A + B only if both A and B were in the taxonomy. Now we do it if at least one of them is in the taxonomy. This will help in particular for products that have "some weird ingredient and salt".
=> fix: better parsing of ingredient (something unknown and something known)

conf/apache-2.4/off-mpm_prefork.conf, conf/apache-2.4/off-pro-mpm_prefork.conf, conf/off-log.conf
This reduces MaxConnectionsPerChild from 500 to 100 on OFF (and activates it on off-pro) in order to reduce the size of the apache mod_perl processes that grow over time.
The processes start at 1.5Gb, but on off-pro they grew up to 2.5Gb.
I also reduced the number of processes on off-pro, as traffic should be very small.
@raphael0202 I accidentally checked in a change to off-log.conf that was on the off container on off2, I assume it's a wanted change?
=> fix: change mpm_prefork configuration for off and off-pro to reduce memory usage

lib/ProductOpener/Ingredients.pm, taxonomies/food/ingredients.txt, tests/unit/allergens.t, tests/unit/allergens_tags.t
We currently have many synonyms of allergens listed in the allergens.txt taxonomy, but very often those are not actual synonyms, but more specific ingredients. (e.g. for the en:fish allergen, we list different species of fish).
This does not scale very well. Instead we now have the allergens:en: property in the ingredients taxonomy. It is currently used to identify allergens listed as ingredients.
This PR extends the use of the allergens:en: property so it can be used to normalize the allergens and traces that are listed manually in the "allergens" and "traces" field.
There are still other uses of the synonyms in allergens.txt (e.g. for parsing phrases like "may contain...". We should try to use the allergens:en: property instead, so that we can ultimately remove the "non synonyms" from …
=> feat: use more the allergens:en property of the ingredients taxonomy

taxonomies/food/ingredients.txt, taxonomies/ingredients_processing.txt
https://www.woolworths.com.au/shop/productdetails/220157/edgell-snack-time-black-beans-charred-capsicum-with-zesty-salsa
We don't call capsicums "bell peppers" :)
Source 1:
>In Australia, New Zealand and [Indian English](https://en.wikipedia.org/wiki/Indian_English), heatless varieties are called "capsicums", while hot ones are called "chilli"/"chillies" (double L). The term "bell peppers" is never used
>
> https://en.wikipedia.org/wiki/Capsicum#Synonyms_and_common_names
Source 2:
> Woolworths, capsicums are on sale
> https://www.woolworths.com.au/shop/productdetails/135306/red-capsicum
> Coles, capsicums are on sale
> https://www.coles.com.au/product/coles-red-capsicum-approx.-220g-4580208
Source 3:
[Australian Centre for International Agricultural Research (ACIAR) …
=> taxonomy: add support for "chargrilled corn" and "red capsicum"

lib/ProductOpener/Import.pm, templates/emails/import_csv_file_admin_notification.tt.html, tests/integration/expected_test_results/convert_and_import_excel_file/carrefour-images/products/stats.json, tests/integration/expected_test_results/convert_and_import_excel_file/openfoodfacts_import_template_fr_test/products/stats.json, tests/integration/expected_test_results/convert_and_import_excel_file/packagings-mousquetaires/products/stats.json, tests/integration/expected_test_results/convert_and_import_excel_file/test/products/stats.json, tests/integration/expected_test_results/import_csv_file/replace_existing_values/stats.json, tests/integration/expected_test_results/import_csv_file/test/stats.json
This is to display the GS1 GLNs used by organizations in the reports (email to pro platform admins) of the import_csv_file.pl script.
Needed so that we can easily override which GLNs goes to which organization.
=> fix: show GLNs used by orgs in GS1 imports

.env, .github/workflows/container-deploy.yml, Makefile, docker/docker-livecheck.sh, docker/run.yml
Use a different target for docker compose up in production so that dependencies aren't also started in dev mode.
=> fix: Use a separate make target for production up to not create dependencies

cgi/import_file_process.pl, cgi/product_multilingual.pl, lib/ProductOpener/CRM.pm, lib/ProductOpener/Import.pm, lib/ProductOpener/Orgs.pm, lib/ProductOpener/Test.pm, tests/integration/expected_test_results/create_pro_user/org-after-subscription.json, tests/integration/expected_test_results/create_pro_user/org-after-validation.json
Fixed:
- A contact was not created in the CRM when the org was validated and the main contact was not the creator.
- The last logged member of the org was not actually stored in the org .sto (missing store_org call) 
- The last import type was not stored in the org but only updated on the crm
=> fix: various fixes to data sync with CRM

po/common/common.pot, po/common/en.po, po/common/fr.po, templates/web/pages/dashboard/display_orgs_table.tt.html
1. added new fields(last login, last import, data sources) to the organisation table
=> feat: display new fields in orgs table

lib/ProductOpener/Routing.pm
Added a dynamic routing mechanism, by allowing to provide a condition that will need to be true for the route to be used after being matched  - or else to pass to the remaining regex patterns. 
It uses an anonymous sub that'll be called during the route match, with the request's context as parameters.
For example, this feature makes it possible to hide certain routes for some languages and allow them for others.
- Fixes #10508
=> feat: add an optional condition for routes to be used or not

lib/ProductOpener/CRM.pm, scripts/check_if_orgs_can_be_safely_synced_with_crm.pl
The script create a csv file that tells what will be matched in the crm and what will be created. 
It's like a verbose dry run of accepting the org.
=> feat: a script to check if existing org can be sync with the crm

templates/web/pages/dashboard/display_orgs_table.tt.html
Made the verified status filter on organisation table a dropdown
- This is an update to this PR https://github.com/openfoodfacts/openfoodfacts-server/pull/10510
- Also fixes #https://github.com/openfoodfacts/openfoodfacts-server/issues/10525
=> feat: make valid org filter field a dropdown

lib/ProductOpener/CRM.pm, lib/ProductOpener/Orgs.pm, scripts/migrations/2024_07_change_main_contact.pl
- Added a script to remove orgs main contact that are not regular users. By default last migration, during the CRM integration, used the creator of the org to set the main contact. This caused the main contact to be agena3000/equadis/.. or even empty for some orgs.
- Allow orgs to not have a main contact if it was imported from an aggregator such as agena3000 or equadis
- New members can still be added to the orgs later ; it will be synced with the crm if the orgs has been accepted.
This script must be run in prod: `scripts/migrations/2024_07_change_main_contact.pl`
=> feat: allow orgs to not have a main contact if imported from an aggregator

lib/ProductOpener/CRM.pm, scripts/check_if_orgs_can_be_safely_synced_with_crm.pl
Overall improvement of the information provided by the csv file generated by the script `scripts/check_if_orgs_can_be_safely_synced_with_crm.pl`
We need to run this script in prod
- depends on #10531
=> fix: improve generated data

conf/off-log.conf
Important fix, already done in production.
Otherwise log was only displaying `ARRAY(xxxx)` instead of information.
=> fix: rate limiter log config

Dockerfile.frontend
Frontend docker container build fails with new npm:latest (20.15.1) version. https://github.com/npm/cli/issues/7639
This PR set the version to the previous 20.15.0 until it's fixed.
```
------
> [dynamicfront builder  6/13] RUN --mount=type=cache,id=npm-cache,target=/root/.npm npm install:
143.0 npm error Exit handler never called!
143.0 npm error This is an error with npm itself. Please report this error at:
143.0 npm error     <https://github.com/npm/cli/issues>
143.0 
143.2 
143.2 npm error A complete log of this run can be found in: /home/node/.npm/_logs/2024-07-11T08_05_58_996Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
make: *** [Makefile:129: build] Error 17
```
=> build: frontend container cannot be built since npm version 20.15.1

lib/ProductOpener/Display.pm
On pro platform, disable caching so that producers can see their edits instantly without Ctrl R
=> fix: disable caching on pro platform

lib/ProductOpener/Routing.pm
Fixes this problem:
Pro moderator and admins experienced issues with the org/[orgid] facet in the url. The feature that allows them to navigate and act as they are part of the org is not properly working.
=> fix: pro_moderator_owner not stored for the admin/moderator user through org/[orgid] facet

lib/ProductOpener/Redis.pm
going forward, Redis clients should use product_type (currently food, beauty, petfood, products) instead of flavor
=> fix: add product_type to redis events

taxonomies/food/ingredients.txt
Add “akaciefiber” as a synonym of “akaciafiber” for Swedish.
[![“Akaciefiber” as unknown ingredient on 7311312007100](https://github.com/user-attachments/assets/40cb0632-e88a-4770-a4cc-e1a2db62ed39)](https://se.openfoodfacts.org/product/7311312007100/crunchy-granola-%C3%A4pple-kanel-risenta#health)
- https://openfoodfacts.slack.com/archives/C06A7LENM/p1721573740332399
=> taxonomy: Add “akaciefiber” synonym (Swedish)

.gitignore
the deps subdir was wrongly added to the repository.
=> build: fix working tree removing shared-services

cpanfile
Fixes the following message spamming test logs:
> yath: Using UUID::Tiny for uuid generation. UUID::Tiny is significantly slower than the 'UUID' or 'Data::UUID::MT' modules, please install 'UUID' or 'Data::UUID::MT' if possible.
=> build(deps-dev): Add `UUID` module

lib/ProductOpener/Data.pm
We recently switched from JSON::PP to Cpanel::JSON::XS, and it looks like JSON::PP decode_json() was accepting to decode raw numbers, without having to specify allow_non_ref.
We had an issue when trying to deploy to prod, because on count requests, the return value we get from off-query is a raw number, which could not get decoded:
[2024/07/23 15:28:00] /srv/off/lib/ProductOpener/Display.pm 5369 ProductOpener.Display {error => '
JSON text must be an object or array (but found number, string, true, false or null, use allow_non
ref to allow this) at /srv/off/lib/ProductOpener/Data.pm line 140. ',request => 'qwfXeMshf0b7OpAF'
,tags => [{canon_tagid => 'en:canadaschtroumpf',display_tag => 'Canadaschtroumpf',new_tagid => 'en
:canadaschtroumpf',new_tagid_path => '/country/canadaschtroumpf',tag …
=> fix: use allow_non_ref in JSON decoding of off-query

taxonomies/food/ingredients.txt
Adds Swedish translation of `en:habanero chili` as it was missing.
- https://se.openfoodfacts.org/product/7350113940056/zeina-s-hummus-mix-original-chili-soltorkad-tomat#health
=> taxonomy: Add Swedish for habanero chili

taxonomies/food/ingredients.txt, taxonomies/ingredients_processing.txt
Add Swedish translations and synonyms
- lågfett kakaopulver (low-far cocoa powder, ingredients)
- kokoschips (coconut chips, ingredients)
- frystorkade (freeze dried, processing)
- https://se.openfoodfacts.org/product/7311312007117/risenta-crunchy-granola-kakao-hallon-kokos#health
=> taxonomy: Add Swedish translations and synonyms

taxonomies/food/categories.txt, taxonomies/labels.txt
remove opposite when not needed (categories)
put back opposite when it was used, before https://github.com/openfoodfacts/openfoodfacts-server/pull/10378 (labels). Remember that opposite tag is used in Import.pm.
=> fix: dq new facet for opposite tags fix

.github/workflows/pr_actions.yml
As we often use them on PR from foreign repositories
=> ci: don't test ownership for actions

taxonomies/food/ingredients.txt
Add Swedish translations for carrot concentrate and almond chunks/pieces.
[![unknown ingredients](https://github.com/user-attachments/assets/228d13fe-c414-42ff-94ff-0d5b3f64a90e)](https://se.openfoodfacts.org/product/4056489627821/vemondo-veganska-mandel-glasspinnar-lidl#health)
- https://se.openfoodfacts.org/product/4056489627821/vemondo-veganska-mandel-glasspinnar-lidl#health
=> taxonomy: Add Swedish translations for carrot concentrate and almond chunks/pieces

docs/api/ref/api.yml, docs/api/ref/responses/change_ref_properties.yaml
The `api.yaml` file contained a reference to a non-existent `./responses/change_ref_properties.yaml` file, causing validation to fail. This PR adds the missing file to ensure the OpenAPI definition is valid.
- Fixes #10659
=> fix(docs): Correct OpenAPI definition by fixing missing reference 

taxonomies/food/ingredients.txt
Adds Swedish translation of rice bran oil to taxonomy, since it was missing.
[![missing ingredient](https://github.com/user-attachments/assets/f9a3090a-45fc-450c-85c5-20239e961fc1)](https://se.openfoodfacts.org/product/4056489412236/vitasia-rice-cracker-spicy-sweet-chili-flavour-lidl#health)
- https://se.openfoodfacts.org/product/4056489412236/vitasia-rice-cracker-spicy-sweet-chili-flavour-lidl#health
=> taxonomy: Add Swedish translation of rice bran oil

README.md
Related to #10666
Add the OpenSSF Best Practices badge to the README file.
* Place the badge near the top of the `README.md` file, next to other existing badges.
* Use the provided markdown for the badge: `[![OpenSSF Best Practices](https://www.bestpractices.dev/projects/9345/badge)](https://www.bestpractices.dev/projects/9345)`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/openfoodfacts/openfoodfacts-server/issues/10666?shareId=9b29307e-6f78-4f6e-8359-90cb1a302dd2).
=> docs: Add OpenSSF Best Practices badge to README

taxonomies/food/ingredients.txt
Have `grape sugar` inherit from `glucose` rather than `monosaccharide`.
Grape sugar is always glucose (and in many languages the two terms are mostly interchangeable) and glucose has the `vegan` and `vegetarian` flags set, while monosaccharide does not.
Glucose also inherits from monosaccharide, so grape sugar should still inherit anything from there that is needed for classifications.
[![unknown vegan status](https://github.com/user-attachments/assets/db9a1d45-bba3-478a-b5a1-20c9cc4c34ae)](https://se.openfoodfacts.org/product/4056489412236/vitasia-rice-cracker-spicy-sweet-chili-flavour-lidl#health)
- https://se.openfoodfacts.org/product/4056489412236/vitasia-rice-cracker-spicy-sweet-chili-flavour-lidl#health
=> taxonomy: Have `grape sugar` inherit from `glucose` rather than `monosaccharide`

taxonomies/food/ingredients.txt, tests/integration/expected_test_results/unknown_tags/ingredient-apple-exists.html
Adds [Idared (red) apples](https://en.wikipedia.org/wiki/Idared) to the ingredients list, including related Danish and Swedish translations/synonyms.
[![missing ingredient](https://github.com/user-attachments/assets/fc997b59-814a-4db6-a701-32b5231f51b9)](https://se.openfoodfacts.org/product/4056489447665/r%C3%B6da-%C3%A4pplen#health)
- https://se.openfoodfacts.org/product/4056489447665/r%C3%B6da-%C3%A4pplen#health
=> taxonomy: Add Idared (red) apples

scripts/gen_users_emails.pl
The users_emails.sto file in production got deleted (and rebuilt with new users, but it was missing old users). I ran this script to repair it.
We will move to Keykloak hopefully soon, so we won't have those issues once we move.
=> fix: gen_users_emails.pl

taxonomies/food/ingredients.txt
Adds `sv:pecannötter` and `sv:lönnsirap` to the ingredient taxonomy.
[![unrecognised ingredients](https://github.com/user-attachments/assets/bcc35416-8dc5-40bd-876b-79cde675dd82)](https://se.openfoodfacts.org/product/7311312007865/granola-crunchy-pekan-l%C3%B6nnsirap-risenta#health)
- https://se.openfoodfacts.org/product/7311312007865/granola-crunchy-pekan-l%C3%B6nnsirap-risenta#health
=> taxonomy: Add sv:pecannötter and sv:lönnsirap

taxonomies/food/ingredients.txt, taxonomies/ingredients_processing.txt
Adds Swedish terms for hydrolysed soy protein and ginger extract.
I added “hydrolyserat” both to `food/ingredients.txt` and to `ingredients_processing.txt`. Not sure if I should only do the latter, or if it’s fine to have both since “hydrolysed soy protein” is already in `food/ingredients.txt`.
[![unknown ingredients](https://github.com/user-attachments/assets/8ab60e9b-8627-436d-9bb9-29543c6b8cf7)](https://se.openfoodfacts.org/product/7340083469077/heta-chilin%C3%B6tter-eldorado#health)
- https://se.openfoodfacts.org/product/7340083469077/heta-chilin%C3%B6tter-eldorado#health
=> taxonomy: Add Swedish terms for hydrolysed soy protein and ginger extract

taxonomies/food/ingredients.txt
Adds “grädd” as Swedish alias for cream.
While “cream” in Swedish is “grädde”, when it joins with other terms it will often drop the -e. E.g., like “powder” → “cream powder” is “gräddpulver”. As such, the “grädd” synonym is needed to properly parse ingredient lists.
[![“gräddpulver” not being recognised](https://github.com/user-attachments/assets/be77ab91-6248-4398-9a5c-514f7335c339)](https://se.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=gr%C3%A4ddpulver&type=add&action=process&submit=Submit+Query)
- https://se.openfoodfacts.org/ingredient/gr%C3%A4ddpulver
- https://se.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=gr%C3%A4ddpulver&type=add&action=process&submit=Submit+Query
=> taxonomy: Add “grädd” alias for cream

html/js/product-search.js, lib/ProductOpener/Display.pm, lib/ProductOpener/Routing.pm, tests/integration/expected_test_results/web_html/es-ingredients.html, tests/integration/expected_test_results/web_html/world-products-multiple-codes.html, tests/integration/web_html.t, tests/unit/expected_test_results/routing/api-v0-attribute-groups.json, tests/unit/expected_test_results/routing/api-v3-product-code.json, tests/unit/expected_test_results/routing/api-v3-product-gs1-data-uri.json, tests/unit/expected_test_results/routing/facet-url-group-by-in-english.json, tests/unit/expected_test_results/routing/facet-url-group-by.json, tests/unit/expected_test_results/routing/facet-url-with-page-number.json, tests/unit/expected_test_results/routing/facet-url-with-synonym-and-page-number.json, tests/unit/expected_test_results/routing/facet-url.json, tests/unit/expected_test_results/routing/geoip-get-country-from-ipv4-us.json, tests/unit/expected_test_results/routing/geoip-get-country-from-ipv6-fr.json, tests/unit/expected_test_results/routing/invalid-last-url-component.json, tests/unit/expected_test_results/routing/products-code.json, tests/unit/expected_test_results/routing/products-codes.json, tests/unit/routing.t
As noted by Telperion on Slack https://openfoodfacts.slack.com/archives/C06KYTQSG/p1719812540659769 , the feature to display several products by barcode on the OFF website is not working anymore:
http://world.openfoodfacts.localhost/products/7622201133337,3229820100234
It turns out it was broken in 3 different ways:
- the routing /products/7543543,43243242 was assigning "products" to code
- the query to the API http://world.openfoodfacts.localhost/api/v0/search?code=7622201133337,3229820100234&fields=code,product_display_name&page_size was crashing (division by 0 error) because it was trying to compute pagination data (unneeded as it is an API query with no pagination) with a $limit of 0 (still need to investigate why $limit was set to 0, possibly some config issue)
- the Javascript to …
=> fix: 3 fixes to make /products/[code1],[code2] work again

taxonomies/food/ingredients.txt
Adds taxonomy ingredient entry for `sv:krispiga flingor`.
I wasn’t exactly sure where to put it, but given that the [only current occurrences](https://se.openfoodfacts.org/ingredient/krispiga-flingor) are corn/rice/wheat/rye/sv:korn based, I put it as a child of `cereal flakes`.
I also didn’t know whether to add the English translation or not, so I added it, but commented‐out. 🙃 This way, non-Swedish speakers at least have an idea of what it is when looking at the list.
[![unknown ingredient](https://github.com/user-attachments/assets/6499da09-b615-4f2e-8f49-d92dc774640b)](https://se.openfoodfacts.org/product/7311312007100/crunchy-granola-%C3%A4pple-kanel-risenta#health)
- https://openfoodfacts.slack.com/archives/C06A7LENM/p1723472446091359?thread_ts=1721573740.332399&cid=C06A7LENM
=> taxonomy: Add `sv:krispiga flingor` to ingredients

taxonomies/ingredients_processing.txt
Adds `högpastöriserad` processing variant as a child of unspecified/general pasteurisation, as it is used for a number of (esp. dairy) products in Swedish. There will also be equivalents for at least the other Scandinavian/Nordic languages.
[![“högpastöriserad grädde” isn’t recognised](https://github.com/user-attachments/assets/88b8661e-7819-4eb3-a660-2f1d2a2b49e4)](https://se.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=h%C3%B6gpast%C3%B6riserad+gr%C3%A4dde&type=add&action=process&submit=Submit+Query)
- https://se.openfoodfacts.org/ingredients?status=unknown&filter=h%C3%B6gpast%C3%B6riserad
- https://se.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=h%C3%B6gpast%C3%B6riserad+gr%C3%A4dde&type=add&action=process&submit=Submit+Query
=> taxonomy: Add sv:högpastöriserad processing

lib/ProductOpener/GeoIP.pm, lib/ProductOpener/Routing.pm
If the geoip endpoint is called without parameter `/api/v3/geoip` the remote address is used.
- Fixes #10699
=> feat: geoip/ api use the remote address if ip not provided as param

taxonomies/food/ingredients.txt
Adds “kakaokräm” as Swedish translation for cocoa cream.
[![unknown ingredient “kakaokräm”](https://github.com/user-attachments/assets/bbee3960-c125-463e-a132-a166c16677aa)](https://se.openfoodfacts.org/product/4056489872450/sol-mar-mini-churros-rellenos-with-chocolate-flavoured-filling#health)
- https://se.openfoodfacts.org/product/4056489872450/sol-mar-mini-churros-rellenos-with-chocolate-flavoured-filling#health
=> taxonomy: Add sv:kakaokräm

taxonomies/food/ingredients.txt, tests/unit/expected_test_results/attributes/en-attributes.json, tests/unit/expected_test_results/attributes/en-nova-groups-markers.json, tests/unit/expected_test_results/nutriscore/fr-ice-tea-with-sweetener.json, tests/unit/expected_test_results/routing/api-v0-attribute-groups.json, tests/unit/expected_test_results/routing/api-v3-product-code.json, tests/unit/expected_test_results/routing/api-v3-product-gs1-data-uri.json, tests/unit/expected_test_results/routing/facet-url-group-by-in-english.json, tests/unit/expected_test_results/routing/facet-url-group-by.json, tests/unit/expected_test_results/routing/facet-url-with-page-number.json, tests/unit/expected_test_results/routing/facet-url-with-synonym-and-page-number.json, tests/unit/expected_test_results/routing/facet-url.json, tests/unit/expected_test_results/routing/geoip-get-country-from-ipv4-us.json, tests/unit/expected_test_results/routing/geoip-get-country-from-ipv6-fr.json, tests/unit/expected_test_results/routing/invalid-last-url-component.json
Some adjustments based on details from the NOVA team:
> Vitamins and minerals (e.g., flour enriched with iron, orange juice enriched with calcium, breakfast cereals with minerals and vitamins): Vitamins and minerals are not considered markers of UPF.
> 
> Vegetable fiber (e.g., potato fiber, corn fiber): Soluble or insoluble fiber is considered a food substance with little or no culinary use and is primarily used in the manufacture of UPFs. Therefore, they are markers of UPFs.
> 
> Vegetable extracts (e.g., pepper extract, spice extract, vanilla extract, onion extract, yeast extract): Since yeast extracts (such as Vegemite and Marmite) typically contain colorants and flavorings, we classify them as UPFs. While 100% vanilla extract is not considered a UPF, commercially available vanilla …
=> taxonomy: updates to NOVA 4 markers

.github/workflows/container-deploy.yml
This enable long running operations on staging (eg. testing a migration).
=> ci: add a NO_DEPLOY flag to temporarily block deployments

taxonomies/labels.txt
Fix `no:` entries in `labels.txt` to be `nb:`.
Norwegian has two (primary) variants: Nynorsk (`nn`) and Bokmål (`nb`). It seems like Norwegian OFF uses `nb` for its language rather than the generic `no` language code—e.g., looking at https://no.openfoodfacts.org/label/n%C3%B8kkelhullet I get directed to answer robotoff questions related to `nb:nøkkelhullet`.
[![“Answer robotoff questions about label nb:nøkkelhullet for country Norway”](https://github.com/user-attachments/assets/aa1b7aef-e302-4176-a1a8-c0d8bf390aae)](https://no.openfoodfacts.org/label/n%C3%B8kkelhullet)
- https://no.openfoodfacts.org/label/n%C3%B8kkelhullet
=> taxonomy: fix specifying Norwegian as Bokmål (labels.txt)

taxonomies/labels.txt
Add some Swedish terms for Rainforest Alliance to improve recognition in ingredients lists etc.
Note that “Rainforest Alliance” is intentionally duplicated in the Swedish list to ensure that “Rainforest Alliance” remains the label for the, uh, label in Swedish.
[![unrecognised label “Rainforest Alliance Kakao”](https://github.com/user-attachments/assets/07968f38-a4e6-4cfe-b3b4-119f89ddf3d8)](https://se.openfoodfacts.org/product/7340083448188/chokoflarn-eldorado)
[![unrecognised qualifier “Rainforest Alliance-certifierad”](https://github.com/user-attachments/assets/914af8d9-71e6-4411-b8e6-1337254f48fd)](https://se.openfoodfacts.org/cgi/test_ingredients_analysis.pl?ingredients_text=Rainforest+Alliance+certifierad+fettreducerat+kakaopulver%2C+Rainforest+Alliance+certifierad+kakaopulver%2C+Rai …
=> taxonomy: Add Swedish Rainforest Alliance synonyms

gulpfile.ts
Remove [no more existing](https://jqueryui.com/changelog/1.14.0/) jQuery UI file from Gulp build.
=> fix: remove unused jquery-ui safe-active-element module

html/js/product-multilingual.js
Applies the solution in [my comment](https://github.com/openfoodfacts/openfoodfacts-server/issues/10632#issuecomment-2278228057).
- Fixes #10632
=> fix: Synonyms in taxonomized suggestions

cgi/org.pl, cgi/user.pl, lib/ProductOpener/CRM.pm, lib/ProductOpener/Display.pm, lib/ProductOpener/Orgs.pm, lib/ProductOpener/Users.pm, po/common/common.pot, po/common/en.po, po/common/fr.po, scripts/migrations/2024_08_validate_and_sync_crm_existing_orgs.pl, scss/_off.scss, templates/emails/en/org_rejected.tt.html, templates/emails/fr/org_rejected.tt.html, templates/web/pages/org_form/org_form.tt.html, templates/web/pages/user_form/user_form_page.tt.html, tests/integration/expected_test_results/create_pro_user/org-after-validation.json
Fixed a bunch of things in the sync process in CRM.pm.
Also, in migration script : 
- orgs created after the date of dump, used to review the orgs, are skipped.
=> fix: existing orgs migration script to crm

lib/ProductOpener/Tags.pm
This creates a new .extended.json file for all taxonomies, that contain extended synonyms.
Fixes #10742
Notes:
- synonyms_extended entries are normalized (no accents, capitals, all non letter chars turned to dashes etc.)
- synonyms are not normalized (as in the normal export)
- properties, parents, childrens are not included (they are in the .full export)
- the .full export is not changed (it does not contain the extended synonyms)
Sample output in test taxonomy:
```
en:passion-fruit-yogurts: {
synonyms_extended: { },
normalized_synonyms: {
nl: [
"yoghurts-met-passievrucht"
],
en: [
"passion-fruit-yogurts"
],
fr: [
"yaourts-au-fruit-de-la-passion"
]
},
name: {
nl: "Yoghurts met passievrucht",
fr: "Yaourts au fruit de la passion",
en: "Passion fruit yogurts"
}, …
```
=> feat: new [taxonomy].extended.json with extended synonyms

Makefile
Can't use -e flag when calling make targets in dependencies
Fixes #10749
=> fix: import_prod_data not working

lib/ProductOpener/Config_off.pm
We were rate-limiting metrics requests
=> fix: add Moji server IP to rate-limit allow-list

docs/api/ref/schemas/ingredient.yaml
"#/" refers to a property with empty name. "#" refers to the root.
=> fix: incorrect self-reference in ingredient.yaml

docs/api/ref/schemas/product_misc.yaml
"string." is not a valid JSON type.
=> fix: invalid type in product_misc.yaml

docs/api/ref/schemas/product_base.yaml, docs/api/ref/schemas/product_images.yaml, docs/api/ref/schemas/product_meta.yaml, docs/api/ref/schemas/product_quality.yaml
Some schema files have incorrect YAML syntax. When a key-value pair is split on two lines, the colon separating the value from the key should be followed by a pipe. While most YAML files contain the pipe chars when required, some of them miss one or two pipe chars.
=> Fix: YAML syntax in schema files.

scripts/product_revision_to_historical_events.pl
Use the product revision to determine delete and obsolete status
- Fixes #10789
=> fix: Determine obsolete and deleted from the product revision

Makefile
Update the `Makefile` to use the dynamic shell path instead of the hardcoded `/bin/bash`. This ensures that the correct shell is used across different environments. Additionally, the environment variable `SHELL` is updated to use the `which` command to locate the path of the bash shell.
=> refactor: Update Makefile to use dynamic shell path

html/js/folksonomy.js
List of properties /properties:
* Display documentation of the property at the left (fixes #10817)
* Use a 🛈
Folksonomy property /property/this_property:
* change column titles
Knowledge panel on product page:
* display documentation of existing properties
=> feat: Small fixes + improvements

.github/workflows/crowdin.yml
=> ci: Update crowdin.yml

lib/ProductOpener/API.pm, lib/ProductOpener/Export.pm, tests/integration/expected_test_results/api_v3_product_write/patch-broken-json-body.json
- Might solve https://github.com/openfoodfacts/openfoodfacts-server/issues/10835
=> fix: do not localize ecoscore on obf,opf,opff

taxonomies/food/categories.txt
The `ja` translation for `en:dried-tomatoes` was under `en:dried-vegetables` so fix that.
=> taxonomy: Fix misplaced ja translation of en:dried-tomatoes

lib/ProductOpener/Attributes.pm, lib/ProductOpener/Config_off.pm
This changes the result of http://wold.openfoodfacts.org/api/v2/attribute_groups to add a "values" array to list the possible values for each attribute.
Fixes #9370
Most attributes have 4:
values: [
"not_important",
"important",
"very_important",
"mandatory"
]
Allergens + vegan and vegetarian have 2:
values: [
"not_important",
"mandatory"
]
Full file:
```
[
{
attributes: [
{
default: "very_important",
icon_url: "http://static.openfoodfacts.localhost/images/attributes/dist/nutriscore-a.svg",
id: "nutriscore",
name: "Nutri-Score",
panel_id: "nutriscore",
setting_name: "Good nutritional quality (Nutri-Score)",
setting_note: "The Nutri-Score is computed and can be taken into account for all products, even if is not displayed on the packaging.",
values: [
"not_important",
"important", …
```
=> fix: indicate some attributes have only mandatory / not_important options

docs/api/tutorial-off-api.md
Name of product on query: fixed
- No related with previous fixes or issues
=> fix: docs Fixed proper denomination of product in query

html/js/folksonomy.js
In the table, property and value headers are not at the right place
+ fix css
=> fix: In the Folksonomy Engine table, property and value headers were not at the right place

conf/nginx/sites-available/off, scripts/gen_feeds_daily_off.sh, scripts/mongodb_dump.sh
Upload the following dump files to AWS S3, just after being created in gen_feed_daily script:
- en.openfoodfacts.org.products.csv
- en.openfoodfacts.org.products.csv.gz
- fr.openfoodfacts.org.products.csv
- fr.openfoodfacts.org.products.csv.gz
- en.openfoodfacts.org.products.rdf
- fr.openfoodfacts.org.products.rdf
- openfoodfacts-products.jsonl.gz
- openfoodfacts-mongodbdump.gz
- openfoodfacts_recent_changes.jsonl.gz
Also add redirects (HTTP 302) to AWS S3 in the off nginx configuration so that we save I/O.
We use minio client (mc) for synchronization. We expect `/home/off/.mc/config.json` to contain AWS credentials.
=> feat: upload DB dump to AWS S3

docs/api/ref/schemas/product_ecoscore.yaml
docs: reviewing the Ecoscore.pm program and fixing the product_ecoscore.yaml schema
===================================================================================
This pull request applies to:
```
lib/ProductOpener/Ecoscore.pm
docs/api/ref/schemas/product_ecoscore.yaml
```
Actually, nothing is modified in `Ecoscore.pm`.
Within the "ecoscore_data/adjustments/origins_of_ingredients", "ecoscore_data/grades" and "ecoscore_data/scores" hierarchies, we find many key-values pairs, where the key is a 2-char code, or the string "world". According to `product_ecoscore.yaml`, the 2-char code is a language code and the 5-char string "world" is not allowed.
On the other hand, when reading `Ecoscore.pm`, we find the hard-coded string "world" together with a list …
=> docs: reviewing the Ecoscore.pm program and fixing the product_ecoscore.yaml schema

docs/api/ref/api.yml, docs/api/ref/requestBodies/add_or_edit_a_product.yaml, docs/api/ref/responses/get_nutrients.yaml, docs/api/ref/responses/get_product_by_barcode.yaml, docs/api/ref/schemas/ingredient.yaml, docs/api/ref/schemas/knowledge_panels/elements/element.yaml, docs/api/ref/schemas/nutrients.yaml, docs/api/ref/schemas/product_ingredients.yaml
This pull request updates the `ingredients.yaml` and `product_ingredients.yaml` file to improve the schema definitions and ensure conformity with OpenAPI 3.1 specification. Specifically, it includes:
- Support better the self reference (SDK client gen compliant) correcting the `$ref` path for `ingredients`.
- Added descriptions for properties.
- Ensured all types are correct and conform to OpenAPI 3.1 specification.
No open issue related
=> docs: Improve api def ingredient schema

gulpfile.ts
This reverts commit 9407e860b96cf6be4543878509d7568ce90ad8a8.
After replicating the nutrient autosuggest selection problem (one of a few JavaScript-related problems) described in #10861 in a local development instance, I attempted a revert of #10708 because the name of the dependency seems similar to a missing function that appeared in the JavaScript console as an error:
```
Uncaught TypeError: e.ui.safeActiveElement is not a function
```
After reverting #10708, the error no longer appears and I'm able to select entries from the nutrient autosuggest as expected.
https://github.com/user-attachments/assets/eb40f7dd-3167-4c0b-a982-9bc46db06988
- Fixes #10861 (in combination with #10877).
=> fix: Revert "fix: remove unused jquery-ui safe-active-element module (#10708)"

lib/ProductOpener/Attributes.pm, stop_words.txt
Some products (in the obsolete collection) do not have new Nutri-Score data (but may have data in an older format).  In that case the attribute Nutri-Score should be unknown. This can also happen if we display an older revision of a product.
I'll also recompute the Nutri-Score for the current revision of obsolete products.
Fixes https://github.com/openfoodfacts/smooth-app/issues/5699
=> fix: attribute for product without new nutriscore data

.github/workflows/pull_request.yml, Makefile
cache taxonomies in pr workflow
=> ci: cache taxonomies in pr workflow

.github/ISSUE_TEMPLATE/bug_report.md
Reverts openfoodfacts/openfoodfacts-server#10968
it looks it broke the ability to submit a new issue
=> ci: Revert "docs: Update bug_report.md"

docs/api/ref/api.yml, docs/api/ref/schemas/product.yaml, docs/api/ref/schemas/product_nutriscore.yaml
Nutriscore definition proposal to reference unmapped properties
#9114
=> docs: openapi nutriscore definition

lib/ProductOpener/Display.pm
This is to be able to run commands with update_all_products.pl like:
./scripts/update_all_products.pl --query categories_tags=en:some-old-entry-that-is-now-a-synonym!
the ending ! means that the value should not be normalized with the taxonomy, but instead should be searched for as specified in mongodb
=> fix: allow to query tags without normalization

scripts/count_product_contributions_by_year.pl
Sample output on the dev test database:
```
year	active_editors	new_editors	products_edited	products_added	total_products
2012	2	2	1	1	1
2013	5	4	3	2	3
2014	6	4	3	2	5
2015	7	3	6	5	10
2016	6	4	5	3	13
2017	12	7	27	21	34
2018	21	11	55	44	78
2019	26	18	74	40	118
2020	31	17	120	53	171
2021	34	21	92	40	211
2022	36	17	147	67	278
2023	55	30	117	34	312
2024	48	21	96	49	361
all	159	159	361	361	361
```
Output on the whole database: https://docs.google.com/spreadsheets/d/11nrerWDwzFV1gZb0i16TI_shh9C3XgddYn5KcGl4DO8/edit?gid=0#gid=0
=> feat: script to count product contributions by year

cgi/product_jqm_multilingual.pl, cgi/product_multilingual.pl, lib/ProductOpener/APIProductWrite.pm, tests/integration/change_product_code_and_product_type.t, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-code-api-v2-normal-account.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-code-api-v2-not-logged-in.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-code-api-v3-moderator-existing-code.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-code-api-v3-moderator-invalid-code.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-type-to-beauty-api-v2-normal-account.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-type-to-empty-string-api-v2-moderator.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-type-to-null-api-v2-moderator.json, tests/integration/expected_test_results/change_product_code_and_product_type/change-product-type-to-opff-api-v3-invalid-product-type.json, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-with-new-code.json
I'm hoping this PR will fix https://github.com/openfoodfacts/smooth-app/issues/5864
If we receive product_type=null, we just ignore it.
Also refactored the code to remove some duplication.
=> fix: refactor + ignore 'null' product_type sent by app

lib/ProductOpener/APIProductRead.pm, lib/ProductOpener/Display.pm, tests/integration/change_product_code_and_product_type.t, tests/integration/expected_test_results/change_product_code_and_product_type/get-obf-product-with-api-v3-no-product-type.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-opf-with-all-product-type-api-v2.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-opf-with-all-product-type-api-v3.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-opf-with-right-product-type-api-v2.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-opf-with-right-product-type-api-v3.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-opff-with-all-product-type-api-v3.html, tests/integration/expected_test_results/change_product_code_and_product_type/get-product-with-new-code.json, tests/integration/expected_test_results/change_product_code_and_product_type/send-existing-product-type-api-v2-normal-account.json, tests/integration/expected_test_results/change_product_code_and_product_type/send-existing-product-type-api-v3-normal-account.json
Add a missing / in the redirect URL, spotted by @monsieurtanuki  : 
https://github.com/openfoodfacts/openfoodfacts-dart/issues/995#issuecomment-2495542456
=> fix: API redirects for product types

.github/workflows/github-projects-ventilation.yml
ci: add metrics and matomo to the metrics project
- uses: actions/add-to-project@main
with:
project-url: https://github.com/orgs/openfoodfacts/projects/84 # Add issue to the Metrics project
github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
labeled: matomo
label-operator: OR
=> ci: add metrics and matomo to the metrics project

lib/ProductOpener/Ingredients.pm
Add a check that the ingredient has labels before doing a regexp on them, in order to avoid Perl warnings.
Also small refactor to avoir repeating all suffixes for proxies.
=> fix: remove warning in ecobalyse matching of ingredients

.github/workflows/pull_request.yml, Makefile, scripts/gen_feeds_daily.sh, scripts/import_sample_data.sh, taxonomies/food/categories.txt
We currently have an action to run "make dev" in GitHub PR checks. This loads product .sto files and images from static.openfoodfacts.org, and it can be quite slow.
e.g. this test has been running for 3 hours:
https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/12082629626/job/33694707420?pr=11068
also added smaller dump:
```
off@off:/srv/off/html/exports$ (off) ls -lrt products.random-modulo-100*
-rw-r--r-- 1 off off   552875078 May 20  2024 products.random-modulo-100.tar.gz
-rw-r--r-- 1 off off    59335855 Nov 23 12:55 products.random-modulo-1000.tar.gz
-rw-r--r-- 1 off off 13099413539 Nov 23 14:04 products.random-modulo-1000.images.tar.gz
-rw-r--r-- 1 off off     8866855 Nov 23 14:05 products.random-modulo-1000.jsonl.gz
-rw-r--r-- 1 off off    10660049 Nov 23 14:05 …
```
=> build: do not import sample data in GitHub PR checks for make_dev

lib/ProductOpener/Products.pm, scripts/load_products_in_mongodb.pl, stop_words.txt
Script used to refresh products in MongoDB, following the bug that created OFF pro products on the OFF mongodb database:
https://github.com/openfoodfacts/openfoodfacts-server/issues/11064
```
2014  mongoexport --host 10.1.0.102 --db=off --collection=products --query='{"$expr": {"$ne":["$_id","$id"]},"data_sources_tags":"producers"}' --fields=_id > off-pro-products-on-off.json
2027  mongoexport --host 10.1.0.102 --db=off --collection=products_obsolete --query='{"$expr": {"$ne":["$_id","$id"]},"data_sources_tags":"producers"}' --fields=_id > off-pro-products-on-off.obsolete.json
2028  vi off-pro-products-on-off.obsolete.json
2029  ./scripts/load_products_in_mongodb.pl --product off-pro-products-on-off.obsolete.json 
2030  ./scripts/load_products_in_mongodb.pl --product …
```
=> fix: Load products in mongodb

lib/ProductOpener/Tags.pm, tests/unit/expected_test_results/ingredients/en-ingredient-ending-with-a.json, tests/unit/ingredients.t
I think this may be the reason for https://github.com/openfoodfacts/openfoodfacts-server/issues/11014
E120 and E124 have synonyms "Cochineal Red" and "Cochineal Red A".
In the ingredients taxonomy, "a" is a stopword.
E124 becomes a synonym of E120.
Solution: we don't consider A / a to be a stopword when it is at the end of a string, as in English, "a" comes before a noun.
=> fix: letter A at end of string is not a stopword

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
Error is: Nutrition-soluble-fiber-plus-insoluble-fiber-greater-than-fiber should not be raised for 
> Fiber = 5
> insoluble fiber < 1
> soluble fiber = 5
and similar cases.
The PR covers only Fibers, insoluble fiber and soluble fiber.
The PR covers only if symbol is "<"
- Fixes #11075
=> fix: data quality, false positive, nutrition sum with lower symbol

lib/ProductOpener/Images.pm
new images symlinks were mistakenly created in /srv/off/products/new_images/
I will move them to /srv/off/new_images/ so that they get processed
=> fix: new images path

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
error should not be raised when 
sugar = 0
lactose < 0.01
In the product given in the issue, lactose is given below the table. Similar to #11076, lactose with symbol "<" will be ignore for the error.
+ fix some non declared variable warnings like 
> dataqualityfood.t: Use of uninitialized value in string eq at /opt/product-opener/lib/ProductOpener/DataQualityFood.pm line 1040.
- Fixes #10715
=> fix: data quality, false positive, nutrition sum with lower symbol for milk below the table

conf/nginx/snippets/off.locations-redirects.include
redirect https://world.openfoodfacts.org/nutriscore-v2 to https://world.openfoodfacts.org/new-nutriscore
=> fix: redirect /nutriscore-v2 to /new-nutriscore

Dockerfile, Dockerfile.frontend
1. Add a cache for `/var/lib/apt` during `backend` image build
2. Cache `/root/.npm/_cacache` instead of `/root/.npm` to avoid polluting the cache with `/root/.npm/_logs`
3. Don't copy (apparently) unused `node_modules` to the `frontend` image - saves a ~200 MiB layer in the final image
=> build: Minor docker build optimizations

Makefile
This pull request includes changes to the `Makefile` to improve the handling of environment variables and streamline the import of sample data.
Environment variables:
* Removed the unused `SKIP_SAMPLE_IMAGES` variable definition to avoid incorrect initialization to a constant string.
Sample data import:
* Updated the `import_sample_data` rule to pass the `SKIP_SAMPLE_IMAGES` environment variable directly to the Docker container, ensuring that sample images are skipped during import.
Fixes #11013
=> build: update Makefile to skip downloading sample images in CI

taxonomies/food/categories.txt, tests/unit/dataqualityfood.t
Because the nutriscore has changed recently, **expected_nutriscore_grade:en:** for **Extra-virgin olive oils** category has changed from C to B.
See: https://theconversation.com/en-2024-le-nutri-score-evolue-pourquoi-et-que-faut-il-en-retenir-221697
See @aleene comment in quality-data channel on Slack
> Something changed? Nutri score grade from category does not match calculated grade https://world.openfoodfacts.org/product/4088700000472/olive-oil and others
=> fix: nutriscore grade from category change for extra virgin olive oils

.github/workflows/pull_request.yml
Delete the downloaded container image from the temporary path; the GitHub action has already loaded it into docker.
This annoying workaround should help with build runs still failing with #11013.
=> ci: Delete downloaded container image

packager-codes/get_packager_code_from_html_ireland.py, scripts/generate_dump_for_offline_apps.py, scripts/mappingGES.py, scripts/packager-codes/at_packagers_refresh_part1.py, scripts/packager-codes/at_packagers_refresh_part2.py, scripts/packager-codes/cy_packagers_refresh.py, scripts/packager-codes/cz_packagers_refresh_part1.py, scripts/packager-codes/cz_packagers_refresh_part2.py, scripts/packager-codes/dk_packagers_refresh_part1.py, scripts/packager-codes/dk_packagers_refresh_part2.py, scripts/packager-codes/hu_packagers_refresh_part1.py, scripts/packager-codes/hu_packagers_refresh_part2.py, scripts/packager-codes/ie_packagers_refresh_part1.py, scripts/packager-codes/ie_packagers_refresh_part2.py, scripts/packager-codes/it_packagers_refresh.py, scripts/packager-codes/lu_packagers_refresh_part1.py, scripts/packager-codes/lu_packagers_refresh_part2.py, scripts/packager-codes/non-eu/non_eu_spider.py, scripts/packager-codes/non-eu/packager_codes.py, scripts/packager-codes/non-eu/pdf_extraction.py, scripts/packager-codes/poland_packager_code.py, scripts/packager-codes/portugal-concatenate-csv-sections.py, scripts/packager-codes/si-packagers-refresh.py, scripts/run_ocr.py, scripts/snippets/agribalyse_categories_csv.py, scripts/update_tags_per_languages.py, scripts/update_tags_per_languages_tests.py, scripts/usda-import/keep_most_recent_row_for_each_product.py
style: Reformat all Python code with PEP8 for normalization
CodeQL reported an error with a Python file because of a compilation error: https://github.com/openfoodfacts/openfoodfacts-server/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BNMFXGC3DZONUXGLTZNVWA/81b016e0e16ad77829222f64441894263139370096f7c96cdedadd2642eb9d37
=> fix: Correct indentation, so that CodeQL can work with the code

.sonarcloud.properties, html/js/display-list-of-tags.js, html/js/product-multilingual.js, html/js/search.js, scss/_footer.scss, scss/_off.scss, scss/_product-list.scss, scss/_topbar.scss
Fix a handful of issues reported by SonarCloud, or add a workaround for the issue.
=> fix: SonarCloud issues

taxonomies/food/categories.txt
Fix taxonomy errors and warning spotted using the Taxonomy editor:
The only one remaining is this one: `WARNING: Entry with same id fr:terrines-foie-volaille already exists, duplicate id in file at line 116496. The two nodes will be merged, keeping the last values in case of conflicts.`
It looks like `Terrines de foie de volaille` and `Terrines au foie de volaille` are merged into the same entity due to stopwords, I'm not sure how to fix this one.
=> taxonomy: Fix category taxonomy warnings

.github/workflows/pull_request.yml, Makefile
See https://openfoodfacts.slack.com/archives/C02LDQDDD/p1734814872519649 for discussion.
Pro: Speeds up the `make dev` check by a lot, and it use less disk space, reducing the risk of the build agent running out of space.
Con: While similar, it doesn't run `make build` as part of the `make dev_no_build` check, making it not 100% identical to the local `make dev`
=> ci: Speed up build by using pre-built image from previous stage for `make dev`-like check

lib/ProductOpener/DataQualityFood.pm, tests/unit/dataqualityfood.t
Increase the threshold from 0.001 to 0.01
Soluble fiber + insoluble fiber > fiber + 0.01
- Fixes #10491
=> fix: data quality - increase threshold for comparison between fiber and its subnutriments

lib/ProductOpener/Food.pm, tests/unit/food.t
apply remove_insignificant_digits function (created by @stephanegigandet in a previous PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/3489) for nutriments
- Fixes #8501
=> feat: data-quality/apply-remove_insignificant_digits-for-nutriments

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, taxonomies/food/categories.txt, tests/unit/dataqualityfood.t
push data quality error if ingredients count is lower than the expected number of ingredients
- Fixes #9732
=> feat: data-quality - minimum number of ingredients

lib/ProductOpener/Config_obf.pm, taxonomies/beauty/labels.txt, taxonomies/labels.txt
Remove the nova drilldown field for Open Beauty Facts
\+ commented duplicates between labels taxonomies for food and beauty. Make lint made more changes. Look for "# already in food labels.txt" in the code.
- Fixes #11111
=> fix: rm nova drilldown field for beauty

taxonomies/countries.txt, taxonomies/origins.txt
```
Error 3
https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/7462755789/job/20306470532?pr=9288#step:4:560
Name "FFI::Platypus::keep" used only once: possible typo at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm line 111.
error: ecoscore origin does not exist in taxonomy {origin => "IW",origin_id => "en:IW"}
error: ecoscore origin does not exist in taxonomy {origin => "SW",origin_id => "en:SW"}
error: ecoscore origin does not exist in taxonomy {origin => "US-AL",origin_id => "en:US-AL"}
error: ecoscore origin does not exist in taxonomy {origin => "US-GA",origin_id => "en:US-GA"}
error: ecoscore origin does not exist in taxonomy {origin => "US-LA",origin_id => "en:US-LA"}
error: ecoscore origin does not exist in taxonomy {origin => "US-MS",origin_id => "en:US-MS"} …
```
=> fix: environmental_score

lib/ProductOpener/ImportConvert.pm, lib/ProductOpener/ImportConvertCarrefourFrance.pm, lib/ProductOpener/Ingredients.pm
```
Error 1
https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/7462755789/job/20306470532?pr=9288#step:4:3088
error: error parsing xml file with XML::Rules {error => "\nno element found at line 1, column 83, byte 83 at /opt/perl/local/lib/perl5/XML/Rules.pm line 745.\n",file => "tests/unit//inputs/import_convert_carrefour_france/13003_3270190006787_valNut.xml"}
Use of uninitialized value in addition (+) at /opt/product-opener/lib/ProductOpener/ImportConvertCarrefourFrance.pm line 399.
File tests/unit//inputs/import_convert_carrefour_france/13766_8431876196009_text.xml - Code: 8431876196009
Reading file tests/unit//inputs/import_convert_carrefour_france/13766_8431876196009_text.xml
Use of uninitialized value in concatenation (.) or string at …
```
=> fix: warnings in import_convert_carrefour_france

taxonomies/food/ingredients.txt
Add missing ingredients from mymuesli product
=> taxonomy: Add missing ingredients from mymuesli

html/images/logos/off-logo-icon-dark.svg
Hi everyone!
A really tiny change, but the dark variant of the OFF logo is flipped.
We use it in dark mode in the app.
=> fix: Invalid OFF dark icon

lib/ProductOpener/ConfigEnv.pm, tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html, tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html, tests/integration/expected_test_results/product_read/get-existing-product.html, tests/integration/expected_test_results/web_html/fr-product-2.html, tests/integration/expected_test_results/web_html/fr-product.html, tests/integration/expected_test_results/web_html/world-product.html
Copy of https://github.com/openfoodfacts/openfoodfacts-server/pull/11182 so that the branch is on the openfoodfacts-server repo, in order to be able to use the /update_tests_results GitHub action
=> fix: Nutripatrol url trailing slash removal regex

html/images/attributes/src/nutriscore-not-applicable-new-de.svg, html/images/attributes/src/nutriscore-not-applicable-new-en.svg, html/images/attributes/src/nutriscore-not-applicable-new-fr.svg, html/images/attributes/src/nutriscore-not-applicable-new-lb.svg, html/images/attributes/src/nutriscore-not-applicable-new-nl.svg, html/images/attributes/src/nutriscore-unknown-new-de.svg, html/images/attributes/src/nutriscore-unknown-new-en.svg, html/images/attributes/src/nutriscore-unknown-new-fr.svg, html/images/attributes/src/nutriscore-unknown-new-lb.svg, html/images/attributes/src/nutriscore-unknown-new-nl.svg
Hi everyone!
On some Nutri-score V2 SVG files, there is a blank space:
Without this fix, we have this weird layout in the mobile app:
=> fix: "NutriScore V2" SVGs with blank space

conf/nginx/sites-available/off
We added the priority apache.
But initially we did add only a few path to it.
As it's working fine, make more requests goes through it as they are important for product contribution.
A [graph is visible here](https://prometheus.openfoodfacts.org/graph?g0.expr=apache_workers%7Bstate%3D%22busy%22%2Cenv%3D%22prod%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2h).
=> chore: make more requests goes to priority apache

lib/ProductOpener/Attributes.pm, lib/ProductOpener/KnowledgePanels.pm, po/common/common.pot, po/common/en.po, po/common/fr.po, templates/api/knowledge-panels/environment/environmental_score/environmental_score.tt.json, templates/api/knowledge-panels/environment/environmental_score/environmental_score_unknown.tt.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card-knowledge_panels_excluded-health_card.json, tests/integration/expected_test_results/api_v2_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-attribute-groups-all-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card-knowledge_panels_excluded-health_card.json, tests/integration/expected_test_results/api_v3_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json, tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels.json, tests/integration/expected_test_results/api_v3_product_write/patch-request-fields-updated-attribute-groups-knowledge-panels.json, tests/integration/expected_test_results/data_quality_knowledge_panel/data-quality.json, tests/integration/expected_test_results/data_quality_knowledge_panel/no-data-quality.json, tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html, tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html, tests/integration/expected_test_results/product_read/get-existing-product.html, tests/integration/expected_test_results/web_html/fr-product-2.html, tests/integration/expected_test_results/web_html/fr-product.html, tests/integration/expected_test_results/web_html/world-index-signedin.html, tests/integration/expected_test_results/web_html/world-index.html, tests/integration/expected_test_results/web_html/world-product.html
A few fixes/changes:
- we still had a "A-PLUS" instead of "A+" in a knowledge panel title
- separated title and subtitle
- for not-applicable, changed the "short description" so that it includes the non-applicable category (e.g. "sodas"), and display it directly in the attribute subtitle. (it's a bit longer, but probably worth displaying directly).
=> fix: Green-Score attributes/panels titles and subtitles

html/resources/files/tagline-off-android-v3.json, html/resources/files/tagline-off-ios-v3.json
Hi everyone!
We don't use these 2 JSON files for the tagline in the mobile app (hosted on GitHub instead).
That's why we force the old users to update the app.
=> feat: Update the tagline to force the app upgrade

cgi/product_image_move.pl, cgi/product_image_upload.pl, cgi/product_multilingual.pl, cgi/search.pl, lib/ProductOpener/Import.pm, lib/ProductOpener/Products.pm, scripts/check_photos.pl, scripts/import_images.pl, scripts/import_systemeu.pl, scripts/tag_stores_magasins_u.pl, tests/unit/expected_test_results/taxonomies/eurocodes.csv
The import of images in the pro platform is currently tied to the import of product data: we import images only of they come with product data.
Some producers can send us product photos in bulk, without sending product data at the same time.
The new image_import.pl script is to load those photos.  The script essentially uses existing code from Import.pm (which has been moved a bit in separate functions).
=> feat: new import_images.pl script for pro platform

lib/ProductOpener/Display.pm, templates/api/knowledge-panels/health/nutriscore/nutriscore_new_computation.tt.json
=> fix: link of nutri-score knowledge panel on pro platform

.github/workflows/pull_request.yml
Removes the two PR build jobs that just finished without doing anything.
=> ci: Remove empty PR build jobs

env/env.opf
This was generating dumps with the wrong name on Open Products Facts !
Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/11118
=> fix: FLAVOR_NAME is openproductsfacts

taxonomies/food/categories.txt
I added translations for the ones I saw in my products and were not translated.
I removed the "Słodycze" from en:Candies and moved to en:Confectioneries - I believe it's a better match to PL language.
I don't have a docker setup to run `make lint_taxonomies`. Sorry. I tried to remove ending white characters from the lines manually 
=> taxonomy: Added PL translations to some categories

lib/ProductOpener/Config.pm
Removing line that is causing an error:
Can't modify modulus (%) in scalar assignment at /opt/product-opener/lib/ProductOpener/Config.pm line 37, near ");"
=> fix: remove %options

Makefile
We did not use the right docker compose command… due to a change november, but I think as long as some container where still running in staging it was invisible ! But as they go down (maybe a restart of the VM), it refuses to start on staging.
=> chore: fix make prod_up

taxonomies/food/categories.txt
This is to fix a build error we have on the main branch:
ERROR - unknown_parent - en:bananas-fresh-whole-red has an undefined parent 
+ some changes to make the bananas categories similiar to other categories (no "Bananas (something)")
=> taxonomy: fix bananas

package-lock.json, package.json
Remove dependency on `xml2json`. It's only used by an obsolete script.
- Closes #4894 
- Fixes https://github.com/openfoodfacts/openfoodfacts-server/security/dependabot/57
=> chore: Remove outdated xml2json dependency

Dockerfile
Because first step that runs apt update might be taken from cache.
=> build: run apt update in needed in Dockerfile at various steps

cgi/product_multilingual.pl
issue reported by @benbenben2 
fix applied in opff prod:
https://hr.openpetfoodfacts.org/cgi/product.pl?type=edit&code=8716811001809
=> fix: always show as sold nutrition in petfood edit form

scripts/export_database.pl, scripts/gen_feeds_daily.sh
As suggested by @alexgarel , this PR adds a mechanism to see if some of the commands failed, and list them at the end so that we get them in the email failure.
If this is ok, we can add checks for the other commands (and possibly make those commands return a non 0 status on errors if they don't already).
=> fix: gen_feeds_daily.sh: failure email for export_database.pl

taxonomies/labels.txt
Added ssme Rainforest Alliance labels found on products, + full name as synonym
=> taxonomy: more Rainforest Alliance labels

.gemini/config.yaml
- ci: Test Gemini Code Assist, only on explicit requests (https://github.com/marketplace/gemini-code-assist) 
- Once this PR is merged, I'll need to enable it on the repo, and then you'll be able to require a review manually at any time
- https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github?hl=fr#default-configuration
- https://blog.google/technology/developers/gemini-code-assist-free/
=> ci: Config to disable automatic Gemini Assist before enabling it on the repo

.gemini/config.yaml
ci: reenable manual interactions on Gemini Code Assist
=> ci: reenable manual interactions on Gemini Code Assist

taxonomies/food/categories.txt, taxonomies/food/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt
`se` is the language code for Northern Sámi, but all the copied entries are in Swedish (`sv`). It is common to mistakenly use `se` for Swedish, since `se` is also the country code for Sweden.
I didn’t remove the Sámi entries since North Sámi _is_ spoken in parts currently occupied by Sweden, so there is likely some loan words and other linguistic influences. I have my doubts with a lot of these though, but I’m not a Sámi speaker of any sort and I don’t know the circumstances of why they were added.
=> taxonomy: Copy some `se` entries to `sv`

taxonomies/additives.txt, taxonomies/additives_classes.txt, taxonomies/food/categories.txt, taxonomies/food/ingredients.txt, taxonomies/ingredients_processing.txt, taxonomies/labels.txt
A number of (mostly) Swedish entries were added, based on unrecognised ingredients on product pages:
- https://world.openfoodfacts.org/product/8601900503411/eurocream-spread-takovo#health
- https://se.openfoodfacts.org/product/86019101/eurokr%C3%A4m-swisslion#health
- https://se.openfoodfacts.org/product/8606103381842/instant-noodle-vegies-has#health
- https://se.openfoodfacts.org/product/7340083459436/pesto-bomba-calabrese-garant#health
- https://se.openfoodfacts.org/product/7340083472329/granola-kokos-quinoa-garant#health
- https://se.openfoodfacts.org/product/7311590002262/n%C3%B6t-cr%C3%A8me-original#health
- https://se.openfoodfacts.org/product/4000194331894/vegan-light-chocolate-salty-caramel-green-star#health
- https://se.openfoodfacts.org/product/7311043006090/ekologiskt-citrongr%C …
=> taxonomy: More Swedish (sv) labels

docs/api/ref/api.yml, docs/api/ref/schemas/product.yaml
This change corrects a misalignment between product.yaml and api.yml by updating the reference in product.yaml from Product-Data-Quality to Product-Quality, ensuring it correctly points to the intended schema. Additionally, the redundant Product-Data-Quality component definition in api.yml is removed, as it incorrectly referenced product_knowledge_panels.yaml instead of the appropriate product_quality.yaml.
- Fixes #11275
=> docs: in the YAML schema, fix the link to product_quality.yaml

lib/ProductOpener/Display.pm
When testing popularity queries via off-query we need to set the no_cache parameter but this supresses using off-query for some counts
- Part of #11334
=> fix: Override no_cache parameter if database is explicitly set to off-query

lib/ProductOpener/Data.pm, lib/ProductOpener/Display.pm
database=off-query parameter was clashing with an existing database parameter passed into MongoDB. Changed to use off_query=1
- Part of #11334
=> fix: Use off_query parameter to not clash with existing database parameter

lib/ProductOpener/DataQualityFood.pm, taxonomies/data_quality.txt, taxonomies/food/categories.txt, tests/unit/dataqualityfood.t, tests/unit/dataqualityfood_labels.t
There is a bug with quality facets for this product: https://world.openfoodfacts.org/product/5411188128311/coconut-unsweetened-alpro
Calcium source label claim but calcium below 0.8
Vitamin b12 source label claim but vitamin b12 below 1e-06
Vitamin D source label claim but Vitamin D below 5e-06
Here is the reference EU regulation document: https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:31990L0496 (see Annex)
See also https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02006R1924-20141213 for difference between source of something and rich in something
The threshold for all vitamins and minerals in the reference EU regulation document should not be the values given but 15% of the values.
\+ also update thresholds values for jam, extra jam and jelly to reflect last …
=> fix: data quality label threshold source of vitamins and minerals

conf/apache-2.4/sites-available/off.conf
To have logrotate works correctly
(Already deployed to production)
=> chore: use a .log extension for apache2 logs

docs/api/ref-cheatsheet.md
This PR adds support for the [taxonomy suggestions API](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v3/#get-/api/v3/taxonomy_suggestions) in OpenFoodFacts. The API provides suggestions for various taxonomy fields such as categories, packaging materials, and synonyms.
- Fixes #10328
=> docs: Update ref-cheatsheet.md to mention suggest from search

taxonomies/food/categories.txt, taxonomies/packaging_shapes.txt
Adds some Danish (`da`) and Swedish (`sv`) translations of a few categories and packaging shapes.
=> taxonomy: Some Danish and Swedish translations

taxonomies/additives.txt, taxonomies/food/ingredients.txt, taxonomies/minerals.txt
Remove duplicate appearing when rebuilding taxonomies
Moved at the very end all ingredients that can be 2 different ingredients in some languages:
```
< en:crayfish
< en:shrimp
en: crayfish or shrimp
it: gambero, gamberi
< en:cucumber
< en:gherkin
en: cumcumber or gherkin
de: Gurke
it: cetriolo o cetriolo
< en:plant
en: spice or bell pepper
bg: червен пипер, паприка
cs: paprika
da: paprika
de: Paprika
fi: paprika
hu: paprika
lv: paprika
nb: paprika
nl: paprika
nn: paprika
no: paprika
pl: papryka, papryki, paprykowy, paprykowe, paprykowa
sl: paprika
sv: paprika
```
=> fix: remove duplicates in taxonomies 2

scss/_off.scss
Wrapped long username in data source card
- Fixes #7496
=> fix: wrap long username in cards

lib/ProductOpener/Display.pm
This PR:
- disables Memcached for results on the pro platform
- makes no_cache only affect Memcached: no_cache=1 queries can now go to off-query
- adds a new no_off_query parameter to indicate we want results from MongoDB
=> fix: no_cache + no_off_query

taxonomies/food/categories.txt
Adds “Baby spinach” as synonym for “Spinach young leaves” and adds Danish and Swedish translations.
See also discussion on Slack:
https://openfoodfacts.slack.com/archives/C02VDSWHT/p1741637133755419
=> taxonomy: Add “Baby spinach” synonym

scss/_product-list.scss
fix spacing between numbers in pagination
- Fixes #11257
=> fix: spacing between numbers in pagination

html/js/product-search.js, scss/_product-list.scss
This PR addresses the issue where the grid layout was not displaying the expected number of columns (5) on large screen sizes. Additionally, it resolves the unwanted extra space appearing in the last row of the grid.
- Fixed the grid layout to correctly display 5 columns on screens with a minimum width of 90.063em (xlarge size).
- Removed extra space between cards in the last row, ensuring consistent spacing across all rows.
- Adjusted CSS for better responsiveness across different breakpoints (small, medium, large, xlarge).
- Fixes #[#11579]
@teolemon If any suggestions related to changes, feel free to provide feedback or recommendations, and I’ll be happy to address them before merging the PR.
=> fix: style ui and fix bugs

.github/scripts/path-filter.sh, .github/workflows/pull_request.yml
Hey @stephanegigandet and @alexgarel, we finally made it! 🎉    
I've tested this solution in my local repo, so there won't be any further excuses. I just want to clarify that the issue last time wasn't with the merge file solution — that was correct. The real problem was with the `dorny/path-filter` action, which turned out to be buggy.    
I've now switched to `tj-actions/changed-files`, which works perfectly and is well-maintained. ✅
=> ci: replaced dorny/path-filter to tj-actions/changed-files

docs/api/ref/schemas/product_meta.yaml
When I found that many documents contained an undocumented `last_updated_t` property,
I first thought it was a typo for `last_modified_t`. But after reading
[issue 9646](https://github.com/openfoodfacts/openfoodfacts-server/pull/9646),
[the change log](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/CHANGELOG.md)
and the 
[message](https://github.com/openfoodfacts/openfoodfacts-server/compare/v2.25.0...v2.26.0).
for tag 2.26.0,
I understood this is a real property.
So here is its documentation.
Some other properties need to be documented, but I do not know what to say
about them and in which file the documentation should be written. These
properties are:
* packaging_materials_tags
* packaging_recycling_tags
* packaging_shapes_tags
* packagings_materials
=> docs: Documentation for 'last_updated_t'.

.github/workflows/pull_request.yml
`tj-action/changed-files` is compromised and I have replaced it with the best alternative of it.
=> fix: replace tj-actions/changed-file by step-security/changed-files

cgi/product_image_upload.pl
Added CORS headers to image upload API (needed for openfoodfacts-explorer)
```
curl -I http://world.openfoodfacts.localhost/cgi/product_image_upload.pl
HTTP/1.1 200 OK
Server: nginx/1.26.3
Date: Mon, 24 Mar 2025 09:37:34 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,If-None-Match,Authorization
Access-Control-Allow-Methods: HEAD, GET, PATCH, POST, PUT, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Range
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-XSS-Protection: 1; mode=block
X-Request-ID: fZzSBGJoBRay1IUx
```
=> fix: CORS headers for image upload API

templates/web/pages/user_form/user_form.tt.js, tests/integration/expected_test_results/web_html/user-register.html
The user registration process uses the `cgi-bin/user.pl` script in two modes: `display` mode to present an input form where the user enters their details, and confirms items such as whether they are creating a producer account, and secondly a `process` mode where the user's input is processed.
The browser scripting found in the `user_form.tt.js` template is only relevant for the `display` mode, and causes a browser-side error on the welcome page because an element it expects to find does not appear in the HTML of that page.
This changeset filters `user_form.tt.js` so that the relevant scripting is only included on the page in `display` mode -- retaining the functionality while also preventing the error.
- Resolves #11721
=> fix: include user_form.tt.js only in display mode

cgi/session.pl
**Signed-off-by:** Areeb Ahmed ([areebshariff@acm.org](mailto:areebshariff@acm.org))
1. Set conditional page titles based on login state:  
- Empty title when the user is signed in  
- "Sign out" when logging out  
- "Sign in" only on the login form  
2. Removed the generic title previously used for all states  
Closes #11723
=> fix: update session handling titles for sign in/out actions

lib/ProductOpener/Tags.pm
Removes a noisy log ouput message, emitted for each taxonomy retrieval, from `Tags.pm`.
- Fixes #11765.
Edit: update checklist
=> fix: remove noisy taxonomy-retrieval message output

taxonomies/food/ingredients.txt
Several lactic acid bacteria were recategorised in 2020, including Lactobacillus plantarum being reassigned to the “new” genus Lactiplantibacillus, thus becoming Lactiplantibacillus plantarum.
See
https://en.wikipedia.org/wiki/Lactobacillaceae
https://en.wikipedia.org/wiki/Lactiplantibacillus
https://en.wikipedia.org/wiki/Lactiplantibacillus_plantarum
=> taxonomy: Update L. plantarum ingredient

taxonomies/food/categories.txt, taxonomies/food/ingredients.txt
Right now pickled and non-pickled cucumbers and gherkins seem to be mixed together with no clear purpose or clear separation of what should go where.
This is an attempt at starting to unravel this.
See:
https://openfoodfacts.slack.com/archives/C06A7LENM/p1744912951211729
https://en.wikipedia.org/wiki/Pickled_cucumber
https://www.wikidata.org/wiki/Q1211297
https://www.wikidata.org/wiki/Q1365891
Related (but not addressed here) issue:
https://github.com/openfoodfacts/openfoodfacts-server/issues/11798
=> taxonomy: Untangle un/pickled cucumbers/gherkins

.github/workflows/container-deploy.yml, .github/workflows/github-projects-ventilation.yml, .github/workflows/merge-conflict-autolabel.yml
Three of the GitHub Actions that we use in our GitHub Actions CI workflows (via the `uses: ...` clause in the YAML files) refer to those actions based on a branch name, instead of a conventional tagged release number or fixed commit ID.
The three relevant actions are:
* `actions/add-to-project` (used to add issues/PRs to our GitHub Project boards)
* `appleboy/ssh-action` (used during some of our deployment workflows)
* `mschilde/auto-label-merge-conflicts` (used to annotate PRs that currently have merge conflicts)
I noticed this during some auditing of our GitHub Actions references during [Slack discussion](https://openfoodfacts.slack.com/archives/C02LDQDDD/p1744723461030369) of the possible merits and disadvantages of [`ratchet`](https://github.com/sethvargo/ratchet/) and how it relates …
=> ci: GitHub Actions: prefer tags/commit IDs instead of branch names

templates/web/pages/search_form/search_form.tt.html, tests/integration/expected_test_results/web_html/fr-search-form.html, tests/integration/expected_test_results/web_html/world-search-form.html
Removes a duplicate set of radiobox controls for filtering product search based on ingredient-related properties (additives, relationship to palm oil) from the HTML template used by `cgi/search.pl`.
Also removes a closing `</div>` that was causing an HTML parsing/validation error:
Resolves #11832.
=> fix: product search: de-duplicate ingredient filtering controls

.github/dependabot.yml
We use `jquery` v2.x for compatibility with the Foundation UI framework, as described in #11109.
However, Dependabot isn't yet configured to know about this, so it attempts to suggest that we upgrade to `jquery` v3.x - e.g. #11820 that it opened earlier today.
So, let's [configure Dependabot to ignore](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#ignoring-specific-dependencies) those particular updates.
- Follow-up to #11109.
=> ci: dependabot: ignore 'jquery' updates to v3.0.0+

mkdocs.yml
Should add a link "Edit on Github" on every page, if I believe https://www.mkdocs.org/user-guide/configuration/#edit_uri
=> feat: add "Edit this page" on every documentation page

lib/ProductOpener/Ingredients.pm, tests/integration/expected_test_results/facets/brand_-brand1.json, tests/integration/expected_test_results/facets/brand_-unknown.json, tests/integration/expected_test_results/facets/brand_brand1.json, tests/integration/expected_test_results/facets/brand_brand2_brand_-brand1.json, tests/integration/expected_test_results/facets/brand_unknown.json, tests/integration/expected_test_results/facets/category-vitamins.json, tests/integration/expected_test_results/facets/category_-apples.json, tests/integration/expected_test_results/facets/category_-apples_label_-organic.json, tests/integration/expected_test_results/facets/category_-apples_label_organic.json, tests/integration/expected_test_results/facets/category_apples.json, tests/integration/expected_test_results/facets/category_apples_label_organic.json, tests/integration/expected_test_results/facets/category_bananas_label_organic_brand_-brand1.json, tests/integration/expected_test_results/facets/category_bananas_label_organic_brand_brand1.json, tests/integration/expected_test_results/facets/contributor-alice-label_organic.json, tests/integration/expected_test_results/facets/contributor-alice.json, tests/integration/expected_test_results/facets/contributor-bob.json, tests/integration/expected_test_results/facets/de-accented-cafe-label.json, tests/integration/expected_test_results/facets/label_fair-trade_label_-organic.json, tests/integration/expected_test_results/facets/packager-code_fr-85-222-003-ce.json, tests/unit/expected_test_results/ingredients/en-vegetal-ingredients.json, tests/unit/expected_test_results/ingredients/fr-vegetal-origin.json, tests/unit/expected_test_results/ingredients/nl-e471-niet-dierlijk.json, tests/unit/ingredients_analysis.t
In the ingredients structure, we have inconsistent values for the "vegetarian" and "vegan" properties. In the taxonomy, they are set to "yes", "no", "maybe", but in the ingredients analysis, if there was a label or vegetal origin (e.g. "coagulating enzyme (vegan)", we would put "en:yes" as a value.
=> fix: use 'yes' instead of 'en:yes' for vegan / vegetarian ingredients properties

lib/ProductOpener/Packaging.pm, tests/unit/packaging.t
This handles the case where we know all the packaging (`packagings_complete` is set to true/`1`), it only consists of a single packaging item, _and_ we don’t know the weight of it. Even without knowing the actual weight, we do know that that single item makes up 100% of the packaging’s weight.
=> feat: Add weight % for single-item packaging

Makefile, taxonomies/brands.txt
The current `brands.txt` is _almost_ fully sorted alphabetically. This commit now commits to this and sorts all the entries, as per `sort -bi` in the `C.UTF-8` locale. This ignores case (`-f`) and leading whitespace (`-b`).
I also tried with the `--dictionary-order` and `--ignore-nonprinting` options, but these seem to fully ignore non-ASCII characters, leading to a less human-sensible ordering (e.g., “Änglamark” getting sorted with the n’s as “nglamark”).
It also adds a test in the `Makefile` to check for the brand ordering going forward.
=> taxonomy: Sort brands.txt

lib/ProductOpener/Ingredients.pm
Fix bug for text extraction, reported on Slack **contribution** channel
```
Unmatched ) in regex; marked by <-- HERE in m/\*?\s*\bdoporu) <-- HERE c|Ä)eny zp(u|Å¯)sob p(r|Å™)(i|Ã)pravy\b(.*)$/ at /srv/off/lib/ProductOpener/Ingredients.pm line 5862.
```
=> fix: text extraction issue for CZ and LT

taxonomies/labels.txt, tests/integration/expected_test_results/api_v3_product_write/patch-tags-fields.json
Currently the lacto- and ovo-vegetarian labels both derive from lacto-ovo-vegetarian, which will almost always be wrong. Ovo-vegetarians consume eggs but not dairy, while lacto-vegetarians consume dairy but not eggs—ovo-lacto-vegetarians consume both dairy and eggs.
This makes the `en:Ovo-lacto-vegetarian` labels instead be a parent of `en:Lacto-vegetarian` and `en:Ovo-vegetarian` instead, since anything that is either lacto- or oco-vegetarian will also be ovo-lacto-vegetarian. `en:Ovo-lacto-vegetarian` is additionally made a child of `en:Vegetarian` since the ovo/lacto modifier adds additional restrictions, so vegetarians who still consume non-human animal byproducts (like dairy and eggs) will be fine with this.
=> fix: Lacto-ovo-vegetarian taxonomy

taxonomies/food/ingredients.txt
The Taxonomy Editor currently doesn’t allow for editing the Food Ingredients taxonomy file due to a number of errors:
> Missing child link at line 905 for en:sodium-cyclamate: parent_id cyclamate not found in tags_ids_en
> Missing child link at line 26477 for en:oat-fibre: parent_id vegetable-fibre not found in tags_ids_en
> Missing child link at line 26511 for en:oat-husk-fiber: parent_id vegetable-fibre not found in tags_ids_en
> Missing child link at line 33898 for en:hydrolyzed-wheat-protein: parent_id vegetable-hydrolysed-protein not found in tags_ids_en
> Missing child link at line 33912 for en:hydrolysed-corn-protein: parent_id vegetable-hydrolysed-protein not found in tags_ids_en
> Missing child link at line 86234 for fr:oeufs-categorie-poules-elevees-plein-air: parent_id …
=> fix: Errors in food ingredients

docs/api/index.md, docs/api/ref/api-v3.yml, docs/api/ref/api.yml, docs/api/ref/requestBodies/add_or_edit_a_product.yaml, docs/api/tutorial-off-api.md, docs/api/tutorial-uploading-photo-to-a-product.md
Make it really clear that it's better not to use email to login when using the API.
=> docs: precise that user_id is username, not email

po/tags/es.po
In the localization resources under the `po` directory, it seems that all tagnames should be lowercase.
However, there is a tagname in Spanish that begins with an uppercase ASCII character.  It seems to be the only one at the moment:
```sh
$ grep -rw -A 1 'msgid "editors"' po/tags | grep msgstr | grep '\.po-.*[A-Z]'
```
This pull request modifies it to be lowercase too, for consistency.
- Discovered / noticed by https://github.com/openfoodfacts/openfoodfacts-server/pull/11861#issuecomment-2912151272
=> fix: localization: lowercase the Spanish translation of the 'editors' resource string

taxonomies/labels.txt
Kött and Mjölk från Sverige specifically refers to meat and milk respectively and doesn’t necessarily apply to the rest of the ingredients (I think?). Even if it does, if there’s only the Kött or Mjölk label on packaging and no “Från Sverige”, we probably don’t want to show both logos on product pages, which would be another result of this inheritance.
=> taxonomy: “Orphan” Kött/Mjölk från Sverige

.devcontainer/devcontainer.json
The previous home was `/var/www/`, which the vscode user wasn't allowed to write to.
=> chore(dev): Update devcontainer to use different dir as home

Makefile
During a recent manual QA/testing process for #11884, I was working mostly offline (with my laptop's Internet connection turned off) in order to reduce distractions.
Attempting to restart the local development environment between tests failed at a `git pull` step in the `Makefile` -- and I'd like to suggest that we could make that step optional - with a warning if it fails - provided that the user already has a checkout of the dependency.
N/A
- This suggestion is based on practical experience from a round of testing described at: https://github.com/openfoodfacts/openfoodfacts-server/pull/11884#issuecomment-2939482998
=> build: allow stale dependency git repo clones

cgi/product_multilingual.pl, lib/ProductOpener/Images.pm
There's a small bug in v2.69.0 that is being deployed: in the web product edit form, it doesn't show that an image is already selected. This is a hot fix for it.
=> fix: display selected image in product edit form

taxonomies/food/categories.txt
I misunderstood how `expected_ingredients` worked when I added these[1], so removing again to stop them getting flagged for quality issues!
And while I was at it, I also added one that _could_ use it. :)
[1] I thought it would just want that ingredient to be in 
the ingredient list, not that it would want it to be
the sole ingredient.
=> taxonomy: Fix and amend some `expected_ingredients`

lib/ProductOpener/Data.pm, lib/ProductOpener/Display.pm
Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/12059
https://github.com/openfoodfacts/openfoodfacts-server/pull/12045 was too aggressive: we should not send API search / list of products queries to off-query, as they expect to get all product fields.
Some API queries may ask only for supported fields, so we could add support for that at a later point.
=> fix: disable off-query for API queries that may need unsupported fields

Makefile, docker/integration-test.yml
Use new Keycloak testcontainer image with config built in which improves startup time
- Fixes https://github.com/openfoodfacts/openfoodfacts-auth/issues/207
Note this changes the way clients are created in Keycloak. Instead of creating them on-the-fly on startup they need to be created manually via the admin UI or API. The full process for creating a client would be as follows:
1. Create the client in Keycloak (copy from the OFF client if it needs full permission). The client id should match the Product Opener flavour in upper case
2. Get the secret and add this as a GitHub secret in openfoodfacts-server
3. Update the openfoodfacts-server image deployment script to add this secret to the environment.
For production the edits would be more manual
=> fix: Use testcontainer directly with simplified configuration

taxonomies/food/categories.txt
Correction of salty biscuits categories. There was a mistranslation of the French word "feuilleté" in "puffed" instead of "flaky".
=> taxonomy: correction salty flaky biscuits

conf/nginx-docker/nginx.conf, conf/nginx/sites-available/obf, conf/nginx/sites-available/off, conf/nginx/sites-available/off-pro, conf/nginx/sites-available/opf, conf/nginx/sites-available/opff, html/robots.txt
robots.txt is currently generated for every request by Product Opener, so that we can have different rules:
- based on user-agent (e.g. to allow some facets like /brands for some crawlers)
- based on cc + lc (to be able to list facets like /facets/marques in French for instance, and also to disallow crawling of subdomaines like fr-en)
It's not very convenient though, as some robots use tons of ips, and some of those send thousands of requests for robots.txt, that go to our low priority Apache, which is often overloaded and not responding.
I would really like to make robots.txt static again, so that it can be served instantly by nginx.
This PR contains a simple robots.txt:
- it disallows /facets for everyone, except Googlebog and Bingbot
- it disallows / for a bunch of robots that have …
=> fix: make robots.txt static

scripts/migrate_users_to_keycloak.pl
We need to set a password for Keycloak users in staging as otherwise there is no way to log in. Password will be copied from the existing value
=> fix: Get Keycloak anonymized migration to use the existing password

docs/api/aws-images-dataset.md
The image folder structure was out of date.
Solves https://github.com/openfoodfacts/openfoodfacts-server/issues/12166
=> docs: update documentation about AWS images

Makefile
Because it's annoying to have a lot of running containers
See also:
* https://github.com/openfoodfacts/openfoodfacts-auth/pull/235
* https://github.com/openfoodfacts/openfoodfacts-shared-services/pull/15
that adds the "stop" targets to dependencies.
=> build: add a stop_deps target

docker-compose.yml
Upgrade docker to use PostgreSQL 13 as this corresponds to Production and a recent Minion upgrade has removed support for PostgreSQL 12.
- Fixes #12281
=> fix: Upgrade to PostgreSQL 13

.github/dependabot.yml
- ci: Add devcontainers configuration to dependabot
- stolen from @john-gom 
- package-ecosystem: "devcontainers"
directory: "/"
schedule:
interval: "monthly"
allow:
- dependency-type: "all"
groups:
devcontainers:
patterns:
- "*"
=> ci: Add devcontainers configuration to dependabot

Makefile, docs/dev/how-to-release.md, lib/ProductOpener/Producers.pm, scripts/build_pro_platform_fields_columns_names.pl
When we upload CSV / Excel files to the pro platform, we currently recompute all possible column names to OFF field mappings for the current language (+ English), which can take quite a lot of time.
Instead we can just build all languages and store the corresponding mappings.
=> fix: build and save pro platform column names mapping

lib/ProductOpener/APIProductRead.pm, lib/ProductOpener/Display.pm, scripts/update_all_products.pl
and some call to compute_product_history_and_completeness
ex: http://world.openfoodfacts.localhost/api/v2/product/5601244500087/?blame=1
=> fix: API blame parameter

.github/workflows/container-deploy.yml
Because a running container, can prevent them from being removed, as it happened for a few weeks… making js / css etc not up to date on .net…
Also change deprecated script_stop to continue-on-error in deploy workflow
=> ci: verify dist volumes are removed on deployment

lib/ProductOpener/Store.pm, tests/unit/store.t
Getting an error when adding a product without a bar code. Was caused because we store the last number in a file but the JSON serialization was not coping with this
Fixed by converting to and from refs when dealing with scalars
- Fixes #12331
=> fix: Not able to add products without a bar code

lib/ProductOpener/Food.pm, taxonomies/nutrients.txt
Reported on Slack that energy appears on pet food nutrition facts.
As mentioned in EU regulation - https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02009R0767-20181226&qid=1734788661215 - enegy and proteins can appear (optional) on the packages. 
Hence, this PR adds energy (always visible) and proteins (not visible)
- Fixes #-none- (on Slack)
=> fix: add energy and proteins for pet food nutrition

.github/workflows/pull_request.yml
Github workflow is failing on the following PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/12262
Due to 
> ##[error]Error: Command failed: docker save openfoodfacts-server/backend:dev -o /tmp/openfoodfacts-server_backend_dev
> write /tmp/.docker_temp_901694671: no space left on device
The following PR attempt to free some space before to call "ishworkh/container-image-artifact-upload@v2.0.0" step in "build_backend:" job
=> fix: free space during workflow

docs/dev/how-to-quick-start-guide.md
Add hint about `make -j32` potentially speeding up `make dev` (and other local development).
N/A
N/A
=> docs: Improve quick start guide with additional GNU make parallel execution tips

taxonomies/food/ingredients.txt, tests/unit/expected_test_results/attributes/en-maybe-vegan.json, tests/unit/expected_test_results/attributes/en-nova-groups-markers.json
We mistakenly mark some plain yoghurts as NOVA 3 because of the microbial culture. They should be NOVA 1.
=> fix: do not consider microbial cultures and enzymes NOVA 3 markers

Makefile
Removed the '--fix' option from the npm lint command in the Makefile. `make front_lint` is run as a PR check. It's supposed to fail in case of an error. Using the `--fix` option would hide JS/CSS/SCSS issues.
N/A
It looks like the parameter was added in 209a7338bd7567e60cbaf5fce57af1f1685014f9 by accident.
=> chore: Update front_lint command to remove --fix option

Makefile
I'm very often using "make restart" when I code (because of changes to .pm files). It's taking a bit more time than before because it restarts the dependencies.
This new "make restart_backend" only restarts Apache. It takes 10 seconds instead of 15. Not big but I run this command a lot. :)
=> fix: add new make restart_backend

env/env.obf, env/env.off, env/env.off-pro, env/env.opf, env/env.opff, lib/ProductOpener/Tags.pm, tests/unit/tags.t
Can't use the public URL from the backend servers. Also removed redundant client_id from envorinment files.
Fixed cc_to_country to cope with undefined input
=> chore: Need to use backchannel URL for Keycloak

taxonomies/food/ingredients.txt
Correction of coating ingredients. "en: berry coating" was in berry, which would count it as a fruit for the nutriscore. However, berry coating is susceptible to contain other ingredients, such as sugar, and should'nt be classified as a fruit. Same for "chocolate and hazelnut coating" which was indirectly in "hazelnut" through "hazelnut coating". It classifies it as a "fruit, vegetable or nut" for the nutriscore calculation.
=> taxonomy: correction coating ingredients

Dockerfile, cpanfile
Use slim base image and don't install recommended packages to reduces the image size.
N/A
N/A
Uncompressed size (`docker inspect`): 2304932834 Bytes
`docker history`: 
```
IMAGE          CREATED         CREATED BY                                      SIZE      COMMENT
f2a1c6993135   3 minutes ago   CMD ["apache2ctl" "-D" "FOREGROUND"]            0B        buildkit.dockerfile.v0
<missing>      3 minutes ago   ENTRYPOINT ["/docker-entrypoint.sh"]            0B        buildkit.dockerfile.v0
<missing>      3 minutes ago   USER www-data                                   0B        buildkit.dockerfile.v0
<missing>      3 minutes ago   WORKDIR /opt/product-opener/                    0B        buildkit.dockerfile.v0
<missing>      3 minutes ago   COPY ./docker/docker-entrypoint.sh / # build… …
```
=> chore: Use slim base image and don't install recommended packages

taxonomies/food/categories.txt
the category "Whole or semi-whole pastas" contains now both "Semi-whole pastas" and "Whole pastas".
Added also english translation
=> taxonomy: fix some whole and semi-whole pastas categories

taxonomies/allergens.txt
Added a synonym of mustard in czech based on a product containing this allergen: https://world.openfoodfacts.org/product/5051007128902/2-tortillas-mexicana-tesco
https://en.wiktionary.org/wiki/ho%C5%99%C4%8Dice
=> taxonomy: synonym mustard czech
