- .github/labeler.yml
- taxonomies/data_quality.txt
> feat: "en:Serving size is missing digits" description

- taxonomies/categories.txt
> taxonomy: Meat corrections

- taxonomies/categories.txt
Trying to get the number of reported errors down.
> chore: taxonomy repairs

- taxonomies/ingredients.txt
This commit adds one more ingredient: potassium iodide. I found it in a product: https://de.openfoodfacts.org/produkt/7610227935219/plant-based-filet-h%C3%A4hnchen-art-green-mountain
none
none
> taxonomy: add ingredient potassium iodide

- taxonomies/ingredients.txt
This commit adds one more ingredient: oat fiber. I found it in a product: https://de.openfoodfacts.org/produkt/4311501704318/protein-wraps-edeka
none
none
> taxonomy: add ingredient oat fiber

- taxonomies/categories.txt
> taxonomy: oat milks

- CONTRIBUTING.md
- docs/introduction/api.md
- docs/introduction/knowledge-panels.md
- docs/introduction/robotoff.md
- docs/reference/api-cheatsheet.md
- docs/tutorials/uploading-photo-to-a-product.md
- docs/tutorials/using-the-OFF-API-tutorial.md
- Update documentation introduction
- Update Knowledge Panel introduction
- Update the RObotoff  introduction
- Update upload a photo tutorial
- Update using the OFF tutorial
> docs: Docs overhaul

- taxonomies/additives.txt
- taxonomies/categories.txt
- taxonomies/ingredients.txt
> chore: taxonomy additions

- scripts/snippets/agribalyse_categories_csv.py
A simple script to get a CSV of agribalyse categories.
> chore: a small script to export agribalyse

- .github/workflows/container-deploy.yml
We added Facets Knowledge panels (see #8055), but they need to be configured on staging.
> ci: facets knowledge panels on staging

- cgi/user.pl
- lib/ProductOpener/Users.pm
- scripts/snippets/remove_broken_entry_with_empty_email.pl
> fix: changing orgs for pro moderators 

- taxonomies/categories.txt
- tests/integration/expected_test_results/export/0850032917148.json
- tests/integration/expected_test_results/export_more_fields/0850032917148.json
Improved the categories fro apple juices.
Background can be found here: https://wiki.openfoodfacts.org/Apple_juices_category_-_en
> chore: Apple juices category improvements

- taxonomies/additives.txt
- taxonomies/ingredients.txt
Update taxonomy languages Catalan and Spanish.
> taxonomy: Update ingredients in Catalan and Spanish

- taxonomies/ingredients.txt
add :de: alias for Creme Fraiche without the accents e.g. as seen in ingredient list of https://de.openfoodfacts.org/produkt/4008366009763/schlemmerfilet-brokkoli-mandel-frosta
> taxonomy: add :de: alias for Creme Fraiche without the accents

- templates/web/common/includes/producers_platform_front_page.tt.html
fixed link on producers platform
> fix: link to import photos

- taxonomies/categories.txt
> taxonomy: Changes to juices

- conf/mongodb/create_indexes.js
Added a new index to solve #8168
As we already have 64 indexes, I removed one for amino_acids which hopefully is not much useful
> fix: mongodb index for countries_tags + created_t 

- lib/ProductOpener/Import.pm
Split some code into 2 new separate functions.
> refactor: break huge function

- lib/ProductOpener/Display.pm
> fix: link to pro platform in edit product form 

- taxonomies/categories.txt
Add `en:cheeses` parent to `en:breaded-cheeses`
> taxonomy: update category taxonomy

- taxonomies/additives.txt
> taxonomy: de syn E306

- docs/api/ref/api.yml
- docs/api/ref/requestBodies/unselect_a_photo.yaml
Add it to OpenAPI v2 documentation.
> docs: add documentation about unselecting photo

- taxonomies/ingredients.txt
> taxonomy: Mortadella

- taxonomies/categories.txt
> taxonomy: Fish preparations

- taxonomies/ingredients.txt
> taxonomy: minor synonymes

- docker/README.md
- mkdocs.yml
- scripts/build_mkdocs.sh
being consistent with github or vscode rendering
> build: make docs list formating better

- templates/web/pages/product_edit/product_edit_form_display.tt.html
- templates/web/pages/product_edit/product_edit_form_process.tt.html
> fix: fix icons and small glitch with nutrition image

- taxonomies/categories.txt
> taxonomy: Concentrate fruit juices

- templates/web/pages/product_edit/product_edit_form_display.tt.html
Solves #8292 and reopens #8287
> fix: remove z-index:-3 on nutrition photo 

- html/.well-known/assetslinks.json
- feat: Create assetslinks.json
> feat: Create assetslinks.json

- lib/ProductOpener/Routing.pm
- stop_words.txt
- tests/unit/routing.t
Fixes issue #8304 
Also adds a few tests, but we should clearly add tests for all possible route types.
> fix: Fix routing pages

- taxonomies/nutrients.txt
trying to re-do the PR https://github.com/openfoodfacts/openfoodfacts-server/pull/5160 from @laralem... after 2 years!
Due to the evolution of the file for the last 2 years, the following changes from the previous PR could not be added:
> pt:gordura insaturada
> pt:Gordura insaturada, Ácidos gordos insaturados, Lípidos insaturados
> ...
> # pt-pt:Colesterol
> ...
> pt:Vitaminas, Vitamina
> ...
> pt:Sais minerais, Minerais, Mineral, Matéria mineral, Sal mineral
> ...
> pt:Cloro, Cl2, Cℓ, Cl-
> ...
> pt:Sulfato, SO42-, SO4
> ...
> pt:Frutas - vegetais e frutos secos (estimativa da lista de ingredientes)
> ...
> pt:Grau de nutrição
> ...
> pt:Clorofilas, Clorofila
> ...
> pt:Resíduo seco a 180 °C, Resíduos secos a 180 °C
> ...
> pt:EBU, European Bitterness Unit
> taxonomy: added changes from laralem

- lib/ProductOpener/Ingredients.pm
- stop_words.txt
- taxonomies/ingredients.txt
- tests/unit/ingredients_processing.t
Continuation of https://github.com/openfoodfacts/openfoodfacts-server/pull/8327 by @Teiron 
- added a stop word so that POD tests pass
- added some unit tests
> feat: Enable Polish ingredients processing + tests

- taxonomies/nutrients.txt
added (sugar alcohols) for easier findability
> chore: polyols

- docs/api/ref/requestBodies/add_photo_to_existing_product.yaml
- docs/api/ref/requestBodies/crop_a_photo.yaml
- Improve OpenAPI documentation about image selection/upload.
- #7446
> docs: improve OpenAPI documentation about images

- cgi/top_translators.pl
> fix: canonical url for /cgi/top_translators.pl 

- .github/workflows/crowdin.yml
- Add a better Crowdin PR so that more people review translation PRs
> ci: Add a better Crowdin PR

- taxonomies/labels.txt
copy paste of the amazing contribution from @laralem (https://github.com/openfoodfacts/openfoodfacts-server/pull/5053)
if this PR is approved, please discard the initial one.
**comment:** the following line was ignored because it refers to Intermarche which is a distributor in France only:
- pt:Seleção Intermarché, Intermarché Seleção
> taxonomy: copied pasted contribution from laralem

- .github/workflows/github-projects-for-openfoodfacts-design.yml
> ci: fix-opf-autoaddition

- lib/ProductOpener/Display.pm
- po/common/en.po
fix: Add contributors link in user profile for easier account deletion
-
> fix: Add contributors link in user profile for easier account deletion

- .github/labeler.yml
ci: labeler for packager codes files
> ci: labeler for packager codes files

- lib/ProductOpener/Products.pm
> fix: provide Robotoff details about product updates

- docs/api/aws-images-dataset.md
- docs/api/how-to-download-images.md
- Add reference to AWS dataset
- #7744
> docs: update docs about downloading images

- lib/ProductOpener/Tags.pm
- taxonomies/categories.txt
uncommented the exclusion of category for errors in Tags.pm. Also, fix the errors
No issue, but an old issue is related to this: https://github.com/openfoodfacts/openfoodfacts-server/issues/6382 and was written in the code.
> fix: uncomment error raised in tag and fix errors

- scss/_product-list.scss
Fix the alignments of products at the beginning and the end of the list of products so as to make it more aesthetically coherent with the whole list and new app design.
- Fixes #[7309]
> fix: make products aligned again in list #7309

- taxonomies/additives.txt
> taxonomy: portuguese synonyme

- taxonomies/ingredients.txt
> taxonomy: german ingredients

- taxonomies/ingredients.txt
Additions for the Divinfood EU project that focuses on neglected and underutilized crops such as lupine, fava beans, grey peas, einkorn... Added some entries and translations / synonyms. + tonka bean that we missed.
> taxonomy: lupine, einkorn, grey pea for Divinfood + tonka bean

- taxonomies/categories.txt
> taxonomy: Correction bars

- taxonomies/ingredients.txt
Some rare legumes and cereals that are of interest to the Divinfood EU project.
> taxonomy: rare legumes and wheat / divinfood project

- lib/ProductOpener/Products.pm
- scripts/make_user_moderator.pl
Iterate over products and products_obsolete when deleting a user
- Fixes #8475
> fix: Iterate over both product collections on user delete

- .github/labeler.yml
> labeling for nginx

- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- templates/web/common/producers_resources_list.tt.html
- templates/web/common/site_layout.tt.html
- templates/web/pages/session/signed_in.tt.html
Added an option " Join the next Pros' Meet-up "  in the menu of the Pro-platform and made necessary changes in the .po/.pot files to make it translatable.
- Fixes #8407
> feat: Added Pros' Meet-Ups link in Menu

- taxonomies/categories.txt
> chore: taxonomy updates

- scripts/ban_abusive_ip.pl
Saving an existing file from off1.
> build: ban_abusive_ip.pl script (taken from off1)

- taxonomies/nutrients.txt
feat: translations for Fruits estimates
> feat: translations for Fruits estimates

- lang-default/en/texts/index-pro.html
Added intro video for pro platform in lang-default/en/texts/index-pro.html.
- **for smaller screens**
- Fixes #8526
> feat: Added Welcome Video in Pro Platform

- .github/ISSUE_TEMPLATE/feature_request.md
> chore: Update and rename feature_request.yml to feature_request.md

- templates/web/pages/import_file_upload/import_file_upload.tt.html
Added tuto video 2 & 3 in templates/web/import_file_upload/import_file_upload.tt.html.
- Fixes #8527
> feat: Added Tutorial Videos about Data-Import in Pro Platform

- docs/api/index.md
- docs/api/ref-cheatsheet.md
- docs/api/ref/requestBodies/crop_a_photo.yaml
- docs/api/tutorial-off-api.md
- docs/api/tutorial-uploading-photo-to-a-product.md
- docs/assets/api-rapidoc.html
- fix broken links
- fix typos
- improve documentation about image cropping
> docs: Update API documentation

- taxonomies/categories.txt
> taxonomy: compound dairy creams

- .github/labeler.yml
- Autolabeler improvements for PIMs
> ci: Autolabeler improvements for PIMs

- .github/labeler.yml
> fix: fix labeler duplicate

- html/files/tagline-off-android-v2.json
- html/files/tagline-off-ios-v2.json
> feat: tagline for 2023 survey

- .dockerignore
> chore: more dockerignore files

- html/files/tagline-off-android-v2.json
- html/files/tagline-off-ios-v2.json
feat: add tagline for French and Fallback
> feat: add tagline for French and Fallback

- .github/ISSUE_TEMPLATE/bug_report.md
> fix: fix bug template

- templates/web/pages/org_profile/org_profile.tt.html
The link to the product page on the official site of the producer opens in a new tab.
- Fixes #8618
> fix: Link to the product page opens in a new tab

- taxonomies/ingredients.txt
A few additions and corrections to Danish ingredients.
E.g. Danish "issalat" is not iceberg lettuce, but the flowering plant Mesembryanthemum.
> taxonomy: Danish additions, corrections

- docs/dev/how-to-quick-start-guide.md
more explanation in quick start guide on how to download wget with the executable wget.exe
> docs: explanation on how to download wget on Windows

- taxonomies/allergens.txt
> german stop word

- taxonomies/ingredients.txt
- tests/unit/ingredients_processing.t
adds creaming powder entry (used in Japanese ingredients: ja:クリーミングパウダー )
> taxonomy: creaming powder, creaming agent

- taxonomies/ingredients.txt
- tests/unit/expected_test_results/parse_origins_from_text/real-list-fr.json
Solved some of the errors reported by the taxonomy build of ingredients.txt
> taxonomy: some fixes to ingredients taxonomy

- docs/api/index.md
- docs/api/ref/api-v3.yml
- docs/api/ref/api.yml
- docs/api/tutorial-off-api.md
- docs/api/tutorial-uploading-photo-to-a-product.md
- docs/assets/api-rapidoc.html
removal of the off:off references in the API documentation
> docs: remove off:off references in the API documentation

- taxonomies/additives.txt
- taxonomies/additives_classes.txt
- taxonomies/allergens.txt
- taxonomies/ingredients.txt
- taxonomies/ingredients_processing.txt
- taxonomies/vitamins.txt
added Croatian ingredients into the taxonomies. 
(+ added ingredients mentioned in Slack in ingredients channel)
> taxonomy: added Croatian ingredients in taxonomies

- taxonomies/ingredients.txt
> taxonomy: italien ingredient

- taxonomies/ingredients.txt
Added some missing ingredients for a couple of products.
> taxonomy: Lithuanian ingredients

- taxonomies/categories.txt
> taxonomy: corrections yogurts

- taxonomies/ingredients.txt
> taxonomy: German ingredient

- lib/ProductOpener/Mail.pm
Bug was introduced during PR review.
> fix: fix bug in Mail.pm

- scripts/remove_empty_products.pl
the script was timing out because it used the "empty" field for which we don't have an index
also removed useless cruft
> fix: use states_tags index for remove_empty_products.pl

- .github/labeler.yml
> ci: labeler for OpenAPI

- Makefile
- cgi/product_multilingual.pl
> fix: always display contribution panel after edit

- taxonomies/categories.txt
Identified in https://es.openfoodfacts.org/product/8422628300072/salsa-boletus-juker
> taxonomy: Add mushroom sauces for Spanish and Catalan

- taxonomies/ingredients.txt
> taxonomy: de and cz ingredients

- taxonomies/ingredients.txt
added ingredients in the taxonomies.
> taxonomy: added ingredients in taxonomies

- scripts/gen_feeds.sh
- scripts/gen_feeds_daily_obf.sh
- scripts/gen_feeds_daily_off.sh
- scripts/gen_feeds_daily_opf.sh
- scripts/gen_feeds_daily_opff.sh
- scripts/gen_feeds_obf.sh
- scripts/gen_feeds_off.sh
- scripts/gen_feeds_opf.sh
- scripts/gen_feeds_opff.sh
> chore: only run gen_top_tags_per_country daily

- taxonomies/nutrients.txt
added PP to Vitamin B3
- Fixes #8755
> chore: added PP to Vitamin B3

- html/robots.txt
temporary test to disable bingbot by @raphael0202 + ban of seekportbot
> chore: disallow SeekportBot & Bingbot

- taxonomies/categories.txt
> taxonomy: correction Roscón de Reyes

- taxonomies/categories.txt
> taxonomy: correction to mueslis

- lib/ProductOpener/Ingredients.pm
- tests/unit/ingredients_percent.t
fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/8782
> fix: illegal division by zero in percent estimation

- docs/api/ref/schemas/product_extended.yaml
- docs/api/ref/schemas/product_nutrition.yaml
that was blocking rendering with rapidoc.
> docs: fix OpenAPI product_extended.yaml

- conf/nginx/sites-available/opff
Augment nginx body size.
- Part of: #8750
> fix: enable large file upload for Open Pet Food Facts

- conf/nginx/sites-available/obf
- Augment nginx body size + gzip more mime types.
- Part of: #8750
> fix: enable large file upload for Open Beauty Facts

- conf/nginx/sites-available/opf
> fix: gzip more files in nginx for Open Product Facts

- docs/dev/how-to-use-repl.md
typo and adding some instructions if re.pl is not found
> docs: update how-to-use-repl.md

- taxonomies/ingredients.txt
- tests/unit/expected_test_results/ingredients/fr-semi.json
- tests/unit/ingredients.t
more synonyms and entries for wholemeal / semi-wholemeal
> taxonomy: semi-complete flour

- taxonomies/ingredients.txt
- tests/unit/expected_test_results/ecoscore/fr-viande-porcine-francaise.json
- tests/unit/expected_test_results/ingredients/fr-viande-porcine-francaise.json
Added Eurocode 2 groups for leaf vegetables
https://web.archive.org/web/20170712020835/http://www.ianunwin.demon.co.uk/eurocode/docmn/ec99/ecmg08cl.htm
Also moved entries to put them in the eurocode order.
Part of #8825
> taxonomy: eurocode 2 group 8.10 - leaf vegetables

- scripts/update_all_products.pl
Added an option to remove a category (might be useful for mispellings)
> fix: Remove category

- lib/ProductOpener/Ingredients.pm
- taxonomies/ingredients.txt
- tests/unit/expected_test_results/ingredients/ca-middle-dot.json
- tests/unit/expected_test_results/ingredients/ja-parenthesis.json
- tests/unit/expected_test_results/recipes/fr-margherita-pizzas.fr-margherita-pizza-2-compound-ingredients.json
fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/8844
> fix: simplify vegan/vegetarian ingredients analysis and merge 'ignore' and 'maybe'

- cgi/org.pl
- cgi/product_image.pl
- cgi/search.pl
- cgi/spellcheck_test.pl
- cgi/test_ingredients_analysis.pl
- cgi/user.pl
- lib/ProductOpener/Display.pm
Removing unused coed. In the new website design, there's no side column, so no need for a full width mode either.
> chore: remove unused code/variable full_width

- crowdin.yml
ci: attempt to fix the PR name
> ci: attempt to fix the PR name

- .github/workflows/top-issues.yml
dashboard_title: 👍 Top Issues Dashboard
> ci: emojification of the dashboard

- .github/labeler.yml
- taxonomies/unused/stores.txt
feat: add some US stores
- https://github.com/openfoodfacts/openfoodfacts-server/issues/5689
> feat: add some US stores

- .github/workflows/pull_request.yml
to have an up to date version at codecov.io
> ci: run code coverage on each push on main

- taxonomies/ingredients.txt
Adding more eurocode properties to:
8.15 | Brassicas |   |  
-- | -- | -- | --
  | 8.15.10 | Broccoli | Brassica oleracea var italica |  
  | 8.15.12 | Broccoli tops | Brassica oleracea var italica | Mainly leaves
  | 8.15.15 | Cauliflower | Brassica oleracea var botrytis |  
  | 8.15.20 | Cabbage | Brassica oleracea var capitata alber | Inc. White cabbage, Spring greens
  | 8.15.24 | Red cabbage | Brassica oleracea var capitata rubra |  
  | 8.15.28 | Chinese cabbage | Brassica oleracea var pekinensis | Celery cabbage
  | 8.15.32 | Cabbage penca |   |  
  | 8.15.40 | Brussels sprouts | Brassica oleracea var gemmifera |  
  | 8.15.42 | Brussels tops | Brassica oleracea var gemmifera | Cabbage-like top of plant
  | 8.15.46 | Turnip tops | Brassica rapa var rapifera |  
  | 8.15.50 | …
> taxonomy: eurocode for ingredients - brassicas, stalk vegetables, shoot vegetables

- .github/workflows/merge-conflict-autolabel.yml
ci: add name and concurrency to the Merge Conflict script
> ci: add name and concurrency to the Merge Conflict script

- taxonomies/categories.txt
Add en taxonomy for the 4 subcategories of `en:Biscuit with a filled chocolate bar covering` by obvious derivative.
> taxonomy: Extend en taxonomy of subcategories of `en:Biscuit with a filled chocolate bar covering`

- lib/ProductOpener/Ingredients.pm
- taxonomies/allergens.txt
- taxonomies/categories.txt
- taxonomies/ingredients.txt
- taxonomies/packaging_materials.txt
- taxonomies/packaging_shapes.txt
I added and fixed some missing/wrong Polish translations in taxonomies
> taxonomy: Update polish taxonomy

- lib/ProductOpener/Tags.pm
- tests/unit/tags.t
> fix: xx: entries for ingredients matching 

- taxonomies/ingredients.txt
- taxonomies/ingredients_processing.txt
Updated ingredients processing taxonomy based on an European Official Journal publication: https://eur-lex.europa.eu/search.html?DB_COLL_OJ=oj-l&SUBDOM_INIT=ALL_ALL&DTS_SUBDOM=ALL_ALL&DTS_DOM=ALL&whOJ=NO_OJ_OLD%3D261%2CYEAR_OJ_OLD%3D1998&lang=en&type=advanced&qid=1692866511913
+ added some entries requested by other contributors
> taxonomy: add ingredients and processing

- .github/workflows/release-please.yml
for js/css/images dist generation and copy
> ci: fix release please to be more resilient

- lib/ProductOpener/APITest.pm
- tests/integration/delete_user.t
> fix: delete_user_test should not hang indefinitely 

- scripts/gen_feeds_daily_off.sh
:facepalm: moment when I realized I moved the lines in #8693 without seeing we where changing directory…
NB: change already made on off1 to see if it works tomorrow.
> fix: fix gen_feeds_daily for madenearme

- taxonomies/additives.txt
> taxonomy: german syn E341

- taxonomies/allergens.txt
> fix: New stopword french "pouvant"

- Makefile
> build: change default makefile target

- taxonomies/ingredients.txt
> taxonomy: synonymes hungarian

- taxonomies/additives_classes.txt
> taxonomy: syn hungarian

- taxonomies/additives_classes.txt
> taxonomy: plural antioxidantes portuguese

- taxonomies/categories.txt
> taxonomy: more vegan categories

- html/files/tagline-off-android-v2.json
- html/files/tagline-off-ios-v2.json
> fix: tagline donation

- scripts/import_carrefour_pro_off1.sh
fixes issue in carrefour import script (caused by a change in Import.pm a few months ago)
> fix: fix source_id org-carrefour in import script

- taxonomies/categories.txt
add 'Frozen' and 'Canned' subcategories to 'Meals with meat'
> taxonomy: add Frozen and Canned to Meals with meat

- cgi/product_image.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Images.pm
Use the image subdomain in more places where the current subdomain is currently used.
- Related to #8994
> fix: Use images subdomain for images

- taxonomies/ingredients.txt
> taxonomy: de and nl ingredients

- lib/ProductOpener/Images.pm
A small fix to use the right domain for edit form.
> fix: use images sub domain for edit product form

- taxonomies/additives.txt
> taxonomy: estonian names for E331 and E333

- taxonomies/ingredients.txt
> taxonomy: estonian and german ingredients

- cgi/user.pl
- conf/systemd/apache2.service.d/override.conf
There is also a commit of a file already modified on the server.
> fix: force user subscription on main website

- lib/ProductOpener/Display.pm
> fix: images urls on pro platform

- taxonomies/additives_classes.txt
> taxonomy: German synonym for antioxydant

- taxonomies/ingredients.txt
> taxonomy: correction soy protein

- taxonomies/categories.txt
> taxonomy: agribalyse proxy added

- taxonomies/ingredients.txt
> taxonomy: add macaroni (pasta)

- taxonomies/ingredients.txt
Added Norwegian synonym for tarragon.
> taxonomy: add Norwegian synonyms for tarragon

- taxonomies/ingredients.txt
> taxonomy: czech ingredients

- taxonomies/allergens.txt
> taxonomy: adding syn gluten

- lib/ProductOpener/Display.pm
Fixes some redirects like https://fr-fr.openfoodfacts.org/cgi/user.pl that currently redirect to https://fr.openfoodfacts.org/
this is needed because we disabled user creation on Open Beauty Facts etc. by redirecting to OFF: https://fr.openbeautyfacts.org/cgi/user.pl is redirected to https://fr-fr.openfoodfacts.org/cgi/user.pl
> fix: keep cgi script path when redirecting to canonical subdomain

- taxonomies/additives_classes.txt
> taxonomy: synonyme cs regulátory kyselosti

- taxonomies/labels.txt
With as many people around the world experimenting with the ketogenic diet as an intervention for weight loss and improving metabolic, mental, neurological, cardiovascular health (and more!), its addition is overdue.
Note: this is my first taxonomical label contribution, so please let me know if there's any best practices I may have overlooked (like where to add new items amongst existing ones, etc).
Also, please note that I used ChatGPT to generate translations, and got feedback from native speakers of at least Greek, Russian, and Italian that it's sane.
- Special diets
> taxonomy: add taxonomy labels for keto foods

- taxonomies/origins.txt
> taxonomy: adding german stopword Landwirtschaft

- taxonomies/ingredients.txt
> taxonomy: finnish ingredients

- taxonomies/categories.txt
> taxonomy: lentil soups correction

- lib/ProductOpener/Food.pm
- tests/unit/food.t
> fix: conversion from IU for prepared nutrients 

- html/js/folksonomy.js
fix: cardify Folksonomy Engine
> fix: cardify Folksonomy Engine

- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Food.pm
- lib/ProductOpener/FoodGroups.pm
- tests/unit/expected_test_results/nutriscore/beverage-with-80-percent-milk.json
- tests/unit/expected_test_results/nutriscore/dairy-drink-with-80-percent-milk.json
- tests/unit/expected_test_results/nutriscore/en-milk.json
- tests/unit/expected_test_results/nutriscore/fr-plant-beverages-soy-milk.json
- tests/unit/expected_test_results/nutriscore/milk.json
- tests/unit/nutriscore.t
In the new Nutri-Score formula, milk, dairy drinks and dairy drinks substitutes are considered beverages.
> fix: milk, dairy drinks and plant-based beverages Nutri-Score 2023

- scss/_product-page.scss
The arrow is not centered in Manage image button
- Fixes #7489
> fix: arrow is not centered in Manage image button Fixes #7489

- taxonomies/allergens.txt
> taxonomy: polish synonym orzeszki arachidowe

- taxonomies/categories.txt
- taxonomies/ingredients.txt
> chore: week41 taxonomy changes

- taxonomies/ingredients.txt
> taxonomy: few additions (cocoa, anis)

- lib/ProductOpener/Display.pm
- tests/integration/madenearme.t
attempt to correct bug on madenearme (currently only showing french locations)
> fix: fix madenearme scripts to load geo codes

- taxonomies/categories.txt
- Added some more beer categories
- Added a lot of descriptions to better understand categories.
- Most of the work was done towards Lagers - one of the primary types of beers.
> taxonomy: Even more beer categories

- templates/web/common/site_layout.tt.html
- remove OFF Days banner and put back donation banner
- #5720
> chore: put back donation banner

- .github/labeler.yml
> fix: fixes for Labeler

- html/files/tagline-off-android-v2.json
- html/files/tagline-off-ios-v2.json
- html/files/tagline-off.json
> feat: support-2024

- .github/workflows/daily.yml
So that we can see it failed !
> build: daily should fail if import_prod_data fails

- po/common/common.pot
- po/common/en.po
- po/common/fr.po
- scss/_off.scss
- templates/web/common/includes/donate_banner.tt.html
> fix: update donation banner text

- taxonomies/nutrients.txt
> chore: added acidity

- taxonomies/additives.txt
- taxonomies/allergens.txt
- added anses tag in additives, first step of
- add a property anses_additives_of_interest in the taxonomy.
- count those additives in each product, in a new anses_additives_of_interest_n tag (similar to the existing additives_n tag)
- use this data in the producers platform to signal those additives, and compare to similar products from other categories
- added one allergen
- Fixes #8967, Fixes #9101 (first step of #2912)
> taxonomy: added anses tag in additives, added one allergen

- scripts/convert_gs1_xml_to_json_in_dir.pl
I broke the script in the last refactor :(
> fix: broken convert_gs1_xml_to_json_in_dir.pl

- .github/labeler.yml
> ci: labeler

- .github/labeler.yml
> fix: labeler emojis

- .github/workflows/merge-conflict-autolabel.yml
> fix: merge conflicts

- .github/labeler.yml
- Fixes duplicate entry preventing PR auto-labelling
> fix: labeler

- taxonomies/ingredients_processing.txt
- taxonomies/preservation.txt
Also reorder lines by language
> taxonomy: update Spanish sentences (processing.txt & preservation.txt)

- conf/nginx/sites-available/off
- lib/ProductOpener/Routing.pm
> fix: /.well-known/change-password 

- lib/ProductOpener/GS1.pm
Some new field values found in recent imports.
> chore: new GS1 field values

- taxonomies/categories.txt
> taxonomy: breaded halloumi

- taxonomies/categories.txt
> taxonomy: biscuit mixes

- .github/dependabot.yml
> ci: less-frequent-dependabot

- taxonomies/categories.txt
> taxonomy: vegetarian pizzas, pure mashed potatoes

- .github/labeler.yml
> ci: More emojis for labeler

- .github/workflows/stale.yml
> fix: fix stale bot

- taxonomies/categories.txt
> taxonomy: more sorbet categories

- docs/api/index.md
Clarify requirement about User-Agent use in API docs.
> docs: improve API documentation

- taxonomies/categories.txt
> taxonomy: minor corrections

- lib/ProductOpener/Ingredients.pm
Added stopwords before or after ingredients that are listed in this wiki page: https://wiki.openfoodfacts.org/Ingredients_List_Cutting
> feat: ingredients_list_cutting

- .github/labeler.yml
> ci: labeler for mongo dump

- scripts/mongodb_dump.sh
* avoid working from upper directory while we have a lot of symlinks
* make file visible only when they are ready
> fix: fix export script after server move

- cgi/product_multilingual.pl
> fix: identation of nutrients in product edit form

- html/donate/fr.helloasso.html
An illustration was preventing some user from donating, delete the image as a hotfix.
> fix: fix donation banner

- templates/web/common/includes/donate_banner.tt.html
Fix close button of donation-banner on top of the page.
@stephanegigandet
> fix: Close button don't work

- lib/ProductOpener/Display.pm
add a parameter to get % in list of tags (e.g. for Nutri-Score and Eco-Score), plus a sort_by parameter to sort by tag name or by count, with some sensible defaults
> fix: display percent and sort options

- taxonomies/categories.txt
fix missing parents (on en/fr/xx only)
> taxonomy: fix missing parents

- taxonomies.obf/categories.txt
taxonomy: translations for Open Beauty Facts
> taxonomy: translations for Open Beauty Facts

- taxonomies/amino_acids.txt
More Wikidata entries for amino acids
> taxonomy: More Wikidata entries for amino acids

- taxonomies/nutrients.txt
taxonomy: Translate 2 nutrients
> taxonomy: Translate 2 nutrients

- taxonomies/labels.txt
> taxonomy: some translations for labels

- taxonomies/improvements.txt
chore: expand translations for the producer platform
> chore: expand translations for the producer platform

- .github/labeler.yml
Fix agena 3000 path for the labeler
> fix: Fix agena 3000 path for the labeler

- taxonomies/unused/labels_categories.txt
taxonomy: add translations for Label categories
> taxonomy: add translations for Label categories

- taxonomies/labels.txt
> taxonomy: various label translations

- taxonomies.obf/body_parts.txt
taxonomy: translation of the Open Beauty Facts body part taxonomy
> taxonomy: translation of the Open Beauty Facts body part taxonomy

- taxonomies.opff/categories.txt
taxonomy: OPFF Categories translation
> taxonomy: OPFF Categories translation

- taxonomies/packaging_materials.txt
- taxonomies/packaging_shapes.txt
taxonomy: add translations for shapes and materials
> taxonomy: add translations for shapes and materials

- taxonomies/improvements.txt
taxonomy: further translations for the improvements taxonomy for the producer platform
> taxonomy: further translations for the improvements taxonomy for the producer platform

- taxonomies/data_quality.txt
taxonomy: add some missing description to Data Quality
> taxonomy: add some missing description to Data Quality

- lib/ProductOpener/Food.pm
fix: Slight improvements on modifiers parsing for Spanish in Food.pm
> fix: Slight improvements on modifiers parsing for Spanish in Food.pm

- lib/ProductOpener/Ingredients.pm
- taxonomies/ingredients.txt
added EN ingredients in the taxonomy.
- Fixes -none
> taxonomy: tax_world_unknown_ingred_3

- taxonomies/ingredients_analysis.txt
taxonomy: Ingredient analysis translations
> taxonomy: Ingredient analysis translations

- taxonomies/ingredients_processing.txt
taxonomy: translations for ingredients_processing.txt
> taxonomy: translations for ingredients_processing.txt

- taxonomies/nova_groups.txt
taxonomy: translate NOVA groups more broadly
> taxonomy: translate NOVA groups more broadly

- lib/ProductOpener/Ingredients.pm
Added strings parsing for Spanish and Catalan.
> taxonomy: Update ingredients parsing for Spanish and Catalan

- taxonomies/ingredients.txt
> taxonomy: soy base

- lib/ProductOpener/Food.pm
Added acidity to food.pm, so it appears in the selection list
> chore: added acidity to food.pm

- taxonomies.obf/labels.txt
taxonomy: Translation of Open Beauty Facts labels
> taxonomy: Translation of Open Beauty Facts labels

- taxonomies/ingredients.txt
some CIQUAL matches for popular ingredients
I'm using this spreadsheet, and if you want to help, there's a coordination tab: https://docs.google.com/spreadsheets/d/1g9Kn-4Sz6ndF8gUH_uflAHDp1ubPg3LKKaAYpOHR2DM/edit#gid=1671290204
> taxonomy: some CIQUAL matches for popular ingredients

- taxonomies/ingredients.txt
taxonomy: some Ingredient translations
> taxonomy: some Ingredient translations

- taxonomies/ingredients.txt
> taxonomy: german additions

- taxonomies/categories.txt
> taxonomy: stollen

- taxonomies/additives.txt
> taxonomy: german syn iron gluconate

- taxonomies/ingredients_processing.txt
> taxonomy: add processing synonyms for Spanish

- taxonomies/origins.txt
> taxonomy: origin translations

- taxonomies/ingredients.txt
For https://es.openfoodfacts.org/producto/8480000155979/caocream-hacendado ,
The listed ingredient `cream` is non-milk, but made of sugar and oils.
Created new ingredient as `cream filling`.
> taxonomy: add new cream ingredient

- taxonomies/data_quality.txt
- taxonomies/ingredients.txt
Small taxonomy file fixes for `data_quality.txt` and `ingredients.txt`
> fix: fix small taxonomy encoding issues

- conf/systemd/producers_import@.service
- scripts/export_producers_platform_data_to_public_database.sh
multiline arrays don't work in sh, needs bash
> fix: export_producers_platform_data_to_public_database.sh

- lib/ProductOpener/Ingredients.pm
- tests/unit/ingredients_parsing.t
fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/9537
> fix: parsing of (fr) huile de palme, noisettes

- scripts/imports/producers_imports.sh
> chore: more verbose producers import

- taxonomies/ingredients.txt
> taxonomy: finnish and swedish ingredients

- lib/ProductOpener/Ingredients.pm
- taxonomies/additives.txt
- taxonomies/categories.txt
- taxonomies/ingredients.txt
- taxonomies/ingredients_processing.txt
- taxonomies/labels.txt
- taxonomies/preservation.txt
From multiple products, including:
https://es.openfoodfacts.org/producto/7792430902803/mani-con-chocolate-bariloche
https://es.openfoodfacts.org/producto/7790380034063/turron-blando-de-mani-con-cacao-georgalos
https://es.openfoodfacts.org/producto/8437009809150/galetes-bones-fetes-per-bones-persones-el-rosal
https://es.openfoodfacts.org/producto/8422410346189/pa-torrat-integral-bonpreu
https://es.openfoodfacts.org/producto/8422410018772/truita-de-carxofa-bonpreu
https://es.openfoodfacts.org/producto/8422410247585/banderilles-d-anxoves-i-seitons-del-cantabric-bonpreu
> taxonomy: Add Spanish and Catalan ingredients and labels

- taxonomies/ingredients.txt
for correctly analysing this product:
https://world.openfoodfacts.org/product/20316488/candiezz
> taxonomy: add cherry plum tomatoes to tomato

- taxonomies/categories.txt
> taxonomy: chutney

- taxonomies/additives.txt
> taxonomy: syn E336i

- taxonomies/additives.txt
- taxonomies/categories.txt
- taxonomies/nutrients.txt
- taxonomies/units.txt
Taxonomy improvements for week 52
> chore: week52

- taxonomies/categories.txt
- taxonomies/ingredients.txt
- taxonomies/labels.txt
Improvements to the taxonomies
> chore: taxonomies maintenance

- taxonomies/ingredients.txt
> taxonomy: German ing

- conf/logrotate/nginx
We need them for scanbot (computing popularity)
> chore: keep nginx logs for more time

- taxonomies/categories.txt
> taxonomy: new cake category and cottage cheese correction

- scss/_product-page.scss
Fixes #9277
Removed the extra character in the "Delete Images" button.
> fix: Removed Extra Character in Delete Images Button

- .github/workflows/pull_request.yml
- Makefile
> ci: remove build_backend in makefile

- templates/web/panels/panel.tt.html
There is only one command change that is causing unexpected behavior in UI.
The issue I solved is #9118 you can go through it.
And this is my first contribution to open source and exited to get my first pull request merged.
- Fixes #9118
> fix: Leaflet map goes above content.

- docs/api/ref/schemas/product_base.yaml
- docs/api/ref/schemas/product_misc.yaml
Add documentation for the 2 new field of the API
- Related to #9608
> docs: add description of new field in the taxonomy docs

- scripts/utils/logs/download_matomo_logs.pl
needed to compute scan stats from the app matomo logs
> fix: add retry to download_matomo_logs.pl

- lib/ProductOpener/Ecoscore.pm
- scripts/gen_feeds_daily_obf.sh
- scripts/gen_feeds_daily_off.sh
- scripts/gen_feeds_daily_opf.sh
- scripts/gen_feeds_daily_opff.sh
- tests/integration/expected_test_results/convert_and_import_excel_file/test/products/3270190128403.json
- tests/unit/expected_test_results/ecoscore/carrots-plastic.json
- tests/unit/expected_test_results/ecoscore/carrots.json
- tests/unit/expected_test_results/ecoscore/grade-a-with-non-recyclable-label.json
- tests/unit/expected_test_results/ecoscore/grade-a-with-recyclable-label.json
- tests/unit/expected_test_results/ecoscore/origins-of-ingredients-in-origins-field.json
- tests/unit/expected_test_results/ecoscore/origins-of-ingredients-specified.json
- tests/unit/expected_test_results/ecoscore/packaging-fr-new-shapes.json
- tests/unit/expected_test_results/ecoscore/packaging-unspecified-no-a-eco-score.json
added some misc_tags for ecoscore
> chore: misc tags for ecoscore

- templates/api/knowledge-panels/environment/carbon_footprint.tt.json
fixes #9654 
related to https://github.com/openfoodfacts/smooth-app/issues/4948#issuecomment-1891466199
> fix: remove unneeded escape of quotes in carbon footprint knowledge panel

- taxonomies/categories.txt
Add some herbs and spices categories in Polish
> taxonomy: Add polish herbs translations

- scripts/gen_feeds_daily_opf.sh
and add refresh_products daily refresh
Relates to https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/288
> chore: fix mongodb url

- scripts/gen_feeds_daily_obf.sh
and add refresh_products daily refresh
Relates to https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/288
> chore: obf mongodb url

- taxonomies/categories.txt
> taxonomy: meringue roulades

- taxonomies/test.txt
Small parent id fix on the `test.txt` taxonomy
> taxonomy: fix test taxonomies

- lib/ProductOpener/Ingredients.pm
- tests/unit/ingredients_parsing.t
> taxonomy: parsing plant proteins in French and German

- Makefile
- docker/README.md
Enable using args="--progress plain" to get build log in console in case of error
> chore: add args to make build

- .github/labeler.yml
- lib/ProductOpener/Display.pm
- scripts/generate_madenearme_pages.sh
Make madenearme writes atomic
Also fix a warning for concatenation with undefined.
> chore: madenearme atomic write

- .github/labeler.yml
ci: add dockerignore to labeler
> ci: add dockerignore to labeler

- taxonomies/unused/labels_categories.txt
> taxonomy: labels_categories

- taxonomies/food_groups.txt
> taxonomy: food_groups

- taxonomies/states.txt
> taxonomy: translate states

- scripts/update_all_products.pl
> fix: last_modified_t needs to be a number and not a string

- lib/ProductOpener/DataQualityFood.pm
- stop_words.txt
- taxonomies/ingredients.txt
- tests/unit/dataqualityfood_labels.t
added vegan and vegetarian tag for soy sauce.
- Fixes #-slack-
> taxonomy: soy_sauce_vegan

- lib/ProductOpener/Images.pm
> docs: document OCR detection type

- lib/ProductOpener/Web.pm
- taxonomies/categories.txt
• frozen food boost
• various corrections and additions to existing categs : some typos (we believe they are typos ;-)
• proposed categories additions : bunch of new categs proposed
• proposed new agribalyse proxies + 1 proposed change on Dehydrated fish broths 25918 is N/A -> 25919
> taxonomy: frozen food boost plus many additions

- lib/ProductOpener/Users.pm
> fix: load Brevo.pm in Users.pm

- taxonomies/categories.txt
- Fix categories.txt (1 line correction)
> taxonomy: fix categories.txt

- taxonomies/additives.txt
> fi syn gellaani

- lib/ProductOpener/DataQualityFood.pm
Added condition
Use $expected_minimal_amount_specific_ingredients variable only if it is defined.
Where can I see the error in the logs when I run locally????
- Fixes #9780
> fix: fix_uninitialized_value

- scripts/update_all_products.pl
> fix: add --fix-non-string-codes option

- lib/ProductOpener/Display.pm
- tests/integration/expected_test_results/facets/contributor-alice-label_organic.json
- tests/integration/facets.t
> fix: contributor plus another facet

- po/openfoodfacts/openfoodfacts
> fix: removed unused file

- taxonomies/categories.txt
Various products in this update : updates on wines, meats, seafood, dry products
> taxonomy: updates on wines, meats, seafood, dry products

- taxonomies/countries.txt
- taxonomies/origins.txt
Added Polish origin translations for some of the most popular origins
> taxonomy: add origins translations

- lib/ProductOpener/Routing.pm
- tests/integration/expected_test_results/facets/category-vitamins.json
- tests/integration/facets.t
> fix: parsing of facets in URL 

- taxonomies/labels.txt
- taxonomies/misc.txt
- taxonomies/states.txt
> taxonomy: misc translations

- taxonomies/additives.txt
> taxonomy: additives.txt

- taxonomies/categories.txt
- add semi-milled rices
- add brown and semi-milled categories for several rice types (jasmin, basmati, Camargue)
> taxonomy: add new rices categories

- taxonomies/categories.txt
Large update on "Charcuteries" - processed meats
> taxonomy: large update on processed meats

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Ingredients.pm
- po/common/fr.po
- tests/unit/ingredients_processing.t
> fix: match processing inside ingredients 

- taxonomies/ingredients.txt
> taxonomy: farines

- taxonomies/ingredients_processing.txt
> taxonomy: fermented in german

- lib/ProductOpener/Ingredients.pm
> taxonomy: improve stop words in HR

- taxonomies/categories.txt
Large update on Cheeses, Diary products
> taxonomy: large update on diary products

- docs/api/ref-cheatsheet.md
- docs/api/ref/api.yml
- docs/api/tutorial-off-api.md
> docs: warning about search API v2 not supporting full text search

- taxonomies/data_quality.txt
fix missing entry in taxonomy for dq
> taxonomy: fix missing entry in taxonomy for dq

- taxonomies/food/categories.txt
More category doubles taken from the taxonomy editor
> chore: more category doubles

- lib/ProductOpener/Config_off.pm
Photos are still uploaded if any.
> feat: Ignore *-chakib apps data

- docs/dev/how-to-quick-start-guide.md
> docs: propose to fork in quick start guide

- taxonomies/packaging_materials.txt
- taxonomies/packaging_shapes.txt
taxonomy: packaging translations
> taxonomy: packaging translations

- taxonomies/data_quality.txt
- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
> taxonomy: misc fixes

- .github/labeler.yml
> fix: labeler fixes

- docs/dev/how-to-quick-start-guide.md
Explain how to use "single branch" clone and "shallow clone" to reduce repository size on developers' PCs.
> docs: Update cloning instructions in quick start guide

- cgi/import_photos_upload.pl
- cgi/product_multilingual.pl
- cgi/top_translators.pl
- lib/ProductOpener/Display.pm
- scripts/gen_sugar.pl
- scripts/gen_top_tags_per_country.pl
- templates/web/common/includes/folksonomy_script.tt.html
I have replaced the occurrence of `<script src="https://static.openfoodfacts.org/js` and <script src="/js with  `<script src="[% static_subdomain %]/js`
[Screencast from 12-03-24 02:32:02.webm](https://github.com/openfoodfacts/openfoodfacts-server/assets/162586393/101b03d9-f50b-437a-826f-16aece88a43f)
- Fixes #9374
> fix: Harmonize handling of JS

- .github/labeler.yml
- .github/workflows/label.yml
- Reformat the labeler so that it conforms with v5 format and does not fail
> fix: labeler.yml reformat

- README.md
doc: hierarchize documentation
> docs: hierarchize documentation

- Makefile
follow up of: https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/325
> ci: check space left before importing mongodb files

- .github/labeler.yml
- .github/workflows/label.yml
> docs: labeler.yml fixes

- lib/ProductOpener/Ingredients.pm
- taxonomies/food/ingredients.txt
> taxonomy: add croatian ingredients

- docs/dev/how-to-use-repl.md
- Remove leftover(?) sentence fragment
- While there, add some markup
> docs: copyedit docs/dev/how-to-use-repl.md

- taxonomies/food/categories.txt
> taxonomy: translation ice cream 

- .perlcriticrc
- Makefile
Re-activate a rule that has no reason to be de-activated.
> fix: re-activate critic rule

- .check_perl_excludes
- Makefile
- lib/ProductOpener/LoadData.pm
- lib/ProductOpener/Tags.pm
* some perl file were not checked !
* try to make it faster by avoiding loading data at compile time, thanks to an env variable.
> ci: better / faster check_perl

- docs/dev/how-to-quick-start-guide.md
-->
- added prerequisites for installing dev environment on WSL (I was struggling to set up the dev environment on Windows, but all the errors I had went away after installing on WSL, so this can help other people struggling to setup on Windows machines)
> docs: updated quick start guide with prerequisites for WSL 

- scss/_off.scss
- templates/web/pages/product_edit/product_edit_form_display.tt.html
Added visual signals to distinguish features exclusive to moderators. This helps prevent confusion and also makes it easier to spot specific functionalities.
- Fixes #6758
> feat: Differentiate features available only for moderators

- conf/logrotate/apache2
- conf/logrotate/nginx
- conf/systemd/gen_feeds@.service
- conf/systemd/gen_feeds_daily@.service
Same as https://github.com/openfoodfacts/openfoodfacts-server/pull/10073
> fix: better logs

- taxonomies/food/categories.txt
- taxonomies/food/ingredients.txt
Ingredients needed to get the Nutri-Score on https://contribalim.openfoodfacts.org
> taxonomy: ingredients for Contribalim

- taxonomies/origins.txt
> fix: add missing origins

- docs/api/API_TODO.md
Discussed with @alexgarel.
While there, light copyediting.
> docs: Mention v2 API as having priority over v3.

- taxonomies/food/categories.txt
> taxonomy: Extruded cereals

- cgi/sugar_random.pl
[http](https://howmuchsugar.in/) was broken, this repairs it
> fix: howmuchsugar / combiendesucres

- scripts/mongodb_dump.sh
which hinders creating the deltas index.txt
NB: already reported on production.
> fix: fix typo in monogdb_dump

- taxonomies/allergens.txt
> taxonomy: romanian sulfit

- docs/api/explain-knowledge-panels.md
> docs: better alt= for panel screenshot

- taxonomies/food/ingredients.txt
- tests/integration/expected_test_results/unknown_tags/ingredient-apple-exists.html
- tests/unit/expected_test_results/ingredients/fi-do-not-match-myanmar.json
> taxonomy: Romanian ingr

- docs/api/ref/api.yml
- docs/api/ref/requestBodies/change_ref_properties.yaml
OpenAPI documentation of parameters that goes to change_ref.
> docs: add change ref parameters to product edit

- scripts/export_products_data_and_images.pl
- scripts/gen_feeds_daily_off.sh
useful for developers setting up robotoff or search-a-licious
> chore: add jsonl sample

- docs/api/aws-images-dataset.md
While there, copyedit throughout.
> docs: add the general rule to the splitting example

- docs/api/explain-knowledge-panels.md
ci: Update explain-knowledge-panels.md
> ci: Update explain-knowledge-panels.md

- .github/labeler.yml
> ci: level up NOVA labeler

- taxonomies/countries.txt
adding the OSM-id to countries, might be useful to relate with prices later on.
> chore: Adding OSM id to countries

- taxonomies/food/ingredients.txt
> taxonomy: ingredients - maple sugar, flavor, extract

- .github/labeler.yml
fix: Update labeler.yml with additives_classes and additives
> fix: Update labeler.yml with additives_classes and additives

- docs/api/index.md
- email address for help if reaching limits
- example contact email address in user agent (myapp.com is registered)
- limit for concurrent sessions from a single IP address
While there, copyedit throughout.
> docs: docs/api/index.md: specify or correct some details

- taxonomies/food/categories.txt
> taxonomy: correction italian

- docs/api/intro-robotoff.md
- docs/reference/api-tutorials/reporting-issues-with-nutripatrol.md
docs: Update intro-robotoff.md
> docs: Update intro-robotoff.md

- docs/reference/api-tutorials/working-with-facets.md
> docs: working-with-facets.md

- lib/ProductOpener/Ingredients.pm
- taxonomies/food/ingredients.txt
- taxonomies/labels.txt
add more HR words in taxonomy
+ stopwords in HR and other languages
> taxonomy: taxonomy_add_croatian_ingredients

- README.md
docs: API README clarifications
> docs: API README clarifications

- taxonomies/allergens.txt
> taxonomy: synonyms for Czech

- taxonomies/food/ingredients.txt
> taxonomy: czech ingr

- .github/labeler.yml
- docs/reference/api-tutorials/how-to-create-data-quality-controls-in-your-app.md
- Add a mention of Nutri-Patrol
- Add a mention of the real-time checks API (upcoming)
- Add links to other tutorials
- Add links to this tutorial from other tutorials
> docs: How to create data quality controls in your app

- .github/labeler.yml
- docs/reference/api-tutorials/scanning-cosmetics-pet-food-and-other-products.md
- docs/reference/api-tutorials/scanning-cosmetics.md
docs: Create scanning-cosmetics.md
> docs: Create scanning-cosmetics.md

- taxonomies/food/ingredients.txt
translate ingredients in Croatian
- Fixes #-
> taxonomy: translate ingredients in Croatian

- docs/reference/api-tutorials/license-be-on-the-legal-side.md
feat: license-be-on-the-legal-side.md
> feat: license-be-on-the-legal-side.md

- docs/reference/api-tutorials/get-ingredient-related-analysis.md
- docs: ingredient related analysis inline
> docs: ingredient related analysis inline

- docs/reference/api-tutorials/get-in-touch-with-openfoodfacts.md
docs: Create get-in-touch-with-openfoodfacts.md
> docs: Get in touch with Open Food Facts

- docs/reference/api-tutorials/get-the-ecoscore.md
docs: promo for product addition in the Eco-Score documentation
> docs: promo for product addition in the Eco-Score doc

- docs/api/API_TODO.md
> fix: Update API_TODO.md

- lib/ProductOpener/Display.pm
> fix: update list of detected bots

- docs/api/tutorial-dev-journey.md
> fix: journeys

- po/common/fr.po
- taxonomies/nutrients.txt
- tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json
- tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product.html
Some changes suggested by Santé publique France
I also did the corresponding changes in Crowdin
> chore: better French translations for fat, saturated fat and legumes

- docs/reference/api-tutorials/creating-a-local-cache-of-open-food-facts-data.md
doc: Create creating-a-local-cache-of-open-food-facts-data.md
> docs: Create creating-a-local-cache-of-open-food-facts-data.md

- docs/reference/api-tutorials/working-with-facets.md
docs: Update working-with-facets.md
> docs: Update working-with-facets.md

- taxonomies/food/categories.txt
> taxonomy: correction glazes with vinegar

- taxonomies/food/ingredients.txt
> taxonomy: german ingr

- conf/etc-default/prometheus-apache-exporter
specific config for apache exporter.
Note: already in production.
> build: add apache exporter config

- conf/nginx/sites-available/stub_status
- conf/systemd/email-failures@.service
- conf/systemd/nginx.service.d/override.conf
Also fix alert email
Note: Already done on production server
> build: expose nginx metrics

- lib/ProductOpener/Attributes.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Ingredients.pm
- templates/api/knowledge-panels/environment/ecoscore/origins_of_ingredients.tt.json
Similar to #10344.
Trying to prevent warnings in logs.
> fix: warnings modperl error log

- taxonomies/labels.txt
feat: add on-pack labels for Nutri-Score v2
> feat: add on-pack labels for Nutri-Score v2

- .github/labeler.yml
> ci: apache labeler

- taxonomies/food/ingredients.txt
> taxonomy: New german syn

- taxonomies/food/categories.txt
Various taxonomy updates:
• wines updates
• chicken & hen updates
• fix incoherent "Poulet fermier" categ
• small updates
> taxonomy: update wines, chicken, various

- taxonomies/food/categories.txt
translate categories in Croatian
> taxonomy: translate categories in croatian

- taxonomies/food/ingredients.txt
translate ingredients in Croatian
> taxonomy: translate ingredients in croatian 3

- .github/labeler.yml
ci: Update labeler.yml for Producer platform - improvement opportunities
> ci: Update labeler.yml for Producer platform - improvement opportunities

- po/common/common.pot
> fix: add missing strings to common.pot

- cgi/product_multilingual.pl
- lib/ProductOpener/Food.pm
> fix: checkboxes for nutrition data 

- docs/api/ref/api.yml
- docs/api/ref/responses/get_attribute_groups.yaml
- docs/api/ref/responses/get_preferences.yaml
- docs/api/ref/schemas/product.yaml
- docs/api/ref/schemas/product_attribute_groups.yaml
- docs/dev/explain-personal-search.md
- html/js/product-search.js
Adding explanations on personal search + some related APIs
> docs: explanation on personal search

- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Display.pm
Asked on Slack: https://openfoodfacts.slack.com/archives/C02KVRT2C/p1717624078130739
> fix: raise page size limit to 1000 for logged in users

- .github/labeler.yml
- docs/api/leveraging-links-to-wikidata.md
- docs: leveraging-links-to-wikidata.md
> docs: leveraging-links-to-wikidata.md

- po/common/common.pot
- fix: move back to normal to avoid megadiff
> fix: move back to normal to avoid megadiff

- .github/labeler.yml
ci:Update labeler.yml for systemd apache & nginx
> ci: Update labeler.yml for systemd apache & nginx

- html/resources/files/tagline-off-android-v3.json
- html/resources/files/tagline-off-ios-v3.json
- Files for the 2nd iteration of the tagline format (v3 because we have v1 and v2 of the app) 
- https://github.com/openfoodfacts/smooth-app/pull/5350
> feat: tagline-off-*-v3.json

- html/resources/files/tagline-off-android-v3.json
fix: Update tagline-off-android-v3.json
> fix: Update tagline-off-android-v3.json

- cgi/search.pl
- lib/ProductOpener/Display.pm
- lib/ProductOpener/KnowledgePanels.pm
- replace all info messages by debug messages (we don't need them in production logs)
- fixes some warnings that go in mod_perl_error log
- remove duplicate search log
> fix: reduce logs

- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
Some changes to be able to recognize better milk related ingredients.
> taxonomy: milk improvements in ingredients and processing

- taxonomies/food/ingredients.txt
Made most suggested changes. Did not do `extract`. We need to have more details.
- Fixes #10415
> chore: Nova4 additions

- cgi/search.pl
logged in users can search up to 1000 results
> fix: raise search page size limit for logged in users

- taxonomies/food/categories.txt
Add subcategories of `en:flavoured-oils` by the flavor, orthogonal to the subcategories of  `en:flavoured-olive-oils`
> taxonomy: Complete `en:flavoured-oils` subcategories

- cgi/org.pl
- cgi/user.pl
- lib/ProductOpener/CRM.pm
- lib/ProductOpener/Config2_docker.pm
- po/common/common.pot
- po/common/en.po
- scss/_off.scss
- templates/web/pages/org_form/org_form.tt.html
- templates/web/pages/user_form/user_form_page.tt.html
- tests/integration/expected_test_results/web_html/user-register.html
Added a button in the org and user form visible to admins on the pro platform, which opens their associated CRM page.
> feat: add a button to open the CRM page of the company / contact

- taxonomies/food/ingredients.txt
> taxonomy: Tempeh cultures

- taxonomies/food/categories.txt
> taxonomy: nut butter cups

- taxonomies/food/ingredients.txt
> taxonomy: betaglucan

- taxonomies/food/ingredients.txt
Added a new rare_crop:en:yes property to some ingredients. This is to prepare a new knowledge panel to promote agrobiodiversity.
> taxonomy: rare crops property for ingredients

- cgi/generate_sample_import_file.pl
- cgi/import_file_process.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/CRM.pm
- lib/ProductOpener/Import.pm
- lib/ProductOpener/Orgs.pm
- lib/ProductOpener/Test.pm
- lib/ProductOpener/Users.pm
- tests/integration/expected_test_results/api_v2_product_write/get-product-auth-good-password.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product-gs1-gs.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-all.json
- tests/integration/expected_test_results/create_pro_user/user-after-subscription.json
Add new sync data in CRM:
- last import / export date
- Last date the xlsx import template was downloaded
- last connected user (and date)
- set "onboarding" tag on opportunity of new accepted orgs
- When importing, add corresponding category of its typology : EQUADIS, AGENA3000, CSV, Manual import 
- Fixes #7356
> feat: new sync data in CRM 

- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
> taxonomy: cs translations for cranberry juice and chokeberry juice

- taxonomies/food/ingredients.txt
From Alizarine
> The ingredient "en:hydrogenated fat" is considered "non-vegan". It should be considered "maybe vegan". If someone wants to edit that in the taxonomy 
- Fixes #-
> fix: hydrogenated fat vegan maybe

- docs/api/index.md
Added the .NET repo to the list of supported SDKs on the API documentation which was missing.
> docs: Added the .NET repo to the list of supported SDKs on the API documentation.

- taxonomies/food/categories.txt
> taxonomy: Rusks

- taxonomies/petfood/categories.txt
> taxonomy: Added correct translations for Dutch in categories.txt

- taxonomies/food/ingredients.txt
> taxonomy: German synon

- taxonomies/food/categories.txt
> taxonomy: Liverwurst

- po/common/common.pot
- po/common/en.po
- templates/web/pages/dashboard/display_orgs_table.tt.html
Added product data to be displayed in the org table.
> feat: add product data to org table

- .github/workflows/pr_actions.yml
Fix condition, it's currently running on every comment :grimacing: !
> ci: fix pr-actions conditions (urgent)

- lib/ProductOpener/Routing.pm
- tests/unit/routing.t
The condition to display a text was wrong.
> fix: important fix in routing

- .github/workflows/generate-doc.yml
- .github/workflows/pr_actions.yml
- .github/workflows/pull_request.yml
- Makefile
To make workflows run correctly !
> ci: fix checkout fetch depth and origin/main presence

- .github/workflows/pr_actions.yml
I was wrong on variable availability and there is no way to test this (action must be on main branch to run…)
> ci: fix pr actions (round 3)

- .github/workflows/pr_actions.yml
> ci: fix PR action condition

- lib/ProductOpener/Data.pm
fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/10616
> fix: utf8 decoding of off-query JSON

- taxonomies/food/ingredients.txt
Added missing Polish ingredients and variants
> taxonomy: add Polish ingredients

- lib/ProductOpener/Config_off.pm
- feat: add more admins (necessary to answer to lost users)
- @Valimp what's your OFF id ?
> feat: add more admins

- scripts/imports/intermarche/run_intermarche_import.sh
Fixing an issue that prevented importing files from Intermarché
> fix: intermarche import

- .github/ISSUE_TEMPLATE/task.md
> fix: add proper parent task

- taxonomies/food/categories.txt
> taxonomy: Ice cream bars

- taxonomies/labels.txt
Adds `xx` language entry for Rainforest Alliance (and remove other language entries that have become duplicates).
- https://openfoodfacts.slack.com/archives/C02VDSWHT/p1723116366754529
> taxonomy: add XX entry for Rainforest Alliance

- taxonomies/food/categories.txt
More improvements of various kind
> chore: taxonomy updates week 32

- taxonomies/ingredients_processing.txt
Processing by steaming and/or rolling wasn’t recognised in ingredients lists in Swedish. They should be after this PR.
- https://se.openfoodfacts.org/product/7340083480638/fiberhavregryn-garant#health
> taxonomy: Add Swedish steaming and rolling

- lib/ProductOpener/CRM.pm
- lib/ProductOpener/Orgs.pm
- scripts/save_org_product_data_daily_off_pro.pl
The daily script `(save_org_product_data_daily_off_pro.pl)` which updates orgs data now sync the number of public/prod products with CRM.
> feat: sync number of product public/pro in CRM

- taxonomies/food/categories.txt
Add `dashi` and `heirloom-tomatoe` categories.
> taxonomy: add new categories

- docs/api/ref/api-v3.yml
- docs/api/ref/api.yml
- lib/ProductOpener/KnowledgePanels.pm
- templates/api/knowledge-panels/root.tt.json
- tests/integration/api_v2_product_read.t
- tests/integration/api_v3_product_read.t
- tests/integration/expected_test_results/api_v2_product_read/get-existing-product.json
- tests/integration/expected_test_results/api_v2_product_read/get-fields-knowledge-panels-knowledge-panels_excluded-environment_card.json
- tests/integration/expected_test_results/api_v2_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card-knowledge_panels_excluded-health_card.json
- tests/integration/expected_test_results/api_v2_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product-gs1-data-uri.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product-gs1-fnc1.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product-gs1-gs.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-all.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-attribute-groups-all-knowledge-panels.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-knowledge-panels-knowledge-panels_excluded-environment_card.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card-knowledge_panels_excluded-health_card.json
- tests/integration/expected_test_results/api_v3_product_read/get-fields-knowledge-panels-knowledge-panels_included-health_card-environment_card.json
Added a `knowled_panels_included=x,y` and `knowled_panels_excluded=x,y` parameter to the API, to specify which panels should be in the response.
- Fixes #9369
> feat: knowledge API to specify which panels should be returned

- docs/reference/api-tutorials/how-to-create-data-quality-controls-in-your-app.md
docs: Update how-to-create-data-quality-controls-in-your-app.md
> docs: Update how-to-create-data-quality-controls-in-your-app.md

- taxonomies/additives.txt
- taxonomies/food/ingredients.txt
Added more Polish ingredients to taxonomy
> taxonomy: Polish ingredients

- docker/dev.yml
- lib/ProductOpener/Images.pm
- lib/ProductOpener/Products.pm
- scripts/run_cloud_vision_ocr.pl
- tests/integration/expected_test_results/run_cloud_vision_ocr/robotoff_request_body.json
- tests/integration/run_cloud_vision_ocr.t
Robotoff now uses Redis Stream to get information about product updates.
> fix: remove robotoff webhook trigger

- taxonomies/food/categories.txt
> taxonomy: Teewurst

- docs/api/ref/schemas/product_misc.yaml
updated the schema for product, including a basic description for the `product.popularity_key` and `product.popularity_tags` fields.
> docs: add description to product.popularity_key + popularity_tags

- taxonomies/food/ingredients.txt
> taxonomy: add more Polish ingredients

- taxonomies/food/categories.txt
Going through the vegetable categories in order to identify which one are also sold fresh. This will be used for selection by prices.
And while I am at this I also add the quality check on expected_ingredients.
> chore: Fresh categories

- docs/dev/how-to-learn-perl.md
It seems like a good resource.
> docs: add reference to perl.fish in learn perl doc

- lib/ProductOpener/Display.pm
- templates/web/pages/robots/robots.tt.txt
- tests/integration/expected_test_results/page_crawler/get-robots-txt-ch-it.text
- tests/integration/expected_test_results/page_crawler/get-robots-txt-fr-pro-platform.text
- tests/integration/expected_test_results/page_crawler/get-robots-txt-fr.text
- tests/integration/expected_test_results/page_crawler/get-robots-txt-world-pro-platform.text
- tests/integration/expected_test_results/page_crawler/get-robots-txt-world.text
Following Cloudflare analysis on
https://blog.cloudflare.com/declaring-your-aindependence-block-ai-bots-scrapers-and-crawlers-with-a-single-click/
> fix: block more AI bots

- taxonomies/food/ingredients.txt
Adds Swedish translation for “sustainability certified palm oil” (`sv: hållbarhetscertifierad palmolja`) to the ingredients taxonomy.
[![unknown ingredient](https://github.com/user-attachments/assets/58383c18-ea7a-4d2e-a19a-f23e031a5133)](https://se.openfoodfacts.org/product/7340083481895/peanut-butter-creamy-dazzley#health)
- https://se.openfoodfacts.org/product/7340083481895/peanut-butter-creamy-dazzley#health
> taxonomy: Add Swedish “sustainable” palm oil

- html/js/folksonomy.js
Change folksonomy.js to use the right service for folksonomy.
> feat: prepare folksonomy for multi-domain

- html/js/folksonomy.js
- templates/web/common/includes/folksonomy_script.tt.html
- tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html
- tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html
- tests/integration/expected_test_results/product_read/get-existing-product.html
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product.html
- tests/integration/expected_test_results/web_html/world-product.html
Fix https://github.com/openfoodfacts/openfoodfacts-server/issues/10360
Will make some issues more annoying:
* https://github.com/openfoodfacts/folksonomy_api/issues/128
* https://github.com/openfoodfacts/openfoodfacts-server/issues/6169
> feat: Open folksonomies for all connected users

- taxonomies/food/categories.txt
> taxonomy: half iced tea and half lemonade

- .github/workflows/github-projects-ventilation.yml
Fix dispatching to match labels which have been around for a while
> ci: Fix GitHub projects dispatching to match labels which have been around for a while

- taxonomies/food/categories.txt
> taxonomy: correction fruit juices

- scripts/run_ocr.py
This script is used to regenerate missing or outdated OCR JSON files. The script was out of date.
> fix: improve OCR JSON generation script

- taxonomies/food/categories.txt
- tests/integration/expected_test_results/page_crawler/crawler-does-not-get-facet-knowledge-panels.html
- tests/integration/expected_test_results/page_crawler/normal-user-get-facet-knowledge-panels.html
> chore: taxonomy updates week 38

- scripts/check-translations.sh
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/openfoodfacts/openfoodfacts-server?shareId=e7cb54f5-9bcc-4eff-b736-78fa5f930eec).
> fix: also check .pot GetText files in addition to .po files

- docs/reference/api-tutorials/get-ingredient-related-analysis.md
Added closing ) to generate proper internal link
- No fixes previous fixes or issues
> fix: docs Adding closing ) to generate proper internal link

- docs/reference/api-tutorials/adding-missing-products.md
Semantic issue
- No related previous issue
> fix: docs (paragraph 24)

- docs/reference/api-tutorials/how-to-create-data-quality-controls-in-your-app.md
Syntax issues
- No fixes previous issues
> fix: docs Syntax issues

- taxonomies/food/categories.txt
> taxonomy: Correction butter dairy

- taxonomies/additives.txt
> taxonomy: E501 German

- lib/ProductOpener/Display.pm
Recognize this new bot from google.
**Important**: already applied in prod.
> fix: add googleOther bot

- lib/ProductOpener/KnowledgePanels.pm
- po/common/fr.po
- scss/_off.scss
- templates/api/knowledge-panels/environment/ecoscore/agribalyse.tt.json
- templates/api/knowledge-panels/environment/ecoscore/ecoscore.tt.json
- templates/api/knowledge-panels/environment/ecoscore/total.tt.json
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product.html
- tests/integration/expected_test_results/web_html/world-product.html
This is to display better the knowledge panels for Eco-Score A+ and F
> fix: cosmetic changes for new Eco-Score grades

- taxonomies/food/ingredients.txt
new PR corresponding to @challengee 's PR https://github.com/openfoodfacts/openfoodfacts-server/pull/10903 + linting
> taxonomy: small format fixes in ingredient taxonomy - lint

- .github/workflows/github-projects-ventilation.yml
ci: Add API issues for triage in the API board
> ci: Add API issues for triage in the API board

- taxonomies/food/ingredients.txt
> ci: Improve Corn support

- html/donate/en.html
fix: donation page now uses Matomo like the rest of OFF
> fix: donation page now uses Matomo like the rest of OFF

- html/resources/files/tagline-off-android-v3.json
- html/resources/files/tagline-off-ios-v3.json
Hi everyone!
We would like to update the tagline (= message on the homepage) of the mobile for the donation campaign.
FYI, in the future, we will host this content on a dedicated repo to be more flexible and reduce (a bit) the load on the server.
> chore: Update the mobile tagline for the donation campaign

- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Display.pm
- templates/web/common/site_layout.tt.html
This PR adds the matomo tracking code for OBF, OPF and OPFF.
> fix: matomo config for obf, opf, opff

- .github/workflows/pull_request.yml
- lib/ProductOpener/Tags.pm
- taxonomies/data_quality.txt
- taxonomies/food/ingredients.txt
- taxonomies/labels.txt
- taxonomies/nutrients.txt
- taxonomies/origins.txt
- taxonomies/packaging_materials.txt
- taxonomies/packaging_recycling.txt
- tests/integration/expected_test_results/api_v3_taxonomy_suggestions/packaging-recycling-fr-recy.json
* Include {tag}.extended.json files in exported taxonomies (#10742)
* Some more synonym and stop-words in Italian translations
* Align github PR script to fetch origin/main (for linting of taxonomies)
> taxonomy: synonyms, stop-words, extended json exports

- po/openbeautyfacts/en.po
- po/openpetfoodfacts/en.po
- po/openproductsfacts/en.po
> ci: remove windows phone

- .github/workflows/github-projects-ventilation.yml
ci: Update github-projects-ventilation.yml
> ci: Update github-projects-ventilation.yml

- .github/ISSUE_TEMPLATE/bug_report.md
- Auto-add type bug instead of auto-adding label bug
> docs: Update bug_report.md

- taxonomies/additives.txt
Added a french term for E160b(ii). There was none.
> taxonomy: Add french term for E160b(ii)

- taxonomies/food/categories.txt
- tests/integration/expected_test_results/web_html/fr-categories.html
- tests/integration/expected_test_results/web_html/world-categories.html
> taxonomy: correction coconut macaroons

- taxonomies/additives.txt
> taxonomy: german additives

- .github/ISSUE_TEMPLATE/bug_report.md
> ci: Update bug_report.md

- .github/ISSUE_TEMPLATE/epic.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
> ci: issue template improvements

- conf/nginx/snippets/off.locations-redirects.include
feat: increase donation locales
> feat: increase donation locales

- html/resources/files/tagline-off-android-v3.json
- html/resources/files/tagline-off-ios-v3.json
> fix: Update the mobile tagline for the donation campaign

- .github/labeler.yml
- ci: add OpenAPI yaml files
- Thematic documentation of OpenAPI yaml files
> ci: add OpenAPI yaml files

- taxonomies/food/ingredients.txt
> taxonomy: Italian for bacon

- taxonomies/food/categories.txt
- taxonomies/food/ingredients.txt
> chore: week47

- .github/workflows/github-projects-ventilation.yml
ci: send translations PRs to the translation project
> ci: send translations PRs to the translation project

- cgi/product_jqm_multilingual.pl
- cgi/product_multilingual.pl
- lib/ProductOpener/APIProductRead.pm
- lib/ProductOpener/APIProductWrite.pm
- lib/ProductOpener/Config.pm
- lib/ProductOpener/Display.pm
- lib/ProductOpener/Products.pm
fixes #11064
debug notes in the issue: https://github.com/openfoodfacts/openfoodfacts-server/issues/11064#issuecomment-2506412589
> fix: pro platform product writes to the public platform MongoDB database

- taxonomies/additives.txt
> taxonomy: E470 German

- taxonomies/food/categories.txt
> taxonomy: gingerbreads

- cgi/product_image_move.pl
fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/11067
> fix: product image move #11067

- docs/dev/how-to-quick-start-guide.md
> docs: some more pre-requisite for docker desktop

- .github/workflows/release-please.yml
- ci: update to googleapis/release-please-action  per https://github.com/openfoodfacts/.github/issues/39
> ci: Update release-please.yml

- .env
- lib/ProductOpener/ConfigEnv.pm
- tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html
- tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html
- tests/integration/expected_test_results/product_read/get-existing-product.html
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product.html
- tests/integration/expected_test_results/web_html/world-product.html
> fix: nutripatrol URL

- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
As discussed in Slack: https://openfoodfacts.slack.com/archives/C02LDQDDD/p1733996905024769
> feat: change redis stream name to product_updates

- .github/labeler.yml
> fix: fix OPF PR labelling

- lib/ProductOpener/DataQualityFood.pm
- tests/unit/dataqualityfood.t
allow serving size to be hyphen ("-")
- Fixes #10961
> fix: allow serving size to be hyphenated

- docs/reference/api-tutorials/scanning-cosmetics-pet-food-and-other-products.md
doc: Update scanning-cosmetics-pet-food-and-other-products.md
> docs: Update scanning-cosmetics-pet-food-and-other-products.md

- Makefile
- docker-compose.yml
- docker/admin-uis.yml
- docker/dev.yml
- docker/devcontainer.yml
- docker/geolite2.yml
- docker/jslint.yml
- docker/monitor.yml
- docker/perldb.yml
- docker/prod.yml
- docs/dev/how-to-develop-using-docker.md
- Update docs for how-to-develop-using-docker
- Remove version in docker files, this is obsolete now, and print a warning
- Fix "make info"
> docs: upd docs, fix version, rm docker composer version

- taxonomies/additives.txt
- taxonomies/food/ingredients.txt
Added Polish natural flavorings taxonomy entries + isomalt.
> taxonomy: Polish natural aromas

- taxonomies/food/ingredients.txt
Add german and italian words for semi-skimmed milk
> taxonomy: Add german and italian words for semi-skimmed milk

- lib/ProductOpener/Config_opf.pm
fix: Removing irrelevant fields in the Open Products Facts config
> fix: Removing irrelevant fields in the Open Products Facts config

- taxonomies/product/categories.txt
Note: we do not yet build taxonomies for opf / obf / opff in CI so this kind of error is not catched…
> taxonomy: fix product categories taxonomy

- taxonomies/food/ingredients.txt
Added more missing flavorings in Polish
> taxonomy: more flavorings translated to Polish

- taxonomies/food/ingredients.txt
Add mymuesli spelt ingredients. Flakes and flour
> taxonomy: Add mymuesli spelt ingredients

- taxonomies/additives.txt
- taxonomies/food/ingredients.txt
- taxonomies/minerals.txt
Added popular, missing, Polish translations of taxonomy
> taxonomy: popular missing Polish translations of taxonomy

- scripts/deploy/verify-deployment.sh
Linked to https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/452
> chore: add minion to verify-deployment

- taxonomies/food/ingredients.txt
Add more translations for Polish language - mainly for flour and pasta
> taxonomy: polish translations for flour and pasta

- lib/ProductOpener/Ingredients.pm
> fix: Add more german stopwords

- taxonomies/food/categories.txt
- taxonomies/product/categories.txt
feat: add common categories found on re-commerce websites
> feat: add common categories found on re-commerce websites

- taxonomies/beauty/labels.txt
- taxonomies/food/categories.txt
- feat: Add common cosmetic allegations
> feat: Add common cosmetic allegations

- conf/nginx/conf.d/log_format_realip.conf
- conf/nginx/sites-available/off
* fix apache_port regexp so that all cgi but search and facets goes to priority server
* add request_time in access logging for simple perf assessments
> chore: fix nginx configuration (apache port and request time)

- conf/nginx/sites-available/off
So that contribution is fast again
> chore: add more api requests into priority apache

- taxonomies/food/ingredients.txt
- add pork tripe (important part of Polish dish https://en.wikipedia.org/wiki/Flaki)
- add honey flavouring
- add more Polish assorted translations of taxonomy
> taxonomy: add Polish translations

- po/openproductsfacts/en.po
- po/openproductsfacts/openproductsfacts.pot
- po/openproductsfacts/pt_BR.po
- po/openproductsfacts/pt_PT.po
fix: Open Products Facts lang fixes
> fix: Open Products Facts lang fixes

- html/.well-known/security.txt
Add security information to website.
- Fixes #11258
> feat: Add security.txt

- taxonomies/food/ingredients.txt
Polish taxonomy translations for:
- various types of vinegar
- various types of sugar
- cocoa-related products
- others
> taxonomy: Polish taxonomy vinegar, sugar and others

- templates/api/knowledge-panels/report_problem/incomplete_or_incorrect_data.tt.json
display nutripatrol knowledge panels even on mobiles
> feat: enable nutripatrol panel on mobile

- taxonomies/food/categories.txt
replaces https://github.com/openfoodfacts/openfoodfacts-server/pull/11273
> fix: separate granulated sugars from white sugars

- .github/labeler.yml
> ci: nutripatrol-labeler

- Dockerfile
duplicate of https://github.com/openfoodfacts/openfoodfacts-server/pull/11357 with fix from @hangy
> ci: tentative repair Imager::File::WEBP install - 2

- lib/ProductOpener/Config.pm
(Already applied in prod for OFF)
> chore: no rate limiting for ks1

- lib/ProductOpener/Config_off.pm
> (WIP) feat: Samples for key countries and backport

- docs/api/ref-cheatsheet.md
docs: Update ref-cheatsheet.md to mention suggest from search
> docs: Update ref-cheatsheet.md to mention suggest from search

- taxonomies/product/labels.txt
taxonomy: Labels for Open Products Facts
> taxonomy: Labels for Open Products Facts

- taxonomies/packaging_materials.txt
taxonomy: Packaging materials translations
> taxonomy: Packaging materials translations

- taxonomies/states.txt
> taxonomy: States translations

- taxonomies/additives_classes.txt
Additives Classes translations
> taxonomy: Additives Classes

- taxonomies/beauty/labels.txt
taxonomy: Cosmetic labels translations
> taxonomy: Cosmetic labels translations

- taxonomies/unused/labels_categories.txt
taxonomy: Label categories translations
> taxonomy: Label categories translations

- taxonomies/improvements.txt
- taxonomies/unused/labels_categories.txt
taxonomy: Pro Platform improvements taxonomy translations
> taxonomy: Pro Platform improvements taxonomy translations

- README.md
> docs: README fixes

- taxonomies/data_quality.txt
update actions for some data quality facets
- Fixes #11143
> fix: update actions for some data quality facets

- taxonomies/origins.txt
taxonomy: translations for origins
> taxonomy: translations for origins

- .github/labeler.yml
> ci: Labeler for tags

- Dockerfile
Because Docker file use sh by default
> build: fix bash pattern to sh

- .github/dependabot.yml
> ci: monthly dependabot

- lib/ProductOpener/Ingredients.pm
add stopword in Croatian
apply suggestion from @hangy in #11431
> taxonomy: add stopword in Croatian

- docs/api/tutorials/license-be-on-the-legal-side.md
> docs: Update license-be-on-the-legal-side.md

- scripts/gen_feeds_daily.sh
The condition to know if were on the pro platform was wrong.
> fix: fix gen_feeds for pro platform

- taxonomies/additives.txt
- taxonomies/additives_classes.txt
- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
- taxonomies/minerals.txt
- taxonomies/vitamins.txt
resubmit changes from old pr from @FemmeNoire 
- Closes #8920
> taxonomy: resubmit taxonomy for de from old pr

- scripts/export_scans_to_query.pl
Fix resume from checkpoint when exporting scans to off-query
- #11334
> fix: Fix resume from checkpoint code in export scans

- taxonomies/food/categories.txt
> chore: taxonomy updates.

- taxonomies/beauty/inci_functions.txt
taxonomy: Translate inci_functions taxonomy
> taxonomy: Translate inci_functions taxonomy

- taxonomies/labels.txt
- taxonomies/prompts.txt
taxonomy: translations for OFF labels
> taxonomy: translations for OFF labels

- taxonomies/additives.txt
- taxonomies/food/ingredients.txt
Added taxonomy entries for pork meat in Polish (+ some others),
> taxonomy: pork in Polish

- taxonomies/food/categories.txt
> taxonomy: correction chocolate mousses

- docs/api/ref/api-v3.yml
- docs/api/ref/api.yml
- docs/api/tutorials/scanning-cosmetics-pet-food-and-other-products.md
Also link to API intro in api ref v2 and v3.
> docs: explicit product_type in universal scanning tutorial

- taxonomies/food/categories.txt
> taxonomy: correction mixed nuts and dried fruits

- taxonomies/food/ingredients.txt
Added taxonomy translations for Polish in regards to cereals.
> taxonomy: Polish cereals

- taxonomies/misc.txt
taxonomy: Translation of the misc taxonomy
> taxonomy: Translation of the misc taxonomy

- lib/ProductOpener/Products.pm
- scripts/update_all_products.pl
will need to be run again on off, opf, obf, opff, off-pro to fix missing product_types
fixes #11492
> fix: add missing product_type field to products, 

- taxonomies/allergens.txt
taxonomy: Allergens taxonomy translations
> taxonomy: Allergens taxonomy translations

- taxonomies/unused/labels_categories.txt
taxonomy: Update labels_categories.txt
> taxonomy: Update labels_categories.txt

- taxonomies/food/categories.txt
> taxonomy: new categories salted spreads

- html/.well-known/assetlinks.json
- feat: Update assetlinks.json to enable credential sharing
- https://developers.google.com/identity/credential-sharing?hl=fr
- https://developers.google.com/identity/credential-sharing/set-up?hl=fr
> feat: Update assetlinks.json to enable credential sharing

- taxonomies/food/categories.txt
more small changes and reverts
> chore: taxonomies week 9

- scripts/obsolete/check_images.pl
- scripts/obsolete/move_ean8_products_to_new_path.pl
- scripts/obsolete/normalize_code.pl
some scripts that should not be needed anymore, putting them in github for reference
> chore: save some old scripts, for reference

- cpanfile
- lib/ProductOpener/Config.pm
- lib/ProductOpener/Routing.pm
- tests/unit/routing.t
whitelist EPITECH school's block
> feat: whitelist IP blocks for rate limiting

- taxonomies/food/categories.txt
taxonomy: mass translate VVUC (Very Very Used Categories)
> taxonomy: mass translate VVUC (Very Very Used Categories)

- taxonomies/product/labels.txt
taxonomy: Open Products Facts label translations
> taxonomy: Open Products Facts label translations

- taxonomies/petfood/categories.txt
taxonomy: opff category translation
> taxonomy: opff category translation

- taxonomies/misc.txt
taxonomy: Make the Misc Facets consistent with their populated tags
> taxonomy: Make the Misc Facets consistent with their populated tags

- taxonomies/beauty/categories.txt
feat: cosmetic categories translations
> feat: cosmetic categories translations

- taxonomies/food/categories.txt
- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
> chore: week 10 taxonomy

- docs/dev/how-to-write-and-run-tests.md
Added info in docs to avoid failing integration tests in workflow when making changes to .pot, .po files.
- Fixes #11576
> docs: Add note about regenerating expected results for integration tests.

- scripts/tags_and_languages.py
* -m or --modify option to modify products, otherwise there are left as is
* --nb option to specify the max number of products to modify (default 10000)
> feat: Several tags_and_languages script improvements

- lib/ProductOpener/Ingredients.pm
- taxonomies/nutrients.txt
add stopwords and synonym for analytics nutrients
> taxonomy: add stopwords and synonym for analytics nutrients

- .github/workflows/pr_actions.yml
Trying to have on demand actions work on fork.
> ci: make pr actions run on fork

- .github/workflows/pull_request.yml
This was omitted from the previous commit because Now as believe it is unnecessary to build the image every time when only the documentation is updated.
- Fixes #11555
> fix: fixed the issue of pull_request.yml file

- .github/workflows/pull_request.yml
Until we find the right logic to do that.
This rollback some changes from #11555 and #11617
> ci: roll-back conditional runs for now

- html/js/folksonomy.js
fix: remove the ugly bg color for the Folksonomy Engine
> fix: remove the ugly bg color for the Folksonomy Engine

- taxonomies/beauty/categories.txt
- taxonomies/food/categories.txt
- taxonomies/ingredients_processing.txt
Unrecognised ingredients etc. from a number of products:
- https://se.openbeautyfacts.org/product/7330878351175/bomullspinnar-bambu
- https://ie.openbeautyfacts.org/product/2000000152287/irish-flag-lemon-lime-the-soap-bar
- https://se.openfoodfacts.org/product/7311043011629/pomodori-secchi-a-cubetti-garant
and some Danish and Swedish translations I did along the way.
> taxonomy: Various updates/additions

- taxonomies/food/categories.txt
> taxonomy: more vegan sauces

- taxonomies/additives_classes.txt
- taxonomies/food/ingredients.txt
- taxonomies/ingredients_processing.txt
- taxonomies/other_nutritional_substances.txt
- taxonomies/petfood/ingredients.txt
add some ingredient for open pet food fact
> taxonomy: openpetfoodfacts

- docs/dev/how-to-use-automated-pr-actions.md
Small doc to explain how to use actions.
> docs: Create how-to-use-automated-pr-actions.md

- taxonomies/food/ingredients.txt
taxonomy: very used ingredients translations
> taxonomy: very used ingredients translations

- scripts/tags_and_languages.py
small fixes when running the script
1) return in run_modifications instead of break, to continue with next tag_type.
2) added comment when updating product
3) remove limit from query because it makes query very long, but kept it at the update level
4) fix on dict update
- related to #11549
> feat: tags_and_languages_script_improvements

- docs/api/ref/schemas/product_ingredients.yaml
docs: Update product_ingredients.yaml - allergens json mention
> docs: Update product_ingredients.yaml - allergens json mention

- docs/api/ref/schemas/product_quality.yaml
docs: Update product_quality.yaml
> docs: Update product_quality.yaml

- taxonomies/beauty/inci_functions.txt
taxonomy: Translate INCI functions
> taxonomy: Translate INCI functions

- docker/dev.yml
- tests/integration/expected_test_results/api_v2_product_read/get-fields-all-knowledge-panels.json
- tests/integration/expected_test_results/api_v2_product_read/get-fields-all.json
- tests/integration/expected_test_results/api_v2_product_write/get-product-auth-good-password.json
- tests/integration/expected_test_results/api_v3_product_read/get-existing-product-gs1-caret.json
- tests/integration/expected_test_results/api_v3_product_read/get-specific-fields-ecoscore-api-v3.json
Connectivity between some of the Docker containers during development seemed to be unavailable; the symptom of this during a `make update_tests_results` run is reported at #11646.
From searching on the OpenFoodFacts Slack, I found a useful thread in the `#outreachy` channel describing exactly this problem, with a suggested possible solution (thanks, @alexgarel).  This pull request suggests applying that by default.
- Resolves #11646
> ci: configure additional DNS hosts for Docker development environment

- taxonomies/brands.txt
- Add pointers to documentation about brands: doc: doc for brands
> docs: doc for brands

- cgi/product_jqm_multilingual.pl
- tests/integration/change_product_code_and_product_type.t
- tests/integration/expected_test_results/change_product_code_and_product_type/change-product-name-of-oppf-product-with-api-v2.html
fixes #11744 (and added a test for it)
> fix: missing redirect_to_url import

- package-lock.json
- package.json
- po/common/common.pot
- po/common/en.po
- templates/web/common/includes/robotoff_nutrients.tt.html
- templates/web/common/includes/robotoff_question.tt.html
- tests/integration/expected_test_results/page_crawler/crawler-access-product-page.html
- tests/integration/expected_test_results/page_crawler/normal-user-access-product-page.html
- tests/integration/expected_test_results/product_read/get-existing-product.html
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product.html
- tests/integration/expected_test_results/web_html/world-product-content-only.html
- tests/integration/expected_test_results/web_html/world-product-smoothie.html
- tests/integration/expected_test_results/web_html/world-product.html
Update `robotoff-question` and `robotoff-nutrients` to add requested changes.
- Robotoff question 
- Robotoff nutrients
- https://github.com/openfoodfacts/openfoodfacts-webcomponents/issues/84
- https://github.com/openfoodfacts/openfoodfacts-server/issues/11691
- https://github.com/openfoodfacts/openfoodfacts-server/issues/11690
> feat: update robotoff-question and robotoff-nutrients to last version

- docs/api/tutorials/reporting-issues-with-nutripatrol.md
docs: reporting-issues-with-nutripatrol.md
> docs: reporting-issues-with-nutripatrol.md

- docs/api/tutorials/get-the-nutriscore.md
docs: Fixes for get-the-nutriscore.md
> docs: Fixes for get-the-nutriscore.md

- docs/api/tutorials/get-the-green-score.md
docs: Fixed for get-the-green-score.md
> docs: Fixed for get-the-green-score.md

- docs/api/tutorials/folksonomy-engine.md
docs: folksonomy api doc fix + exec sum
> docs: folksonomy api doc fix + exec sum

- docs/api/tutorials/finding-healthy-cereals.md
- docs: Update finding-healthy-cereals.md
> docs: Update finding-healthy-cereals.md

- docs/api/index.md
openfoodfacts-spring-boot-starter spring boot sdk repository link added.
> docs: sprig boot starter sdk link added.

- README.md
docs: Mention the design file in the README.md
> docs: Mention the design file in the README.md

- lib/ProductOpener/Display.pm
- lib/ProductOpener/Routing.pm
- lib/ProductOpener/URL.pm
- tests/integration/expected_test_results/facets/redirect-facets-agg-with-json.html
- tests/integration/expected_test_results/facets/redirect-facets-search-with-json.html
- tests/integration/facets.t
> feat: resolve redirection problem on facets

- conf/nginx/sites-available/off
- scripts/convert_gs1_json_to_off_csv.pl
Two small fixes needed to deploy v2.63.0
> fix: typo in nginx config + missing load_data()

- taxonomies/food/categories.txt
> taxonomy: paratha

- README.md
> fix: design promo

- docs/api/index.md
Staging auth is not documented anywhere. Here's a quick fix, with an example.
> feat: Staging documentation

- templates/web/pages/session/sign_in_form.tt.html
fix: Update sign_in_form.tt.html with mobile ready buttons for sign in
> fix: Update sign_in_form.tt.html with mobile ready buttons for sign in

- lib/ProductOpener/Display.pm
fix: Update Display.pm to make obf edge-to-edge
> fix: Update Display.pm to make obf edge-to-edge

- taxonomies/additives.txt
> taxonomy: polish syn

- lib/ProductOpener/Food.pm
- taxonomies/nutrients.txt
Needed for https://world.openfoodfacts.org/product/8901088002530/soffala-tasty
See also https://openfoodfacts.slack.com/archives/C02KVRT2C/p1747122955205409
> taxonomy: Add oryzanol to nutrients

- taxonomies/food/categories.txt
See https://github.com/openfoodfacts/openfoodfacts-server/pull/11432#issuecomment-2898161826
> taxonomy: fix parsing errors in food category taxonomy

- scripts/imports/systemeu/run_systemeu_import.sh
Spaces should never have been allowed in file names ;)
> fix: Systeme U import

- docs/api/ref/schemas/product_ecoscore.yaml
docs: Update product_ecoscore.yaml
> docs: Update product_ecoscore.yaml

- taxonomies/food/categories.txt
> taxonomy: swedish-style oat biscuits

- taxonomies/food/ingredients.txt
- tests/integration/expected_test_results/convert_and_import_excel_file/test/products/3270190128403.json
The list of NUCs for Divinfood is here: https://divinfood.eu/our-neglected-crops-en/
added peas, beans and lentils
> taxonomy: new 'rare' crops / NUCs for Divinfood

- conf/logrotate/apache2
so that apache2 priority is also restarted.
> chore: fix apache2 logrotate script

- .github/workflows/pull_request.yml
Build backend and run tests for pushes to the main branch
- Fixes #11985
> ci: Keep test coverage up-to-date

- docs/api/ref/schemas/product_base.yaml
> fix: Update product_base.yaml

- docs/api/ref/schemas/knowledge_panels/panel.yaml
docs: Update panel.yaml with evaluation fixes
> docs: Update panel.yaml with evaluation fixes

- .env
- lib/ProductOpener/Data.pm
- tests/integration/expected_test_results/page_crawler/crawler-access-category-facet-page.html
- tests/integration/expected_test_results/page_crawler/normal-user-access-category-facet-page.html
- tests/integration/expected_test_results/page_crawler/normal-user-get-facet-knowledge-panels.html
- tests/integration/expected_test_results/page_crawler/normal-user-get-non-official-cc-lc.html
- tests/integration/expected_test_results/recipes_stats/parent-ingredients-stats.html
- tests/integration/expected_test_results/unknown_tags/country-cambodia-exists-but-empty.html
- tests/integration/expected_test_results/unknown_tags/country-doesnotexist.html
- tests/integration/expected_test_results/unknown_tags/country-france-exists.html
- tests/integration/expected_test_results/unknown_tags/ingredient-apple-exists.html
- tests/integration/expected_test_results/unknown_tags/ingredient-someunknownandemptyingredient-does-not-exist-and-empty.html
- tests/integration/expected_test_results/unknown_tags/ingredient-someunknowningredient-does-not-exist-but-not-empty.html
- tests/integration/expected_test_results/web_html/fr-categories.html
- tests/integration/expected_test_results/web_html/fr-index.html
- tests/integration/expected_test_results/web_html/fr-search-results-no-cache.html
- tests/integration/expected_test_results/web_html/fr-search-results.html
- tests/integration/expected_test_results/web_html/world-categories.html
- tests/integration/expected_test_results/web_html/world-index.html
- tests/integration/expected_test_results/web_html/world-label-organic.html
- tests/integration/expected_test_results/web_html/world-search-results.html
Send queries to off-query irrespective of the sort column
- Part of #11755
- Depends on: https://github.com/openfoodfacts/openfoodfacts-query/pull/140
> feat: Send to off-query irrespective of sort

- taxonomies/food/categories.txt
> taxonomy: New biscuits categories

- taxonomies/brands.txt
We currently have 62–66 products of this brand.
https://world.openfoodfacts.org/facets/brands/yeo-s
https://world.openfoodfacts.org/facets/brands/yeos
> taxonomy: Add Yeo’s brand

- lib/ProductOpener/Images.pm
fix issue from refactor of product image upload
> fix: moving images to another product

- taxonomies/food/categories.txt
Category Agar agar is only in seafood for now, along side with fish and seaweed.
I added it in category cooking helpers
> taxonomy: Agaragar cooking helper

- taxonomies/food/ingredients.txt
I added the word "jiné" (other) as a stopword in czech
> taxonomy: stopword czech

- taxonomies/additives_classes.txt
Added the plural of several czech additive classes
> taxonomy: czech plurals

- docs/dev/how-to-develop-with-webcomponents.md
docs: Update how-to-develop-with-webcomponents.md
> docs: Update how-to-develop-with-webcomponents.md

- taxonomies/README.md
> docs: README for taxos

- docs/dev/how-to-write-and-run-tests.md
to better point at stored expected results
> docs: small rework on how-to-write-and-run-tests

- docs/api/index.md
Minor edit on the READ ME to: 
* Fix the formatting of the warning "Please read me" 
* Encourage to redirect reusers towards the form rather than mailto:contact@ which creates unneccessary incoming emails load
> docs: Update index.md

- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
Need some variables to be there to avoid a compilation error for OBF, OPF and OPFF
> fix: recipe_estimator_url variable for obf, opf, opff

- taxonomies/product/labels.txt
taxonomy: fixes and translations for Open Products Facts
> taxonomy: fixes and translations for Open Products Facts

- lib/ProductOpener/Auth.pm
> fix: log oidc failures as errors

- docs/dev/explain-javascript-usage-and-strategy.md
- docs/dev/ref-javascript.md
to explain the current state of affairs, the long term vision, and provide clarity on why we use nodejs (and how safe it is to bump it)
> docs: explanation on javascript usage and strategy

- docker/run.yml
- lib/ProductOpener/Config_obf.pm
- lib/ProductOpener/Config_off.pm
- lib/ProductOpener/Config_opf.pm
- lib/ProductOpener/Config_opff.pm
- lib/ProductOpener/Redis.pm
- scripts/run_cloud_vision_ocr.pl
Solves #12256.
Once merged, I will add documentation about Redis events in a new PR.
> feat: add an `ocr_ready` Redis Stream to notify of OCR result creation

- taxonomies/allergens.txt
I added a czech synonym for soy: sóju; and added the stop word "ostatní": other.
> taxonomy: czech synonym soy

- docs/api/ref-api-and-product-schema-change-log.md
- docs/api/tutorial-dev-journey.md
- docs/api/tutorial-uploading-photo-to-a-product.md
Some are still to be fixed, see warning and errors here: https://github.com/openfoodfacts/openfoodfacts-server/actions/runs/17213437164/job/48830894573
> docs: fix broken links

- README.md
> fix: Fixed typo in README (thoughfully → thoughtfully)

- taxonomies/allergens.txt
Added German declensions for some stopwords.
> taxonomy: German stopwords allergens

- taxonomies/food/categories.txt
not all prepared eggplant are frozen
> taxonomy: not all prepared eggplant are frozen

- taxonomies/food/ingredients.txt
Added some czech synonym about oils.
> taxonomy: czech ingredients 4 - Added some czech synonym about oils.

- templates/emails/README.md
docs: Create README.md for the email folder
> docs: Create README.md for the email folder

- .github/workflows/github-projects-ventilation.yml
- ci: Add action to include JavaScript issues in JS opportunities project
> ci: Add action to include JavaScript issues in JS project

- .env
- docker/dev-webcomponents.yml
- docker/dev.yml
- docs/dev/how-to-develop-with-webcomponents.md
- gulpfile.ts
- web-default/web-components/.empty
A hopefully working implementation
> docs: develop webcomponents integration

- package-lock.json
- package.json
Upgrade openfoodfacts-webcomponents to a working version.
Version 1.13.0 was not working, we need 1.13.1
> fix: webcomponents library version

- docker-compose.yml
Use the latest version of PostgeSQL that is consistent with production
> chore: Upgrade PostgreSQL image to version 17

- taxonomies/allergens.txt
added the plural of mollusc in German: Weichtieren
> taxonomy: German plural mollusc allergen

- docs/api/ref/schemas/image.yaml
- Add `imgid` to OpenAPI v2 images response specification
> fix(docs): add imgid to api v2 image schema

- lib/ProductOpener/Redis.pm
> fix: remove reference to AE::cv in push_ocr_ready_to_redis function

- taxonomies/packaging_materials.txt
- tests/integration/expected_test_results/api_v3_taxonomy_suggestions/packaging-materials-1.json
I add synonyms to C/PAP 81, C/PAP 84, C/90 LDPE, C/ALU 90 and C/FE 91. In case of C/91 I modify from tin to steel  
Discussion on Slack and at the conference OFF
> taxonomy: fix packaging materials.txt

- lib/ProductOpener/Display.pm
Fixes https://github.com/openfoodfacts/openfoodfacts-server/issues/12380
I'll add an integration test later, when https://github.com/openfoodfacts/openfoodfacts-server/pull/12383 is merged as it adds a new integration test file for taxonomy APIs
> fix: taxonomy API error, fixes #12380

- package-lock.json
- package.json
This solves an issue with OFF webcomponent (Robotoff).
> chore(deps): upgrade openfoodfacts-webcomponents

- taxonomies/food/ingredients.txt
Added 2 German and 1 French synonyms
> taxonomy: minor additions

- .github/workflows/container-deploy.yml
We now have a folksonomy staging instance, use it in staging.
> chore: use staging folksonomy in staging

- taxonomies/food/categories.txt
Added a new category for instant porridges.
> taxonomy: Instant porridges

- cpanfile
- tests/integration/expected_test_results/api_v2_product_read/get-knowledge-panels-fr.json
- tests/integration/expected_test_results/api_v3_product_read/get-knowledge-panels-fr.json
- tests/integration/expected_test_results/page_crawler/normal-user-get-non-official-cc-lc.html
- tests/integration/expected_test_results/web_html/es-ingredients.html
- tests/integration/expected_test_results/web_html/fr-product-2.html
- tests/integration/expected_test_results/web_html/fr-product-raw-panel.html
- tests/integration/expected_test_results/web_html/fr-product.html
> build: fix CGI version
